### ISSUE TITLE
Can it support a custom endpoint (similar to TF options)

### ISSUE THREAD

**Issue by rom-stratoscale** [GoogleCloudPlatform/terraformer#1]
https://www.terraform.io/docs/providers/aws/guides/custom-service-endpoints.html

**Comment by sergeylanzman** [comment]
Why you need this?
I think it's possible.
Need send to provider config as terraform.ResourceConfig{}
Part of config can be map[string]interface{} Endpoints
https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/provider_wrapper/provider.go#L147 

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/provider.go#L1012

**Comment by rom-stratoscale** [comment]
@sergeylanzman - @ Stratoscale, we build a private cloud solution that exposes aws APIs. Hence, I would like to explore this tool for internal usage with our product.
Thanks
