### ISSUE TITLE
  Should I must to use `gcloud auth application-default login`, to import `google monitoring` ?

### ISSUE THREAD

**Issue by saitotqr** [GoogleCloudPlatform/terraformer#100]
Hi,
When I set credencial as service account from JSON like this, 
`export GOOGLE_APPLICATION_CREDENTIALS='/path/to/mycred.json'`

terraformer import monitoring doesn't work well.

```
terraformer import google --resources=monitoring --connect=true --zone=asia-northeast1-a --projects=my-gcp-prj
2019/06/11 16:17:39 error with alert: rpc error: code = PermissionDenied desc = Permission denied (or the resource may not exist).
2019/06/11 16:17:39 error with alert: rpc error: code = PermissionDenied desc = Permission denied (or the resource may not exist).
2019/06/11 16:17:39 error with alert: rpc error: code = PermissionDenied desc = Permission denied (or the resource may not exist).
...
```

Must I have to use `gcloud auth application-default login`, to import `google monitoring` ?

the import other resources work well in credencial from JSON.

**Comment by sergeylanzman** [comment]
GRPC monitoring client use GOOGLE_APPLICATION_CREDENTIALS params as HTTP client.
here in code https://github.com/googleapis/google-api-go-client/blob/master/internal/creds.go#L47

Maybe your service account in JSON don't have same permissions?

**Comment by saitotqr** [comment]
service account in JSON has Project-Owner role, so I think I have every permissions...
