### ISSUE TITLE
AWS EBS resources are not imported

### ISSUE THREAD

**Issue by barcherf5** [GoogleCloudPlatform/terraformer#1003]
I ran `terraformer import aws --resources=* --regions=us-east-1 --profile=<valid profile>` but nothing was imported. Two files were created in the usual place (generated/aws/ebs), but they had no content.

During the import, these lines went by (date and time stamps omitted):

aws importing... ebs
aws done importing ebs
Number of resources for service ebs: 0
Filtered number of resources for service ebs: 0
aws save ebs
aws save tfstate for ebs

Likewise, there were no TF resources created when restricting to just EBS resources. Happy to provide any information that's needed!

**Comment by barcherf5** [comment]
I should clarify, other resources were imported when I ran that command, just nothing for EBS.

**Comment by barcherf5** [comment]
The only item that I see with -v that looks possibly relevant is `[DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"`, but I don't know if it is.

**Comment by burner1024** [comment]
Same symptoms, but for me, no resources are imported at all. (Even those that were importing fine a month or so ago). As far as I can tell, AWS functionality is dead.

**Comment by aleksei-geeksters** [comment]
Any ideas how to fix this?

**Comment by aleksei-geeksters** [comment]
<img width="655" alt="image" src="https://github.com/GoogleCloudPlatform/terraformer/assets/98822712/e2b1f8cb-80b5-4fff-907e-482a8544d81e">
