### ISSUE TITLE
Support for EC2 and EBS

### ISSUE THREAD

**Issue by ctopherwilliams** [GoogleCloudPlatform/terraformer#102]
The addition of these two services would make this tool much more powerful.

**Comment by shadiakiki1986** [comment]
This issue is good to be closed. I just tested the import of ec2 instances, and it works.

**Comment by shadiakiki1986** [comment]
Actually I just realized that the EBS part is still missing, so better keep this open. Sorry for the false alarm

**Comment by jalbstmeijer** [comment]
Using:

terraform 0.11.14
provider.aws 2.18.0
terraformer 0.7.5

I found that this module is not creating a variables.tf file including the "sg" and "subnet" state files and referring to those objects as variables in instance.tf like the other modules do.
Should I create a separate issue for this? like https://github.com/GoogleCloudPlatform/terraformer/issues/130

**Comment by sergeylanzman** [comment]
fixed connection to SG and subnet here https://github.com/GoogleCloudPlatform/terraformer/commit/519aa61f389d2198b47446c6bae34c7b8163dcf4
