### ISSUE TITLE
Terraformer ignoring --regions flag when using MFA

### ISSUE THREAD

**Issue by pavlospt** [GoogleCloudPlatform/terraformer#1020]
Hello! 

I am running the following command but it seems that the provider is not respecting the `--regions` flag! 

```shell
$ terraformer import aws --resources=route53 --regions=eu-west-1
```

Output:
```
2021/08/20 15:05:58 aws importing default region <-- this should be mentioning eu-west-1
```

Is there something I am missing?

Edit # 1: it seems to be an issue when using MFA. 
Another thing I noticed is that the AWS provider CMD treats regions differently than GCP for example!

**Comment by cmaritan** [comment]
Hello,

route53 is a global service not bound to specific region.
If I'm not missing something in the code, this is an expected behavior.
See: 
https://github.com/GoogleCloudPlatform/terraformer/blob/f0635e1d33d99d561523d1115a31d5a9410a2187/cmd/provider_cmd_aws.go#L24
and:
https://github.com/GoogleCloudPlatform/terraformer/blob/f0635e1d33d99d561523d1115a31d5a9410a2187/providers/aws/aws_provider.go#L40

Bye.

**Comment by pavlospt** [comment]
That is true, but if it was working properly it should be importing resources 🤔

**Comment by cmaritan** [comment]
Hello,

your post didn't mentioned that importing resources was not working, only that output message was wrong.
Moreover the title stated that terraformer was ignoring regions flag, that's untrue as per my previous reply.

So instead are you saying that import is not working at all if MFA credentials are used?
Please add full output and terraformer version. It's difficult to understand your use case without additional information.
I tested a normal route53 import with region flag but no MFA and it's working as expected. I don't have MFA enabled credentials right now.

Bye.

**Comment by pavlospt** [comment]
@cmaritan I updated the title and yes it might be my mistake that I didn't add a full output but I refrained from it since it is not working at all, so I did not find any meaning to that! 

Terraformer version: **latest**

## My use case
Just a simple `terraformer import aws`!!

Not sure what other info I can provide! When using MFA and configuring a specific profile `terraformer` is able to correctly start importing resources from Route53.
