### ISSUE TITLE
AWS EMR fails if a large number of clusters is available

### ISSUE THREAD

**Issue by MarcoLugo** [GoogleCloudPlatform/terraformer#1022]
The AWS EMR API fails whenever there is a large number of clusters. AWS CLI output below:

```
aws emr list-clusters

An error occurred (ThrottlingException) when calling the ListClusters operation (reached max retries: 4): Rate exceeded
```  

This call succeeds if  _--max-items_ is set to something reasonable (e.g. <1000). The ideal solution would be for AWS to fix this issue on their end. This also affects the SDK and thus terraformer:

```
terraformer import aws --resources=emr --regions us-east-2
2021/08/23 17:10:48 aws importing region us-east-2.    
2021/08/23 17:10:49 aws importing... emr.    
2021/08/23 17:11:04 aws error initializing resources in service emr, err: operation error EMR: ListClusters, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestI
```

 In the meantime, is there any way to limit the size (as _--max-items_ or some other parameter would) in terraformer when doing _aws import --ressources=emr_?

**Comment by sergeylanzman** [comment]
You can try use this flags
```
  -n, --retry-number int      number of retries to perform when refresh fails (default 5)
  -m, --retry-sleep-ms int    time in ms to sleep between retries (default 300)
```

more sleep and retry ....aws rate limit....

**Comment by MarcoLugo** [comment]
None of those flags help as it is the SDK itself that makes multiple calls (one per 50 clusters). AWS rate limit increase would help but it would mean having to continually increase it (which requires a AWS support ticket and may not necessarily be granted). I was able to work around it by manipulating my network connection in order to slow things down.

**Comment by sergeylanzman** [comment]
Other options from code
Change parallel number of workers from 15 to 1-5
https://github.com/GoogleCloudPlatform/terraformer/blob/3f1d08ef5fe49162facc99e15e2d1b96f6547d0e/terraformutils/utils.go#L72
