### ISSUE TITLE
GCP filters still not working

### ISSUE THREAD

**Issue by georgewilliamherbert** [GoogleCloudPlatform/terraformer#1023]
Following up #801 which was described as probably being fixed in #816 , but reading the code the 816 patch only solved for Datadog provider it appears.  I'm also struggling with GCP filters; following all the recommended patters from README.md and #793 and #798 and not getting anywhere.  The patterns from #801 are almost identical to mine; we're trying to add functionality to import for configuration backup individual GCP objects (compute instances, routes, storage, ... anything) and it appears that the filters aren't in practice working.  It always dumps all the objects in the resource and region match ignoring any filter pattern.

I can post-process if necessary, but the filter should be fixed.  Thanks.

**Comment by ee07dazn** [comment]
I am having the same problem where filters are essentially getting ignored completely.

**Comment by xakraz** [comment]
I have the same issue with other providers, like GitHub today

**Comment by brianpham** [comment]
I am seeing the same issues as well. I can't seem to find successfully find any good examples of what the filters should be as well. 

For example, running this will import every instance in that region instead of a particular instance. 
```terraformer import google --resources instances --projects <project_id> --filter google_compute_instance=<gce-instance> --regions us-west1```

**Comment by georgewilliamherbert** [comment]
Pinging to avoid stale label.  Still unresolved for at least some of the functionality.

**Comment by godwhoa** [comment]
Source all the confusion is this commit: https://github.com/GoogleCloudPlatform/terraformer/commit/2d766d87f4de2315b63a63886a165f024eda4917

You need to trim the provider prefix(`google_`) before passing it to a filter.

**Comment by rfortmann-ewolff** [comment]
> I am seeing the same issues as well. I can't seem to find successfully find any good examples of what the filters should be as well.
> 
> For example, running this will import every instance in that region instead of a particular instance. `terraformer import google --resources instances --projects <project_id> --filter google_compute_instance=<gce-instance> --regions us-west1`
> 
> EDITED: I finally got it working using the following filter. `terraformer import google --resources instances --projects <project-id> --filter compute_instance=<instance-name> --regions us-west1`

Tried the same with BigQuery but it is not working:
`terraformer import google --resources bigQuery --projects="<project ID>" --filter="bigquery_dataset=<name of dataset>" --regions=<name of the region>`

Any workaround?

**Comment by godwhoa** [comment]
@rfortmann-ewolff Try `--filter="bigquery_dataset='<project>:<dataset_id>'"`.

**Comment by ramonmpa** [comment]
> > I am seeing the same issues as well. I can't seem to find successfully find any good examples of what the filters should be as well.
> > For example, running this will import every instance in that region instead of a particular instance. `terraformer import google --resources instances --projects <project_id> --filter google_compute_instance=<gce-instance> --regions us-west1`
> > EDITED: I finally got it working using the following filter. `terraformer import google --resources instances --projects <project-id> --filter compute_instance=<instance-name> --regions us-west1`
> 
> Tried the same with BigQuery but it is not working: `terraformer import google --resources bigQuery --projects="<project ID>" --filter="bigquery_dataset=<name of dataset>" --regions=<name of the region>`
> 
> Any workaround?

@rfortmann-ewolff  check if helps you. https://github.com/GoogleCloudPlatform/terraformer/issues/793#issuecomment-1335186977
