### ISSUE TITLE
getting older terraform version(0.12.31) in tfstate file

### ISSUE THREAD

**Issue by dev-opsworld** [GoogleCloudPlatform/terraformer#1027]
Hi Team, 
I am getting older terraform version in tfstate file, I want tfstate with the same version that is installed on my server.
Please do the needful help

**Comment by umasankar-c** [comment]
I am also facing the same issue. Please help us here.

**Comment by ba1dr** [comment]
Same here. Terraform of version 0.12.31 is dated by April 26, 2021, while the latest is 1.0.7 atm (released September 15, 2021).

**Comment by devopsrick** [comment]
Many providers don't support 0.12 anymore.  This really should be updated to support 0.13 at minimum.

**Comment by caleb15** [comment]
Same issue with latest version of terraformer-datadog-linux-amd64 (0.8.18). @sergeylanzman can this be reopened please?

**Comment by shivangivar** [comment]
@dev-opsworld  getting the same issue on my linux OS terraform version is 1.1.9 but in tfstate file it is showing 0.12.31
