### ISSUE TITLE
Error while importing Datadog resources - err: edge.laptop_large is not a valid SyntheticsDeviceID

### ISSUE THREAD

**Issue by MohitDubeyGitHub** [GoogleCloudPlatform/terraformer#1034]
We are unable to import the Datadog synthetic tests using terraformer as it gives an error  and doesn't recognize edge.laptop_large as a valid SyntheticsDeviceID .

err: edge.laptop_large is not a valid SyntheticsDeviceID

![image](https://user-images.githubusercontent.com/52689488/131441356-4db122a9-efcd-46ee-bf4e-9f78b224cf19.png)

**Comment by skarimo** [comment]
👋  the following pr https://github.com/GoogleCloudPlatform/terraformer/pull/1028 should resolve this issue. You can built the latest master from source to use it: https://github.com/GoogleCloudPlatform/terraformer#installation
