### ISSUE TITLE
How do i add new providers to Terraformer

### ISSUE THREAD

**Issue by kiranchavala** [GoogleCloudPlatform/terraformer#1047]
Hi Team

I would like to add support for apache cloudstack 

https://cloudstack.apache.org/

https://github.com/apache/cloudstack-terraform-provider

I am able to deploy resources to cloudstack using terraform without any issues

What is the procedure to import the existing resources on my cloudstack, could someone guide me on how  to do that

**Comment by prein** [comment]
Some documentation on the process of requesting / adding a new provider would be nice indeed.

**Comment by sunil29feb** [comment]
Here are high-level steps
1.  Initialize provider details in cmd/root.go and create a provider initialization file  in the terraformer/cmd folder
2. Create a folder under terraformer/providers/ for your provider
3. Create two files under this folder
- <provide_name>_provider.go
- <provide_name>_service.go
4. Initialize all provider's supported services in <provide_name>_provider.go file
