### ISSUE TITLE
panic: unknown resource type google_compute_region_instance_group (dup #683)

### ISSUE THREAD

**Issue by georgewilliamherbert** [GoogleCloudPlatform/terraformer#1050]
This duplicates / reopens #683 which is closed and I can't reopen, but issue is still present on 0.8.15 at least.

Reopening as this is still happening with 0.8.15. Running from my Mac against GCP projects now seeing:

2021/09/14 12:56:49 Refreshing state... google_compute_region_instance_group.tfer--europe-002D-west4-002D-puppetmaster

panic: unknown resource type google_compute_region_instance_group
goroutine 32644 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xc00087e1c0, 0xa9a0383, 0x24, 0x0, 0x0)
github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0x12a
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc00087e1c0, 0xa9a0383, 0x24, 0xb6e2318, 0xc00192b9f0, 0x985cbe0, 0xc0036383c0, 0x104e88b0, 0x0, 0x0, ...)
github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0xa5
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc0001d7110, 0xc00020e320, 0xc00020e0a0, 0x2, 0xc00662c770, 0x63)
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x305
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc0051b7950, 0xc0001d7110)
github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x4f
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0xc0026e2720, 0xc005145f90, 0xc0001d7110)
github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xcd
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0x145

$ terraform version
Terraform v1.0.4
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.0.6. You can update by downloading from https://www.terraform.io/downloads.html

$ terraformer version
Terraformer v0.8.15

**Comment by ronenh** [comment]
I'm running into the same problem:

```
$ terraformer import google --projects=<my-project> --resources=regionInstanceGroups -z=us-east1
2021/09/16 10:23:31 google importing project <my-project> region us-east1
2021/09/16 10:23:33 google importing... regionInstanceGroups
2021/09/16 10:23:33 google done importing regionInstanceGroups
2021/09/16 10:23:33 Number of resources for service regionInstanceGroups: 1
2021/09/16 10:23:33 Refreshing state... google_compute_region_instance_group.tfer--speaker-002D-splitter
panic: unknown resource type google_compute_region_instance_group

goroutine 162 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xc000a844d0, 0xacafdcf, 0x24, 0x0, 0x0)
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0x12a
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc000a844d0, 0xacafdcf, 0x24, 0xba3c338, 0xc0021d8500, 0x9b10a60, 0xc00247f8c0, 0x109660f8, 0x0, 0x0, ...)
	github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0xa5
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc000a85f80, 0xc0011ce780, 0xc0011ce730, 0x2, 0xc001fd2420, 0x55)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x305
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc001fe4120, 0xc000a85f80)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x4f
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0xc001ff0000, 0xc0011ee8b0, 0xc000a85f80)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xcd
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0x145

$ terraformer --version
version v0.8.16

$ terraform version
Terraform v1.0.6
on darwin_amd64
```

**Comment by tsm2k** [comment]
any solutions yet?

**Comment by georgewilliamherbert** [comment]
We're working around it by excluding the resource type, adding the "--excludes=regionInstanceGroups" argument to the command line every invocation.  That's not a fix, but a workaround.  If you need regionInstanceGroups then the underlying issue needs resolution.

**Comment by shankerganesh** [comment]
> We're working around it by excluding the resource type, adding the "--excludes=regionInstanceGroups" argument to the command line every invocation. That's not a fix, but a workaround. If you need regionInstanceGroups then the underlying issue needs resolution.

Any resolution yet? I am stuck with this issue can someone help with a solution?

**Comment by akamalov** [comment]
Greetings. This is becoming a hindrance. We're using region instance groups and cannot skip it because it is part of the deployment.  https://github.com/GoogleCloudPlatform/terraformer/issues/1859
