### ISSUE TITLE
importing DataDog synthetics_test fails

### ISSUE THREAD

**Issue by ezraroi** [GoogleCloudPlatform/terraformer#1057]
`error initializing resources in service synthetics_test, err: Data failed to match schemas in oneOf(SyntheticsAssertion)`

**Comment by therve** [comment]
Hi,

Can you share more about the payload? There might be various features in Synthetics causing this.

**Comment by albferrari** [comment]
I'm having a similar issue importing the synthetic test seems to fails with this error
```
terraformer import datadog --resources synthetics_test --api-key $(API_KEY) --app-key $(APP_KEY)
2021/10/01 11:37:39 datadog importing... synthetics_test
2021/10/01 11:37:39 datadog error initializing resources in service synthetics_test, err: global is not a valid SyntheticsConfigVariableType
2021/10/01 11:37:39 datadog Connecting.... 
```

**Comment by ezraroi** [comment]
@therve which payload do you need?

**Comment by FlorianVeaux** [comment]
👋  Hello, I'm facing the same issues which I was able to workaround by bumping the datadog-api-client library. I just opened a PR for it

**Comment by kuchukullaritesh** [comment]
This issue still exists
