### ISSUE TITLE
open /Users/../.terraform.d/plugins/darwin_amd64: no such file or directory

### ISSUE THREAD

**Issue by Yusadolat** [GoogleCloudPlatform/terraformer#1072]
I followed the process here on MacOS Big Sur.

```
export PROVIDER={all,google,aws,kubernetes}
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64
chmod +x terraformer-${PROVIDER}-darwin-amd64
sudo mv terraformer-${PROVIDER}-darwin-amd64 /usr/local/bin/terraformer
```
but set the export provider to `aws` only. On trying out the give below error

```
open /Users/.../.terraform.d/plugins/darwin_amd64: no such file or directory
```

**Comment by efarrapo** [comment]
> same issue, i tried to place the exec in the folder but another error appeared
> 
> ```
> 2021/10/11 20:41:32 google importing project trusk-playground region europe-west1
> 2021/10/11 20:41:33 Attempting an import of ALL resources in google
> 2021/10/11 20:41:33 fork/exec : no such file or directory
> ```

Same problem here. Any solution?

**Comment by bentonjimmy** [comment]
> installation manual

I followed what was suggested here even though I installed with homebrew and this solved the issue for me.  The way the installation instructions are laid out it wasn't clear that you need to perform the `terraform init` step for all types of installation.
