### ISSUE TITLE
How does terraformer load AWS_DEFAULT_PROFILE now?

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/terraformer#1075]
I have both credentials and config files setup and I would be able to run `aws ecr describe-repositories` after the `AWS_DEFAULT_PROFILE` config, but somehow, I cannot run `terraformer import aws --resources=ecr --regions=us-east-1` to get the desired resources, did I miss anything? Thanks!

**Comment by korncola** [comment]
same problem here `AWS_DEFAULT_PROFILE` is set and also `assume_role` is set in the `provider.tf `for terraform, but terraformer connects to a different account and the result is empty, also the generated `provider.tf`has no account info in it.

**Comment by korncola** [comment]
after some digging: i think this whole project is broken and looks abandonded, even pull requests for the readme that are more than 1 year old doesnt get marged. sad.
Account/Profile managemnt is totally broken, comments in issue regarding this are a mess, even the --progile option (which is not working) are not stated in README

**Comment by based3** [comment]
You should install Terraform with AWS first and then use Terraformer.

Current on going development:  
 https://github.com/GoogleCloudPlatform/terraformer/pull/994

Many pull requests are stuck due to google-cla signing step which require a google (mail) account.

**Comment by based3** [comment]
You can use something like --regions=eu-central-1 --profile=default

[default]
