### ISSUE TITLE
build breaks on tencentcloud

### ISSUE THREAD

**Issue by ppbrown** [GoogleCloudPlatform/terraformer#1079]
when trying to do the documented "go build -v" (on debian default OS install on a google VM) it bombs out with 

go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: unknown revision v3.0.82

But if I try to build it with JUST google, that also fails.
The docs (README) seem to say I just need to do
go run build/main.go  google

but that too, STILL bombs out with whines about tencentcloud.

Could you make your "only build the one provider", actually only build the one provider, please?

**Comment by ArielZamparini-REISys** [comment]
Getting the same reported issue, 

to reproduce make sure to have a clean install of go with nothing downloaded and start following the terraformer install instructions, nothing works neither does selection by specific provider. 

Attempting the fixes described here also do not work:
https://github.com/GoogleCloudPlatform/terraformer/issues/948

Error messages shown:
`go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.233+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.233: unknown revision v3.0.233`

When attempting the fixes from #948 :
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /root/terraformer-test/terraformer/build/main.go:18 +0x12a7
exit status 2
```

When attempting with either the release version of Terraformer or built from source yields this extra line:
`go: github.com/hashicorp/terraform@v0.12.31 requires
        github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82`
        
Please Advise, even tried removing dependencies to tencent even by manually modifying go.mod but still borked.

**Comment by ppbrown** [comment]
I should mention that I think i had more luck on the latest version of
ubuntu for some reason.

**Comment by GennadySpb** [comment]
@sergeylanzman could you try to build terraformer from default branch without GOPROXY?

https://gist.github.com/GennadySpb/b71aa5dc7891e4827c390ef21ca9ed88

I've got the same error. There is no more version v3.0.233 of github.com/tencentcloud/tencentcloud-sdk-go
