### ISSUE TITLE
GCP: Google Project IAM Resources

### ISSUE THREAD

**Issue by yu-iskw** [GoogleCloudPlatform/terraformer#108]
I would like to import existing IAM settings as followings:

- `google_project_iam_policy`
- `google_project_iam_binding`
- `google_project_iam_member`
- `google_project_iam_custom_role`

## Terraform
- https://www.terraform.io/docs/providers/google/r/google_project_iam.html
- https://www.terraform.io/docs/providers/google/r/google_project_iam_custom_role.html

**Comment by yu-iskw** [comment]
MEMO: We already have the file to implement it. But, everying is in TODO.
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/iam.go#L61

**Comment by mrusme** [comment]
Apparently @reinoudk (partially?) implemented this, however there seems to be no info on this available in the documentation. What's the way to import IAM config?

**Comment by reinoudk** [comment]
@mrusme sorry, I forgot to update the README, I'll create a PR sometime today to fix that. You can import `google_project_iam_member` and `google_project_iam_custom_role` resources by running `terraformer import google --resources=iam`. 

The `google_project_iam_binding` and `google_project_iam_policy` resources conflict with `google_project_iam_member` and have therefore not been implemented.

**Comment by ponkumarm** [comment]
Hi @reinoudk - Does google_project_iam_binding and google_project_iam_policy resources available now? It would be super helpful if you could advise about it.

**Comment by reinoudk** [comment]
Hi @ponkumarm, I've just glanced at the `iam` code again and I don't think it has changed. So I think there's only support for `google_project_iam_member` as per the reasons mentioned above.
