### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by mc-digit** [GoogleCloudPlatform/terraformer#1085]
Hi. When i try to export panos config I receive an error:

2021-10-08T22:05:38.224+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/paloaltonetworks/panos/1.8.3/linux_amd64/terraform-provider-panos_v1.8.3 pid=25137
2021-10-08T22:05:38.224+0200 [DEBUG] plugin: plugin exited
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/panos.(*FirewallNetworkingGenerator).PostConvertHook(0xc001998600)
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/providers/panos/firewall_networking.go:709 +0x2625
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc000371a00)
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/terraformutils/providers_mapping.go:175 +0xb4
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc00086c120, 0x1, 0x1}, {0x106b2a68, 0x0, 0x0}, {0xc000bc21b0, 0x24}, ...}, ...)
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/cmd/import.go:104 +0x2d6
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdPanosImporter.func1(0xc0014d8580, {0x963d253, 0x2, 0x2})
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/cmd/provider_cmd_panos.go:62 +0x3d2
github.com/spf13/cobra.(*Command).execute(0xc0014d8580, {0xc0000faf20, 0x2, 0x2})
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0012e6dc0)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
        /home/user/Data/DC/palo-terraformer/terraformer/terraformer/main.go:39 +0x35

I have tried running terraformer on three firewalls and i get that same error.

Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/paloaltonetworks/panos v1.8.3

**Comment by Trois-Six** [comment]
I am sorry, I have just seen that issue (yes, it's my fault), is it resolved?

**Comment by mc-digit** [comment]
No, I still get an error when trying to import network configuration but I
don't know golang language so it is difficult for me to fix the issue.

wt., 9 lis 2021, 16:13 użytkownik Pierre Erraud ***@***.***>
napisał:

**Comment by Trois-Six** [comment]
The stacktrace is still the same?

**Comment by mc-digit** [comment]
Yes that same line in firewall_networking.go and that same error.

wt., 9 lis 2021, 16:38 użytkownik Pierre Erraud ***@***.***>
napisał:

**Comment by Trois-Six** [comment]
Can you test something like:

```
diff --git a/providers/panos/firewall_networking.go b/providers/panos/firewall_networking.go
index c5bc5202..abcc4d5e 100644
--- a/providers/panos/firewall_networking.go
+++ b/providers/panos/firewall_networking.go
@@ -706,8 +706,10 @@ func (g *FirewallNetworkingGenerator) PostConvertHook() error {
                }
 
                if r.InstanceInfo.Type == "panos_ipsec_tunnel_proxy_id_ipv4" {
-                       if _, ok := mapInterfaceNames[r.Item["ipsec_tunnel"].(string)]; ok {
-                               r.Item["ipsec_tunnel"] = mapInterfaceNames[r.Item["ipsec_tunnel"].(string)]
+                       if _, exists := r.Item["ipsec_tunnel"]; exists {
+                               if _, ok := mapInterfaceNames[r.Item["ipsec_tunnel"].(string)]; ok {
+                                       r.Item["ipsec_tunnel"] = mapInterfaceNames[r.Item["ipsec_tunnel"].(string)]
+                               }
                        }
                }
```

**Comment by mc-digit** [comment]
Can you tell me how to test this code (or send me some tutorial links)
without a github commit ?.

wt., 9 lis 2021, 17:31 użytkownik Pierre Erraud ***@***.***>
napisał:

**Comment by Trois-Six** [comment]
1. Clone the repository of Terraformer:
```
git clone git@github.com:GoogleCloudPlatform/terraformer.git
cd terraformer
```
2. Modify the file providers/panos/firewall_networking.go to apply the proposed patch (I just added a test before `if _, ok := mapInterfaceNames[r.Item["ipsec_tunnel"].(string)]; ok {`)

3. Compile Terraformer
```
go build -v
```

4. Use the compiled binary and not the one you were using...

**Comment by mc-digit** [comment]
So what I understand terreformer executable file is created/build from
local *.go file copies not from github ?.

wt., 9 lis 2021, 17:46 użytkownik Pierre Erraud ***@***.***>
napisał:

**Comment by Trois-Six** [comment]
Yes

**Comment by mc-digit** [comment]
I will try to test your solution today or tomorrow.

wt., 9 lis 2021, 19:05 użytkownik Pierre Erraud ***@***.***>
napisał:

**Comment by mc-digit** [comment]
Ok, I have tested your fix and it's working, no errors. Thank you for the
fix.

wt., 9 lis 2021 o 19:09 Marcin DiGiT ***@***.***> napisał(a):
