### ISSUE TITLE
Attempts to import kubernetes fails - cause its looking at localhost?

### ISSUE THREAD

**Issue by npsoni88** [GoogleCloudPlatform/terraformer#1093]
Hey folks,

I am trying to import a bunch from deployments from a namespace to understand how terraformer works. Mine just fails outright and the errors suggest its looking for the resources on localhost instead of hitting the cluster's API Server. Here's a snippet of the output.

2021/10/18 13:37:43 Refreshing state... kubernetes_deployment.tfer--default-002F-golang-002D-ex-002D-git
2021/10/18 13:37:44 Get "http://localhost/apis/apps/v1/namespaces/xxx/deployments/ayyy": dial tcp 127.0.0.1:80: connect: connection refused
2021/10/18 13:37:44 WARN: Fail read resource from provider, wait 300ms before retry
2021/10/18 13:37:44 Refreshing state... kubernetes_deployment.tfer--xx-002D-xx-002D-xx-002D-dev-002F-xx-002D-xx-002D-graphql-002D-dev
2021/10/18 13:37:44 Fail read resource from provider, trying import command
2021/10/18 13:37:44 Get "http://localhost/apis/apps/v1/namespaces/openshift-cluster-storage-operator/deployments/csi-snapshot-controller-operator": dial tcp 127.0.0.1:80: connect: connection refused

I have - 
1. Added a versions.tf which indicated kubernetes as a provider and ran terraform init.2
2. Ran the command to import deployment objects using terraformer.

Any idea how do I make it interact with the actual API server instead of localhost?

**Comment by jkessel-sray** [comment]
I'm facing the same issue with GKE

**Comment by emostar** [comment]
I'm also having this issue, compiling from master branch.

@juliankessel Which plugin are you referring to as the workaround?

**Comment by emostar** [comment]
So a versions.tf with the below contents works,just make sure to clear out the .terraform* files and call `terraform init` again.

```
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "= 1.13.4"
    }
  }
  required_version = ">= 0.13"
}
```

The version after that is 2.0.0, which is where it tries to connect to localhost. Probably worth opening a ticket in the kubernetes terraform repository, but I'm not sure where the actual problem exists.

**Comment by emostar** [comment]
So further investigation revealed the [2.0.0 migration doc](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide) mentions that it does not default to using `~/.kube/config` by default and the new environment variable `KUBE_CONFIG_PATH` should be used.

Running terraformer like this will work properly:

```
KUBE_CONFIG_PATH=~/.kube/config terraformer import kubernetes --resources=deployments,services,namespaces
```
