### ISSUE TITLE
Terrraformer AWS import: Filters does not work

### ISSUE THREAD

**Issue by jobinpresidio** [GoogleCloudPlatform/terraformer#1119]
_```
terraformer % terraformer import aws --resources=rds --filter="Type=db_instance;Name=tags.name;Value=testing" --regions=us-east-1 
2021/11/01 18:08:42 aws importing region us-east-1
2021/11/01 18:08:47 aws importing... rds
2021/11/01 18:08:51 aws done importing rds
2021/11/01 18:08:51 Number of resources for service rds: 35
```_

While trying to import a single resource from the AWS rds console, i get all the 35 resources in RDS  😑

Can anyone please guide me on how to use filters / resolve this?

**Comment by sunil29feb** [comment]
Please try removing Type and its value and test-
terraformer import aws --resources=rds --filter="Name=tags.name;Value=testing" --regions=us-east-1

**Comment by gliptak** [comment]
Thank you @sunil29feb below worked for me

```
terraformer import aws --resources=s3 --filter "Name=id;Value=mybucket"
```

**Comment by rajaie-sg** [comment]
I was also running into this problem. Solution above worked for me.
