### ISSUE TITLE
Azure || network_security_group || [ERR]: duplicate resource found: azurerm_network_security_group.tfer--

### ISSUE THREAD

**Issue by sunil29feb** [GoogleCloudPlatform/terraformer#1127]
Two different resource groups can have network security group with same name in azure. If we try to get all network security group for a subscription, then Terraformer throws an error " [ERR]: duplicate resource found: azurerm_network_security_group.tfer--<nsg name> ".

**Comment by TxusBlack** [comment]
Hi everyone, I have this error with the version 0.8.24.

![image](https://github.com/GoogleCloudPlatform/terraformer/assets/13071556/22e067ed-e8df-4c71-90f7-9dd1293974ea)
