### ISSUE TITLE
okta problems

### ISSUE THREAD

**Issue by devopsrick** [GoogleCloudPlatform/terraformer#1129]
None of the new Okta app resources will import for me.

https://github.com/GoogleCloudPlatform/terraformer/pull/1030 

I get the following errors.

> 2021/11/04 08:43:04 okta importing... okta_app_auto_login
> 2021/11/04 08:43:07 okta error initializing resources in service okta_app_auto_login, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:07 okta importing... okta_app_basic_auth
> 2021/11/04 08:43:08 okta error initializing resources in service okta_app_basic_auth, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:08 okta importing... okta_app_bookmark
> 2021/11/04 08:43:10 okta error initializing resources in service okta_app_bookmark, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:10 okta importing... okta_app_oauth
> 2021/11/04 08:43:12 okta error initializing resources in service okta_app_oauth, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:12 okta importing... okta_app_saml
> 2021/11/04 08:43:13 okta error initializing resources in service okta_app_saml, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:13 okta importing... okta_app_secure_password_store
> 2021/11/04 08:43:15 okta error initializing resources in service okta_app_secure_password_store, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:15 okta importing... okta_app_swa
> 2021/11/04 08:43:16 okta error initializing resources in service okta_app_swa, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:16 okta importing... okta_app_three_field
> 2021/11/04 08:43:17 okta error initializing resources in service okta_app_three_field, err: json: cannot unmarshal object into Go value of type okta.App
> 2021/11/04 08:43:17 okta importing... okta_app_user_schema
> 2021/11/04 08:43:18 okta error initializing resources in service okta_app_user_schema, err: json: cannot unmarshal object into Go value of type okta.App

**Comment by hstringa01** [comment]
I have the same issue.

**Comment by okta-mikeb** [comment]
Same issue, please advise

**Comment by sergeylanzman** [comment]
fixed
