### ISSUE TITLE
Allow specifying profile from the AWS credentials file

### ISSUE THREAD

**Issue by caseyclarkjamf** [GoogleCloudPlatform/terraformer#114]
An option similar to the `--profile` parameter in the AWS CLI would be useful when working with multiple AWS accounts that require different set of credentials. 

Thanks!

**Comment by sergeylanzman** [comment]
Current solution for profile here
https://github.com/GoogleCloudPlatform/terraformer/issues/45#issuecomment-502340887

**Comment by meshuga** [comment]
I added #123 where it is no longer necessary to use `assume-role`, profile can be selected with `--profile` parameter. MFA code is prompted from application, which I think is fine for this kind of tool. The generated temporary access code is then passed to TF.
