### ISSUE TITLE
Runtime panic while importing resources from AWS:  interface conversion: interface {} is map[string]interface {}, not string

### ISSUE THREAD

**Issue by ycd** [GoogleCloudPlatform/terraformer#1145]
**What did you do?**

1. Ran the following command
```zsh
terraformer import aws --regions="us-east-1"  --resources="*"
```

Got the following output:

```zsh 
goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0xc003874520, 0x10, 0x5cf2fad}, {0xc0035e4a98, 0x0}, {0xc001d794a0, 0x2d}, {0x56a6b40, 0xc0018c3830})
        /Users/sergey/temp/terraformer/terraformutils/walk.go:102 +0x965
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0x5d155c5, 0xc0011290b0}, {0xc0035e4a98, 0x15}, {0xc001d794a0, 0x58}, {0x56a6b40, 0xc0018c3830})
        /Users/sergey/temp/terraformer/terraformutils/walk.go:34 +0x8a
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc000fbc0c0, {0x5d06254, 0xc}, {0xc0023e6f78, 0x2, 0xc001ee5dc0}, {0xc0013a6a00, 0xc003845b80, 0x0, {0xc00168a9a0, ...}, ...}, ...)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:54 +0x365
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc000a44be0, 0x1, 0x5cfdeed)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:31 +0x393
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0x67c7ec8, 0xc000a44be0}, 0x5cf4420)
        /Users/sergey/temp/terraformer/cmd/import.go:223 +0x155
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(_, {{0xc000a8d000, 0x51, 0x80}, {0x8328e68, 0x0, 0x0}, {0x5d5a5ed, 0x1e}, {0x5cfd2b1, ...}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:191 +0x3b3
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc000a8d000, 0x51, 0x80}, {0x8328e68, 0x0, 0x0}, {0x5d5a5ed, 0x1e}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:106 +0x319
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc00091d9b0, 0x1, 0x1}, {0x8328e68, 0x0, 0x0}, {0x5d5a5ed, 0x1e}, {0x5cfd2b1, 0x9}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:112 +0x278
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00030c840, {0x5cf42dc, 0x2, 0x2})
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:51 +0x36e
github.com/spf13/cobra.(*Command).execute(0xc00030c840, {0xc000a5c7a0, 0x2, 0x2})
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030c000)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /Users/sergey/temp/terraformer/cmd/root.go:36 +0x1e
main.main()
        /Users/sergey/temp/terraformer/main.go:39 +0x35
```

Which is caused by this line:

https://github.com/GoogleCloudPlatform/terraformer/blob/11cf110af0b6f838799e8a96b2bde3d06d25a9da/terraformutils/walk.go#L102

**versions.tf** file:

```tf
terraform {
  required_providers {
     aws = {
      source = "hashicorp/aws"
    }
  }
  required_version = ">= 0.13"
}
```

* Terraformer version: `Terraformer v0.8.18`
* Terraform version: `Terraform v1.0.1` 
* Provider version: `provider registry.terraform.io/hashicorp/aws v3.64.`

**Comment by justin-stubbs** [comment]
+1 also having this issue:

command:

`terraformer import aws --resources="*" --regions=ap-southeast-2 --excludes organization,accessanalyzer -v`

```
$ terraformer -v
version v0.8.18

```

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.67.0"
    }
  }
}
```

```
2021/11/30 10:31:39 aws Connecting.... 
2021-11-30T10:31:39.755+1100 [DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-11-30T10:31:39.761+1100 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.67.0/linux_amd64/terraform-provider-aws_v3.67.0_x5 pid=22225
2021-11-30T10:31:39.762+1100 [DEBUG] plugin: plugin exited
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0xc0029c2a50, 0x10, 0x50ed10e}, {0xc000c4d9c8, 0x0}, {0xc0029ba8a0, 0x2d}, {0x4aa2220, 0xc0025888a0})
        /Users/sergey/temp/terraformer/terraformutils/walk.go:102 +0x965
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0x510f998, 0xc001938510}, {0xc000c4d9c8, 0x15}, {0xc0029ba8a0, 0x58}, {0x4aa2220, 0xc0025888a0})
        /Users/sergey/temp/terraformer/terraformutils/walk.go:34 +0x8a
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc001938930, {0x5100588, 0xc}, {0xc001c32f78, 0x2, 0xc000f92b80}, {0xc000b9e0a0, 0xc001f84ff0, 0x0, {0xc000b980e0, ...}, ...}, ...)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:54 +0x365
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc000785860, 0x1, 0x50f81b9)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:31 +0x393
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0x5bc1808, 0xc000785860}, 0x50ed3be)
        /Users/sergey/temp/terraformer/cmd/import.go:223 +0x155
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(_, {{0xc0007fd000, 0x4f, 0x80}, {0xc0007a32e0, 0x2, 0x2}, {0x5154b82, 0x1e}, {0x50f744b, ...}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:191 +0x3b3
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc0007fd000, 0x4f, 0x80}, {0xc0007a32e0, 0x2, 0x2}, {0x5154b82, 0x1e}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:106 +0x319
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc0004b77a0, 0x1, 0x1}, {0xc0007a32e0, 0x2, 0x2}, {0x5154b82, 0x1e}, {0x50f744b, 0x9}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:112 +0x278
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00012b340, {0x50ee438, 0x5, 0x5})
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:51 +0x36e
github.com/spf13/cobra.(*Command).execute(0xc00012b340, {0xc0007857c0, 0x5, 0x5})
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012a000)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /Users/sergey/temp/terraformer/cmd/root.go:36 +0x1e
main.main()
        /Users/sergey/temp/terraformer/main.go:39 +0x35
```

**Comment by FelipeMartinez10** [comment]
@justin-stubbs Did you find a solution?

**Comment by dreampuf** [comment]
I got the same issue.

**Comment by justin-stubbs** [comment]
> @justin-stubbs Did you find a solution?

No unfortunately, I tried older version combinations as well no luck :(

**Comment by martineslon** [comment]
Seems I have same issue:
version v0.8.18
Terraform v1.1.3
provider[registry.terraform.io/hashicorp/aws] ~> 3.25

...
2022/02/02 22:36:06 aws Connecting....
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0x14003539b70, 0x1, 0x1}, {0x140027c8e70, 0x15}, {0x140030b2c60, 0x58}, {0x10b307da0, 0x14001e6a990})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:102 +0x97c
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0x109c45160, 0x10}, {0x140027c8e70, 0x15}, {0x140030b2c60, 0x58}, {0x10b307da0, 0x14001e6a990})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:34 +0x9c
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0x140024f73e0, {0x109c2bc0f, 0xc}, {0x14002b4eee0, 0x2, 0x2}, {0x1400199fe50, 0x14002e17b80, 0x0, {0x14001307820, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:54 +0x33c
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0x140024f73e0, 0x1, 0x140024f7440)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:31 +0x2c4
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0x10c89d0e8, 0x14000594820}, 0x14001797b80)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:223 +0x14c
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(0x14002b4f758, {{0x14001868000, 0x51, 0x80}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, {0x109c1d0dd, ...}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:191 +0x3d0
github.com/GoogleCloudPlatform/terraformer/cmd.Import({0x10c89d0e8, 0x14000594820}, {{0x14001868000, 0x51, 0x80}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:106 +0x27c
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0x1400170dbc0, 0x1, 0x1}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, {0x109c1d0dd, 0x9}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x294
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0x140016e5600, {0x1400183cc90, 0x0, 0x3})
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x364
github.com/spf13/cobra.(*Command).execute(0x140016e5600, {0x1400183cc60, 0x3, 0x3})
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140016e4840)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x404
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x24
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x50

**Comment by goldencut** [comment]
Seems I have same issue:
version v0.8.18
Terraform v1.1.3
provider[registry.terraform.io/hashicorp/aws] ~> 3.25


$ terraformer import aws --resources="*" --profile=mfa --regions=us-east-1

...[I deleted some lines here]...

2022/02/02 22:36:06 Filtered number of resources for service waf: 0
2022/02/02 22:36:06 aws Connecting....
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0x14003539b70, 0x1, 0x1}, {0x140027c8e70, 0x15}, {0x140030b2c60, 0x58}, {0x10b307da0, 0x14001e6a990})
github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:102 +0x97c
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0x109c45160, 0x10}, {0x140027c8e70, 0x15}, {0x140030b2c60, 0x58}, {0x10b307da0, 0x14001e6a990})
github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:34 +0x9c
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0x140024f73e0, {0x109c2bc0f, 0xc}, {0x14002b4eee0, 0x2, 0x2}, {0x1400199fe50, 0x14002e17b80, 0x0, {0x14001307820, ...}, ...}, ...)
github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:54 +0x33c
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0x140024f73e0, 0x1, 0x140024f7440)
github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:31 +0x2c4
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0x10c89d0e8, 0x14000594820}, 0x14001797b80)
github.com/GoogleCloudPlatform/terraformer/cmd/import.go:223 +0x14c
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(0x14002b4f758, {{0x14001868000, 0x51, 0x80}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, {0x109c1d0dd, ...}, ...}, ...)
github.com/GoogleCloudPlatform/terraformer/cmd/import.go:191 +0x3d0
github.com/GoogleCloudPlatform/terraformer/cmd.Import({0x10c89d0e8, 0x14000594820}, {{0x14001868000, 0x51, 0x80}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, ...}, ...)
github.com/GoogleCloudPlatform/terraformer/cmd/import.go:106 +0x27c
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0x1400170dbc0, 0x1, 0x1}, {0x1127b7da8, 0x0, 0x0}, {0x109caf07a, 0x1e}, {0x109c1d0dd, 0x9}, ...}, ...)
github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x294
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0x140016e5600, {0x1400183cc90, 0x0, 0x3})
github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x364
github.com/spf13/cobra.(*Command).execute(0x140016e5600, {0x1400183cc60, 0x3, 0x3})
github.com/spf13/cobra@v1.1.1/command.go:850 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x140016e4840)
github.com/spf13/cobra@v1.1.1/command.go:958 +0x404
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x24
main.main()
github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x50
