### ISSUE TITLE
import AWS ebs fails: Panic: interface conversion: interface {} is map[string]interface {}, not string 

### ISSUE THREAD

**Issue by based3** [GoogleCloudPlatform/terraformer#1147]
'terraformer import aws -r ec2_instance,ebs,eip --regions=eu-west-X'

2021/11/11 19:09:31 Filtered number of resources for service ec2_instance: 10
2021/11/11 19:09:31 Filtered number of resources for service ebs: 8
2021/11/11 19:09:31 Filtered number of resources for service eip: 0

2021/11/11 19:09:31 aws Connecting.... 
panic: interface conversion: interface {} is map[string]interface {}, not string

--
goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride({0xc000c0f2a0, 0x10, 0x99bd74d}, {0xc0016be180, 0x0}, {0xc001948660, 0xc0019fac68}, {0x8778200, 0xc0019c8ba0})
        /terraformer/terraformutils/walk.go:102 +0x965
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride({0x99f5583, 0x1}, {0xc0016be180, 0x15}, {0xc001948660, 0x58}, {0x8778200, 0xc0019c8ba0})
        /terraformer/terraformutils/walk.go:34 +0x8a
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc001ad7080, {0x99dbe45, 0xc}, {0xc00354ef78, 0x2, 0xc001aa0800}, {0xc000ec6730, 0xc00162cdc0, 0x0, {0xc0013c6140, ...}, ...}, ...)
        /terraformer/terraformutils/connect.go:54 +0x365
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc000110370, 0x1, 0x99ce7b5)
        /terraformer/terraformutils/connect.go:31 +0x393
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan({0xaa4b2d0, 0xc000110370}, 0xc0007cc087)
        /terraformer/cmd/import.go:223 +0x155
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(_, {{0xc00019d400, 0x3, 0x4}, {0x10ccf6c0, 0x0, 0x0}, {0x9a60350, 0x1e}, {0x99cd159, ...}, ...}, ...)
        /terraformer/cmd/import.go:191 +0x3b3
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc00019d400, 0x3, 0x4}, {0x10ccf6c0, 0x0, 0x0}, {0x9a60350, 0x1e}, ...}, ...)
        /terraformer/cmd/import.go:106 +0x319
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc00019d380, 0x3, 0x4}, {0x10ccf6c0, 0x0, 0x0}, {0x9a60350, 0x1e}, {0x99cd159, 0x9}, ...}, ...)
        /terraformer/cmd/provider_cmd_aws.go:112 +0x278
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0011f5b80, {0x99bfbc2, 0x3, 0x3})
        /terraformer/cmd/provider_cmd_aws.go:51 +0x36e
github.com/spf13/cobra.(*Command).execute(0xc0011f5b80, {0xc0016a54a0, 0x3, 0x3})
        /home/XXXX/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011f4dc0)
        /home/XXXX/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/XXXX/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()

ebs seems failing, as i got a success with 'terraformer import aws -r ec2_instance,eip --regions=eu-west-X'

thanks,

**Comment by based3** [comment]
Context:

> terraform version
Terraform v1.0.10
on linux_amd64

> terraformer -v
version v0.8.18

Others issues (duplicates!):

- https://github.com/GoogleCloudPlatform/terraformer/issues/1130
 
  https://github.com/hashicorp/terraform-provider-aws/issues/21633

- https://github.com/GoogleCloudPlatform/terraformer/issues/1060

   https://github.com/GoogleCloudPlatform/terraformer/issues/1071

- https://github.com/GoogleCloudPlatform/terraformer/issues/1055   EC2 and deleted the EBS

- https://github.com/GoogleCloudPlatform/terraformer/issues/1145

**Comment by based3** [comment]
go reference: https://bitfieldconsulting.com/golang/map-string-interface

**Comment by bugcy013** [comment]
@based3 did you find any workaround for this issue. I am also facing the same error.

**Comment by FelipeMartinez10** [comment]
Any update on this?

**Comment by liamstevens** [comment]
I have also run into this issue when targeting ec2_instances specifically.
