### ISSUE TITLE
An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"

### ISSUE THREAD

**Issue by bugcy013** [GoogleCloudPlatform/terraformer#1149]
Hi Team,

I am trying to import resources from azure I am getting this error. can you please help with this?

```
➜ terraformer version                                                             
Terraformer v0.8.18
```

```
➜ terraformer plan azure --output hcl --resource-group JumpServer -r "*" --verbose                       
2021/11/13 22:03:59 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/11/13 22:03:59 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/11/13 22:03:59 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/11/13 22:03:59 Testing if Managed Service Identity is applicable for Authentication..
2021/11/13 22:03:59 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/11/13 22:03:59 Using Obtaining a token from the Azure CLI for Authentication
2021/11/13 22:03:59 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```

Please guide me, how to fix this.

Thanks
-Dhanasekaran.

**Comment by erbeh77** [comment]
Same Issue:

2021/11/24 14:10:21 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/11/24 14:10:21 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/11/24 14:10:21 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/11/24 14:10:21 Testing if Managed Service Identity is applicable for Authentication..
2021/11/24 14:10:21 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/11/24 14:10:21 Using Obtaining a token from the Azure CLI for Authentication
2021/11/24 14:10:21 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"

version v0.8.18
$ENV:ARM_ENVIRONMENT     = "AzureCloud"

**Comment by Derek-Ashmore** [comment]
I'm having the exact same issue -- any help appreciated!

**Comment by Derek-Ashmore** [comment]
I also got the same issue for 0.8.17.  Does anybody know when the last working version for Azure was?

**Comment by huzaifa-dot** [comment]
Facing the same issue. Did anyone find the solution or last working version of az and terraformer?

**Comment by sunil29feb** [comment]
It seems there is some issue in az version. Below az version is working for me.
 az version
{
  "azure-cli": "2.28.1",
  "azure-cli-core": "2.28.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by danmanners** [comment]
Running into this as well.

```bash
➜  homelab-k3s-terraform git:(main) ✗ terraformer import azure -r "*"       
2021/12/23 13:21:19 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/12/23 13:21:19 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/12/23 13:21:19 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/12/23 13:21:19 Testing if Managed Service Identity is applicable for Authentication..
2021/12/23 13:21:19 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/12/23 13:21:19 Using Obtaining a token from the Azure CLI for Authentication
2021/12/23 13:21:19 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```

**Comment by danmanners** [comment]
It would appear things are functional now, but I'm not entirely sure why

The only things I've done that I am aware of are:
- Install the latest version of the Azure CLI
- Downgraded to 2.28
- Upgraded back up to latest version again

Interestingly, it still was not working for a while, and then it magically was. Could it have been tied to an auth token expiration with Azure? Happy to provide any other information to help folks troubleshoot.

**Comment by mhgrichlee** [comment]
Same error here.  I've tried the above and AZ CLI 2.32.  Still not working with the "An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD" error

**Comment by dd-ctss** [comment]
I had the same issue with Azure-cli version 2.32, so I downloaded the Windows msi installer for version 2,28.0 from this link https://github.com/Azure/azure-cli/releases/download/azure-cli-2.28.0/azure-cli-2.28.0.msi, installed it, and set the environment variable in an Admin level CMD console session to "set ARM_SUBSCRIPTION_ID=<subscriptionid>" (Note the subscriptionid value is 36 characters). using this version worked with an az login session, and did not produce the AZURECLOUD error.

**Comment by wplj** [comment]
> I had the same issue with Azure-cli version 2.32, so I downloaded the Windows msi installer for version 2,28.0 from this link https://github.com/Azure/azure-cli/releases/download/azure-cli-2.28.0/azure-cli-2.28.0.msi, installed it, and set the environment variable in an Admin level CMD console session to "set ARM_SUBSCRIPTION_ID=" (Note the subscriptionid value is 36 characters). using this version worked with an az login session, and did not produce the AZURECLOUD error.

Didn't work for me with az cli 2.28 either, the same issue.

**Comment by dreh23** [comment]
Same error in Ubuntu Focal 22..04 with:
```
terraformer --version
version v0.8.18
```
and
az version
{
  "azure-cli": "2.33.0",
  "azure-cli-core": "2.33.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

**Comment by ION28** [comment]
Also receiving this same error and various upgrades/downgrades/re-upgrades of the Azure CLI did not fix it for me :(

**Comment by nvasion** [comment]
This is still happening for me as well. Downgrading and upgrading did not work as well.

**Comment by dd-ctss** [comment]
This problem is the result of changes to the Azure-cli code, that really needs to be fixed. I found the only way to use an az login session, was to download and use, the **Windows** msi installer for version 2.28.0 from this link https://github.com/Azure/azure-cli/releases/download/azure-cli-2.28.0/azure-cli-2.28.0.msi as per my previous post above from 12th Jan 2022.

**Comment by ashleywb** [comment]
I've downgraded to 2.28.0 and still get this issue, any other ideas? If not, are there any alternatives to Terraformer?

**Comment by ION28** [comment]
> I've downgraded to 2.28.0 and still get this issue, any other ideas? If not, are there any alternatives to Terraformer?

Are you using the Windows version 2.28 of the azure cli? That's what I needed to do

**Comment by ashleywb** [comment]
Windows version 2.28
![image](https://user-images.githubusercontent.com/9212081/162691834-3a976cab-4b52-4ea9-92f3-1fb125a22105.png)

**Comment by ION28** [comment]
> Windows version 2.28
> ![image](https://user-images.githubusercontent.com/9212081/162691834-3a976cab-4b52-4ea9-92f3-1fb125a22105.png)
> 

Do you by chance have a screenshot of the error that is still occurring by chance? The steps that do seem to work currently are: 
- install 2.28.0 
- run terraform init with a versions.tf to install the azure terraform provider if not already present 
- run az login and follow the prompts 
- set the environment variable (see above comments)
- run terraformer azure

**Comment by pguan-ntap** [comment]
This looks like the same error described in https://github.com/GoogleCloudPlatform/terraformer/issues/654

**Comment by lukasz-cpu** [comment]
Have the same issue, just leaving the tactical comment to observe the topic.
