### ISSUE TITLE
aws: `tag_all` should be excluded in the generated resource

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/terraformer#1152]
It looks like currently in the generated the resource it has `tag_all` ready only attribute. So instead of having 

```
resource "aws_vpc" "example" {
  # ... other configuration ...

  tags = {
    Name = "MyVPC"
  }

  tags_all = {
    Name = "MyVPC"
  }  
}
```

The generated resource would be like this:

```
resource "aws_vpc" "example" {
  # ... other configuration ...

  tags = {
    Name = "MyVPC"
  }

}
```

**Comment by based3** [comment]
This may be linked to workaround https://github.com/hashicorp/terraform-provider-aws/issues/18311

**Comment by olenm** [comment]
I am a fan of seeing a distinction of the source of the tags by resource items vs `tags_all` which is based upon the provider's `default_tags` and the resources `tags` (but prioritizes the items within `default_tags`) - perhaps indicating in the generated resource it is read only may do the trick?


Also re-naming `default_tags` to something more descriptive based upon the nature of what it does maybe wise; such as `enforced_tags` - though last I checked some resources that have a `tags` input do not always get `default_tags` items.
