### ISSUE TITLE
Github import: fork/exec : no such file or directory

### ISSUE THREAD

**Issue by f3l1x** [GoogleCloudPlatform/terraformer#1153]
Hello. I'm hitting `fork/exec : no such file or directory` calling `terraformer import`.

Platform: MacOS
Version: 12.0.1
Terraform: 1.0.11

I've tried:

1. brew install terraformer
2. brew install --HEAD terraformer
3. github releases

 ```
export PROVIDER={all,google,aws,kubernetes}
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64
chmod +x terraformer-${PROVIDER}-darwin-amd64
sudo mv terraformer-${PROVIDER}-darwin-amd64 /usr/local/bin/terraformer
```

But not luck.

```
➜ terraformer import github --owner=example --resources=repositories
2021/11/20 12:55:13 github importing organization example
2021/11/20 12:55:13 fork/exec : no such file or directory
```

Thank you for your help.

**Comment by kecskemethy** [comment]
Hi @f3l1x ,

This is the missing terraform github provider plugin problem afaik. (at least I had similar issue with aws)
So basically you need to get github terraform provider plugin in place either using `terraform init` or manually unzip it to dir ~/.terraform.d/plugins/darwin_amd64

for manual download go here: https://releases.hashicorp.com/terraform-provider-github/
for terraform init you need to create provider.tf ...

Cheers, Zoltan

ps: this is similar to #1171
