### ISSUE TITLE
GCP: fail import KMS on global region

### ISSUE THREAD

**Issue by cikupin** [GoogleCloudPlatform/terraformer#1161]
Hi, I got error when importing KMS on global regions

```shell
$ terraformer import google --resources=kms --projects=my-company-project
2021/11/29 12:32:02 google importing project my-company-project region global
2021/11/29 12:32:03 googleapi: Error 404: The resource 'projects/my-company-project/regions/global' was not found, notFound
2021/11/29 12:32:04 googleapi: Error 404: The resource 'projects/my-company-project/regions/global' was not found, notFound
2021/11/29 12:32:04 google importing... kms
2021/11/29 12:32:05 google done importing kms
2021/11/29 12:32:05 Number of resources for service kms: 2
2021/11/29 12:32:05 Refreshing state... google_kms_crypto_key.tfer--my-company-project_global_sops_sops-key
2021/11/29 12:32:05 Refreshing state... google_kms_key_ring.tfer--global_sops
2021/11/29 12:32:06 ERROR: Read resource response is null for resource google_kms_crypto_key.tfer--my-company-project_global_sops_sops-key
2021/11/29 12:32:06 ERROR: Unable to refresh resource tfer--my-company-project_global_sops_sops-key
2021/11/29 12:32:06 Filtered number of resources for service kms: 1
2021/11/29 12:32:06 google Connecting.... 
2021/11/29 12:32:06 google save kms
2021/11/29 12:32:06 google save tfstate for kms
```

1. Why it's asking for `regions/` ? it should use `locations/` based on this [API documentation](https://cloud.google.com/kms/docs/reference/rest). And it cannot refresh the resources.

2. It also cannot produce kms_crypto_key terraform file. My key ring actually have its keys. Terraformer just cannot produce it.

![Screen Shot 2021-11-29 at 12 57 21](https://user-images.githubusercontent.com/9508513/143817300-1ca2d94c-9999-44d3-acbc-5b22b72ee0e5.png)

How to fix these?

**Comment by tfgstudios** [comment]
I also get errors about the global region. I'm looking to export the entire project to migrate to IaaC, but having problems.
Were you able to find a solution?

**Comment by nyarly** [comment]
I'm seeing the same issue. Could we re-open this?

**Comment by tsener-qb** [comment]
hitting the same one

**Comment by abower-digimarc** [comment]
I also have the same issue. Whether I use the --resources flag or not, I get an error:

importing project myproject region global

error 404 the resource 'myproject' was not found.

I am not sure why it's looking for 'myproject' as a resource, when that's actually the project in GCP.

**Comment by laithalissa** [comment]
In my sitation this error was misleading- the real error was I was operating outside of an initialised terraform environment. After creating a `providers.tf` file and executing `terraform init` the import command worked, but it it still reported the 404 error, which didn't seem to be a problem.
