### ISSUE TITLE
Force to use terraform 0.12

### ISSUE THREAD

**Issue by julienpierini** [GoogleCloudPlatform/terraformer#117]
Hi,

I want to generate a tfstate an tf file in version `0.12`, but i can't my files are generated in version use in go.mod `0.11.12`. I use terraform version `0.12.2` and terraformer version `0.7.4`.

Thanks !

**Comment by sergeylanzman** [comment]
same issue
https://github.com/GoogleCloudPlatform/terraformer/issues/119

**Comment by sergeylanzman** [comment]
@meshuga working on this(Thanks!!!) here(https://github.com/GoogleCloudPlatform/terraformer/compare/master...meshuga:tf_12)

**Comment by sergeylanzman** [comment]
merged to master
https://github.com/GoogleCloudPlatform/terraformer/pull/181
