### ISSUE TITLE
Error running terraformer-google: fork/exec : no such file or directory

### ISSUE THREAD

**Issue by webpwnized** [GoogleCloudPlatform/terraformer#1171]
/opt/terraformer/terraformer-google import google --resources="*" --projects=_project_ --regions=us-central1
google importing project _project_ region us-central1
Attempting an import of ALL resources in google
**fork/exec : no such file or directory**

**Linux version**: Linux 5.11.0-41-generic #45~20.04.1-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by kecskemethy** [comment]
Hi @webpwnized ,

  This is the missing terraform google provider plugin problem afaik. (at least I had similar issue with aws)
So basically you need to get google terraform provider plugin in place either using `terraform init` or manually unzip it to dir ~/.terraform.d/plugins/linux_amd64 (this is for linux).

Cheers, Zoltan
