### ISSUE TITLE
AWS Record wont export anymore

### ISSUE THREAD

**Issue by julienpierini** [GoogleCloudPlatform/terraformer#118]
Hi,

The `record.SetIdentifier` will cause no record to be exported at all.
fix -> remove it from line 82, 83 and in the map line 90.

https://github.com/GoogleCloudPlatform/terraformer/blob/7ad90c5847b94e276aaaf93f271be1cb8b186a28/providers/aws/route53.go#L82

**Comment by sergeylanzman** [comment]
bug in https://github.com/GoogleCloudPlatform/terraformer/pull/106/files

**Comment by sergeylanzman** [comment]
I tested route53 and it's work.
Can you please write you example
Terraform version
Aws provider version
Records type
