### ISSUE TITLE
Building for one provider results in --resources flag is unkown error

### ISSUE THREAD

**Issue by thacoon** [GoogleCloudPlatform/terraformer#1184]
I wanted to build terraformer for only one provider but I encoutered the same error as in #348, that the `--resources` flag is unkown. However, if I build for all providers it works.

See my steps below to reproduce:

```
$ git clone https://github.com/GoogleCloudPlatform/terraformer.git \
        && cd terraformer/ \
        && go mod download

$ go run build/main.go {aws} 
$ go build -v 

# Init terraform with aws as requried provider

$ ./terraformer-{aws} import aws --resources=vpc,subnet --filter=vpc=myvpcid --regions=eu-west-1
2022/01/03 10:46:35 unknown flag: --resources

$ ./terraformer import aws --resources=vpc,subnet --filter=vpc=myvpcid --regions=eu-west-1
2022/01/03 10:48:39 aws importing region eu-west-1
```

**Comment by sunil29feb** [comment]
@thacoon - 
Try building and use terraformer binary for AWS like this.
1.go run build/main.go aws
2. ./terraformer-aws import aws --resources=vpc,subnet --filter=vpc=myvpcid --regions=eu-west-1
3.

**Comment by thacoon** [comment]
@sunil29feb thank you, your solution works.
