### ISSUE TITLE
Can't Import CloudFront Distribution

### ISSUE THREAD

**Issue by jamiejackson** [GoogleCloudPlatform/terraformer#1187]
I've been meaning to try terraformer for a while since importing existing resources is a pain with plain terraform (at least the workflow that I've figured out).

However, I tried terraformer for the first time today and got this:

```sh
$ terraformer import aws --resources=aws_cloudfront_distribution --filter=aws_cloudfront_distribution=ERL68G1N67ZUY
2022/01/06 15:28:16 aws importing default region
2022/01/06 15:28:17 aws importing... aws_cloudfront_distribution
2022/01/06 15:28:17 aws error importing aws_cloudfront_distribution, err: aws: aws_cloudfront_distribution not supported service
2022/01/06 15:28:17 aws Connecting.... 
```

So either I've got the syntax wrong or Terraformer doesn't support CloudFront Distributions.

What's the scoop? 

Thanks.

**Comment by jamiejackson** [comment]
I'm getting closer:

```sh
 terraformer import aws --resources=cloudfront --filter=cloudfront=ERL68G1N67ZUY
 ```

That created terraform HCL for all of the CloudFront distributions, which is very cool. Now I've got to figure out how to filter properly.

**Comment by kostyanius** [comment]
the most stupid tool i have ever used. it import all the resources or no one. filtering just does not work. the logic of work of this app is very stupid and not clear for normal people. wasted one hour and get 0 results. documentation i sppor and not cover even common use cases. especially with filtering.

**Comment by etherwitch** [comment]
In case anyone finds this later and needs the answer:
`terraformer import aws -r cloudfront --filter='Name=id;Value=ERL68G1N67ZUY'`
