### ISSUE TITLE
terraformer import aws --resources=glue --regions=us-west-2 receiving the below error.

### ISSUE THREAD

**Issue by hrpitta** [GoogleCloudPlatform/terraformer#1208]
I'm trying to run the terraformer import aws --resources=glue --regions=us-west-2 and I'm receiving the below error message.
2022/01/18 15:36:56 Filtered number of resources for service glue: 314
2022/01/18 15:36:56 aws Connecting....
2022/01/18 15:36:56 aws save glue
2022/01/18 15:36:58 At 8:5: expected: IDENT | STRING | ASSIGN | LBRACE got: SUB

**Comment by Boulet-** [comment]
Hi @hrpitta,

I have a fix for this bug if you want to give it a try in the MR above.
