### ISSUE TITLE
You must complete the Terraform 0.13 upgrade process before upgrading to later versions.

### ISSUE THREAD

**Issue by ishanrakitha** [GoogleCloudPlatform/terraformer#1211]
Hi All,

I have generated the current state and I want to cross check with the existing infra.
Please advise on the below error message.

`
C:\Users\ishan\Documents\Projects\Terraformer\generated\aws\ec2_instance>terraform plan
╷
│ Error: Inconsistent dependency lock file
│
│ The following dependency selections recorded in the lock file are inconsistent with the current configuration:
│   - provider registry.terraform.io/hashicorp/aws: required by this configuration but no version is selected
│
│ To make the initial dependency selections that will initialize the dependency lock file, run:
│   terraform init
╵

C:\Users\ishan\Documents\Projects\Terraformer\generated\aws\ec2_instance>terraform init

Initializing the backend...
╷
│ Error: Invalid legacy provider address
│
│ This configuration or its associated state refers to the unqualified provider "aws".
│
│ You must complete the Terraform 0.13 upgrade process before upgrading to later versions.
╵
`

Thank You.

**Comment by MushiTheMoshi** [comment]
you can downgrade terraform version to latest 0.13.X , this worked for me
