### ISSUE TITLE
ERROR: Read resource response is null for resource aws_lb_target_group_attachment

### ISSUE THREAD

**Issue by amateope** [GoogleCloudPlatform/terraformer#1213]
Hi, I'm new to terraformer sorry. 
I'm trying to get all my resources from AWS and got some errors like below. How could I fix that?
Thanks in advance.

These are my environment versions:

- Terraformer v0.8.18
- Terraform v1.1.4 on linux_amd64
- provider registry.terraform.io/hashicorp/aws v3.73.0

What I'm trying:
`terraformer import aws --path-pattern=./resources/ --regions eu-west-1 --resources=alb`

And the output:
> 2022/01/25 13:43:41 aws importing region eu-west-1
2022/01/25 13:43:45 aws importing... alb
2022/01/25 13:43:47 aws done importing alb
2022/01/25 13:43:47 Number of resources for service alb: 71
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000d
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-redsys-kamailio-2-002F-d122e36cd94e2dd7-2022012512434753810000001b
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000018
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000016
2022/01/25 13:43:47 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-f2f4fbfc0b610770
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000014
2022/01/25 13:43:47 Refreshing state... aws_lb.tfer--k8s-multiasi-multiasi-15a6ab7567
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000013
2022/01/25 13:43:47 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-61209ef5838cf0c4
2022/01/25 13:43:47 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-EcsBo-Priva-PAFPTMB7SFFT-002F-915f5b095eadabd1-002F-7ee4abcd8360f3ff
2022/01/25 13:43:47 Refreshing state... aws_lb.tfer--EcsBo-Priva-PAFPTMB7SFFT
2022/01/25 13:43:47 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-2eb53cb62fe3957b-002F-7b57969182a7ae2c
2022/01/25 13:43:47 Refreshing state... aws_lb_target_group.tfer--redsys-kamailio-2
2022/01/25 13:43:47 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-61209ef5838cf0c4-002F-058facabfb3e5a5e
2022/01/25 13:43:47 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-f2f4fbfc0b610770-002F-e83596d22764f86a
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000013
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-f2f4fbfc0b610770-002F-a05c2ba62cc575ed
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000014
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-8ea5edf6ca594007-002F-fbe514d54e7b1386
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000d
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-phone-target-002F-ef82210eab8f67b0-2022012512434743890000001a
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000016
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-ac481912342469ab-002F-93577b2810ff6ea8
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000018
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000010
2022/01/25 13:43:48 Refreshing state... aws_lb.tfer--redsysLoadBalancer
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-8ea5edf6ca594007-002F-fdee9b16c86fc177
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-20220125124347248900000008
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-ac481912342469ab-002F-fe7f234f6fc24388
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-2022012512434724900000000b
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-2eb53cb62fe3957b-002F-483b732ce09e0f00
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000010
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-phone-target-002F-ef82210eab8f67b0-20220125124347438900000019
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000006
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-2eb53cb62fe3957b-002F-9d9cb2d5aebba5d7
2022/01/25 13:43:48 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-a8dd70a0f093d9d2
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-8ea5edf6ca594007-002F-c85370cdda3551fa
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000006
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000e
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-f2f4fbfc0b610770-002F-56ffc8a8fcd1d97d
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-61209ef5838cf0c4-002F-b7f41dc5ab74cbad
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000f
2022/01/25 13:43:48 Refreshing state... aws_lb.tfer--PhonePlatformLoadBalancer
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-a8dd70a0f093d9d2-002F-44f5f6ee27c5b1e9
2022/01/25 13:43:48 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-net-002F-PhonePlatformLoadBalancer-002F-c8e6a3cda6ab52cd-002F-588fad9d09aa15a6
2022/01/25 13:43:48 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-net-002F-redsysLoadBalancer-002F-74c1015529deaeda-002F-8371214a519cdf13
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000e
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-a8dd70a0f093d9d2-002F-a2095222b5b59c2c
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000f
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-a8dd70a0f093d9d2-002F-4705552c4374c55b
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group.tfer--k8s-multiasi-multiasi-f743b714b9
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-ac481912342469ab-002F-f8b0291b0b0a4f49
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group.tfer--k8s-multiasi-multiasi-387247f390
2022/01/25 13:43:48 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-ac481912342469ab
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-2022012512434724900000000a
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-8ea5edf6ca594007-002F-dcaca9708b20c823
2022/01/25 13:43:48 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-2eb53cb62fe3957b
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-61209ef5838cf0c4-002F-02eea0c57a39c8cb
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-20220125124347248900000009
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group.tfer--phone-target
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000015
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-f2f4fbfc0b610770-002F-5344869753dcf90f
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000005
2022/01/25 13:43:48 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-ac481912342469ab-002F-3161a07c9063c0a0
2022/01/25 13:43:48 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000015
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-2022012512434724900000000c
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group.tfer--k8s-multiasi-multiasi-0a95ef594a
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group.tfer--k8s-multiasi-multiasi-c0d3ee42b1
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000004
2022/01/25 13:43:48 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000011
2022/01/25 13:43:49 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000017
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000004
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group.tfer--EcsBotCluster-drop-2
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182200000001
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182200000001
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000002
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000002
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-387247f390-002F-314262939f98023d-20220125124347248800000007
2022/01/25 13:43:54 Refreshing state... aws_lb_listener.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-8ea5edf6ca594007
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000003
2022/01/25 13:43:54 Refreshing state... aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000012
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000011
2022/01/25 13:43:54 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-2eb53cb62fe3957b-002F-d0d65103d6f3cc92
2022/01/25 13:43:54 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-61209ef5838cf0c4-002F-a71a06cd70cd6973
2022/01/25 13:43:54 Refreshing state... aws_lb_listener_rule.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-listener-rule-002F-app-002F-k8s-multiasi-multiasi-15a6ab7567-002F-088982351ec0e0d8-002F-a8dd70a0f093d9d2-002F-4553dff95f59117f
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000003
2022/01/25 13:43:54 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000012
2022/01/25 13:44:00 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000017
2022/01/25 13:44:04 ERROR: Read resource response is null for resource aws_lb_target_group_attachment.tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000005
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000d
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000018
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000016
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000014
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382700000013
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000010
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000006
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000e
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-2022012512434731410000000f
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000015
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182400000005
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000004
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000011
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-f743b714b9-002F-551d8589ade0487c-20220125124347382800000017
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182200000001
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000002
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-0a95ef594a-002F-e6f56954d7d89b6e-20220125124347182300000003
2022/01/25 13:44:04 ERROR: Unable to refresh resource tfer--arn-003A-aws-003A-elasticloadbalancing-003A-eu-west-1-003A-126162035971-003A-targetgroup-002F-k8s-multiasi-multiasi-c0d3ee42b1-002F-03a4ad4d64d85a24-20220125124347314200000012
2022/01/25 13:44:04 Filtered number of resources for service alb: 53
2022/01/25 13:44:04 aws Connecting....
2022/01/25 13:44:04 aws save
2022/01/25 13:44:04 aws save tfstate

**Comment by fpultera** [comment]
I have a same issue.
Terraformer v0.8.24
Terraform v1.5.7 on darwin_arm64
provider registry.terraform.io/hashicorp/aws  "~> 5.0"
