### ISSUE TITLE
Okta app import issue

### ISSUE THREAD

**Issue by hstringa01** [GoogleCloudPlatform/terraformer#1222]
Hello,
I receive the following error during Okta import. It seems fine for other resources aside from app.

terraformer import okta --resources=okta_app_saml 
2022/02/02 20:43:36 okta error initializing resources in service okta_app_saml, err: json: cannot unmarshal object into Go value of type okta.App

**Comment by devopsrick** [comment]
I have the same issue.  @noinarisak looks like you added the support for it, any insight why this might be happening for us?

**Comment by timbaileyjones** [comment]
I'm not even getting that far.

❯ terraformer import okta import --resources=okta_app_oauth,okta_group
2022/02/16 11:01:00 open /Users/tim_bailey-jones/.terraform.d/plugins/darwin_amd64: no such file or directory

Looks like I have to copy the okta provider binary directory under the plugins directory?

**Comment by hstringa01** [comment]
> I'm not even getting that far.
> 
> ❯ terraformer import okta import --resources=okta_app_oauth,okta_group 2022/02/16 11:01:00 open /Users/tim_bailey-jones/.terraform.d/plugins/darwin_amd64: no such file or directory
> 
> Looks like I have to copy the okta provider binary directory under the plugins directory?

After I downloaded it, I copied the okta provider: sudo mv terraformer-okta-darwin-amd64 /usr/local/bin/terraformer

**Comment by timbaileyjones** [comment]
Thanks!  The solution I came up with was to create a provider.tf file:
```
terraform {
  required_providers {
    okta = {
      source = "okta/okta"
      version = "~> 3.20"
    }
  }
}
```

Then terraform init, then my terraformer run worked perfectly.   At that point, my working directory had the plugin at ./.terraform.  Still didn't have to touch the one in my home directory!

**Comment by noinarisak** [comment]
Thanks, @timbaileyjones! Just getting back from honeymoon-ing! 💒 💍 🎉 . 

@hstringa01  and @devopsrick. That is pretty much it. It is not really clear, IMO, 😅  but the instructions are detailed [here](https://github.com/GoogleCloudPlatform/terraformer#installation) on Step 4. Ran into the same issue while exploring the AWS Provider when I first started with Terraformer. Basic, Terraformer uses the `versions.tf` to know what binaries to pull down to perform the reverse process. 

I think this Issue can be closed @sergeylanzman.

**Comment by hstringa01** [comment]
@noinarisak Thank you for the reply and congratulations!

The provider is pulled down correctly but I still get the initial error if I try to import App resources.

`terraformer import okta --resources=okta_app_saml

2022/02/28 19:46:22 okta importing... okta_app_saml

2022/02/28 19:46:24 okta error initializing resources in service okta_app_saml, err: json: cannot unmarshal object into Go value of type okta.App`

**Comment by devopsrick** [comment]
Same for me.  The provider downloading isn't the issue, I have even tried specific versions from latest back to 3.6.0 and they all fail with the same error on all the okta_app_* resources.  Little Snitch also confirms the correct version of the provider is talking to Okta when terraformer runs.

**Comment by noinarisak** [comment]
Hey @hstringa01 and/or @devopsrick. I am not able to re-create the issue on my mac.

Can you gist your log output and share via the following: 
```
export TF_LOG=TRACE
terraformer import okta --resources=okta_app_saml --verbose > issue.log
```

⚠️ **PLEASE PLEASE PLEASE**, scrub the SSWS header from the log file before posting. 😅 

```
ie. File: issue.log
...
Accept: application/json
Authorization: SSWS {PLEASE_REMOVE_THIS}
Accept-Encoding: gzip 
...
```

**Comment by grizleeeee** [comment]
@noinarisak I'm having the same issue regarding the `unmarshal` error.  Here's the log you requested:  https://gist.github.com/grizleeeee/ec3b20b139fa4daffe8412a12ab8c41e

**Comment by pallyndr** [comment]
Same problem here !
@grizleeeee, did that help to upgrade SDK to latest ?

**Comment by grizleeeee** [comment]
@pallyndr - I hadn't tried to build it prior to you mentioning that, however after updating the SDK version and the terraform provider to the latest release, it fails to build:
```
go run build/main.go okta                                                                                                                                                                                                                                                                                                                                                                                                         
2022/06/08 09:02:34 Build terraformer with okta provider...
2022/06/08 09:02:35 err:# github.com/GoogleCloudPlatform/terraformer/providers/okta
providers/okta/policy_mfa.go:69:27: cannot use nextPolicySet (variable of type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy) as type []"github.com/okta/okta-sdk-golang/v2/okta".Policies in argument to append
providers/okta/policy_mfa.go:72:9: cannot use output (variable of type []"github.com/okta/okta-sdk-golang/v2/okta".Policies) as type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy in return statement
providers/okta/policy_password.go:69:27: cannot use nextPolicySet (variable of type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy) as type []"github.com/okta/okta-sdk-golang/v2/okta".Policies in argument to append
providers/okta/policy_password.go:72:9: cannot use output (variable of type []"github.com/okta/okta-sdk-golang/v2/okta".Policies) as type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy in return statement
providers/okta/policy_signon.go:67:27: cannot use nextPolicySet (variable of type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy) as type []"github.com/okta/okta-sdk-golang/v2/okta".Policies in argument to append
providers/okta/policy_signon.go:70:9: cannot use output (variable of type []"github.com/okta/okta-sdk-golang/v2/okta".Policies) as type []*"github.com/okta/okta-sdk-golang/v2/okta".Policy in return statement
exit status 1
```

I had a feeling this was going to be an issue more complex than just popping in the latest versions, but it was worth a shot.

**Comment by pallyndr** [comment]
If that tool is not able to export Okta apps, what can it be used for?

**Comment by abhs17** [comment]
Hi All, facing the same issue. Any workaround for this?
@noinarisak @devopsrick

**Comment by sergeylanzman** [comment]
I working on this you can see PR

**Comment by pallyndr** [comment]
Sorry, which PR ? Can you provide details ?

Thanks,

**Comment by sergeylanzman** [comment]
https://github.com/GoogleCloudPlatform/terraformer/pull/1361

**Comment by noinarisak** [comment]
Thanks @sergeylanzman for PR #1361!
