### ISSUE TITLE
Not being able to use filters with Heroku provider

### ISSUE THREAD

**Issue by oboxodo** [GoogleCloudPlatform/terraformer#1226]
This is my first time trying to use terraformer so there's a chance I'm doing something wrong but I just can't figure out what.

I have a a few apps running on Heroku. I want to generate the terraform files for only one of those apps. Given the following 3 heroku apps accessible with my API key:

* `my-app`
* `some-other-app`
* `my-last-app`

This properly generates the config files for all of those apps:

```
$ HEROKU_EMAIL=me@example.com HEROKU_API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx \
  terraformer plan heroku --compact --resources 'app'
2022/02/10 18:48:34 heroku importing... app
2022/02/10 18:48:35 heroku done importing app
2022/02/10 18:48:35 Number of resources for service app: 3
2022/02/10 18:48:35 Refreshing state... heroku_app.tfer--my-app
2022/02/10 18:48:35 Refreshing state... heroku_app.tfer--some-other-app
2022/02/10 18:48:35 Refreshing state... heroku_app.tfer--my-last-app
2022/02/10 18:48:37 Filtered number of resources for service app: 3
2022/02/10 18:48:37 Saving planfile to generated/heroku/terraformer/plan.json
```

But if I want to **filter only one of those**, I just can't find the right filter.

I tried all of these:
* `app=heroku_app.tfer--my-app`
* `app=app.tfer--my-app`
* `app=tfer--my-app`
* `app=my-app`

All of them have the same result finding 0 resources:
```
$ HEROKU_EMAIL=me@example.com HEROKU_API_KEY=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx \
  terraformer plan heroku --compact --resources 'app' --filter 'app=heroku_app.tfer--my-app'
2022/02/10 18:56:57 heroku importing... app
2022/02/10 18:56:58 heroku done importing app
2022/02/10 18:56:58 Number of resources for service app: 0
2022/02/10 18:56:58 Saving planfile to generated/heroku/terraformer/plan.json
```

What am I doing wrong?
(All my examples here use the `plan` command but I get the same result with the `import` command.)

**Comment by wchrisjohnson** [comment]
@oboxodo The Heroku provider in Terraformer is a very simple implementation. The filters pattern needs to be implemented by each specific resource in each provider. The Heroku provider currently doesn't support the use of filters. I have an open PR to add a `team_app` resource initially, but plan to fix this specific issue with my next PR. Stay tuned!
