### ISSUE TITLE
Got keycloak: could not get realms attributes in Keycloak when basePath is '/' (instead of '/auth')

### ISSUE THREAD

**Issue by jitbasemartin** [GoogleCloudPlatform/terraformer#1229]
Terraformer doesn't work if Keycloak instance use another base path (default is `/auth`). I got the following message: 

```sh
> terraformer import keycloak --resources=realms                              
2022/02/15 20:59:11 keycloak importing all realms
2022/02/15 20:59:11 keycloak importing... realms
2022/02/15 20:59:12 keycloak error initializing resources in service realms, err: keycloak: could not get realms attributes in Keycloak
2022/02/15 20:59:12 keycloak Connecting....
```

I saw the basePath is hardcoded is the old version of `terraform-provider-keycloak`: [keycloak_client.go#L43](https://github.com/mrparkers/terraform-provider-keycloak/blob/04ff59dd08df07cfdb56e4e51e64e8d2f5fffa56/keycloak/keycloak_client.go#L43)

Can you update this dependency and add basePath setting ?

**Comment by martincolladodev** [comment]
The problem still persists

**Comment by mr-DFX** [comment]
The problem still persists+

**Comment by Tim-herbie** [comment]
What is the correct URL that I have to pass for Keycloak? I have the same error and using the newest keycloak and terraformer version.

**Comment by mosmianiv** [comment]
Are there any updates for this?
