### ISSUE TITLE
Terraformer not generating some S3 resource blocks.

### ISSUE THREAD

**Issue by nidalhaddad** [GoogleCloudPlatform/terraformer#1234]
Hi, while trying to import S3 configuration that is set as static website and CORS. 
I can see the CORS rules  and policy and website rules in my `tfstate` file  but they are not shown in my `s3_bucket.tf `
this is the content of my `s3_bucket.tf`
```
resource "aws_s3_bucket" "tfer--name-of-bucket" {
  arn            = "arn:aws:s3:::name-of-bucket"
  bucket         = "name-of-bucket"
  force_destroy  = "false"
  hosted_zone_id = "ABCDEFGAZFGR"
}
```
Command used : 
`terraformer import aws --resources=s3 --profile dev`

```
go version :  go1.15.15 linux/amd64
Terraform v1.1.6 on linux_amd64
aws provider version = "~> 4.2.0"

```
Thank you.

**Comment by celik0311** [comment]
I suspect this has to do with the major version change in the provider.
