### ISSUE TITLE
Unable to perform terraform init after importing the resources

### ISSUE THREAD

**Issue by howardjohn** [GoogleCloudPlatform/terraformer#1235]
Reviving https://github.com/GoogleCloudPlatform/terraformer/issues/1048 since this is still an issue

Is it necessary to execute these commands after importing resources from aws,gcp,azure

terraform state replace-provider -auto-approve "registry.terraform.io/-/google" "hashicorp/google"

terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"

terraform state replace-provider -auto-approve "registry.terraform.io/-/azurerm" "hashicorp/azurerm"

steps to reproduce the issue

Create a directory and cd

vi provider.tf

provider "aws" {
region = "ap-south-1"
}

terraform init

terraformer import aws --resources="*" --connect=true --regions=ap-south-1

Change the directory to s3 resource

cd generated/aws/s3

terraform init

Initializing the backend...
╷
│ Error: Invalid legacy provider address
│
│ This configuration or its associated state refers to the unqualified provider "aws".
│
│ You must complete the Terraform 0.13 upgrade process before upgrading to later versions.

As a workaround we have to do in order for the terraform init to work
terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"

**Comment by barash-asenov** [comment]
Try doing

```sh
terraform state replace-provider \
-auto-approve \
"registry.terraform.io/-/google" \
"hashicorp/google"
```

Source;
https://stackoverflow.com/questions/65396812/invalid-legacy-provider-address-error-on-terraform

**Comment by howardjohn** [comment]
That does work but I would expect it to be done automatically

**Comment by barash-asenov** [comment]
@howardjohn sorry, I should read description before making comment :slightly_frowning_face: 

https://github.com/GoogleCloudPlatform/terraformer#capabilities

Here in the capabilities it says that support for Terraform 0.13. I assume the problem is because you are using 0.14 or later Terraform versions

**Comment by ihommani** [comment]
Indeed. However I see no plan about accepting new version of  terraform. We are at the 1.1.7 right now.
