### ISSUE TITLE
The state file could not be read

### ISSUE THREAD

**Issue by GeorgeMicro** [GoogleCloudPlatform/terraformer#1245]
Successfully imported AWS resources, one state file 'terraform.tfstate' has been generated but when executing 'terraform plan' I get this error:

Error: Failed to read state file
│
│ The state file could not be read: read terraform.tfstate: The process cannot access the file because another process has locked a portion of the file.

My current workaround is to use window subsystem linux to run terraform plan......which surprisingly works.

**Comment by sergeylanzman** [comment]
you have lock file in same location?

**Comment by GeorgeMicro** [comment]
Yes, I did.
