### ISSUE TITLE
[docs/examples] Unclear how to use this tool safely in existing infrastructure

### ISSUE THREAD

**Issue by frederikfab** [GoogleCloudPlatform/terraformer#1246]
If anyone could provide a small example for how to use this tool safely, it would be much appreciated

A few colleagues and myself have independently researched this, and upon talking about it, its unclear when using the tool, how it could affect remote state and how we'd ensure to avoid it.

Also, we were confused about how to confine terraform config to the subset of state you'd want to modify (e.g. leaving existing infrastructure on gcp out of scope from being affected by it).

I think examples on this in the docs, could go a long way - I'm sure many others are considering this as well to get started with using terraform for a subset of their already existing GCP infrastructure.

**Comment by sergeylanzman** [comment]
terraformer need only read permissions. So no effect on current infrastructure or remote state(you don't need to pass remote state location)

Regarding import, not all resources
1. You can remove from tfstate and tf other resources - or copy what you need
2. You can use filter

PR with example welcome
