### ISSUE TITLE
QUESTION: Is AWS WAFv2 supported?

### ISSUE THREAD

**Issue by nmofonseca** [GoogleCloudPlatform/terraformer#1250]
Hello,

I probably have answered myself but I want to get a confirmation, is AWS WAFv2 (New AWS WAF) supported?

When I try to use terraformer to import some WAF stuff I have one through the AWS management console for experimenting terraformer is not picking anything.

Thank you in advance.

Cheers

**Comment by sergeylanzman** [comment]
https://github.com/GoogleCloudPlatform/terraformer/pull/1254

**Comment by nmofonseca** [comment]
Hello @sergeylanzman ,

Wow, I wasn't expecting this so soon really amazing job from you guys.

Quick question, do I need to wait for a new release, if so do you have any idea when that will happen? Otherwise, what is my option for now?

Once again a big thank you for such an amazing tool and the great work you guys do
