### ISSUE TITLE
no resources found

### ISSUE THREAD

**Issue by MushiTheMoshi** [GoogleCloudPlatform/terraformer#1251]
Hi there,

First I want to say thanks for all the work done here, is really awesome and very well done.

I have been working with the tool a couple of months now, I noticed that sometimes resources come empty while in other similar tools the resources are being pulled correctly.

Is there any guide on how to debug this?

see the image below:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/13651419/157699025-1a7cd6ae-1982-4339-8245-46d5a6755936.png">

Hope you can help me on this one !

Thanks in advance,
Julio

**Comment by sergeylanzman** [comment]
it looks like a profile issue. Can you check the same command with the regular default profile?

**Comment by MushiTheMoshi** [comment]
Hi there,

I get "No EC2 imds role found" error.

![image](https://user-images.githubusercontent.com/13651419/165781391-5c8ead40-24af-4889-8078-d770641ef9e2.png)

Is there any workaround to this?

**Comment by MushiTheMoshi** [comment]
Additionally in other accounts different resources are missing:

This is showing 0 ELBs which is not true...
![image](https://user-images.githubusercontent.com/13651419/165782282-99627dfe-27ce-4ec7-9393-90d53cb4a414.png)

**Comment by MushiTheMoshi** [comment]
it was the provider, I updated the provider to the latest and now it can see all resources...
