### ISSUE TITLE
Google KMS import: only `global` location

### ISSUE THREAD

**Issue by nyarly** [GoogleCloudPlatform/terraformer#1272]
Reviewing KMS import, I see this: `https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/kms.go#L97`

KMS's exist in "locations" in GCP, which are related but different from regions.

It's not immediately clear how to handle this issue; perhaps adding a `--location` flag?

I'd be willing to submit the PR with some guidance.

**Comment by sergeylanzman** [comment]
yes it's will be good
