### ISSUE TITLE
Impossible to effectively use `--path-pattern` for GCP

### ISSUE THREAD

**Issue by nyarly** [GoogleCloudPlatform/terraformer#1273]
The Google provider needs to add `project` and `region` segments to its path, which is does on https://github.com/GoogleCloudPlatform/terraformer/blob/master/cmd/provider_cmd_google.go#L37

The result is that only the default path pattern really works. Would it be possible to update how the pattern is handled to allow for the GCP case?

I could provide a PR if acceptable.

**Comment by sergeylanzman** [comment]
Yes, if it's specifical to GCP

**Comment by nyarly** [comment]
My initial impression is that the issue is that the GCP fields aren't available for the pattern rendering. It might be necessary to update that templating code - if so, would that PR be rejected?
