### ISSUE TITLE
terraformer aws security filter not working

### ISSUE THREAD

**Issue by Raushi007** [GoogleCloudPlatform/terraformer#1302]
Hi can any one help i am importing scurity group through terraformer but it's not filter based on vpc
cloud provider:AWS

in DOC: terraformer import aws -r sg,vpc --filter Type=sg;Name=vpc_id;Value=VPC_ID

i have tried.

terraformer import aws -r sg --filter Type=sg;Name=my-vpc-02;Value=vpc-0f516ebxxxxb96685

terraformer import aws -r sg --filter Type=sg;Name=vpc-0f516ebxxxxb96685;Value=vpc-0f516ebxxxxb96685

but that did not work
please provide the solution

**Comment by wmyre** [comment]
Ran into the same issue. Use "security_group" for the type instead of "sg".
