### ISSUE TITLE
Possible to use Terraformer in an AWS Lambda function?

### ISSUE THREAD

**Issue by bencohen2** [GoogleCloudPlatform/terraformer#1303]
I'm trying to run `terraformer import ....` in the context of an AWS Lambda function, but the CLI requires the plugins to be in a specific system-file location. When I run it in Lambda I get this error:

```
open /.terraform.d/plugins/linux_amd64: no such file or directory
```

It is searching for the file `/.terraform.d/plugins/darwin_amd64/terraform-provider-aws_v4.11.0_x5`, which I have on my local computer, but not in Lambda.

However, Lambda does not allow me to place in this file at `/.terraform.d` etc. 

In essence, how are people running Terraformer in contexts other than local computers? (Sorry if this question is not Terraformer-specific, just having a hard time Googling my way around this question)

**Comment by bencohen2** [comment]
> You will need to create `versions.tf` and run `terraform init` first. The `versions.tf` file should contain aws as a required_provider.

Thank you! I was able to eventually Dockerize my lambda function and get the correct providers installed. 

On another note, do you have any experience contributing to the repo? I submitted the CLA on June 8th but still can’t make any commits or PRs on the repo. 

Thanks!

**Comment by 94rain** [comment]
> > You will need to create `versions.tf` and run `terraform init` first. The `versions.tf` file should contain aws as a required_provider.
> 
> Thank you! I was able to eventually Dockerize my lambda function and get the correct providers installed.
> 
> On another note, do you have any experience contributing to the repo? I submitted the CLA on June 8th but still can’t make any commits or PRs on the repo.
> 
> Thanks!


What's the issue you encountered? Did you fork the repo and commit on your own fork and make the PR?

BTW, did you manage to output the lambda function source code with terraformer?

**Comment by bencohen2** [comment]
> > > You will need to create `versions.tf` and run `terraform init` first. The `versions.tf` file should contain aws as a required_provider.
> > 
> > 
> > Thank you! I was able to eventually Dockerize my lambda function and get the correct providers installed.
> > On another note, do you have any experience contributing to the repo? I submitted the CLA on June 8th but still can’t make any commits or PRs on the repo.
> > Thanks!
> 
> What's the issue you encountered? Did you fork the repo and commit on your own fork and make the PR?
> 
> BTW, did you manage to output the lambda function source code with terraformer? I am not able to do that.

I cloned the repo, made a change and tried to commit but both GitHub CLI and GitHub desktop give me an error saying “you don’t have permissions to commit to this repository” or something of that sort. 

What do you mean about outputting the lambda function source code? I built a docker container (with dockerfile, package.json and app.js file) and use AWS CLI to publish a new version. Happy to go into more detail

**Comment by bencohen2** [comment]
> > > You will need to create `versions.tf` and run `terraform init` first. The `versions.tf` file should contain aws as a required_provider.
> > 
> > 
> > Thank you! I was able to eventually Dockerize my lambda function and get the correct providers installed.
> > On another note, do you have any experience contributing to the repo? I submitted the CLA on June 8th but still can’t make any commits or PRs on the repo.
> > Thanks!
> 
> What's the issue you encountered? Did you fork the repo and commit on your own fork and make the PR?
> 
> BTW, did you manage to output the lambda function source code with terraformer? I am not able to do that.

For example I’d like to contribute to PR #1341 but I can’t.

**Comment by 94rain** [comment]
What I wanted to do is to obtain the lambda function source code with terraformer.

For contributing to that PR, I think what you can do is make suggestions in https://github.com/GoogleCloudPlatform/terraformer/pull/1341/files

See step 6 here:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

**Comment by bencohen2** [comment]
> What I wanted to do is to obtain the lambda function source code with terraformer.
> 
> For contributing to that PR, I think what you can do is make suggestions in https://github.com/GoogleCloudPlatform/terraformer/pull/1341/files
> 
> See step 6 here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request

Re: the PR - yes, I definitely can make comments. But I want to actually push commits since there is no movement on that PR. But I can’t. Do you have write access to this repo? If so how’d you get it?

Re: Lambda - I see what you mean. No, I don’t think terraformer supports that for lambda since only very small snippets of code are even supported on the AWS console for lambda. Anything above a certain file size is stored in s3 as far as I can tell and wouldn’t be downloaded in a Terraformer import

**Comment by 94rain** [comment]
No, I don't have access to the repo. You can fork the repo and continue to commit to the snowflake branch in your fork and request them to merge the new commits from your fork.

> No, I don’t think terraformer supports that for lambda since only very small snippets of code are even supported on the AWS console for lambda.

I see. Would it be possible to get the very small snippets of code?

**Comment by bencohen2** [comment]
> > Do you have write access to this repo? If so how’d you get it?
> 
> No, I don't have access to the repo. You can fork the repo and continue to commit to the snowflake branch in your fork and request them to merge the new commits from your fork.
> 
> > No, I don’t think terraformer supports that for lambda since only very small snippets of code are even supported on the AWS console for lambda.
> 
> I see. Would it be possible to get the very small snippets of code with terraformer?

Got it, I’ll try that thanks. 

I don’t believe the Terraformer lambda provider supports that. It depends on what the AWS terraform provider (the one on hashicorp) supports. I think the most they do is provide links to where the code files are stored, but that might also be wrong too. I’m on mobile right now but can check the lambda terraform provider in the morning.

**Comment by 94rain** [comment]
There is an example for deploying a small code snippet to lambda but I don't know whether it is possible reversely. (https://github.com/hashicorp/terraform-provider-aws/tree/main/examples/lambda)

Thanks anyway!
