### ISSUE TITLE
aws route53 import with filter only imports zone, not records

### ISSUE THREAD

**Issue by rthuffman** [GoogleCloudPlatform/terraformer#1307]
I'm trying to bring a number of Terraform hosted zones under Terraform management.

I'm running the command:

terraformer import aws --resources=route53 --region=us-east-1 --filter="Name=tags.ZoneType;Value=VanityHost"

and I get the exact zones I'm looking for, but no records.

I run:

terraformer import aws --resources=route53 --region=us-east-1 --filter="Type=zone,record;Name=tags.ZoneType;Value=VanityHost"

and I get every record and every zone whether the tags match or not.  Is there something I'm missing, or does the --filter option not support this type of behavior regarding records?

**Comment by bluet** [comment]
Not sure if it's related, but my terraformer supports `--regions` instead of `--region`
