### ISSUE TITLE
AWS imported alb shows changes on terraform plan

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#131]
Using:

terraform 0.11.14
provider.aws 2.18.0
terraformer 0.7.5

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_lb_target_group.origin-1
      lambda_multi_value_headers_enabled: "" => "false"
      proxy_protocol_v2:                  "" => "false"

  ~ aws_lb_target_group.origin-2
      lambda_multi_value_headers_enabled: "" => "false"
      proxy_protocol_v2:                  "" => "false"

Plan: 0 to add, 2 to change, 0 to destroy.

**Comment by sergeylanzman** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/7960
https://github.com/terraform-providers/terraform-provider-aws/issues/5051
