### ISSUE TITLE
on my linux OS terraform version is 1.1.9 but in tfstate file it is showing 0.12.31

### ISSUE THREAD

**Issue by shivangivar** [GoogleCloudPlatform/terraformer#1310]
Hi i have read the doc as terraformer support 0.13 version of terraform. 
can anyone help me how to upgrade/downgrade the terraform version.

**Comment by cloneluke** [comment]
I also have this issue, secondarily have `"version": 3,` also

**Comment by samuelbailey123** [comment]
this project doesn't support tf past 0.13

**Comment by nooranikhan** [comment]
Any update on this? This is a blocker since 0.13 is pretty old now and so much incompatible constructs exists esp for the cloud providers

**Comment by mission-coliveros** [comment]
Any updates?  This is a huge blocker for us as well
