### ISSUE TITLE
AWS route53 empty zone comment is not imported

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#132]
The imported zone gets a default Terraform comment as the original empty one was nog imported. 

Using:

terraform 0.11.14
provider.aws 2.18.0
terraformer 0.7.5

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_route53_zone.xxxxx
      comment: "" => "Managed by Terraform"

  ~ aws_route53_zone.xxxxx
      comment: "" => "Managed by Terraform"

Plan: 0 to add, 2 to change, 0 to destroy.

**Comment by sergeylanzman** [comment]
`comment: "" => "Managed by Terraform" ` - it's default from provider, we can add this to tfstate, but it's good practices after import run apply and add this comment to DNS zone.
