### ISSUE TITLE
aws accessanalyzer error

### ISSUE THREAD

**Issue by Hokwang** [GoogleCloudPlatform/terraformer#1324]
Hi,

I did below command,
```
terraformer import aws -r="*" --profile=xxx-aws --regions=ap-northeast-2
2022/05/13 14:03:17 aws importing region ap-northeast-2
2022/05/13 14:03:17 Attempting an import of ALL resources in aws
2022/05/13 14:03:19 aws importing... accessanalyzer
2022/05/13 14:03:19 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found
...
```

I think region does not be used in accessanalyzer.
Please check this.

**Comment by lv-labwerks** [comment]
Stale or not, this issue still persists when trying to import all resources from AWS. It causes the import to fail as a result:
`$ terraformer import aws --resources=accessanalyzer --regions=us-east-1
2022/12/10 12:37:41 aws importing region us-east-1
2022/12/10 12:37:42 aws importing... accessanalyzer
2022/12/10 12:37:42 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found
2022/12/10 12:37:42 aws Connecting....`

**Comment by damo78** [comment]
Why does this issue keep getting closed with no resolution if the issue still persists?

2023/11/01 13:04:58 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found

The new issue is also closed with the same: https://github.com/GoogleCloudPlatform/terraformer/issues/1590

**Comment by austerecryptid** [comment]
Reopening this issue as it appears to be a bug? We have an access analyzer with the appropriate permissions in an AWS environment and it's unable to connect to it and fails out.

**Comment by 1on1security** [comment]
New user, thought I'd found the "eureka" sauce.
I too am experiencing the same error on AWS.

terraformer import aws --resources="*" --regions=us-west-1

Early in the output we see:
2024/06/02 18:59:22 aws importing... accessanalyzer
2024/06/02 18:59:22 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found

It continues through 
2024/06/02 18:59:56 aws importing... identitystore
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).GetIdentityStoreId(0xc004c670d0?)
        /Users/sergey/temp/terraformer/providers/aws/identitystore.go:44 +0x1ce
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IdentityStoreGenerator).InitResources(0x0?)
        /Users/sergey/temp/terraformer/providers/aws/identitystore.go:169 +0x25
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc001a8d6d0?)
        /Users/sergey/temp/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc000b37800, 0x56, 0x80}, {0x12999268, 0x0, 0x0}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc000b37800, 0x56, 0x80}, {0x12999268, 0x0, 0x0}, {0xb20575b, 0x1e}, {0xb15cdd8, ...}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:166 +0x1c5
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc000b37800, 0x56, 0x80}, {0x12999268, 0x0, 0x0}, {0xb20575b, 0x1e}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc0007bcbf0, 0x1, 0x1}, {0x12999268, 0x0, 0x0}, {0xb20575b, 0x1e}, {0xb15cdd8, 0x9}, ...}, ...)
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc000c02580?, {0xb14e4f4?, 0x3?, 0x3?})
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:58 +0xa0e
github.com/spf13/cobra.(*Command).execute(0xc000c02580, {0xc001370660, 0x3, 0x3})
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009a7340)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /Users/sergey/temp/terraformer/cmd/root.go:36 +0x1e
main.main()
        /Users/sergey/temp/terraformer/main.go:39 +0x50
