### ISSUE TITLE
Authentication seems to be lost mid-operation

### ISSUE THREAD

**Issue by fclaudiopalmeira** [GoogleCloudPlatform/terraformer#1337]
I'm trying to import an instance with 3 attached volumes (Openstack) by using the following Env variables:
export OS_AUTH_URL=https://mykeystone.here
export OS_PROJECT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
export OS_PROJECT_NAME="project_name_here"
export OS_USER_DOMAIN_NAME="Default"
export OS_PROJECT_DOMAIN_ID="default"
export OS_DOMAIN_ID="default"
export OS_USERNAME="username"
export OS_PASSWORD="password"
export OS_REGION_NAME="myregion"
export OS_IDENTITY_API_VERSION=3
All working fine with terraform and openstack native client, but when trying to import this resource (or any other), it errors out like this:
```
[root@localhost IaC_VM]# terraformer import openstack --resources=compute,blockstorage --regions=myregion
```
```
2022/06/02 09:15:57 openstack importing region myregion
2022/06/02 09:15:57 openstack importing... compute
2022/06/02 09:15:59 openstack done importing compute
2022/06/02 09:15:59 openstack importing... blockstorage
2022/06/02 09:15:59 Using BlockStorage API v3
2022/06/02 09:15:59 openstack done importing blockstorage
2022/06/02 09:15:59 Number of resources for service compute: 3
2022/06/02 09:15:59 Number of resources for service blockstorage: 3
2022/06/02 09:15:59 Refreshing state... openstack_blockstorage_volume_v3.tfer--Cassandra-0020-Database-0020-Volume
2022/06/02 09:15:59 Refreshing state... openstack_compute_volume_attach_v2.tfer--n-peaks-pv01vdd
2022/06/02 09:15:59 Refreshing state... openstack_compute_volume_attach_v2.tfer--n-peaks-pv01vdc
2022/06/02 09:15:59 Refreshing state... openstack_blockstorage_volume_v3.tfer--Data-Volume
2022/06/02 09:15:59 Refreshing state... openstack_compute_instance_v2.tfer--n-peaks-pv01
2022/06/02 09:15:59 Refreshing state... openstack_blockstorage_volume_v3.tfer--Windows-0020-OS
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:15:59 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:15:59 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack block storage client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:00 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:00 WARN: Fail read resource from provider, wait 300ms before retry
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Fail read resource from provider, trying import command
2022/06/02 09:16:01 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/06/02 09:16:01 ERROR: Unable to refresh resource tfer--n-peaks-pv01
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ParseTFstate(0xc00159f290, {0xafbf520?, 0xc001a98190?}, {{0xb06d448?, 0xc001a94420?}})
        /home/runner/work/terraformer/terraformer/terraformutils/resource.go:151 +0xff
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ConvertTFstate(0xc00159f290, 0xc000036380)
        /home/runner/work/terraformer/terraformer/terraformutils/resource.go:176 +0x397
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).ConvertTFStates(0xc0011a1a60, 0x2?)
        /home/runner/work/terraformer/terraformer/terraformutils/providers_mapping.go:151 +0xab
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc0000c5d40, 0x2, 0x2}, {0x11297e80, 0x0, 0x0}, {0xc0007271d0, 0x24}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:102 +0x2c5
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdOpenStackImporter.func1(0xc000864580?, {0xa091888?, 0x2?, 0x2?})
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_openstack.go:36 +0x254
github.com/spf13/cobra.(*Command).execute(0xc000864580, {0xc0000c5c40, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000ac2c0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
        /home/runner/work/terraformer/terraformer/main.go:39 +0x50

```
What could be happening here?

thank you in advance

**Comment by kiranchavala** [comment]
Can someone fix this issue, 
its still present 


❯ terraformer import openstack --resources=compute  --regions=RegionOne
2022/08/12 20:56:55 openstack importing region RegionOne
2022/08/12 20:56:55 openstack importing... compute
2022/08/12 20:57:03 openstack done importing compute
2022/08/12 20:57:03 Number of resources for service compute: 3
2022/08/12 20:57:03 Refreshing state... openstack_compute_instance_v2.tfer--test
2022/08/12 20:57:03 Refreshing state... openstack_compute_volume_attach_v2.tfer--testvdb
2022/08/12 20:57:03 Refreshing state... openstack_compute_instance_v2.tfer--test-VM-PM
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 ERROR: Unable to refresh resource tfer--test
2022/08/12 20:57:05 ERROR: Unable to refresh resource tfer--test-VM-PM
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ParseTFstate(0x140012db560, {0x10edf3b38?, 0x140010a3810?}, {{0x10eea18f8?, 0x140010cf060?}})
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:151 +0xcc
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ConvertTFstate(0x140012db560, 0x1400049e4d0)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:176 +0x32c
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).ConvertTFStates(0x14001953a30, 0x1?)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providers_mapping.go:151 +0x7c
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0x140007a8c20, 0x1, 0x1}, {0x114fc6480, 0x0, 0x0}, {0x14000621890, 0x28}, ...}, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:102 +0x1cc
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdOpenStackImporter.func1(0x14000912580?, {0x10be3f357?, 0x2?, 0x2?})
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_openstack.go:36 +0x204
github.com/spf13/cobra.(*Command).execute(0x14000912580, {0x140007c4280, 0x2, 0x2})
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001067340)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x24
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x58
