### ISSUE TITLE
AWS: Support for Route53 Traffic Policies

### ISSUE THREAD

**Issue by klemmari1** [GoogleCloudPlatform/terraformer#1338]
Hi!

Will there be support for these resources that were [added](https://github.com/hashicorp/terraform-provider-aws/pull/23602) in the tf aws provider v4.7.0?
- [aws_route53_traffic_policy](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/route53_traffic_policy)
- [aws_route53_traffic_policy_document](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/data-sources/route53_traffic_policy_document)
- [aws_route53_traffic_policy_instance](https://registry.terraform.io/providers/hashicorp%20%20/aws/latest/docs/resources/route53_traffic_policy_instance)

**Comment by driv** [comment]
Still nothing?
