### ISSUE TITLE
Add support import from tfstate

### ISSUE THREAD

**Issue by sergeylanzman** [GoogleCloudPlatform/terraformer#136]
Same as import from plan today, but use `tfstate` file and create `tf` files

**Comment by meshuga** [comment]
To make TF 0.12 migration work, I had to change how refresh functionality works to first perform import and then refresh https://github.com/meshuga/terraformer/blob/d0e0641f51d9728c596172a0984a04cb56376e98/terraform_utils/provider_wrapper/provider.go#L129
