### ISSUE TITLE
"panic: interface conversion: interface {} is nil, not string" within Panorama_Policy

### ISSUE THREAD

**Issue by wolfwood03** [GoogleCloudPlatform/terraformer#1365]
https://github.com/GoogleCloudPlatform/terraformer/issues/1085

Same issue as above, this was fixed in other resource objects but not panorama_policy

Excerpt of diff from merge #1085 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61850741/176482773-17eb672a-3b0f-4879-9a84-209c71f0f17b.png)

This is the current code for that panorama_policy resource:  
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/61850741/176482836-a4f15b02-7e61-4f5b-8e9e-4d4c2911877d.png)

Current Error for reference: 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/61850741/176483192-c8fee751-df9c-40b1-aebb-245a14f94bda.png)

**Comment by notclaytonjohnson** [comment]
After building/testing locally, we were able to avoid these issues by doing the same sorts of checks that were done in the merge to resolve #1085 . 

Our changes to [this line](https://github.com/GoogleCloudPlatform/terraformer/blob/60adc353b5ac058e49090e9396dc37cc9612e407/providers/panos/panorama_policy.go#L161) (`panorama_policy:161`) below:    
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/106109529/176704714-1064bb08-8977-4687-b6af-f73bdc70e129.png)
