### ISSUE TITLE
aws glue terraformer

### ISSUE THREAD

**Issue by ashishstar** [GoogleCloudPlatform/terraformer#1367]
I am generating glue.tf + tfstate files from existing infrastructure.
Currently, my AWS infrastructure consists of one glue table, one glue database, one crawler, and one glue job 

Using the following command to generate resources related to glue
**terraformer import aws --resources=glue --connect=true --regions=us-east-1 --profile=default**

But as per documentation it should create
glue
	glue_crawler
	aws_glue_catalog_database
	aws_glue_catalog_table
	aws_glue_job	
	aws_glue_trigger

![image](https://user-images.githubusercontent.com/108716939/177265070-703f71aa-8256-449f-b3b8-e60a4a98979a.png)

But out of which it is only creating 
	glue_crawler
	aws_glue_catalog_database
	aws_glue_catalog_table

It is not creating resource.tf file for **aws_glue_job,aws_glue_trigger** even if we have one job and one trigger respectively	

Can someone please help to create aws_glue_job and aws_glue_trigger scripts as well?

**Comment by pleasespammelater** [comment]
I'm seeing the same thing.

**Comment by Tduffy-polly** [comment]
I am seeing the same thing. I am not familiar with GO so i cannot debug the script

**Comment by pleasespammelater** [comment]
I discovered that by pulling down the latest source code and building the app myself that the glue jobs do get generated. It appears that the exe that's in the release list is not the latest code.

**Comment by Tduffy-polly** [comment]
ah gotcha, are you downloading the sourcecode.zip from here https://github.com/GoogleCloudPlatform/terraformer/releases?
