### ISSUE TITLE
Required attributes are deleted when empty

### ISSUE THREAD

**Issue by pengux** [GoogleCloudPlatform/terraformer#137]
While trying to add support for a new provider, running import doesn't include some required attributes for the resource in the generated TF file. This is because in the `ConvertTFstate` function of the resource, it delete keys from attributes which are empty. There is an `AllowEmptyValue` argument which can be used to allow attributes with empty values, but not for those of type array (List).

Instead of deleting empty attributes from HCL generation, wouldn't it be better if it was checked against the schema for the resources and only remove the attributes which don't have `Required` set to `true`?

**Comment by sergeylanzman** [comment]
1. `AllowEmptyValue` - it's regex pattern on tfstate attributes. You can use for list pattern like this `^YOU_LIST_NAME.*` or `^YOU_LIST_NAME.[0-9].*`
2. About `Required=true` - Maybe your right but I think it's need more code changes. Maybe part of this task https://github.com/GoogleCloudPlatform/terraformer/issues/25. If you can change for with small code changes why not? or wait for finish 0.12 support here(https://github.com/GoogleCloudPlatform/terraformer/compare/master...meshuga:tf_12) and after this we can change provider wrapper code

**Comment by meshuga** [comment]
It'll take me a while to move to 0.12. There are internal changes in TF, so want to make sure everything is working as expected.

**Comment by pengux** [comment]
> 1. `AllowEmptyValue` - it's regex pattern on tfstate attributes. You can use for list pattern like this `^YOU_LIST_NAME.*` or `^YOU_LIST_NAME.[0-9].*`
Yes, but it doesn't apply for arrays it seem. It's trivial to add the check for `AllowEmptyValue` for arrays too of course but I still think checking the schema from the provider for `Required` set to `true` is still the best approach.

> 2. About `Required=true` - Maybe your right but I think it's need more code changes. Maybe part of this task #25. If you can change for with small code changes why not? or wait for finish 0.12 support here([master...meshuga:tf_12](https://github.com/GoogleCloudPlatform/terraformer/compare/master...meshuga:tf_12)) and after this we can change provider wrapper code

OK, I guess it's better to wait after your 0.12 rewrite, but will you accept a PR to add `AllowEmptyValue` check for arrays with the current code?

**Comment by sergeylanzman** [comment]
You right, removing empty array it's before AllowEmptyValue checking.
Yes I'll accept PR with support array for AllowEmptyValue.
