### ISSUE TITLE
Not able to import existing Lambda and eks cluster using Terraformer import

### ISSUE THREAD

**Issue by shubhamkj** [GoogleCloudPlatform/terraformer#1371]
Hi,

Trying to import existing lambda and eks cluster reaoureces with terraformer and it turns out to be 0 resources.

bash-4.2# terraformer-aws import aws --regions=us-east-1 --resources=eks
2022/07/08 09:45:54 aws importing region us-east-1
2022/07/08 09:45:55 aws importing... eks
2022/07/08 09:45:59 aws done importing eks
**2022/07/08 09:45:59 Number of resources for service eks: 0**
2022/07/08 09:45:59 aws Connecting....
2022/07/08 09:45:59 aws save eks
2022/07/08 09:45:59 aws save tfstate for eks

bash-4.2# aws eks list-clusters
{
    "clusters": [
        "test-eks-cluster",
        "test-model-container"
    ]
}

similarly for lambda -

bash-4.2# terraformer-aws import aws --regions=us-east-1 --resources=lambda
2022/07/08 09:51:16 aws importing region us-east-1
2022/07/08 09:51:17 aws importing... lambda
2022/07/08 09:51:21 aws done importing lambda
**2022/07/08 09:51:21 Number of resources for service lambda: 0**
2022/07/08 09:51:21 aws Connecting....
2022/07/08 09:51:21 aws save lambda
2022/07/08 09:51:21 aws save tfstate for lambda

**Comment by sergeylanzman** [comment]
same region/profile?
