### ISSUE TITLE
AWS - Import All Resources with given tag/value

### ISSUE THREAD

**Issue by byanke-flexion** [GoogleCloudPlatform/terraformer#1378]
Hello,

I am currently working on migrating some deployed infrastructure to terraform, and all of the resources have a specific tag and value attached to them (for example: `examplecorp:team:app=app1`). However, I have not been able to get terraformer to handle these tags correctly based on `--filter` examples I have found so far - either it ends up importing everything or nothing.

This, for example, imports all lambdas and dynamo tables:
`terraformer import aws --resources=lambda,dynamodb --connect=true --regions=us-east-1 --filter="Name=tags.examplecorp:team:app;Value=app1"`

As does this:
`terraformer import aws --resources=lambda,dynamodb --connect=true --regions=us-east-1 --filter="Name=examplecorp:team:app;Value=app1"`

What is the recommended way to handle this?

**Comment by XerXi** [comment]
Did you try with single quotes areound the examplecorp:team:app? Documentation mentions that when you have : symbol in filters
