### ISSUE TITLE
wrong order when generating a list of values from tfstate. 

### ISSUE THREAD

**Issue by saeednm** [GoogleCloudPlatform/terraformer#1381]
Using terraformer to import kubernetes cronjobs, after the auto-generation of tfstate and tf files I have noticed that the values of a list in the .tf file are not in the correct order although they are correctly ordered in the generated tfstate file

here is the **terrafrom.tfstate** content : 

`"spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.#": "17",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.0": "data-flow",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.1": "run",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.10": "[\"-properties\",\"resources/FOO.properties\"]",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.11": "--num-executors",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.12": "1",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.13": "--wait-for-state",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.14": "SUCCEEDED",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.15": "--wait-for-state",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.16": "FAILED",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.2": "create",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.3": "--compartment-id",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.4": "ocid1.compartment",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.5": "--application-id",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.6": "ocid1.dataflowapplication",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.7": "--display-name",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.8": "FOO",
            "spec.0.job_template.0.spec.0.template.0.spec.0.container.0.args.9": "--arguments",`

the order should follow the args.# but the resulting tf code order is ordered alphabetically! 

`args              = ["--application-id", "--arguments", "--compartment-id", "--display-name", "--num-executors", "--wait-for-state", "--wait-for-state", "1", "FOO", "FAILED", "SUCCEEDED", "[\"-properties\",\"resources/FOO.properties\"]", "create", "data-flow", "ocid1.compartment.", "ocid1.dataflowapplication", "run"]`

instead i was expecting to see : 
`args= [
                "data-flow",
                "run",
                "create",
                "--compartment-id",
...
`

**Comment by sergeylanzman** [comment]
oh. Know issue.
Terraformer running sorting on resources for generating same code every time, but in some cases, it's not good. 
Before sorting it's generated not sorted every time different code(used golang map)
I'll add flag `--no-sort` in one day

**Comment by onemanbucket** [comment]
Hey, we also ran into this problem. Added the --no-sort flag in this PR (but again, please review carefully as I'm not very familiar with golang)

https://github.com/GoogleCloudPlatform/terraformer/pull/1436
