### ISSUE TITLE
vault not supporting Enterprise namespaces

### ISSUE THREAD

**Issue by yrsurya** [GoogleCloudPlatform/terraformer#1397]
I am trying to import vault resources for namespaces which available in Enterprise version but looks like it's currently not supported 

Any work going around it or please correct me if I am wrong

**Comment by sergeylanzman** [comment]
vault integration not tested on Enterprise because i don't have vault Enterprise

**Comment by december1981** [comment]
I have a local branch which adds support for namespaces:
https://github.com/GoogleCloudPlatform/terraformer/compare/master...december1981:terraformer:vault-namespace

I was going to make a pull request - but I needed to update module versions, and put vault 0.10.4 -> 1.8.2 to get this to work...
This brought in some other changes to the package dependency tree.

**Comment by yrsurya** [comment]
Can we able to merge above branch so it can be available?
