### ISSUE TITLE
GCP: Add support Google App Engine Resources

### ISSUE THREAD

**Issue by sergeylanzman** [GoogleCloudPlatform/terraformer#14]

**Comment by willmadison** [comment]
Would love to work on this. I was just about to roll my own by hand since we're leveraging App Engine and terraformer didn't seem to support App Engine Resources. If this work isn't already in flight I'd love to take this on.

**Comment by timmeinerzhagen** [comment]
Importing App Engine ressources does not seem to be available as of yet, right? Would love to see that

**Comment by ChelseaKR** [comment]
My team wants this as well. @willmadison did you ever end up rolling your own solution?

**Comment by willmadison** [comment]
@ChelseaKR we didn't. We ended up replatforming to GKE.
