### ISSUE TITLE
Terraformer import for openstack is not working 

### ISSUE THREAD

**Issue by kiranchavala** [GoogleCloudPlatform/terraformer#1415]
Can someone fix this issue,
its still present

❯ terraformer import openstack --resources=compute --regions=RegionOne
2022/08/12 20:56:55 openstack importing region RegionOne
2022/08/12 20:56:55 openstack importing... compute
2022/08/12 20:57:03 openstack done importing compute
2022/08/12 20:57:03 Number of resources for service compute: 3
2022/08/12 20:57:03 Refreshing state... openstack_compute_instance_v2.tfer--test
2022/08/12 20:57:03 Refreshing state... openstack_compute_volume_attach_v2.tfer--testvdb
2022/08/12 20:57:03 Refreshing state... openstack_compute_instance_v2.tfer--test-VM-PM
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:03 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:03 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:04 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:04 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 WARN: Fail read resource from provider, wait 300ms before retry
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Fail read resource from provider, trying import command
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 Error creating OpenStack compute client: You must provide exactly one of DomainID or DomainName to authenticate by Username
2022/08/12 20:57:05 ERROR: Unable to refresh resource tfer--test
2022/08/12 20:57:05 ERROR: Unable to refresh resource tfer--test-VM-PM
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ParseTFstate(0x140012db560, {0x10edf3b38?, 0x140010a3810?}, {{0x10eea18f8?, 0x140010cf060?}})
github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:151 +0xcc
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).ConvertTFstate(0x140012db560, 0x1400049e4d0)
github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:176 +0x32c
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).ConvertTFStates(0x14001953a30, 0x1?)
github.com/GoogleCloudPlatform/terraformer/terraformutils/providers_mapping.go:151 +0x7c
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0x140007a8c20, 0x1, 0x1}, {0x114fc6480, 0x0, 0x0}, {0x14000621890, 0x28}, ...}, ...)
github.com/GoogleCloudPlatform/terraformer/cmd/import.go:102 +0x1cc
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdOpenStackImporter.func1(0x14000912580?, {0x10be3f357?, 0x2?, 0x2?})
github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_openstack.go:36 +0x204
github.com/spf13/cobra.(*Command).execute(0x14000912580, {0x140007c4280, 0x2, 0x2})
github.com/spf13/cobra@v1.1.1/command.go:850 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14001067340)
github.com/spf13/cobra@v1.1.1/command.go:958 +0x34c
github.com/spf13/cobra.(*Command).Execute(...)
github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x24
main.main()
github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x58

**Comment by sergeylanzman** [comment]
look like the provider code changed and need pass addinitial parameters

**Comment by modzilla99** [comment]
Same prob here. It can be solved like this:

```shell
$ source ~/Downloads/Project-openrc.sh
Please enter your OpenStack Password for project Octavia as user admin:

$ unset OS_USER_DOMAIN_NAME
$ export OS_DOMAIN_ID=default
```
