### ISSUE TITLE
Unable to import terrform configurations for Okta infrastructure

### ISSUE THREAD

**Issue by mjsharma88** [GoogleCloudPlatform/terraformer#1421]
Hi,

I am trying to explore terraformer to import our already existing Okta infrastructure.

I have windows machine and followed the installation steps mentioned on https://github.com/GoogleCloudPlatform/terraformer/.

I actually used "chocolatey" to install terraformer on my machine as steps mentioned under "windows" sections did not work for me.

**_$ terraformer version
Terraformer v0.8.13_**

When I run **_"terraformer import"_** command then I see the following:

manishasharma@EG-PC2CH4PC MINGW64 ~/learn-terraformer
$ terraformer import
Import current state to Terraform configuration

Usage:
import [command]

**_Available Commands:
aws Import current state to Terraform configuration from AWS
plan Import planned state to Terraform configuration_**

Flags:
-h, --help help for import

Use " import [command] --help" for more information about a command.

As you can see above that the only available terraform import commands are for **"aws"**. However, I need it for **"okta"**.

**Note:** Please note I also installed okta provider from the link https://github.com/GoogleCloudPlatform/terraformer/releases and set the "PATH" variable via system environment variable.

Any leads/help on this would be highly appreciated.

Thanks,
Manisha Sharma

**Comment by sergeylanzman** [comment]
bug in chocolatey package

fixed here https://github.com/DrFaust92/chocolatey-packages/pull/12/files

you can download direct from github all version or only okta version
