### ISSUE TITLE
GCS More Than One Project Output Overwrite 

### ISSUE THREAD

**Issue by tomala90** [GoogleCloudPlatform/terraformer#143]
Hi,

When running import on GCS for more than 1 project the generated files contain configuration for the project that was passed as the last argument into `--project=aaa,bbb,ccc` 

I am trying to enumerate every project in my org to get one big terraform file for with with current state of all buckets.

Here is the command that I am running:
`terraformer import google --resources=gcs --projects=project-aaa-001,project-bbb-001,project-ccc-001 --path-pattern {service}/`

**Comment by sergeylanzman** [comment]
Try use this case without `--path-pattern {service}/`.

**Comment by tomala90** [comment]
@sergeylanzman that helped to get the terraform configuration files divided by projects. Is there an easy way to merge them into bigger terraform files that will define configurations for buckets across many projects? Or is it recommended to keep them divided by project?
