### ISSUE TITLE
Any plan to upgrade to terraform version 1.2.7

### ISSUE THREAD

**Issue by mjsharma88** [GoogleCloudPlatform/terraformer#1434]
Hi,

On my machine, I have **_"terraform 1.2.7"_** installed. 

Terraformer version : **_Terraformer v0.8.21_**

I am using terraformer to import okta infrastructure. The problem is that the state file and terraform config files generated using "terraformer" conforms to the old terraform version "0.12.31" which conflicts with the version installed on my machine.

I use below command for the **migration**:

`terraform state replace-provider "registry.terraform.io/-/okta" "registry.terraform.io/okta/okta"`

By using above command, I am able to run "**_terraform init_**" command successfully but "**_terraform plan_**" fails as configuration file is incompatible with the okta provider used by the latest version of the terraform.

```
Error: Unsupported block type
│ 
│   on network_zone.tf line 2282, in resource "okta_network_zone" "tfer--Vendors-0020---0020-WNS":
│ 2282:   gateways {
│ 
│ Blocks of type "gateways" are not expected here. Did you mean to define
│ argument "gateways"? If so, use the equals sign to assign it a value.
```

```
│ Error: Missing required argument
│ 
│   on template_sms.tf line 1, in resource "okta_template_sms" "tfer--template_sms_Default":
│    1: resource "okta_template_sms" "tfer--template_sms_Default" {
│ 
│ The argument "template" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on template_sms.tf line 1, in resource "okta_template_sms" "tfer--template_sms_Default":
│    1: resource "okta_template_sms" "tfer--template_sms_Default" {
│ 
│ The argument "type" is required, but no definition was found.
```

Is there any way to make terraformer use the latest version of terraform? or any other way to resolve such issues?

Any leads would be highly appreciated.

Thanks,
Manisha Sharma

**Comment by samuelbailey123** [comment]
Hi, I think you're looking for this 
https://github.com/GoogleCloudPlatform/terraformer/issues/1356

**Comment by mjsharma88** [comment]
Thank you Samuel for your response. The link you specified above can help me install older versions of terraform on my machine which I can not do as the requirement is to use the latest terraform version.

I am required to use the latest version of terraform which has  "registry.terraform.io/okta/okta"  as okta provider. However, Terraformer uses the old version of terraform (0.12.31) and hence, the terraform files it generates conforms to the syntax/standard of the okta provider used by terraform version 0.12.31 which are not compatible with the terraform's latest version 1.2.7. Due to this "terraform plan" command fails with errors like "missing required argument" or "unexpected argument" etc. 

Please let me know if there is any way to tweak terraformer to use the latest version of terraform.

Thanks
Manisha Sharma

**Comment by ers81239** [comment]
I'm interested in this as well.  I managed to use terraformer to create TF and a statefile and then I used tfenv to install all the interim major versions of terraform and upgraded the state to the latest version.  

That got me pretty far, but I still have the issue that my users are still creating AWS resources manually and I need to add them to the master terraform repo.  Not sure how that would be possible given the version mismatch.

**Comment by thomas-riccardi** [comment]
not stale

**Comment by jhwal47** [comment]
Not stale, interested in this as well

**Comment by arlekinjose** [comment]
Not stale, interested in this as well

**Comment by thomas-riccardi** [comment]
not stale

**Comment by m-rousse** [comment]
Not stale - I'm interested in this as well!
