### ISSUE TITLE
Feature Request: support AWS SSO resources

### ISSUE THREAD

**Issue by HariSekhon** [GoogleCloudPlatform/terraformer#1439]
Feature request to support AWS SSO resources such as these:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment

```shell
$ terraformer --version
version v0.8.21
```

SSO resources are not listed in:

```shell
$ terraformer import aws list | grep -i sso
```

**Comment by HariSekhon** [comment]
still needed

**Comment by ApsTomar** [comment]
@sergeylanzman I can work on this one. Please assign it to me.

@HariSekhon Can you please mention which resources you need apart from `aws_ssoadmin_account_assignment`?

**Comment by bigwheel** [comment]
I suggest https://github.com/linaro-its/aws2-wrap as workaround.

**Comment by colinjohnsonbeyond** [comment]
this is needed!
