### ISSUE TITLE
datadog dashboard: terraform plan: Error: Missing required argument: widget.0.group_definition.0.widget

### ISSUE THREAD

**Issue by thomas-riccardi** [GoogleCloudPlatform/terraformer#1452]
- the datadog dashboard has an empty group (for used with the nice banner image)
- `terraformer` generates a `group_definition` with no `widget` block
- `terraform apply` reveals the datadog provider is not happy:

```
Error: Missing required argument

  on dashboard.tf line 10743, in resource "datadog_dashboard" "tfer--dashboard_9uc-sp4-3wb":
10743:     group_definition {

The argument "widget.4.group_definition.0.widget" is required, but no
definition was found.
```

(I tried with both v0.8.21 and go build git HEAD e9a73ea)

workaround: manually adding `widget {}`
ideal fix: terraformer does it itself

**Comment by skarimo** [comment]
Hi, which `terraform-provider-datadog` version are you using?

**Comment by thomas-riccardi** [comment]
> Hi, which `terraform-provider-datadog` version are you using?

I tried with what's selected by default with latest terraformer + `terraform init`; it was 3.14.0 but I also tried with 3.15.0 IIRC.

**Comment by skarimo** [comment]
Tested this out and seems to work on my end as expected. What does your dashboard look like? Could you share it's JSON definition

**Comment by thomas-riccardi** [comment]
> Tested this out and seems to work on my end as expected. 

does terraformer generates a `group_definition` with no `widget` block and `terraform-provider-datadog` properly handles it? (which versions?)

or: does terraformer generates a `group_definition` with an empty `widget {}`?

I tried again my described scenario:
- create a new dashboard
- add an empty group

Result:
```json
{"title":"bug-terraformer-issue-1452","description":"","widgets":[{"id":7410876912106814,"definition":{"title":"New group","type":"group","layout_type":"ordered","widgets":[]},"layout":{"x":0,"y":0,"width":12,"height":1}}],"template_variables":[],"layout_type":"ordered","is_read_only":false,"notify_list":[],"reflow_type":"fixed","id":"xne-3uz-4kf"}
```

```shell
$ terraformer-datadog-git-e9a73ea import datadog --resources=dashboard --filter=dashboard=xne-3uz-4kf
$ cd generated/datadog/dashboard/
$ ~/dl/terraform-0.12.31 init
... datadog provider: 3.14.0

$ ~/dl/terraform-0.12.31 apply

Warning: Argument is deprecated

  on dashboard.tf line 2, in resource "datadog_dashboard" "tfer--dashboard_xne-3uz-4kf":
   2:   is_read_only = "false"

Prefer using `restricted_roles` to define which roles are required to edit the
dashboard.


Error: Missing required argument

  on dashboard.tf line 9, in resource "datadog_dashboard" "tfer--dashboard_xne-3uz-4kf":
   9:     group_definition {

The argument "widget.0.group_definition.0.widget" is required, but no
definition was found.
```

(same with datadog provider 3.15.1)

**Comment by skarimo** [comment]
Thanks, I had the wrong understanding of the initial issue. I introduced a fix here: https://github.com/DataDog/terraform-provider-datadog/pull/1576 

Should be available in the next release.
