### ISSUE TITLE
Add darwin-arm64 release

### ISSUE THREAD

**Issue by poolski** [GoogleCloudPlatform/terraformer#1453]
Hi folks, 

Could you please add a `darwin-arm64` release for M1/M2 Mac hardware?

Thanks!

**Comment by sergeylanzman** [comment]
supported today https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.21

**Comment by poolski** [comment]
I'm a fool. `ENOTENOUGHCOFFEE`
