### ISSUE TITLE
AWS import aws_kms_grant violates hcl2 syntax

### ISSUE THREAD

**Issue by ioah86** [GoogleCloudPlatform/terraformer#1455]
It took me a while to see the issue, but here is the problem.

I used the following command with aws as my provider (Terraformer version 0.8.21, Terraform version 1.2.9 inside a Docker container running CentOS 8):

```
terraformer import aws --resources=* --regions=ca-central-1;
```

Among other files, it produces a file called `kms_grant.tf`, with the following content (anonymized here for the ticket):

```
resource "aws_kms_grant" "tfer--arn-anon" {
  constraints "encryption_context_subset" {
    "aws:ebs:id" = "vol-SOME-ID"
  }

  grantee_principal = "arn:aws:sts::FUTHER-DEF"
  name              = "some-uuid"
  operations        = ["Decrypt"]
}
```

I am doing further parsing with those files and analysis. My parser is hung up on the third line there, namely the "aws:ebs:id". Looking at the [HCL2 spec](https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md), it expects an identifier based on ID_START and ID_CONTINUE of the [UAX #31 specification](http://unicode.org/reports/tr31/#R3). I think the problem is the quotations around the identifier, which makes it look like a string-literal, which is not placed there according to the HCL2 spec.

I do not know what the right solution is; you must have gotten that value from somewhere. Hence, let us open this discussion here.

**Comment by ioah86** [comment]
Actually, reflecting further on this, the documentation by [Hashicorp](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_grant#encryption_context_subset) is stating that the [encryption_context_subset](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_grant#encryption_context_subset) is supposed to be a list of key value pairs, not a block. This is where I think the bug here lies. But, in their own example they are doing a `encryption_context_equals`, which is also supposed to be a list, as a block. I checked with 

```
aws kms list-grants --key-id MY-KEY-ID
```

and it returns indeed between the lines

```
"Constraints": {
                "EncryptionContextSubset": {
                    "aws:ebs:id": "vol-SOME-ID"
                }
            }
```

Hence, the identifier needs to be possible to be used... So is this now an issue with Terraform, or Terraformer? Or the loose implementation of the spec?

**Comment by ioah86** [comment]
Last additional comment: I tried two parsers on that file: https://github.com/hashicorp/hcl and https://github.com/amplify-education/python-hcl2 . Both had issues parsing the produced file.

**Comment by im-dim** [comment]
I have the same problem...
Have you made any progress with finding a solution?

**Comment by ioah86** [comment]
Well... I was posting it here so that it can get attention. For now, I have renamed that resource with some `sed` magic :-)

**Comment by im-dim** [comment]
how "aws:ebs:id" should look like?

**Comment by ioah86** [comment]
Well, in order for the terraformer script not to put it as a string, the colons need to be replaced by e.g. underscores

**Comment by rawis** [comment]
Facing the same issue.. :'( 



> 

Hi @ioah86 Can you share, how to outsmart it? What exactly needs to be renamed?

**Comment by ioah86** [comment]
"aws:ebs:id" should be renamed aws_key_id, and remove the quotes (from my example aboce.

**Comment by rawis** [comment]
Hi @ioah86 , i just try to renamd like your example, and its not work correctly.. yes, it become valid syntax, but will fail in provisioning..

After found this https://github.com/hashicorp/terraform/issues/19240  and https://github.com/hashicorp/terraform-provider-aws/issues/24933 , then i try to change like this:

`resource "aws_kms_grant" "tfer--arn-anon" {
  constraints       = {
    encryption_context_subset = {
      "aws:ebs:id" = "vol-SOME-ID"
    }
  }

  grantee_principal = "arn:aws:sts::FUTHER-DEF"
  name              = "some-uuid"
  operations        = ["Decrypt"]
}
`
It become valid and works in my case..  need to "manual "implement this also in others resources then..

**Comment by ioah86** [comment]
The issue is still there, but no one addressed it yet.

**Comment by ioah86** [comment]
I cannot remove the stale label, as I do not belong to the org.
