### ISSUE TITLE
unsupported block type on empty label block when trying to terraform plan on imported state

### ISSUE THREAD

**Issue by richardmcsong** [GoogleCloudPlatform/terraformer#146]
When I try to run a terraform plan on the terraformer output, I often get:
```
Error: Unsupported block type

  on dns_managed_zone.tf line 239, in resource "google_dns_managed_zone" "my-zone":
 239:   labels     {}

Blocks of type "labels" are not expected here. Did you mean to define argument
"labels"? If so, use the equals sign to assign it a value.
```
I've run into the same issue with gcs buckets as well, haven't gone further in testing other resources yet. Is there something that I'm misconfiguring?

**Comment by sergeylanzman** [comment]
Terraform version 0.12?

**Comment by richardmcsong** [comment]
```
Richards-MacBook-Pro:global rsong$ terraform -v
Terraform v0.12.1
+ provider.google v2.11.0
```

**Comment by richardmcsong** [comment]
wait no sorry this is user error. it's pointing to my terraform 11 instance for some reason; my tfstate file is 0.11

**Comment by richardmcsong** [comment]
Actually I realize that my `terraform_version` field in `terraform.tfstate` is always pinned to 0.11.12, even after i remove it from my computer.

**Comment by richardmcsong** [comment]
I got it working after running `terraform 0.12upgrade` on the resulting imported tf and tfstate files

**Comment by sergeylanzman** [comment]
`terraform 0.12upgrade` work good after import?
