### ISSUE TITLE
set ARM_SUBSCRIPTION_ID env var

### ISSUE THREAD

**Issue by eortega74** [GoogleCloudPlatform/terraformer#1475]
Hi I was set up the Subscription:
PS C:\Users\EMartinez2\repo\terraformer\azure> $ARM_SUBSCRIPTION_ID="xxxxxx-xxxx-xxxxxx-xxxxxx-xxxxx-xxxx-"
PS C:\Users\EMartinez2\repo\terraformer\azure> ./terraformer import azure -r resource_group
2022/09/21 15:16:18 set ARM_SUBSCRIPTION_ID env var
PS C:\Users\EMartinez2\repo\terraformer\azure>

Have the error?
set ARM_SUBSCRIPTION_ID env var

Thank you
Ed

**Comment by eortega74** [comment]
I try using linux too, but have the same result

**Comment by eortega74** [comment]
I fixed using this 

$ENV:ARM_SUBSCRIPTION_ID = "xxxxxx-xxxx-xxxxx-xxxxx"

Thank you
Edgardo

**Comment by eortega74** [comment]
but now have this error 

 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by smonda41** [comment]
> Hi I was set up the Subscription: PS C:\Users\EMartinez2\repo\terraformer\azure> $ARM_SUBSCRIPTION_ID="xxxxxx-xxxx-xxxxxx-xxxxxx-xxxxx-xxxx-" PS C:\Users\EMartinez2\repo\terraformer\azure> ./terraformer import azure -r resource_group 2022/09/21 15:16:18 set ARM_SUBSCRIPTION_ID env var PS C:\Users\EMartinez2\repo\terraformer\azure>
> 
> Have the error? set ARM_SUBSCRIPTION_ID env var
> 
> Thank you Ed

i am facing similar issue, can you guide me?
