### ISSUE TITLE
tenant panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by eortega74** [GoogleCloudPlatform/terraformer#1476]
Hi I have this error running for azure.

Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant
panic: runtime error: invalid memory address or nil pointer dereference

Thank you 
Edgardo

**Comment by dbhaigh** [comment]
Same as https://github.com/GoogleCloudPlatform/terraformer/issues/1340
