### ISSUE TITLE
Should the import command not override the exist imported resources?

### ISSUE THREAD

**Issue by ozbillwang** [GoogleCloudPlatform/terraformer#148]
`terraformer` has a good feature which we can use option `--filter`,  I am going to import resources with filter keywords, but it doesn't work directly, so I have to write a script to wrapper the task easily.

>If you have better idea, or the function is ready already somewhere, please point out.

Here are the steps:

```
#!/usr/bin/env bash

# you need custom the filter and other parameters or set as import variables.
filter="app1"
resource="sg"
region="ap-southeast-2"
profile="default"

terraformer plan aws --resources=${resource} --regions=${region} --profile=${profile} 2>&1|tee output

cat output

cat output |grep -i "${filter}"| while read line
do
   filter_key=$(echo ${line} |awk '{print $NF}' |awk -F \. '{print $1}')
   filter_value=$(echo ${line} |awk -F _ '{print $NF}')

   echo ${filter_key} ${filter_value}

   terraformer import aws --resources=${resource} --filter=${filter_key}=${filter_value} --regions=${region} --profile=${profile}
done

```

Looks great and easier, right? But it doesn't work as expect. 

every time, when run `terraform import`, it overrides the whole resources and rewrite *.tf files. I only get one security group. 

What I expect:

1) when import, only add these resources. So with above scripts, if I have 3 Security groups after filtered, I should get three resources in terraform HCL files as well.

**Comment by Arlington1985** [comment]
That is also what I want to achieve. Did you find a workaround?
