### ISSUE TITLE
--filter not working as expected

### ISSUE THREAD

**Issue by DFuller134** [GoogleCloudPlatform/terraformer#1490]
Terraformer v0.8.22

I am unable to filter api_gateway resources as Terraformer v0.8.22 returns all api_gateway assets. I followed the 3rd example from [Issue 331](https://github.com/GoogleCloudPlatform/terraformer/issues/331) (see reference below) in an attempt to filter a specific AWS API Gateway by its ID as follows:

resource "aws_api_gateway_rest_api" "tfer--08tqqu1n6a_PetStore" {
api_key_source = "HEADER"
description = "Your first API with Amazon API Gateway. This is a sample API that integrates via HTTP with our demo Pet Store endpoints"
disable_execute_api_endpoint = "false"

endpoint_configuration {
types = ["REGIONAL"]
}

minimum_compression_size = "-1"
name = "PetStore"
}

COMMAND:
terraformer import aws --resources=api_gateway --filter=aws_api_gateway_rest_api=tfer--08tqqu1n6a_PetStore --profile=saml

Note that I also attempted filtering for a lambda_function as per Issue https://github.com/GoogleCloudPlatform/terraformer/issues/331 recommendation to see if the problem was isolated to aws_api_gateway_rest_api and, while a filter was applied, it only resulted in the generation of lambda_event_source_mapping.tf, outputs.tf, provider.tf, and terraform.tfstate files.

From Issue https://github.com/GoogleCloudPlatform/terraformer/issues/331:

> @ssanbeg To answer your concern, you can filter any resource by its resulting Terraform resource attributes. An example of an AWS resource [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html):
> 
> resource "aws_lambda_function" "lambda_function_id" {
>   environment {
>     variables = {
>       SCHEDULE_HOURS = "1"
>     }
>   }
>   runtime = "java8"
>   tags = {
>     "lambda:createdBy" = "SAM"
>   }
>  ...
> }
> To get only that Lambda function, you can issue the following commands:
> 
> terraformer import aws --resources=lambda --filter="Name=environment.variables.SCHEDULE_HOURS;Value=1" --regions=ap-southeast-1 - to filter all resources by nested path environment.variables.SCHEDULE_HOURS with value 1
> terraformer import aws --resources=lambda --filter="Name=runtime;Value=java8" --regions=ap-southeast-1 - to filter all resources by simple path runtime with value java8
> terraformer import aws --resources=lambda --filter=aws_lambda_function=lambda_function_id --regions=ap-southeast-1 - to filter aws_lambda_function resources by its id lambda_function_id
>

**Comment by meshuga** [comment]
let me have a look there, haven't contributed to the project in a while and something could get broken
