### ISSUE TITLE
Datadog import dashboard failing

### ISSUE THREAD

**Issue by plynch-magnolia** [GoogleCloudPlatform/terraformer#1493]
I have verified the dashboard id I am using is correct, as I have even tried importing ALL dashboards and I get the same error. 

Terraformer v0.8.22
Terraform v1.3.1 or v0.13.7
go version go1.18 
All on darwin/amd64 (Mac Intel)

> 2022/09/30 10:48:14 datadog importing... dashboard
2022/09/30 10:48:15 datadog done importing dashboard
2022/09/30 10:48:15 Number of resources for service dashboard: 1
2022/09/30 10:48:15 Refreshing state... datadog_dashboard.tfer--dashboard_mc8-fcg-9qb
2022-09-30T10:48:15.471-0400 [ERROR] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/datadog/datadog/3.9.0/darwin_amd64/terraform-provider-datadog_v3.9.0 pid=91796 error="exit status 2"
2022/09/30 10:48:15 rpc error: code = Unavailable desc = error reading from server: EOF
2022/09/30 10:48:15 WARN: Fail read resource from provider, wait 300ms before retry
2022/09/30 10:48:15 rpc error: code = Canceled desc = context canceled
2022/09/30 10:48:15 WARN: Fail read resource from provider, wait 300ms before retry
2022/09/30 10:48:16 rpc error: code = Canceled desc = context canceled
2022/09/30 10:48:16 WARN: Fail read resource from provider, wait 300ms before retry
2022/09/30 10:48:16 rpc error: code = Canceled desc = context canceled
2022/09/30 10:48:16 WARN: Fail read resource from provider, wait 300ms before retry
2022/09/30 10:48:17 rpc error: code = Canceled desc = context canceled
2022/09/30 10:48:17 WARN: Fail read resource from provider, wait 300ms before retry
2022/09/30 10:48:17 Fail read resource from provider, trying import command
2022/09/30 10:48:17 rpc error: code = Canceled desc = context canceled
2022/09/30 10:48:17 ERROR: Unable to refresh resource tfer--dashboard_mc8-fcg-9qb
2022/09/30 10:48:17 Filtered number of resources for service dashboard: 0
2022/09/30 10:48:17 datadog Connecting....
2022/09/30 10:48:17 datadog save dashboard
2022/09/30 10:48:17 datadog save tfstate for dashboard

**Comment by plynch-magnolia** [comment]
Upgraded to 3.16 but still get the same error

**Comment by skarimo** [comment]
Could you set the env var `TF_LOG=debug` and run terraformer in verbose mode `-v` and share the output. This will probably contain your api/app keys so redact those.

**Comment by skarimo** [comment]
Your `api-url` variable is wrong. See the request: `/api/v2//api/v1/validate`. Use the same format as described in the [terraform docs](https://registry.terraform.io/providers/DataDog/datadog/latest/docs#optional) and omit the path `/api/v2/`

**Comment by plynch-magnolia** [comment]
That was it...Thank you!
