### ISSUE TITLE
Can't install terraformer to Linux due to okta dependency

### ISSUE THREAD

**Issue by andy65535** [GoogleCloudPlatform/terraformer#1498]
Hi!

I'm trying to install terraformer to Fedora Linux.
I cloned current master repo of terraformer:

$ git log
commit 498fa8060a5c03daae91d3da327e712f1590a7e8 (HEAD -> master, tag: 0.8.22, origin/master, origin/HEAD)

and following the README running

$ go mod download

Got error:
go: github.com/okta/okta-sdk-golang/v2@v2.12.2-0.20220602195034-d7ea6917663f: invalid version: unknown revision d7ea6917663f

$ go version
go version go1.15.15 linux/amd64

**Comment by sre-is-josebiro** [comment]
This should be reopened, it's still an issue.

**Comment by sre-is-josebiro** [comment]
As a workaround, you can update go.mod and edit the line:
`    github.com/okta/okta-sdk-golang/v2 v2.12.2-0.20220602195034-d7ea6917663f`
and change it to:
`    github.com/okta/okta-sdk-golang/v2 v2.16.0`

From here `go mod download` should work, and you can `go test ./...` to validate tests still pass.
