### ISSUE TITLE
Cloudflare Error 

### ISSUE THREAD

**Issue by SantiEich** [GoogleCloudPlatform/terraformer#151]
<img width="632" alt="Screen Shot 2019-07-25 at 16 01 17" src="https://user-images.githubusercontent.com/21198777/61901176-8f8b4380-aef5-11e9-8653-3498732838aa.png">

**Comment by sergeylanzman** [comment]
It's from release or master? 
Cloudflare merged to master, but not released.
You can build from master

**Comment by SantiEich** [comment]
It's from release! 
I build from master and works :)
Thanks!
