### ISSUE TITLE
Filtering datasets

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/terraformer#152]
Hi,

How can I filter on datasets ids? For example, I only want dataset id 'foo'.

The filter flag expects 'resource_type:id1:id2' but the resource id for datasets are in form project:dataset_id which conflicts with this.

**Comment by sergeylanzman** [comment]
yes... we use ":" as delimeter :(

You can import with plan command to JSON file and edit/delete your dataset in json, after this import from json.
