### ISSUE TITLE
--filter does not work 

### ISSUE THREAD

**Issue by AdanDaniel** [GoogleCloudPlatform/terraformer#1529]
I'm trying to import 1 ALB using the name tag but terraformer is trying to import all.....

terraformer import aws --resources=alb --regions=us-east-1 --profile=prod --filter="Name=Name;Value=my-alb"

**Comment by thom-vend** [comment]
Same with route53 record, it seems I'm using an invalid filter, silently ignore it and import all.

**Comment by thom-vend** [comment]
^ not really helpful to auto-close and hide problems in a project 🤷

**Comment by laurie-kepford** [comment]
I am having the same problem.  My problem is with filtering EKS clusters.  I posted to another issue: https://github.com/GoogleCloudPlatform/terraformer/issues/1655

judging by the number of issues that getting closed without ever being assigned, I am beginning to think that no one is home here.

**Comment by jakegut** [comment]
To filter on tag you need to do `--filter=Name=tags.<Tag Name>;Value=<Value>`:

`terraformer import aws --resources=alb --regions=us-east-1 --profile=prod --filter="Name=tags.Name;Value=my-alb"`
