### ISSUE TITLE
Filter only requested ids

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/terraformer#153]
When filtering with a dataset id for the bigquery resource, I expect only datasets to be imported. Surprisingly, all BQ tables are also imported. After reading the documentation more I realized even if you only want a specific dataset id, you still have to pass in a filter for tables. So, to stop tables from showing up I had to filter with 'google_bigquery_table=dne'.

The behaviour of filter is not what I would expect. It does not follow gcloud --filter either which only shows what passes your listed filter. The current behaviour also forces the user to keep track of each supported type. For example if today resource_type foo and bar are supported then tomorrow baz is added, I would suddenly start seeing all baz resources being imported.

I would like to request filter to only respect what is listed. If a user wants all of one resource type but specific id of another perhaps support for a wildcard '*' symbol can be added.

Another option could be under --resources to allow only checking for specific resource types e.g.

--resources=bigQuery:google_bigquery_dataset,compute,gke

**Comment by sergeylanzman** [comment]
I think you talk about this https://github.com/GoogleCloudPlatform/terraformer/pull/157

Try this branch
