### ISSUE TITLE
Importing Azure keyvault fails

### ISSUE THREAD

**Issue by berndkaiser** [GoogleCloudPlatform/terraformer#1577]
Importing an Azure keyvault fails:

`terraformer import azure -R 'group' -r 'keyvault'`
```
022/11/29 13:12:57 Testing if Service Principal / Client Secret is applicable for Authentication..
2022/11/29 13:12:57 Testing if OIDC is applicable for Authentication..
2022/11/29 13:12:57 Testing if Managed Service Identity is applicable for Authentication..
2022/11/29 13:12:57 Testing if Obtaining a Multi-tenant token from the Azure CLI is applicable for Authentication..
2022/11/29 13:12:57 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2022/11/29 13:12:57 Using Obtaining a token from the Azure CLI for Authentication
2022/11/29 13:12:57 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant id
2022/11/29 13:12:58 azurerm importing... keyvault
2022/11/29 13:12:58 azurerm done importing keyvault
2022/11/29 13:12:58 Number of resources for service keyvault: 1
2022/11/29 13:12:58 Refreshing state... vault_name
2022/11/29 13:20:29 retrieving `contact` for KeyVault: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: authorizer was not an auth.CachedAuthorizer for https://vault.azure.net
2022/11/29 13:20:29 WARN: Fail read resource from provider, wait 300ms before retry
2022/11/29 13:28:01 retrieving `contact` for KeyVault: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: authorizer was not an auth.CachedAuthorizer for https://vault.azure.net
2022/11/29 13:28:01 WARN: Fail read resource from provider, wait 300ms before retry
```

Version: Terraformer v0.8.22 (31e60cc277a48f281ce0674a6d0a5edf040a3b12)
go version: go1.19.3 linux/amd64

**Comment by juarezr** [comment]
Do you have more information about the context where the error occurs?

- Which [authentication](https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/azure.md#supported-methods) method was [used](https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/azure.md#examples)?
- What are the [roles](https://learn.microsoft.com/en-us/azure/key-vault/general/security-features) and [permissions](https://learn.microsoft.com/en-us/azure/key-vault/general/security-features) granted to the user/login used by `terraformer`?
- There is any policy enabled for the [keyvault](https://learn.microsoft.com/en-us/azure/key-vault/general/troubleshoot-azure-policy-for-key-vault)?
