### ISSUE TITLE
failures importing subnetworks on GCP

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/terraformer#159]
```
$ terraformer import google --resources subnetworks --projects my-project
```
gives me an error:
```
2019/08/01 18:06:16 google importing project peppy-breaker-161717 region global
2019/08/01 18:06:17 google importing... subnetworks
2019/08/01 18:06:17 googleapi: got HTTP response code 404 with body: Not Found
```
The request looks like it's going to an incorrect URL:
```
https://www.googleapis.com/compute/v1/projects/my-project/regions//subnetworks?alt=json&prettyPrint=false
```
Note the double slash after `regions`.  If I put the name of a region in there instead (say, `us-west1`), then I get a reasonable response body.

This is using commit 34538f2.

**Comment by sergeylanzman** [comment]
`$ terraformer import google --resources subnetworks --projects my-project --regions us-west1`?

**Comment by dhduvall** [comment]
Yes, that works; it's only if I take the default of `global`, or explicitly say `--regions global`, that I get this error.

**Comment by sergeylanzman** [comment]
Yes GCP api not support global in subnets..

**Comment by dhduvall** [comment]
Would it not be possible to work around that by enumerating the regions explicitly? This works (sort of) for all the other resources I've tried. I'll also note that specifying a zone instead of a region results in the same problem, though I suppose importing resources from a specific zone is no longer supported.

Basically, it's not particularly user-friendly that if I want to do a global import of all of my resources, it just fails with an error that requires MITMing the connection to diagnose. Once I do so, then I can either remove subnetworks from the import, or do the import region by region, but either way is a pain (and the diagnosis is pretty bad).

**Comment by samveen** [comment]
Workaround I used after finding this issue, on facing the regions issue:

```bash
terraformer import google --projects my-project --regions $(gcloud compute regions list |awk 'BEGIN{s=""}{if(!s){s=","}else{printf "%s%s",s,$1}}') --resources instances
```
