### ISSUE TITLE
accessanalyzer import from AWS not working

### ISSUE THREAD

**Issue by Lorenzo-Vicente** [GoogleCloudPlatform/terraformer#1590]
There is another issue that was marked as stale, because nobody responded to it. Stale or not, this issue still persists when trying to import resources from AWS.

```
$ terraformer import aws --resources=*
2022/12/10 12:44:16 aws importing default region
2022/12/10 12:44:16 Attempting an import of ALL resources in aws
2022/12/10 12:44:16 aws importing... accessanalyzer
2022/12/10 12:44:16 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found
2022/12/10 12:44:16 aws importing... acm
2022/12/10 12:44:16 aws done importing acm
2022/12/10 12:44:16 aws importing... alb
2022/12/10 12:44:17 aws done importing alb
.
.
.
2022/12/10 12:44:46 aws save wafv2_cloudfront
2022/12/10 12:44:46 aws save tfstate for wafv2_cloudfront
```

```
$ terraformer import aws --resources=accessanalyzer --regions=us-east-1
2022/12/10 12:46:03 aws importing region us-east-1
2022/12/10 12:46:04 aws importing... accessanalyzer
2022/12/10 12:46:04 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found
2022/12/10 12:46:04 aws Connecting.... 
```

**Comment by damo78** [comment]
Why does this issue keep getting closed with no resolution if the issue still persists?

2023/11/01 13:04:58 aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found

The old issue is also closed with the same: https://github.com/GoogleCloudPlatform/terraformer/issues/1324

**Comment by monelgordillo** [comment]
I'm getting the same issue for this.  It is asking for a region eventhough I've added a region via --regions=

**Comment by ikemuc** [comment]
I'm having the same problem... I have --regions set, AWS credentials are configured (aws s3 ls is working), but when I try to do "terraformer import aws", the first message is "aws error initializing resources in service accessanalyzer, err: operation error AccessAnalyzer: ListAnalyzers, failed to resolve service endpoint, an AWS region is required, but was not found" and then I get tons of "api error UnrecognizedClientException: The security token included in the request is invalid."

**Comment by vitich** [comment]
I got the same error. 
I see how the developers are rushing to fix an obvious bug - let's wait a few more years...
