### ISSUE TITLE
Error: Missing required argument

### ISSUE THREAD

**Issue by codedev900** [GoogleCloudPlatform/terraformer#1593]
I have ran the import using the command `terraformer import aws --resources="*" --regions=us-east-1` and all worked with no issues. I ran `terraform init` and got the following error "Invalid legacy provider address You must complete the Terraform 0.13 upgrade process before upgrading to later versions". So I ran this command` terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"`

My issue is when I run `terraform plan` I get a lot of "Error: Missing required argument" or "Error: Conflicting configuration arguments". 

You're help would be much appreciated.

**Comment by daizikaikou** [comment]
I have the same problem, do you know how to solve it? @codedev900

**Comment by daizikaikou** [comment]
$ terraform plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
╷
│ Error: Conflicting configuration arguments
│
│   with aws_eks_node_group.tfer--ng-01-20230204082937888500000020,
│   on eks_node_group.tf line 17, in resource "aws_eks_node_group" "tfer--ng-01-20230204082937888500000020":
│   17:   node_group_name        = "ng-01-20230204082937888500000020"
│
│ "node_group_name": conflicts with node_group_name_prefix



I annotate node_group_name_prefix to circumvent this problem
