### ISSUE TITLE
importing GCP compute instances for a region only gives one zone

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/terraformer#160]
If I try to import the compute instances from a region:
```
$ terraformer import google --resources instances --regions us-west1 --projects my-project
```
then I don't get all the instances from that region:
```
2019/08/01 18:49:27 google importing project my-project region us-west1
2019/08/01 18:49:28 google importing... instances
2019/08/01 18:49:29 Refreshing state... google_compute_instance.instance1
2019/08/01 18:49:31 google Connecting....
2019/08/01 18:49:31 google save instances
```
I see that it makes a request to list instances for each zone in the region:
```
https://www.googleapis.com/compute/v1/projects/my-project/zones/us-west1-a/instances&?alt=json&prettyPrint=false
https://www.googleapis.com/compute/v1/projects/my-project/zones/us-west1-b/instances&?alt=json&prettyPrint=false
https://www.googleapis.com/compute/v1/projects/my-project/zones/us-west1-c/instances&?alt=json&prettyPrint=false
```
but then when it gets the details of the instances, it only pulls the data for the instances in `us-west1-c`:
```
https://www.googleapis.com/compute/v1/projects/peppy-breaker-161717/zones/us-west1-c/instances/instance1?alt=json&prettyPrint=false
https://www.googleapis.com/compute/v1/projects/peppy-breaker-161717/zones/us-west1-c/disks?alt=json&pageToken=&prettyPrint=false
https://www.googleapis.com/compute/beta/projects/peppy-breaker-161717/zones/us-west1-c/instances/instance1?alt=json&prettyPrint=false
https://www.googleapis.com/compute/v1/projects/peppy-breaker-161717/zones/us-west1-c/disks/instance1?alt=json&prettyPrint=false
```
Since I can't specify a specific zone, then I don't know how I can work around this and get the instances from `us-west1-a` and `us-west1-b`.

**Comment by rommi4** [comment]
https://github.com/GoogleCloudPlatform/terraformer/issues/156#issuecomment-518673123
think that's  connected issue (have instances in different zones and regions, and got nothing)
@dhduvall where did you get https requests?

**Comment by dhduvall** [comment]
It might be related, though I do get some instances imported, but only ones from the last zone it checks. The same happens for disks, which are similarly spread through multiple zones in the same region.

I got the requests by inserting [mitmproxy](https://mitmproxy.org) into the chain. Set `SSL_CERT_FILE=$HOME/.mitmproxy/mitmproxy-ca-cert.pem` `https_proxy=http://localhost:9999/` in your environment (set the host and port appropriately), and that's enough to get Go's TLS code to accept the certs the proxy creates. Terraformer makes the requests and gets the responses as expected, and you can see all of the detail, replay it, modify individual requests and re-send them, etc.

**Comment by sergeylanzman** [comment]
Thank you for report! fixed
