### ISSUE TITLE
Import Datadog Monitors filtering on tags

### ISSUE THREAD

**Issue by gw-bcharboneau** [GoogleCloudPlatform/terraformer#1605]
is it possible to filter monitor import from datadog on the monitors tags? if so can documentation be provided on how to filter on the tags?

OS: Windows 10
Terraformer Version: 0.8.22
Terraform Version: 1.3.6
Datadog Provider Version: 3.20.0

I have tried multiple variations to try and get it to import tags sometimes it will filter and exclude all, other times it will not exclude anything.

**Comment by henrwal** [comment]
Hi @gw-bcharboneau,

The DataDog provider documentation lacks adequate information on filtering tags. I will submit a Pull Request to provide additional clarification on this topic.

I did manage to get this working though. 

Filtering tags is as follows: `--filter="Name=tags;Value='your tag'"`.

**Examples:**

```shell

# Import monitors based on multiple tags
terraformer import datadog --resources=monitor --filter="Name=tags;Value='foo:bar'" --filter="Name=tags;Value='env:staging'"

# Import monitor based on one tag
terraformer import datadog --resources=monitor --filter="Name=tags;Value='foo:bar'"

# Import monitor where tag doesn't include colon
terraformer import datadog --resources=monitor --filter="Name=tags;Value=anExampleTag"
```

**Considerations**:
- Tag filters are order specific i.e., if your monitor has tags (in the order) `fruit: apple`, `foo:bar` but you filter for `--filter="Name=tags;Value='foo:bar'" --filter="Name=tags;Value='fruit:apple'"`, the monitor won't be imported.
- If your tag includes a colon, wrap the value in apostrophes.

Hope this helps 😄
