### ISSUE TITLE
terraformer v 0.8.22: can not import Myrasec resources

### ISSUE THREAD

**Issue by admantium-sg** [GoogleCloudPlatform/terraformer#1607]
Hello,

I’m using the recent version terraformer binary 0.8.22 darwin-amd64 to import Myrasec resources. 

As documented, I set the environment variables `MYRASEC_API_SECRET` and ` MYRASEC_API_TOKEN`. These secrets are correct and I have resources defined at Myrasec.

However, when I execute an import or plan statement, no resources are recognized, I only see the following error messages:

```
./terraformer-all-darwin-amd64 plan myrasec -r "cache_setting,dns_record,domain,error_page,ip_filter,maintenance,ratelimit,redirect,settings,waf_rule"
2023/01/13 13:22:14 myrasec importing... cache_setting
2023/01/13 13:22:14 myrasec error initializing resources in service cache_setting, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... dns_record
2023/01/13 13:22:14 myrasec error initializing resources in service dns_record, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... domain
2023/01/13 13:22:14 myrasec error initializing resources in service domain, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... error_page
2023/01/13 13:22:14 myrasec error initializing resources in service error_page, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... ip_filter
2023/01/13 13:22:14 myrasec done importing ip_filter
2023/01/13 13:22:14 myrasec importing... maintenance
2023/01/13 13:22:14 myrasec error initializing resources in service maintenance, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... ratelimit
2023/01/13 13:22:14 myrasec error initializing resources in service ratelimit, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... redirect
2023/01/13 13:22:14 myrasec error initializing resources in service redirect, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 myrasec importing... settings
2023/01/13 13:22:14 myrasec done importing settings
2023/01/13 13:22:14 myrasec importing... waf_rule
2023/01/13 13:22:14 myrasec error initializing resources in service waf_rule, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/01/13 13:22:14 Number of resources for service settings: 0
2023/01/13 13:22:14 Number of resources for service ip_filter: 0
2023/01/13 13:22:14 Saving planfile to generated/myrasec/terraformer/plan.json
```

How can I solve this error?

**Comment by smashi** [comment]
Hi, i need to check that. if you have questions about myrasec provider you can ask me.

**Comment by smashi** [comment]
Hi, 
first thing figured out is that there might be a mistake in the documentation, can you please try `MYRASEC_API_KEY` instead of `MYRASEC_API_TOKEN`, but then the error should be a different one.
Which version of the myrasec terraform provider are you using?

**Comment by smashi** [comment]
Hi @admantium-sg,
i created a new pull request to fix this issue, so it should be available soon
BR Tim

**Comment by smashi** [comment]
Or you install terraformer from our repository and use the branch myrasec
https://github.com/Myra-Security-GmbH/terraformer/tree/myrasec#installation

**Comment by admantium-sg** [comment]
Hello @smashi,

I can not see the pull request, so I headed over to the terraformer clone at https://github.com/Myra-Security-GmbH/terraformer. In this project, there is no branch #myrsec either.

Finally I cloned the repo from https://github.com/Myra-Security-GmbH/terraformer, build the binary, and tried the import with the latest Myrasec Provider v1.55.0. The terraformer import does not work.

```
> ./terraformer-myrasec import myrasec --resources "domain,ip_filter,waf_rule" 

2023/02/10 10:33:41 myrasec importing... domain
2023/02/10 10:33:41 myrasec error initializing resources in service domain, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/02/10 10:33:41 myrasec importing... ip_filter
2023/02/10 10:33:41 myrasec done importing ip_filter
2023/02/10 10:33:41 myrasec importing... waf_rule
2023/02/10 10:33:41 myrasec error initializing resources in service waf_rule, err: parse "%!(EXTRA string=domains)": invalid URL escape "%!("
2023/02/10 10:33:41 Number of resources for service ip_filter: 0
2023/02/10 10:33:41 myrasec Connecting....
2023/02/10 10:33:41 myrasec save ip_filter
2023/02/10 10:33:41 myrasec save tfstate for ip_filter

> terraform show  
No state.
```

**Comment by smashi** [comment]
Hi @admantium-sg,
i deleted the myrasec branch and had not updated our master branch.
This is now done, so you can checkout the master and it should work now.
BR Tim

**Comment by admantium-sg** [comment]
Hello @smashi,

thank you, the current main branch of https://github.com/Myra-Security-GmbH/terraformer works flawlessly :) 

Will you open a PR to include your changes into this origin repo?

Kind regards

Sebastian

**Comment by smashi** [comment]
Hi @admantium-sg ,
the changes are already merged to the master of the origin repository here and will be available in the next version.
but of cause i can't tell you when this new version will be released.
BR Tim

**Comment by smashi** [comment]
Our forked master is at the same state as the master here
