### ISSUE TITLE
Using terraformer with AzureUSGovernment fails with SubscriptionNotFound

### ISSUE THREAD

**Issue by nickamon** [GoogleCloudPlatform/terraformer#1608]
Hi,

Using terraformer version v0.8.22 to import existing resources in an Azure US Government cloud subscription fails with the following error:

```
azurerm error initializing resources in service resource_group, err: resources.GroupsClient#List: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '?????' could not be found."
```

I don't have any issues managing the environment with the Azure CLI.  ***In addition, I'm able to successfully create resources using terraform plan/apply with the same configuration but importing any resources fails***, for example:

```
terraformer import azure -r resource_group
```
returned the above error.

Below is my terraform init.tf file:

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

# Configure the Azure provider
provider "azurerm" {
  environment = "azureusgovernment"
  features {}
}
```

How can I solve this error?

**Comment by rdeberry-sms** [comment]
bump
