### ISSUE TITLE
Terraformer - Azure - Import Error - unknown shorthand flag: 'R' in -R

### ISSUE THREAD

**Issue by MrMoshkovitz** [GoogleCloudPlatform/terraformer#1616]
![TerraformerIssue](https://user-images.githubusercontent.com/50079480/215336998-73731bd4-5e94-49ed-ac2f-fedd3756bce3.png)

**My OS Information**
Operating System:    Ubuntu 20.04.5 LTS
Distributor ID:           Ubuntu
Release:                     20.04
Kernel:                       Linux 5.15.0-1031-azure
Architecture:             x86-64
5.15.0-1031-azure

**Terraform Version**
Terraform v1.3.7
on linux_amd64

**Comment by shblue21** [comment]
Hello
Have you installed the terraform azure provider?
It is possible that you have installed a different provider.

**Comment by balagcpcloud** [comment]
> Hello
> 
> Have you installed the terraformer azure or all provider? It is possible that you have installed a different provider.
> 
> Enter `terraformer import --help` command to check if **azure** is in **Available Commands**.
> 
> ![image](https://user-images.githubusercontent.com/25363091/217408765-f839ac70-809e-40f4-9edb-46c4d0aa2e50.png)

How to install azure terraform provider ?
