### ISSUE TITLE
Error: Import Azure with CLI auth throws "exec: no command"

### ISSUE THREAD

**Issue by benydc** [GoogleCloudPlatform/terraformer#1627]
I'm getting this error when trying to do `terraformer import azure -r <some-resource-group>`:

```
2023/02/02 10:38:02 Testing if Service Principal / Client Certificate is applicable for Authentication..
2023/02/02 10:38:02 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2023/02/02 10:38:02 Testing if Service Principal / Client Secret is applicable for Authentication..
2023/02/02 10:38:02 Testing if OIDC is applicable for Authentication..
2023/02/02 10:38:02 Testing if Managed Service Identity is applicable for Authentication..
2023/02/02 10:38:02 Testing if Obtaining a Multi-tenant token from the Azure CLI is applicable for Authentication..
2023/02/02 10:38:02 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2023/02/02 10:38:02 Using Obtaining a token from the Azure CLI for Authentication
2023/02/02 10:38:03 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant <some-tenant-id>
2023/02/02 10:38:04 exec: no command
```

Anyone seen this issue before?

**Comment by k-ayache** [comment]
samething here

**Comment by benydc** [comment]
@k-ayache I was able to fix it by copying the provider binary in the `.terraform.d/plugins/darwin_amd64` folder. Depending on your platform, the last folder might be different. List of provider is from here (under `Links to download Terraform Providers:`): https://github.com/GoogleCloudPlatform/terraformer#using-a-package-manager

**Comment by ayesha54** [comment]
this helped 

`
#!/bin/bash

# Set environment variables
export PROVIDER=datadog
export PROVIDER_VERSION=3.33.0
export OS=darwin

# Install terraformer
TERRAFORMER_VERSION=$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/${TERRAFORMER_VERSION}/terraformer-${PROVIDER}-${OS}-arm64
chmod +x terraformer-${PROVIDER}-${OS}-arm64
sudo mv terraformer-${PROVIDER}-${OS}-arm64 /usr/local/bin/terraformer

# Install Datadog provider
mkdir -p ~/.terraform.d/plugins/${OS}_arm64
curl -L https://releases.hashicorp.com/terraform-provider-datadog/${PROVIDER_VERSION}/terraform-provider-datadog_${PROVIDER_VERSION}_${OS}_arm64.zip -o terraform-provider-datadog.zip
unzip terraform-provider-datadog.zip
mv terraform-provider-datadog_v${PROVIDER_VERSION}* ~/.terraform.d/plugins/${OS}_arm64/

# Cleanup
rm terraform-provider-datadog.zip

`

**Comment by mly-johndpope** [comment]
install properly for m1

```shell

export PROVIDER=all
curl -LO "https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64"
chmod +x terraformer-${PROVIDER}-darwin-amd64
sudo mv terraformer-${PROVIDER}-darwin-amd64 /usr/local/bin/terraformer
```
