### ISSUE TITLE
Support for current version of terraform?

### ISSUE THREAD

**Issue by rupaks** [GoogleCloudPlatform/terraformer#1642]
### Discussed in https://github.com/GoogleCloudPlatform/terraformer/discussions/1257

<div type='discussions-op-text'>

<sup>Originally posted by **9digitdev** March 14, 2022</sup>
What is the process to upgrade Terraformer to support the most recent version of terraform? The most recent version listed today is 1.1.7. Would this be a major overhaul? </div>

**Comment by rupaks** [comment]
Its frustrating to see terraformer  using "terraform_version": "0.12.31"
even Terraform version installed installed is 1.3.2

is there any workaround?

**Comment by shblue21** [comment]
https://github.com/GoogleCloudPlatform/terraformer#migration-state-version
