### ISSUE TITLE
Fetching thousands of resources

### ISSUE THREAD

**Issue by nbajaj90** [GoogleCloudPlatform/terraformer#1644]
Is there any example to fetch thousands of resources in a guaranteed way, for example 60k ec2 instances from a single AWS region.

**Comment by sergeylanzman** [comment]
It’s same like take 100 ec2 instances. Maybe some problem with aws limit and this take more time.

terraformer call list api and after this get api for each instance. interesting memory usage in this case. 
maybe better use tag filter and running with few steps
