### ISSUE TITLE
filtering for an alb resource won't import its underlying resources

### ISSUE THREAD

**Issue by mmigliari** [GoogleCloudPlatform/terraformer#1645]
Problem:

When you do:

terraformer import aws --resources=alb --region=<my-region>

It imports all underlying resources, i.e.

aws_lb
aws_lb_listener
aws_lb_listener_rule
aws_lb_listener_certificate
aws_lb_target_group
aws_lb_target_group_attachment
However, if you filter the alb you want by filtering it via id (arn), it does not import all its underlying resources, but simply the lonely aws_lb.

terraformer import aws --resources=alb --filter="Name=id;Value='arn:aws.......' --regions=<my-region>

This is inconsistent behavior and makes importing a single ALB and its underlying resources a complete chore.

**Comment by vin0thramamoorthy** [comment]
even filter option is not working with tags

terraformer import aws --resources=alb filter="Name=tags:test;Value=import"
