### ISSUE TITLE
Invalid memory address when trying to import security group in aws

### ISSUE THREAD

**Issue by letmetechyou** [GoogleCloudPlatform/terraformer#1650]
`2023/02/24 14:49:10 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x58bcfdf]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
        /home/runner/work/terraformer/terraformer/providers/aws/sg.go:362
github.com/GoogleCloudPlatform/terraformer/providers/aws.baseRuleAttributes({_, _}, {0x0, 0xc001a71c70, {0xc00413bbf0, 0x1, 0x1}, {0x1142c818, 0x0, 0x0}, ...}, ...)  
        /home/runner/work/terraformer/terraformer/providers/aws/sg.go:164 +0x33f   
github.com/GoogleCloudPlatform/terraformer/providers/aws.processRule({0x0, 0xc001a71c70, {0xc00413bbf0, 0x1, 0x1}, {0x1142c818, 0x0, 0x0}, {0x1142c818, 0x0, ...}, ...}, ...)
        /home/runner/work/terraformer/terraformer/providers/aws/sg.go:145 +0x718   
github.com/GoogleCloudPlatform/terraformer/providers/aws.SecurityGenerator.createResources({{{{0xc000e40071, 0x2}, {0x0, 0x0, 0x0}, {0xa1021a8, 0x3}, 0xc003c39980, {0x1142c818, 0x0, ...}, ...}}}, ...)
        /home/runner/work/terraformer/terraformer/providers/aws/sg.go:84 +0x7cd    
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityGenerator).InitResources(0xc003c6ac60)
        /home/runner/work/terraformer/terraformer/providers/aws/sg.go:260 +0x3b0   
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc003bf5950?)
        /home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc00142b700, 0xb, 0x10}, {0x1142c818, 0x0, 0x0}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc00142b700, 0xb, 0x10}, {0x1142c818, 0x0, 0x0}, {0xc0000b819b, 0x15}, {0xa11117c, ...}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:166 +0x1a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc00142b700, 0xb, 
0x10}, {0x1142c818, 0x0, 0x0}, {0xc0000b819b, 0x15}, ...}, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc00137fce0, 0xb, 0xb}, {0x1142c818, 0x0, 0x0}, {0xc0000b819b, 0x15}, {0xa11117c, 0x9}, ...}, 
...)
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0012b4000?, {0xa103340?, 0x2?, 0x2?})
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:66 +0x13egithub.com/spf13/cobra.(*Command).execute(0xc0012b4000, {0xc000385740, 0x2, 0x2})  
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67cgithub.com/spf13/cobra.(*Command).ExecuteC(0xc000e28dc0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39dgithub.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895       
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
        /home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
        /home/runner/work/terraformer/terraformer/main.go:39 +0x50`

**Comment by duclm2609** [comment]
I have same issue.

**Comment by shblue21** [comment]
Hi, are you using the latest version of terrafomer? This seems to be fixed in the latest version #1492

**Comment by zoomincha-rsqaure** [comment]
I have the same issue with v0.8.22
Could I get the help for getting the fixed version above?

**Comment by shblue21** [comment]
@zoomincha-rsqaure It's merged, but it looks like it hasn't been released yet. Can you get the latest code and build it?

**Comment by zoomincha-rsqaure** [comment]
@shblue21 
Thank you for your comment.
I had pulled the master branch and built it. 
So I can run the terraformer properly for importing the security groups on my aws environments.
I look forward to release the latest version soon. 
(I prefer the released version controlled by brew.)

**Comment by jamiejackson** [comment]
Any word on when this will be released (and in which version)? Brew still gives v0.8.22. I realize I can build it myself but I'm just going to go without security group import ability until it's fixed in a release.

**Comment by shblue21** [comment]
Please try the recently released 0.8.24 version
