### ISSUE TITLE
Getting invalid characters for resource names in gcp

### ISSUE THREAD

**Issue by rishu06** [GoogleCloudPlatform/terraformer#1658]
Hi
when i run 
terraformer plan google --resources=iam ---projects=xxxxx, 
in saved plan.json file it gives me invalid characters 
eg: 
resource "google_project_iam_member" "tfer--roles-002F-vieweruser-003A" 

Is this expected ?
or am I missing something?

**Comment by shblue21** [comment]
Yes, this is the intended result. Resources created by terraformers begin with tfer--.

**Comment by rishu06** [comment]
Can we change it somehow ?
