### ISSUE TITLE
datadog dashboard widgets get rearranged

### ISSUE THREAD

**Issue by jsteinberg-rbi** [GoogleCloudPlatform/terraformer#1670]
terrafomer'ing datadog dashboards is impeded by the fact that datadog groups (of widgets) are rearranged via terraformer meaning if you use terraformer datadog dashboard output to create new dashboards in the case of say a large dashboard when you recreate it the widgets will be in a different order than whatever you clickops'd so if you had planned to use such terraform to create say 10 or 20 new dashboards you're going to spend a ton of toil time rearranging the dashboard groups back to how you want them after terraform creates them :-(

**Comment by pietrodn** [comment]
I noticed the same and was able to find a workaround by downgrading to 0.8.21.

**Comment by alexwilkerson** [comment]
Was this issue ever resolved?

**Comment by JordanHLee** [comment]
I guess this was never resolved? Dont really want to downgrade to a version over year old at this point?
