### ISSUE TITLE
Support for Proxmox provider

### ISSUE THREAD

**Issue by vilhelmprytz** [GoogleCloudPlatform/terraformer#1687]
It would be great if Terraformer can support the proxmox provider, see https://registry.terraform.io/providers/Telmate/proxmox/latest

**Comment by vilhelmprytz** [comment]
I still believe this would be a nice addition. I just haven't had the time to look into coding it myself.

**Comment by vilhelmprytz** [comment]
Again, I still believe this would be a nice addition. I still just haven't had the time to look into coding it myself.

**Comment by vilhelmprytz** [comment]
This is still relevant, I think!

**Comment by yelinaung** [comment]
Bumping this to see any plan for this support!

**Comment by icodeforyou-dot-net** [comment]
Yes, it would be great to see support for Proxmox!

**Comment by BasixKOR** [comment]
Would GCP merge any community contributions for Proxmox? I think it would be a neat addition.

**Comment by yelinaung** [comment]
I have found another Promox Terraform Provider 
https://github.com/bpg/terraform-provider-proxmox

It has a section on `import` of the existing resources + Terraform import [generating config](https://developer.hashicorp.com/terraform/language/import/generating-configuration) might do the trick . I have yet to try it myself tho 😅 
https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#import
