### ISSUE TITLE
terraformer import google doesn't work

### ISSUE THREAD

**Issue by LinX9581** [GoogleCloudPlatform/terraformer#1692]
### **version.tf**
<pre>provider "google" {
credentials = file("key.json")
  project = "project_name"
  region  = "asia-east1"
  zone    = "asia-east1-b"
}</pre>

### **terraform init**
<pre>
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/google from the dependency lock file
- Using previously-installed hashicorp/google v4.62.1

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
</pre>

### **terraformer import google --resources=firewall --connect=true --projects=project_name**

![tf](https://user-images.githubusercontent.com/32073475/233308010-1b4495f6-b78f-4970-94f7-676e49dc0e91.png)

**Comment by LinX9581** [comment]
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = "4.0.0"
    }
  }
  required_version = ">= 0.13"
}

4.0.0 it works for me

**Comment by mohamedhassan7981** [comment]
I'm experiencing the same problem as well.

**Comment by akamalov** [comment]
Used this provider `4.0.0`, but it didn't work for me. Also used `5.24.0`, which also not working.  Created new ticket: https://github.com/GoogleCloudPlatform/terraformer/issues/1862
