### ISSUE TITLE
aws provider unknown flag: --resources

### ISSUE THREAD

**Issue by premsgr6** [GoogleCloudPlatform/terraformer#1694]
aws provider unknown flag: --resources
I tried with -r as well,tried all the steps provided in readme to install, even after following this getting above error.

**Comment by pastephens** [comment]
me too

**Comment by jayarjo** [comment]
Same here, for google

**Comment by jbeltrezfox** [comment]
Same here

**Comment by JakobKe** [comment]
Same for me. 
I tried it with the _ionos provider_. (is not included into current verison 0.8.22). Downloaded the repo and switched to head ionos-support and installed it manually.

Still same error: 
./terraformer-ionos import ionos --resources="*"
unknown flag: --resources

Working on a Mac M1.
