### ISSUE TITLE
Feature Request: Alibaba cloud

### ISSUE THREAD

**Issue by Ghost---Shadow** [GoogleCloudPlatform/terraformer#170]
Is someone working on it? If not, I can give it a shot.

**Comment by x-fauzan-x** [comment]
@Ghost---Shadow Thank you!

**Comment by zanglang** [comment]
@Ghost---Shadow the import doesn't seem to work:

```
terraformer import alicloud --profile="default" --regions=us-east-1 --resources=vpc 2>&1 | grep -Ev "Prod|Shared"
2019/10/17 23:04:16 alicloud importing region us-east-1
2019/10/17 23:04:16 alicloud importing... vpc
2019/10/17 23:04:18 Refreshing state... alicloud_vpc.tfer--vpc-xxx__VPC-Dev
2019/10/17 23:04:20 ERROR: Read resource response is null for resource alicloud_vpc.tfer--vpc-xxx__VPC-Dev
2019/10/17 23:04:22 ERROR: Unable to refresh resource tfer--vpc-xxx__VPC-Dev
2019/10/17 23:04:22 alicloud Connecting....
2019/10/17 23:04:22 alicloud save vpc
2019/10/17 23:04:22 alicloud save tfstate for vpc
```

Ditto for all other resources. I've verified that the default profile's access key definitely has full access to Alibaba.

I also noticed that the XXX_ENDPOINT behavior was not documented. Should it be added to README.md?

**Comment by Ghost---Shadow** [comment]
@zanglang You are getting an "Access denied" error.

`--profile` is not implemented. It picks up the first first profile in the [aliyun config array](https://github.com/GoogleCloudPlatform/terraformer#use-with-alicloud)

What is `XXX_ENDPOINT`?

**Comment by zanglang** [comment]
Thanks for the profile fix, the Aliyun CLI has an odd behavior of creating an empty profile with the name "" and putting it in the config.json. However I don't think that's it as the default profile can definitely do "DescribeVpcs". The error message is from https://github.com/GoogleCloudPlatform/terraformer/blob/c8ef79aed8dbf273b2f35f0f8dfa0454cd03964e/terraform_utils/provider_wrapper/provider.go#L169 , could it be a state issue?

Re: ENDPOINT I meant the code here: https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/alicloud/connectivity/endpoint.go

**Comment by Ghost---Shadow** [comment]
@zanglang It just means that when terraform tried to do a `terraform refresh` with this VPC id, the alicloud server did not respond with any data. This usually happens for an "Access denied" like scenarios. 

Try creating a RAM user with Admin access and provide access to your VPC to that RAM role. Then assume role in aliyun configure. See if that fixes the problem. 

The ENDPOINT is for OSS and OTS. Both of which I have not been able to successfully implement yet. VPC isnt using it.

**Comment by zanglang** [comment]
@Ghost---Shadow you're right, I just realized that it was because the generated `provider.tf` did not specify a profile nor an access key that the subsequent refresh fails. If I'm not wrong looking at https://www.terraform.io/docs/providers/alicloud/index.html it will require the two environment variables ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY to be set first. Perhaps an easy fix is to write the "profile" or ram role keys in.

```
$ cat generated/alicloud/vpc/us-east-1/provider.tf
provider "alicloud" {
  region  = "us-east-1"
  version = "~>v1.57.1"
}
```

**Comment by zanglang** [comment]
This should be the fix:

```
diff --git a/providers/alicloud/alicloud_provider.go b/providers/alicloud/alicloud_provider.go
index d2f29d13..64d090a7 100644
--- a/providers/alicloud/alicloud_provider.go
+++ b/providers/alicloud/alicloud_provider.go
@@ -57,6 +57,8 @@ func (p *AliCloudProvider) GetConfig() cty.Value {
        } else {
                val = cty.ObjectVal(map[string]cty.Value{
                        "region": cty.StringVal(region),
+            "access_key": cty.StringVal(config.AccessKey),
+            "secret_key": cty.StringVal(config.SecretKey),
                })
        }
```

**Comment by Ghost---Shadow** [comment]
@zanglang 

I was thinking more like

https://github.com/GoogleCloudPlatform/terraformer/pull/254

**Comment by zanglang** [comment]
The generated provider.tf was updated, but I believe that the refresh was called directly in https://github.com/GoogleCloudPlatform/terraformer/blob/master/cmd/import.go#L99 which hooks into your https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/alicloud/alicloud_provider.go#L34 so the new provider config was not passed.

**Comment by Ghost---Shadow** [comment]
@zanglang Sorry, I forgot.

https://github.com/GoogleCloudPlatform/terraformer/pull/257/files

**Comment by zanglang** [comment]
@Ghost---Shadow  Working fine now, thanks for the hard work!
