### ISSUE TITLE
gcp provider panic

### ISSUE THREAD

**Issue by janet23333** [GoogleCloudPlatform/terraformer#1703]
2023-05-12T16:17:24.450+0800 [ERROR] plugin.terraform-provider-google_v4.63.1_x5: Response contains error diagnostic: tf_provider_addr=registry.terraform.io/hashicorp/google tf_rpc=Configure diagnostic_summary="Value Conversion Error" @module=sdk.proto diagnostic_attribute=""
  diagnostic_detail=
  | An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
  |
  | Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
  |
  | Path:
  | Target Type: google.ProviderModel
  | Suggested `types` Type: basetypes.ObjectValue
  | Suggested Pointer Type: *google.ProviderModel
   diagnostic_severity=ERROR tf_proto_version=5.3 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 tf_req_id=68b642bf-87c7-acef-8c71-4b62127a5b40 timestamp="2023-05-12T16:17:24.450+0800"

 terraform version
Terraform v1.4.6
on darwin_amd64

 terraformer version
Terraformer v0.8.22

provider version
plugins/darwin_amd64/terraform-provider-google_v4.63.1_x5

**Comment by arod0719** [comment]
Did you solve this? Running into the same issue

**Comment by huangyuezhen** [comment]
您好，您的邮件已收到，我会尽快阅读，祝您生活愉快~

**Comment by 880831ian** [comment]
I also have the same problem

**Comment by rober15** [comment]
Me too. :-(

**Comment by rrequero** [comment]
Me too

**Comment by fairglen** [comment]
+1

**Comment by huangyuezhen** [comment]
您好，您的邮件已收到，我会尽快阅读，祝您生活愉快~

**Comment by fhmlsml** [comment]
me too, I also have the same problem

**Comment by nburns** [comment]
Hitting the same issue

**Comment by gmuench-cog** [comment]
I found that 4.59.0 is the highest "hashicorp/google" provider version that works with Terraformer as of 7/11/23.

Terraformer v0.8.24 (darwin_arm64)
Terraform v1.5.2 (darwin_arm64)
terraform-provider-google_v4.59.0_x5 (darwin_arm64)

I also tried with a full amd_64 stack and got the same results.

**Comment by huangyuezhen** [comment]
您好，您的邮件已收到，我会尽快阅读，祝您生活愉快~

**Comment by brianmaresca** [comment]
thank you @gmuench-cog 🥇 💯 👍 !

FWIW, the same error is referenced in these issues:
https://github.com/GoogleCloudPlatform/terraformer/issues/1728
https://github.com/GoogleCloudPlatform/terraformer/issues/1692
https://github.com/GoogleCloudPlatform/terraformer/issues/1695

**Comment by nl-devonainsworth** [comment]
> I found that 4.59.0 is the highest "hashicorp/google" provider version that works with Terraformer as of 7/11/23.
> 
> Terraformer v0.8.24 (darwin_arm64) Terraform v1.5.2 (darwin_arm64) terraform-provider-google_v4.59.0_x5 (darwin_arm64)
> 
> I also tried with a full amd_64 stack and got the same results.

This worked for me  as well.

**Comment by huangyuezhen** [comment]
您好，您的邮件已收到，我会尽快阅读，祝您生活愉快~

**Comment by jralmaraz** [comment]
> I found that 4.59.0 is the highest "hashicorp/google" provider version that works with Terraformer as of 7/11/23.
> 
> Terraformer v0.8.24 (darwin_arm64) Terraform v1.5.2 (darwin_arm64) terraform-provider-google_v4.59.0_x5 (darwin_arm64)
> 
> I also tried with a full amd_64 stack and got the same results.

Thanks ! That made the issue go away! 

I still get 0 number of resources imported, but I think I need to troubleshoot more on why...

Cheers!

**Comment by huangyuezhen** [comment]
您好，您的邮件已收到，我会尽快阅读，祝您生活愉快~

**Comment by boberbeck** [comment]
I still have the problem, even upgrading to a minor version like 4.59.0 from the GCP provider does not help

**Comment by nburns** [comment]
still applies

**Comment by teadur** [comment]
indeed :(

**Comment by bt-nia** [comment]
anyone else running into this, here's a version.tf you can terraform init against:
```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.59.0"
    }
  }
  required_version = "= 1.5.2"
}
```
You can use `tfswitch 1.5.2` to switch the version
