### ISSUE TITLE
Error: Conflicting configuration arguments - AWS EC2 Instance

### ISSUE THREAD

**Issue by jeongchanhui** [GoogleCloudPlatform/terraformer#1712]
Hello,
I've encountered an issue running `terraform plan` after import AWS EC2 instance. 

The error is as follows: 

│ Error: Conflicting configuration arguments
│ 
│   with aws_instance.tfer--i-0cc4f ....(omitted)
│ 
│ "cpu_options.0.core_count": conflicts with cpu_core_count

│ Error: Conflicting configuration arguments
│ 
│ with aws_instance.tfer--i-0cc4f ....(omitted)
│ "cpu_options.0.threads_per_core": conflicts with cpu_threads_per_core

│ Error: Conflicting configuration arguments
│  with aws_instance.tfer--i-0cc4f ....(omitted)
│ 
│ "cpu_threads_per_core": conflicts with cpu_options.0.threads_per_core

It appears that this issue might be stemming from deprecated argument values. I have checked similar issues on Terraformer's GitHub page like [[1](https://github.com/GoogleCloudPlatform/terraformer/issues/1236)] and the main Terraform's GitHub page [[2](https://github.com/hashicorp/terraform/issues)], but could not find a direct solution to this problem.

**Is it possible to configure deprecated arguments not to be imported ?**

**Comment by MateusBMP** [comment]
If you remove `cpu_core_count` and `cpu_threads_per_core` keeping `cpu_options.core_count` and `cpu_options.threads_per_core` it's work fine. So, all we have to do is remove these keys.

See this [CPU options example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#cpu-options-example) from AWS provider on Terraform Registry.

**Comment by jeongchanhui** [comment]
Hi, thanks for the reply.
I have successfully uninstalled it using the method you mentioned. 
But it would be nice if it could be fixed so that we don't have to clear the arguments again and it doesn't load them in the first place : )
