### ISSUE TITLE
No files when generating with --resoruces="*" even tho says imported

### ISSUE THREAD

**Issue by tdiazvelez** [GoogleCloudPlatform/terraformer#1719]
Hi guys, i need to terraform a whole existing infra on google. I have encountered many issues and I was able to fix them reading old issues, but with this I have no clue.

While I import, for example, using:

`terraformer import google --resources=gcs,forwardingRules,httpHealthChecks --connect=true --regions=europe-west4 --projects=MY-PROJECT`

I get the files correct, 10 for gcs, 1 forwarding rule and 0 healthcheck. And there's a generated/ folder

But when im trying to import everything:

`terraformer import google --resources="*" --connect=true --regions=europe-west4 --projects=MY-PROJECT`

it seems like everything is working fine (some exceptions of services i dont use, etc) saying "importing done", even listing the ammount of resources for each service found. BUT I have no generated/ folder, why??

**Comment by tdiazvelez** [comment]
This is a piece of what i get when i run it with `--resources="*"`


`2023/06/09 11:48:23 google done importing schedulerJobs
2023/06/09 11:48:24 google importing... securityPolicies
2023/06/09 11:48:25 google done importing securityPolicies
2023/06/09 11:48:25 google importing... sslCertificates
2023/06/09 11:48:26 google done importing sslCertificates
2023/06/09 11:48:27 google importing... sslPolicies
2023/06/09 11:48:27 google done importing sslPolicies
2023/06/09 11:48:28 google importing... subnetworks
2023/06/09 11:48:29 google done importing subnetworks
2023/06/09 11:48:29 google importing... targetHttpProxies
2023/06/09 11:48:30 google done importing targetHttpProxies
2023/06/09 11:48:31 google importing... targetHttpsProxies
2023/06/09 11:48:31 google done importing targetHttpsProxies
2023/06/09 11:48:32 google importing... targetInstances
2023/06/09 11:48:34 google done importing targetInstances
2023/06/09 11:48:34 google importing... targetPools
2023/06/09 11:48:35 google done importing targetPools
2023/06/09 11:48:35 google importing... targetSslProxies
2023/06/09 11:48:36 google done importing targetSslProxies
2023/06/09 11:48:37 google importing... targetTcpProxies
2023/06/09 11:48:38 google done importing targetTcpProxies
2023/06/09 11:48:39 google importing... targetVpnGateways
2023/06/09 11:48:40 google done importing targetVpnGateways
2023/06/09 11:48:40 google importing... urlMaps
2023/06/09 11:48:41 google done importing urlMaps
2023/06/09 11:48:42 google importing... vpnTunnels
2023/06/09 11:48:42 google done importing vpnTunnels
2023/06/09 11:48:42 Number of resources for service autoscalers: 0
2023/06/09 11:48:42 Number of resources for service images: 0
2023/06/09 11:48:42 Number of resources for service globalAddresses: 5
2023/06/09 11:48:42 Number of resources for service httpHealthChecks: 0
2023/06/09 11:48:42 Number of resources for service sslPolicies: 0
2023/06/09 11:48:42 Number of resources for service instanceGroupManagers: 0
2023/06/09 11:48:42 Number of resources for service resourcePolicies: 0
2023/06/09 11:48:42 Number of resources for service targetInstances: 0
2023/06/09 11:48:42 Number of resources for service vpnTunnels: 0
2023/06/09 11:48:42 Number of resources for service regionDisks: 0
2023/06/09 11:48:42 Number of resources for service schedulerJobs: 0
2023/06/09 11:48:42 Number of resources for service backendBuckets: 0
2023/06/09 11:48:42 Number of resources for service externalVpnGateways: 0
2023/06/09 11:48:42 Number of resources for service routers: 1
2023/06/09 11:48:42 Number of resources for service targetVpnGateways: 0
2023/06/09 11:48:42 Number of resources for service httpsHealthChecks: 0
2023/06/09 11:48:42 Number of resources for service instanceTemplates: 5
2023/06/09 11:48:42 Number of resources for service regionInstanceGroupManagers: 5
2023/06/09 11:48:42 Number of resources for service regionTargetHttpProxies: 0
2023/06/09 11:48:42 Number of resources for service instanceGroups: 0
2023/06/09 11:48:42 Number of resources for service interconnectAttachments: 0
2023/06/09 11:48:42 Number of resources for service subnetworks: 4
2023/06/09 11:48:42 Number of resources for service cloudFunctions: 0
2023/06/09 11:48:42 Number of resources for service dataProc: 0
2023/06/09 11:48:42 Number of resources for service regionAutoscalers: 5
2023/06/09 11:48:42 Number of resources for service regionUrlMaps: 0
2023/06/09 11:48:42 Number of resources for service healthChecks: 9
2023/06/09 11:48:42 Number of resources for service memoryStore: 1
2023/06/09 11:48:42 Number of resources for service regionSslCertificates: 0
2023/06/09 11:48:42 Number of resources for service routes: 45
2023/06/09 11:48:42 Number of resources for service backendServices: 3
2023/06/09 11:48:42 Number of resources for service bigQuery: 0`

**Comment by DanielRieske** [comment]
What are the versions of your Terraformer and the terraform-google-provider that you're using?

**Comment by tdiazvelez** [comment]
>  

Terraform: v1.4.6
Terraformer: v0.8.22
gcp provider: v4.0.0 because using a newer one (i think latest its 4.6.something) explodes everywhere and i found [HERE](https://github.com/GoogleCloudPlatform/terraformer/issues/1695) a solution using 4.0.0

**Comment by DanielRieske** [comment]
@tdiazvelez Had to dig a little bit but this is because `google_compute_region_instance_group` is not a resource but a data source.
As far as I know Terraformer only creates `terraform_remote_state` data sources based on the resources it has but doesn't create any other.

You can solve this by excluding it by

`terraformer import google --resources="*" --excludes="regionInstanceGroups" --regions=europe-west4 --projects=MY-PROJECT `

@sergeylanzman want me to create a PR to remove the `google_compute_region_instance_group` resource?

Also, about the issues with GCP provider, the issue started in `4.60.0` due to the plugin framework added back in, so using version `4.59.0` will work.

**Comment by tdiazvelez** [comment]
thank you @DanielRieske , now its working :)

Hope you have a great weekend!
