### ISSUE TITLE
Request for Information: Next Build Release Date for Terraformer

### ISSUE THREAD

**Issue by Bilal-Muhammad** [GoogleCloudPlatform/terraformer#1723]
Hello,

I would like to inquire about the release date for the new version of Terraformer that includes compatibility with the latest version of Terraform. Additionally, I am interested in knowing if this new release addresses any known bugs or issues present in the previous version.

Could you kindly provide information on the expected release date for this update? This will help me plan my usage of Terraformer accordingly.

Thank you!

**Comment by shblue21** [comment]
Hi, the latest version was released on July 4th. Can you check if the bug is fixed?
