### ISSUE TITLE
Does terraformer support providers built on the plugin framework

### ISSUE THREAD

**Issue by samir-gandhi** [GoogleCloudPlatform/terraformer#1733]
I'm looking at adding a new provider, one which uses the plugin framework and I'm seeing:

```
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]
```

I assume this error is due to the provider relying on the new plugin framework. 
Could someone correct me if I've misdiagnosed. 
Or, if this is actually the issue, is there any intention to support providers that rely on the plugin framework?

**Comment by sinkr** [comment]
I'd like to know the same.

**Comment by pataquets** [comment]
Possible duplicate of #1761.

**Comment by cristiGuranIonos** [comment]
Getting the same error, is it no supported?
