### ISSUE TITLE
AWS import sg returns panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by forhire** [GoogleCloudPlatform/terraformer#1734]
terraformer -v
version v0.8.22

$`terraformer import aws --resources=sg --profile=myprofile
2023/06/26 21:32:29 aws importing default region
2023/06/26 21:32:30 aws importing... sg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ae1cdf]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.fromPort(...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:362
github.com/GoogleCloudPlatform/terraformer/providers/aws.baseRuleAttributes({_, _}, {0x0, 0xc001f376e0, {0xc004b74ed0, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:164 +0x33f
github.com/GoogleCloudPlatform/terraformer/providers/aws.processRule({0x0, 0xc001f376e0, {0xc004b74ed0, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0x116e9878, 0x0, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:145 +0x718
github.com/GoogleCloudPlatform/terraformer/providers/aws.SecurityGenerator.createResources({{{{0xc00044fa20, 0x2}, {0x0, 0x0, 0x0}, {0xa3eb0b0, 0x3}, 0xc003f946f0, {0x116e9878, 0x0, ...}, ...}}}, ...)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:84 +0x7cd
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityGenerator).InitResources(0xc003fa0a20)
	/home/runner/work/terraformer/terraformer/providers/aws/sg.go:260 +0x3b0
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc00257ac30?)
	/home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:61 +0x26
github.com/GoogleCloudPlatform/terraformer/cmd.initServiceResources({_, _}, {_, _}, {{0xc001181b60, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:209 +0x21e
github.com/GoogleCloudPlatform/terraformer/cmd.initAllServicesResources(_, {{0xc001181b60, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, {0xa3f9f79, ...}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:166 +0x1a7
github.com/GoogleCloudPlatform/terraformer/cmd.Import({_, _}, {{0xc001181b60, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/import.go:98 +0x2a5
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources({{0xc001181b30, 0x1, 0x1}, {0x116e9878, 0x0, 0x0}, {0xa497bb9, 0x1e}, {0xa3f9f79, 0x9}, ...}, ...)
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:121 +0x292
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00102e000?, {0xa3ec1d8?, 0x2?, 0x2?})
	/home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:66 +0x13e
github.com/spf13/cobra.(*Command).execute(0xc00102e000, {0xc0003725c0, 0x2, 0x2})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000cc8dc0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute()
	/home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x1e
main.main()
	/home/runner/work/terraformer/terraformer/main.go:39 +0x50
`

**Comment by forhire** [comment]
Running on Ubuntu 22.04.02

**Comment by djgoku** [comment]
I also just ran into this using `terraformer v0.8.22` on macOS Ventura x86. Other resources are working though.

**Comment by kazuuuutaka** [comment]
same...


I also ran into this using v0.8.22 on m2 mac.

**Comment by shblue21** [comment]
Could you please try the recently released 0.8.24 version, it most likely fixed the issue.
#1492

**Comment by djgoku** [comment]
Using version `0.8.24` I was able to get AWS Resource Security Group `sg` to export!
