### ISSUE TITLE
need terraform version 1.5 support

### ISSUE THREAD

**Issue by Ad-squareops** [GoogleCloudPlatform/terraformer#1748]
while importing aws resources from terraformer it is creating the tftate and terraform resource file with  "terraform_version": "0.12.31",.
but right now latest version of terraform is 1.5.
So how i can import aws resources with terraform version 1.5 directlt.
 I don't want to use migration state version command which is provided by you.
 terraform state replace-provider -auto-approve "registry.terraform.io/-/aws" "hashicorp/aws"

**Comment by ruudvandenboomen** [comment]
I'm having the same problem. Did you find a solution already?

**Comment by jackakeller** [comment]
I have the same requirement, but for the Datadog provider. This is a very old terraform version.

This issue has been filed before but was marked stale. Hopefully someone finds time and motivation to contribute a change if there isn't a good reason not to update it.
