### ISSUE TITLE
Unable to apply filters on rds resources

### ISSUE THREAD

**Issue by vinnu1862** [GoogleCloudPlatform/terraformer#1757]
When we tried importing specific resources in rds, we are getting entire RDS reources.

Tried various options, but getting same output with entire RDS resources.

 import aws --resources=rds --filter="Name=aws_db_instance;Value=aardvark-rds" --regions=us-east-1
import aws --resources=rds --filter="DBInstanceIdentifier=='aardvark-rds'" --regions=us-east-1
import aws --resources=rds --filter="aws_db_instance=aardvark-rds"  --regions=us-east-1
import aws --resources=rds --filter='aws_db_instance=aardvark-rds'  --regions=us-east-1
import aws --resources=rds --filter="Name=aws_db_instance;Value=aardvark-rds" --regions=us-east-1
import aws --resources=rds --filter="Name=aws_db_instance;Value='aardvark-rds'" --regions=us-east-1
import aws --resources=rds --filter="Name=identifier;Value=aardvark-rds" --regions=us-east-1
import aws --resources=rds,aws_db_instance --filter="Name=tags.Name;Value=aardvark-rds" --regions=us-east-1

below is the output for all the attempts:

aws importing region us-east-1
aws importing... rds
aws done importing rds
Number of resources for service rds: 252

Any help on how to filter RDS resources will be helpful.

**Comment by TrevorChan1** [comment]
I am also running into the same roadblock. Based on how I've found others using AWS resources (like [this](https://stackoverflow.com/questions/67006665/how-to-use-filters-in-terraformer-for-importing-aws-lambda-function) stackoverflow post), it feels like `--filter="Name=identifier;Value=my_db_identifier"` should work. Any documentation / examples on filtering RDS instances for Terraformer would be a big help!

**Comment by vinnu1862** [comment]
Thanks for the help. It worked for me too now..!!

**Comment by vinnu1862** [comment]
Thanks for the help. It worked for me too now..!!
