### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]

### ISSUE THREAD

**Issue by frankpengau** [GoogleCloudPlatform/terraformer#1761]
When trying to use the following command:
```
terraformer import cloudflare --resources=*
```
or
```
terraformer import cloudflare --resources=dns,page_rule
```

I would get the following error:
```
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]
```

Details:
Using terraformer v0.8.24 with Terraform v1.5.4 and cloudflare provider v4.11.0

**Comment by noudAndi** [comment]
I get the same error for

Using terraformer v0.8.24 with Terraform v1.5.5 and cloudflare provider v4.12.0

**Comment by thefourcraft** [comment]
I'm facing the same issue when importing Cloudflare resources using Terraformer. 

#### Environment:

- Terraform Version: `v1.5.6`
- Cloudflare Provider Version: `v4.13.0`
- Terraformer Version: `v0.8.24`
- Operating System: `macOS (darwin_arm64)`

#### Steps to Reproduce:

1. Set up Cloudflare environment variables (`CLOUDFLARE_API_KEY`, `CLOUDFLARE_EMAIL`, `CLOUDFLARE_ACCOUNT_ID`)
2. Initialize Terraform using `terraform init`
3. Run `terraformer import cloudflare --resources=firewall,dns`

#### Expected Result:

Terraformer should successfully import the Cloudflare resources.

#### Actual Result:

I receive the following error message:

```
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]
```

#### Additional Information:

- I've tried clearing the Terraform plugin cache.
- I've explicitly defined the required Terraform and Cloudflare provider versions in my `main.tf`.

**Comment by Nullreff** [comment]
Fixed this by temporarily downgrading to version `3.12.2` of the terraform package. Later releases use API version 6 which isn't compatible with version 5.

**Comment by rodolfobandeira** [comment]
My guess is that people are using the https://github.com/cloudflare/cf-terraforming project nowadays, which left this part of the project a bit behind on maintenance.

**Comment by pataquets** [comment]
Same here, confirming:
``` console
$ terraform version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.14.0
$ terraformer-all version
Terraformer v0.8.24
$ terraformer-all import cloudflare --resources=dns
2023/09/11 23:47:20 Incompatible API version with plugin. Plugin version: 6, Client versions: [5]
```
I'm working around it by using [cloudflare/cf-terraforming](https://github.com/cloudflare/cf-terraforming).

**Comment by o6uoq** [comment]
Pinning Cloudflare to `3.32.0` and no more recent worked for.

This is due to [this commit](https://github.com/cloudflare/terraform-provider-cloudflare/commit/3a29e1cbd69b5dc49b986bcffb8846d831901a88#), explictly [this line](https://github.com/cloudflare/terraform-provider-cloudflare/commit/3a29e1cbd69b5dc49b986bcffb8846d831901a88#diff-004c813871d941da9fbaa8c8461a82be696a885962bcf366161c18f9b0cf1545R4).

**Comment by pataquets** [comment]
Issue still stands.
@sergeylanzman: care to remove the "Stale" label? This forces people to add no-value/noise comments just to keep just this issue open.

**Comment by frankpengau** [comment]
I believe the issue still exists, can this issue not be closed?

**Comment by pataquets** [comment]
Since provider it's broken and looks like people are already using other tools, I've filed #1883.
BTW, if you need IaC for CF DNS-only resources as it's my case, I'm adding the tool I'm using now [DNSControl](https://dnscontrol.org)  to the alternatives shared by others.
