### ISSUE TITLE
OpenTofu (née OpenTF) support

### ISSUE THREAD

**Issue by skyzyx** [GoogleCloudPlatform/terraformer#1773]
https://opentf.org/announcement

We want to understand how Terraformer is affected by the OpenTF announcement, and what the plans for support are moving forward.

From a technical perspective, I expect that it will be a no-op for the time being as OpenTF anticipates maintaining compat/interop for the foreseeable future. (However, OpenTF has stated that _some_ functionality may be added to OpenTF that is a _superset_ of what's in base Terraform. [[source](https://github.com/opentffoundation/roadmap/issues/24)])

From a process perspective:

1. If there is a bug in OpenTF that does not exist in Terraform (or vice-versa), will bug reports (as they pertain to this project) be treated equally on both platforms?

1. Will testing be performed with code targeting both platforms?

1. For OpenTF's potential future "superset" functionality, will that be treated as a first-class citizen?

**Comment by chazzmoney** [comment]
For those who were looking for "OpenTofu", they are the same thing:

https://opentofu.org/blog/opentofu-announces-fork-of-terraform/

**Comment by chenrui333** [comment]
opentofu just GA today, https://github.com/opentofu/opentofu/releases/tag/v1.6.0

**Comment by lucasfcnunes** [comment]
This project should move towards OpenTofu

**Comment by lucasfcnunes** [comment]
@sergeylanzman @meshuga @skarimo

**Comment by skyzyx** [comment]
It would seem that this project leverages the Terraform Protocol, rather than relying directly on Terraform or OpenTofu directly. As long as the protocol continues to be supported, then the providers which implement the protocol will be supported.
