### ISSUE TITLE
terraformer-aws import exec: no command

### ISSUE THREAD

**Issue by ashaf3** [GoogleCloudPlatform/terraformer#1789]
I am trying to import aws resources, when I run 
terraformer-aws import aws --resources="ecs" --profile=jenny

I get error 
2023/10/02 11:03:10 aws importing default region
2023/10/02 11:03:10 exec: no command

I have checked the binary path as well, it seems okay. 
I tried with versions.tf

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

then terraform init but hitting the same error.

**Comment by BenMeierRecurrency** [comment]
Could you provide the solution?

**Comment by dimaqq** [comment]
@ashaf3 I'd appreciate some pointers how you resolved this

**Comment by ashaf3** [comment]
Hi @dimaqq , @BenMeierRecurrency 
- the solution for this is to make sure the system path on windows is pointing to the folder, where the exe resides for terraformer. 
- make providers.tf
- initialize terraform
- then run terraformer commands

**Comment by davidsonsns** [comment]
my solution

1. create `version.tf` file
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}
```

2. run `terraform init`
3. run terraformer: ie `terraformer import aws --resources=* --regions=us-east-1`

**Comment by aasisdhakal** [comment]
Thanks! @davidsonsns
