### ISSUE TITLE
Slack channel or some other kind of IRL chat

### ISSUE THREAD

**Issue by Ghost---Shadow** [GoogleCloudPlatform/terraformer#180]
For interactive (but asynchronous) collaboration, we should make a slack channel or some other kind of chat forum.

**Comment by cryptomeme** [comment]
How about something like https://gitter.im/ ?

**Comment by Ghost---Shadow** [comment]
@sergeylanzman Discord channel maybe?

**Comment by meshuga** [comment]
I'm available in https://discord.gg/3Ep5fKy (mm99)
