### ISSUE TITLE
`import aws` emits: "open ~/.terraform.d/plugins/darwin_arm64: no such file or directory"

### ISSUE THREAD

**Issue by nhooey** [GoogleCloudPlatform/terraformer#1812]
When running the Terraformer `import aws` command, I get a cryptic error message about a plugin directory not existing:

## Invocation and error message:
```
$ terraformer import aws --resources '*' --connect true --regions '*'
2023/12/04 13:18:19 aws importing region *
2023/12/04 13:18:19 Attempting an import of ALL resources in aws
2023/12/04 13:18:19 open ~/.terraform.d/plugins/darwin_arm64: no such file or directory
```

**Why is this happening, and could this error message be improved?**

## Failed attempted fixes:
1. After creating `providers.tf` and successfully running `terraform init` in the same directory that Terraformer was run in, which creates this lone file `.terraform/providers/registry.terraform.io/hashicorp/aws/5.29.0/darwin_amd64/terraform-provider-aws_v5.29.0_x5` of type `Mach-O 64-bit executable x86_64`.
2. Installing Terraform `1.5.7` with Homebrew (instead of with `tfenv`) has no effect, the same error messages is emitted.

## Version information:
```
$ terraformer --version
version v0.8.24

$ terraform --version
Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.29.0

$ which terraform
/opt/homebrew/bin/terraform

$ tfenv --version
tfenv 3.0.0

$ which tfenv
/opt/homebrew/bin/tfenv

$ # Terraform installed with `TFENV_ARCH=arm64 tfenv install 1.6.5`
```

**Comment by Tim-herbie** [comment]
Here is the solution:
https://github.com/GoogleCloudPlatform/terraformer/issues/590#issuecomment-704781089

**Comment by calebAtIspot** [comment]
I was able to fix this just by running `terraform init` before running terraformer in a directory with the following TF file:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
}
```
