### ISSUE TITLE
could not connect to Keycloak

### ISSUE THREAD

**Issue by Tim-herbie** [GoogleCloudPlatform/terraformer#1813]
Hello,

I installed terraformer today and it´s not possible for me to get the terraform resources from Keycloak.

I exported the following Parameters:
- KEYCLOAK_URL
- KEYCLOAK_CLIENT_ID
- KEYCLOAK_USER
- KEYCLOAK_PASSWORD
I am sure that these are correct and Keycloak is working for me. I can access it via the GUI and Applications redirect to Keycloak for the authentication already.

I created also the terraform provider for keycleak code and run `terraform init`
```
terraformer import keycloak --resources=realms

2023/12/05 15:41:17 keycloak importing all realms
2023/12/05 15:41:17 keycloak importing... realms
2023/12/05 15:41:17 keycloak error initializing resources in service realms, err: keycloak: could not connect to Keycloak
2023/12/05 15:41:17 keycloak Connecting....
```

System: Mac with M1
Terraformer version: version v0.8.24
Terraform version: v1.5.7
Keycloak version: 22.0.5

**Comment by Tim-herbie** [comment]
still not working...

**Comment by mosmianiv** [comment]
Yeah wanted to follow up on this, am getting the same issue.
```
2024/03/29 10:34:22 keycloak importing all realms
2024/03/29 10:34:23 keycloak importing... realms
2024/03/29 10:34:23 keycloak error initializing resources in service realms, err: keycloak: could not connect to Keycloak
2024/03/29 10:34:23 keycloak Connecting....
```

I've tried multiple provider versions including the `4.0.1` that is listed in the docs as supported. No logs on the keycloak side. It's able to get the bearer token though as expected but cant connect.  I see the log line in the verbose output
> [DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"

**Comment by Tim-herbie** [comment]
still not fixed...
