### ISSUE TITLE
Fail to import Datadog Dashboard

### ISSUE THREAD

**Issue by KeisukeYamashita** [GoogleCloudPlatform/terraformer#183]
## What

I have a timeboard on Datadog which I created with UI.

Since the dashboard has Grouped Widget, I want to download by Dashboard API.

```
$ DATADOG_API_KEY="xxx" DATADOG_APP_KEY="xxx" terraformer import datadog --resources=dashboard --filter=datadog_dashboard=xxxxxx

2019/09/17 16:27:49 datadog importing... dashboard
2019/09/17 16:27:52 datadog Connecting.... 
2019/09/17 16:27:52 datadog save dashboard
2019/09/17 16:27:52 [DEBUG] New state was assigned lineage "xxx"
2019/09/17 16:27:52 datadog save tfstate for dashboard
```

The output looks good. But it has no outputs. Just these files are created.

```
generated/
└── datadog
    └── dashboard
        ├── provider.tf
        └── terraform.tfstate
```

Although, I can create a timeboard.

```
$ DATADOG_API_KEY="xxx" DATADOG_APP_KEY="xxx" terraformer import datadog --resources=timeboard --filter=datadog_timeboard=xxxxxx
```

My motivation to use Datadog Dashboard API is to use Grouped Widget to group graphes.

Thank you.

**Comment by sergeylanzman** [comment]
I see you use filter options
filter option get terraform ID for resource. 
In datadog dashboard case it's ID
https://github.com/terraform-providers/terraform-provider-datadog/blob/master/datadog/resource_datadog_dashboard.go#L81

Try use without filter

**Comment by KeisukeYamashita** [comment]
@sergeylanzman 

Thank you very much. I can import Datadog Dashboard now.

**Comment by tunguyen9889** [comment]
@KeisukeYamashita can you please share the command you used to import DataDog Dashboard?

**Comment by tunguyen9889** [comment]
For those who still have trouble to export the dashboard, this command works for me:

```
terraformer import datadog --resources=dashboard --filter=datadog_dashboard="abc-def-123"
```
