### ISSUE TITLE
AWS VPC_Endpoints not imported

### ISSUE THREAD

**Issue by mvadu** [GoogleCloudPlatform/terraformer#1836]
Hello,
I am trying to import from aws and its working for the most part. However I don't see the VPC endpoints pulled into plan or import outputs. I have tried `--resources="*"` , `--resources="aws_vpc_endpoint"` as well as `--resources="vpc_endpoint"` without luck.

```
.\terraformer-aws-windows-amd64.exe --version
version v0.8.24

.\terraformer-aws-windows-amd64.exe import  aws --compact --filter="Name=tags.team;Value=SRE" --regions=us-east-1 --profile "" --resources="aws_vpc_endpoint"
2024/01/08 13:55:38 aws importing region us-east-1
2024/01/08 13:55:42 aws importing... aws_vpc_endpoint
2024/01/08 13:55:42 aws error importing aws_vpc_endpoint, err: aws: aws_vpc_endpoint not supported service

.\terraformer-aws-windows-amd64.exe import  aws --compact --filter="Name=tags.team;Value=SRE" --regions=us-east-1 --profile "" --resources="vpc_endpoint"
2024/01/08 13:55:23 aws importing region us-east-1
2024/01/08 13:55:27 aws importing... vpc_endpoint
2024/01/08 13:55:27 aws error importing vpc_endpoint, err: aws: vpc_endpoint not supported service
```

**Comment by mvadu** [comment]
`.\terraformer-aws-windows-amd64.exe import  aws --compact --filter="Name=tags.fp-team;Value=SREOps" --regions=us-east-1 --profile "" --resources="vpc_endpoint" --verbose > debug.log` output attached (edited to remove the account and email ID).
[debug.log](https://github.com/GoogleCloudPlatform/terraformer/files/13865380/debug.log)

**Comment by italovpg** [comment]
I'm having the same problem

```sh
italo:terraformer$ terraformer import aws -r vpc_endpoint
2024/02/06 10:55:21 aws importing default region
2024/02/06 10:55:25 aws importing... vpc_endpoint
2024/02/06 10:55:25 aws error importing vpc_endpoint, err: aws: vpc_endpoint not supported service
2024/02/06 10:55:25 aws Connecting....
```

**Comment by miguelzenteno** [comment]
VPC endpoints were added after the last release, so would need to re-build the binaries to make it work, or wait for a new version to be released that actually includes the vpc_endpoints

**Comment by packeteer** [comment]
any update?

**Comment by kwilsonmg** [comment]
@sergeylanzman can we please re-open this?

**Comment by djer34** [comment]
Also having the same issue
