### ISSUE TITLE
plugin error 1: open /Users/jvlle/.terraform.d/plugins/darwin_amd64: no such file or directory open /Users/jvlle/.terraform.d/plugins/darwin_amd64: no such file or directory

### ISSUE THREAD

**Issue by jvielle** [GoogleCloudPlatform/terraformer#184]
Hello,

When I try to get terraform from an aws instance with terraformer, i get those errors.

```
2019/09/17 18:45:11 plugin error 1: open /Users/jvlle/.terraform.d/plugins/darwin_amd64: no such file or directory
2019/09/17 18:45:11 open /Users/jvlle/.terraform.d/plugins/darwin_amd64: no such file or directory
```

By launching this command:

```
terraformer import aws --resources=ec2_instance --filter=aws_instance=i-0fdbcf2b432305122cc --regions=eu-west-1 --profile=dev
```
My terraform version is:
```
Terraform v0.11.11
```
My dev profile is working well with the aws cli and I can create infra from terraform with it.

If someone can advise me, any help will appreciated.

Thanks by advance.

Julien

**Comment by kanata2** [comment]
Did you try to exec `$terraform init` after creating some files e.g. init.tf which contains `provider "aws" {}`?
See also Install section in README.

**Comment by jvielle** [comment]
thanks it is ok
