### ISSUE TITLE
Support for Datadog Powerpack Implementation in Terraformer

### ISSUE THREAD

**Issue by QuantumRoamer** [GoogleCloudPlatform/terraformer#1841]
Datadog has recently introduced a Powerpack implementation using Terraform, but Terraformer currently lacks support for this feature. This issue is raised to track the request for adding support for Datadog Powerpack in Terraformer.

```
2024/01/31 10:49:13 datadog importing... powerpack
2024/01/31 10:49:13 datadog error importing powerpack, err: datadog: powerpack not supported service
```

**Documentation Reference:**

For more information on Datadog Powerpack using Terraform, refer to the official documentation: [Datadog Powerpack Terraform Documentation](https://registry.terraform.io/providers/datadog/datadog/latest/docs/resources/powerpack)

**Comment by QuantumRoamer** [comment]
Do we have any update on this?

**Comment by cameres** [comment]
Opened a PR above for this. Hoping that we can get a review on it.
