### ISSUE TITLE
Terraform version > 0.13 not supported

### ISSUE THREAD

**Issue by Abhilash-as** [GoogleCloudPlatform/terraformer#1854]
I am using terraformer v0.8.13 and terraform version v1.7.4 .
I am able to import resources from aws but when I checked the tfstate its mentioned like the terraformVersion :"0.12.29". WHat is the reason for that?
How terraformer confirms which terraform version is to be used for configuration?
Is there any solution for this issue?

**Comment by diepes** [comment]
Does this mean the project is dead?
