### ISSUE TITLE
open \.terraform.d/plugins/windows_amd64: The system cannot find the path specified.

### ISSUE THREAD

**Issue by chetan-alti** [GoogleCloudPlatform/terraformer#1866]
Hai Everyone,  when running terraformer I'm facing open \.terraform.d/plugins/windows_amd64: The system cannot find the path specified.

I have downloaded the [.exe ] (https://github.com/GoogleCloudPlatform/terraformer/releases/download/0.8.24/terraformer-all-windows-amd64) file from release page.
then I have renamed the exe to terraformer and  moved the exe to D://terraformer 
-  I was able to run the terraformer --version (got the result as version v0.8.24)

I have a use-case I'm trying, the following is the prerequiesites
folder structure (added image at the end)
Iac_folder
 |_ localmain.tf
 |_ provider.tf

provider.tf
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.26.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
  access_key = "acces_key"
  secret_key = "sec_key"
}
```
 localmain.tf
```
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
```

I ran terraform init , it generated `.terrform` folder 

but when I run `terraformer import aws --resources=s3 --regions=us-east-1`
getting following error message
2024/04/19 15:57:45 aws importing region us-east-1
2024/04/19 15:57:45 open \.terraform.d/plugins/windows_amd64: The system cannot find the path specified.

![image](https://github.com/GoogleCloudPlatform/terraformer/assets/118523934/6ca8952b-d831-4577-bd3b-cb921009b31e)

Your help much appreciated , Thanks in advance

**Comment by dhilgarth** [comment]
windows_386 looks like you may be on a 32 bit machine instead of 64 bit?

**Comment by chetan-alti** [comment]
Hai @dhilgarth , Thank for your response. I'm using the 64 bit machine.

But I was able to resolve the issue.
# What I did

Update the terraform version to ` v1.8.0` , earlier I was using the older version of terraform.
After this it ran smoothly
![image](https://github.com/GoogleCloudPlatform/terraformer/assets/118523934/784215b1-27aa-406d-92ab-e27608a1ecef)

I could not exactly deduce the root cause, but updating the terraform version resolved :)
