### ISSUE TITLE
GitHub: Add support for GitHub Enterprise

### ISSUE THREAD

**Issue by jantman** [GoogleCloudPlatform/terraformer#187]
It appears that the Github provider doesn't support GitHub Enterprise (self-hosted GitHub). Terraform supports this by passing the ``base_url`` parameter to [the github provider](https://www.terraform.io/docs/providers/github/index.html), and I believe that terraformer could support it by adding a base_url flag to the ``import github`` command, that defaults to ``https://api.github.com``

**Comment by Olin-Vorechovsky** [comment]
Any hints here? Would like to use terraformer against Git Enterprise.

`export GITHUB_BASE_URL=` is not working

**Comment by Olin-Vorechovsky** [comment]
You need to change this
https://github.com/GoogleCloudPlatform/terraformer/blob/7c0dc227dd424030c5d179de5ed547a74afcdecf/providers/github/repositories.go#L37

for this:
```
baseUrl := "https://_YOUR_GITHUB_ENTERPRISE_BAS_URL/api/v3/"
client, _ := githubAPI.NewEnterpriseClient(baseUrl, baseUrl, tc)
```

The same for other resources like teams.go, members.go, ...

**Comment by sergeylanzman** [comment]
@Olin-Vorechovsky Thanks!
can you test/review https://github.com/GoogleCloudPlatform/terraformer/pull/871  ?

**Comment by Olin-Vorechovsky** [comment]
There is one thing overlooked here, replace organization for **owner**:
https://github.com/GoogleCloudPlatform/terraformer/blob/7c0dc227dd424030c5d179de5ed547a74afcdecf/providers/github/repositories.go#L46

and all other resources using that old command line parameter...

You need to change it for:
`repos, resp, err := client.Repositories.ListByOrg(ctx, g.GetArgs()["owner"].(string), opt)`

**Comment by sergeylanzman** [comment]
oh.. https://github.com/GoogleCloudPlatform/terraformer/pull/894
