### ISSUE TITLE
Using multiple filters not working 

### ISSUE THREAD

**Issue by rchand21** [GoogleCloudPlatform/terraformer#1881]
I am trying to filter all resources from aws for a single vpc. 

The example in the Readme is not filtering the results 
terraformer import aws -r sg,vpc --filter Type=sg;Name=vpc_id;Value=VPC_ID --filter Type=vpc;Name=id;Value=VPC_ID

**Comment by Kubes1598** [comment]
have yu tried this
terraformer import aws --resources=vpc,subnet,security_group --filter=Name=vpc_id;Value=VPC_ID
