### ISSUE TITLE
Failing to fetch ECS resources when fetching multiple resource types

### ISSUE THREAD

**Issue by cwatson-im** [GoogleCloudPlatform/terraformer#1886]
Running 
`terraformer plan aws --resources=ecs` works.
`terraformer plan aws --resources=iam` works
`terraformer plan aws --resources=route53,iam` works

However, `terraformer plan aws --resources=ecs,iam` does not work. It fetches iam resources correctly, but fails to fetch ECS infrastructure. 

The `--verbose` output seems to indicate that the resources are not being fetched at all. 
```
2024/06/14 19:26:10 aws importing... ecs
2024/06/14 19:26:12 aws done importing ecs
2024/06/14 19:26:12 Number of resources for service ecs: 0
```

I have not tested with more resources types, so I do not know what all is affected.

**Comment by Lewiscowles1986** [comment]
I've seen this too. Luckily you can run multiple times, specifying a single resource at a time
