### ISSUE TITLE
Errors in multi region AWS resources import

### ISSUE THREAD

**Issue by dkislov** [GoogleCloudPlatform/terraformer#1887]
When running "**terraformer import aws...**" with multiple regions in the **--regions** option, errors are generated on the second region resources import:

**ERROR: Read resource response is null for resource <Resource from the previous region>
ERROR: Unable to refresh resource <Resource from the previous region>**

That is happening because of the caching of configuration in  **provider/aws/aws_service.go**:

in  
func (s *AWSService) generateConfig() (aws.Config, error)  there is piece of code:

if configCache != nil {
	return *configCache, nil
}

**Comment by amine-baaa** [comment]
A quick workaround that helped me was to clear the config cache explicitly before initiating the import for each region. You can achieve this by modifying the `aws_service.go` file to reset the `configCache` at the start of the `generateConfig` function.

Here's a brief patch that you might find useful:

```go
func (s *AWSService) generateConfig() (aws.Config, error) {
    // Clear the cache to ensure a fresh config is generated for each region
    configCache = nil

    if configCache != nil {
        return *configCache, nil
    }
    ...
}
```

This change forces Terraformer to generate a new configuration for each region, which should prevent the errors you’re seeing.

If you're not comfortable modifying the source code directly, you might want to split your imports by region and run them sequentially in separate commands:

```sh
terraformer import aws --resources=identitystore --regions=us-east-1 --profile=terraform-imdiots
terraformer import aws --resources=identitystore --regions=us-west-1 --profile=terraform-imdiots
```
