### ISSUE TITLE
AWS - list of supported service names as --resources parameter

### ISSUE THREAD

**Issue by PabloPessolani** [GoogleCloudPlatform/terraformer#1908]
There should be a list of supported resource names in the "--resources" parameter.
The list in  https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/aws.md is not valid as names for this paramter.
Regards.
PD:
ie: terraformer import aws resources_list  or
terraformer import aws --list

**Comment by coandco** [comment]
I believe the command you're looking for is `terraformer aws import list`:
```
$ terraformer import aws list
accessanalyzer
acm
alb
api_gateway
appsync
auto_scaling
batch
budgets
cloud9
cloudformation
cloudfront
cloudhsm
...
```
