### ISSUE TITLE
Rethink behavior without passing implicitly required options

### ISSUE THREAD

**Issue by kanata2** [GoogleCloudPlatform/terraformer#192]
### Description
In some provider's subcommands, there are some implicitly required flags.(e.g. aws: `regions`, google: `projects`, `regions`)
This means that `Import` function in subcommand does not execute without these options and then only return 0.
I think there is no way to get the cause except for reading source code, so this behavior is not user-friendly.

### Proposal
I think that required options for executing `Import` funciton is distinct from each providers required options and so want to use `(*cobra.Command).MarkFlagRequired` (or some original validations).

I'd like to get your feedback.

**Comment by pdecat** [comment]
This is especially desired for global AWS resources not tied to a specific region, e.g. AWS Route53 zones where having to specify a region seems weird.

**Comment by meshuga** [comment]
@pdecat I agree with you. Apart from that, in case of AWS it should be also possible to handle scenario when we rely on default region (from an env variable or EC2/ECS metadata).

Validating whether `regions` parameter in AWS provider is required or not is not easy, so I'd propose to try to perform import of files to a _global_ directory if no `regions` parameter is passed. In that case we'd solve case of global resources and implicit region.

Let's see how it could be done in GCP, maybe we could make use of `MarkFlagRequired` there.

**Comment by kanata2** [comment]
> This is especially desired for global AWS resources not tied to a specific region

I missed it, I agree with you.
