### ISSUE TITLE
ERROR: Read resource response is null for resource aws_api_gateway_resource

### ISSUE THREAD

**Issue by HLN177** [GoogleCloudPlatform/terraformer#1943]
Hi,

I've recently been migrating my existing AWS architecture to Terraform, and thanks to the Terraformer tool, which saved a lot of time. However, I encountered some issues while using Terraformer to import the API Gateway. For instance, when I run the following command: 

`
terraformer import aws --resources=api_gateway --regions=eu-central-1
`

nearly all resources are imported into the state and generate HCL, except for api_gateway_resource.
After a brief code debug, I found that when refreshing api_gateway_resources, it always results in a resource not found error. Error as follow:

`2024/10/28 15:58:11 Refreshing state... aws_api_gateway_resource.tfer--xxxxxxxxxx`
`2024/10/28 15:58:13 ERROR: Read resource response is null for resource aws_api_gateway_resource.tfer--xxxxxxxxx`
`......`
`ERROR: Unable to refresh resource tfer--xxxxxxxxxxx`

 Could you please explain why this is happening?

**Comment by nbalmaceda-koronet** [comment]
It continues failing for me, I'm using the latest terraform-aws-provider version.

**Comment by lihuaabcder** [comment]
> It continues failing for me, I'm using the latest terraform-aws-provider version.

terraform -v
Terraform v1.9.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.93.0

terraformer -v
version v0.8.24

Here are the version of my current terraform, terraform provider and terraformer, which works in my local environement.

Maybe could have a initial check to see if it works.
