### ISSUE TITLE
NoCredentialProviders: no valid providers in chain. 

### ISSUE THREAD

**Issue by caleb15** [GoogleCloudPlatform/terraformer#197]
I got this error and I was confused because my credentials were already setup - I could use terraform just fine. I did a bit of fiddling and realized that I was specifying a profile but didn't have my aws authentications details set up for that profile.

**Comment by jalbstmeijer** [comment]
Hi, would like to re-open this case.

I use env variables for the credentials.

AWS_DEFAULT_REGION
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID

I just started testing with Terraformer-0.8 and get this error 

> 2019/10/01 09:36:35 NoCredentialProviders: no valid providers in chain. Deprecated.
> For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Switching back to Terraformer 0.7.9 and it works again.
Am I missing something?

**Comment by meshuga** [comment]
Can you use `AWS_REGION ` env variable to provide region in which you want to work with?

I agree, version 0.8 has problems with credentials and https://github.com/GoogleCloudPlatform/terraformer/pull/200 solves the issue you raised. I think we'd need to make a new, stabilising release @sergeylanzman

**Comment by jalbstmeijer** [comment]
> Can you use `AWS_REGION ` env variable to provide region in which you want to work with?

Does not do anything for me, should it?

**Comment by meshuga** [comment]
You can take a look at task #192 to see how we’ll improve the way how region can be passed. There’s a PR ready to be merged for it as well

**Comment by sergeylanzman** [comment]
Released 0.8.1 with last fixes

**Comment by jalbstmeijer** [comment]
Works for me!
Where those trace and debug messages intended?

2019/10/01 18:47:03 [TRACE] GRPCProvider: GetSchema
2019/10/01 18:47:03 [TRACE] GRPCProvider: Configure
2019/10/01 18:47:05 [TRACE] GRPCProvider: GetSchema
2019/10/01 18:47:05 [TRACE] GRPCProvider: GetSchema
2019/10/01 18:47:05 [TRACE] GRPCProvider: Configure
2019/10/01 18:47:07 [DEBUG] New state was assigned lineage "a83eefc8-90b1-cfa8-8a2b-631100c8f50e"
