### ISSUE TITLE
tags not valid TF

### ISSUE THREAD

**Issue by caleb15** [GoogleCloudPlatform/terraformer#198]
may be related to #85

see https://github.com/hashicorp/terraform/issues/19325 - tags have to have equal sign, like so:

```
  tags = {
    Name = "testTag"
  }
```

However, the generated tag format is like this:

```
  tags {
    Name = "testTag"
  }
```

The generated format is incorrect.

**Comment by caleb15** [comment]
this is using:

Terraform v0.12.9
+ provider.aws v2.29.0

**Comment by meshuga** [comment]
What version of terraformer do you use? Latest version has this issue solved (#117 ).

**Comment by sergeylanzman** [comment]
Support terraform 0.12 merged to master, but not released.
Try use code from master

**Comment by sergeylanzman** [comment]
try laster version
