### ISSUE TITLE
0.8.1: alb Error: "vpc_id": this field cannot be set

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#209]
using:
terraformer-0.8.1
terraform-0.12.9
terraform-provider-aws_v2.3

lb.tf gets a vpc_id imported in resource aws_lb

This results in error while running terraform plan; 

Error: "vpc_id": this field cannot be set

commenting vpc_id fixes it.

**Comment by sergeylanzman** [comment]
Hey 
Thank for your bug report.
Which resources has vpc_id? aws_lb? 
it's network balancer or application?

**Comment by jalbstmeijer** [comment]
Ah, sorry for my unclear report, but yes as the subject suggests it about the ALB and the resource is called aws_lb

**Comment by nachieket** [comment]
Hi, is this issue fixed yet please? I am stuck with the same error and can't move forward. I have upgraded to v0.12.13 but it is still not working. I am not sure if fix issue 209 means this is now resolved in which case I don't know how to get the update. Thanks.
