### ISSUE TITLE
0.8.1: ECS import issues

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#210]
using:
terraformer-0.8.1
terraform-0.12.9
terraform-provider-aws_v2.3.0

while running terraform plan:

Error: Unsupported argument
on ecs_cluster.tf
An argument named "task_definition" is not expected here.
* Had to comment it for now

Error: expected propagate_tags to be one of [SERVICE TASK_DEFINITION ], got NONE
on ecs_service.tf 
* had to change it to: propagate_tags = "SERVICE" ,  for now

Error: Unsupported argument
on ecs_task_definition.tf
An argument named "task_definition" is not expected here.
* had to comment it for now

Error: "revision": this field cannot be set
on ecs_task_definition.tf
* had to comment it for now

**Comment by jalbstmeijer** [comment]
> Error: expected propagate_tags to be one of [SERVICE TASK_DEFINITION ], got NONE
> on ecs_service.tf
> 
> had to change it to: propagate_tags = "SERVICE" , for now

Commenting propagate_tags worked better for me.. it seems an optional attribute and NONE is not a valid value.

**Comment by meshuga** [comment]
For reference: `iam_role` argument in `aws_ecs_service` is also generating an error - terraform-providers/terraform-provider-aws#4657.
