### ISSUE TITLE
Should global AWS resources not be imported from us-east-1?

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#211]
using:
terraformer-0.8.1
terraform-0.12.9
terraform-provider-aws_v2.3.0

When importing multiple regions, some things are duplicate.
Examples, iam and route53.
Would it not be better to have these linked to the us-east-1 region only?

**Comment by meshuga** [comment]
Thanks for raising the issue. I think in case of global resources, it'd be best not to point to a specific region at all, just keep as they are but perhaps we should check if a given resource as global and stop importing that resource into a specific region.
