### ISSUE TITLE
provide backend file

### ISSUE THREAD

**Issue by moos3** [GoogleCloudPlatform/terraformer#242]
Is it possible to provide a backend TF file to be included in the provider? So that you don't have to cut and paste the same block of code a to every single service's configuration?

**Comment by sergeylanzman** [comment]
Can you get example for this?

**Comment by moos3** [comment]
So something like below. It seems anytime I add something to provider.tf the next time I run terraformer, it blows it away. I would be nice if I could provide a template provider file or even a state.tf file that could allow me to use remote state storage on terraform cloud. 

```
provider "google" {
  project = "${var.google_project_name}"
}

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "${var.tfc-org}"
    token = "${var.tfc-token}"
    workspaces {
      name = "${var.tfc-workspace}"
    }
  }
}
```
