### ISSUE TITLE
Embed providers in terraformer executable

### ISSUE THREAD

**Issue by meshuga** [GoogleCloudPlatform/terraformer#245]
Since now it's possible to create separate executable per provider with `build/main.go`, it'd be good to embed Terraform provider in Terraformer for simpler installation.

**Comment by sergeylanzman** [comment]
I think this is not necessary, because the terraformer can use different versions of providers. Today there is an easy installation with terraform init, it's simple.

**Comment by meshuga** [comment]
Okay, let's close this issue for now then.
