### ISSUE TITLE
Can't find provider version (Invalid version constraint in Terraform)

### ISSUE THREAD

**Issue by sjourdan** [GoogleCloudPlatform/terraformer#252]
Since the 0.8.4 release, the AWS importer outputs the following (I don't know about other providers): 

```
$ ./terraformer-all-darwin-amd64 --version
version v0.8.4
$ ./terraformer-all-darwin-amd64 import aws --regions=eu-west-3 --resources=vpc --state local
[...]
2019/10/21 14:29:57 aws save vpc
2019/10/21 14:29:57 Can't find provider version
2019/10/21 14:29:57 aws save tfstate for vpc
```

The generated provider.tf indeed doesn't include the provider version: 

```
$ cat generated/aws/vpc/eu-west-3/provider.tf
provider "aws" {
  region  = "eu-west-3"
  version = ""
}
```

Which in turn leads to a Terraform provider error: 

```
$ terraform plan

Error: Invalid version constraint

  on provider.tf line 3, in provider "aws":
   3:   version = ""

This string does not use correct version constraint syntax.
```

In 0.8.3, no issue: 

```
$ ./terraformer-darwin-amd64 --version
version v0.8.3
$ ./terraformer-darwin-amd64 import aws --regions=eu-west-3 --resources=vpc --state local
[...]
2019/10/21 14:37:08 aws save vpc
2019/10/21 14:37:08 aws save tfstate for vpc
$ cat generated/aws/vpc/eu-west-3/provider.tf
provider "aws" {
  region  = "eu-west-3"
  version = ">2.25.0"
}
```

**Comment by sergeylanzman** [comment]
How you install provider? Whats file name of provider?

**Comment by sjourdan** [comment]
I wget directly from https://releases.hashicorp.com/terraform-provider-aws/ and move the provider to its default location in my home dir: 

```
$ ls -al ~/.terraform.d/plugins/darwin_amd64/terraform-provider-aws
-rwxr-xr-x  1 sjourdan  staff  151037856 Oct  3 17:03 /Users/sjourdan/.terraform.d/plugins/darwin_amd64/terraform-provider-aws
```

**Comment by sergeylanzman** [comment]
By default all provider file name include version, I don't find in provider interface for get version from code and I get version from provider file name.
here https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/provider_wrapper/provider.go#L245-L260

I think if we don't have version not need write in provider.tf `version = ""`

**Comment by sjourdan** [comment]
Oh you're right. I don't know why I've been renaming the provider file. 
With the default naming (the one you'd get by using `terraform init`), it works like a charm.

Let's close this! Thanks for the hint Sergey!
