### ISSUE TITLE
[AWS provider] Add support for customer-gateways and transit-gateways

### ISSUE THREAD

**Issue by dbarranco** [GoogleCloudPlatform/terraformer#279]
First of all, thank you so much for the work that's being done here.
It's helping me a lot to create some DR plans.

So I'd like to know if there is any plan for adding the following AWS resources:

* AWS transit gateway
* AWS customer gateway

Based on what I've seen in this repo it seems it is not difficult at all to add support for these resources, so if you give me some pointers I could help with this :)

Thanks again!

**Comment by meshuga** [comment]
It's a pleasure to hear that!

Adding support for a new resource type consists of the following steps:
1. Create a file for each resource group where you'd generate needed resources e.g. https://github.com/GoogleCloudPlatform/terraformer/blob/0.8.4/providers/aws/vpn_connection.go
2. Add a reference to the provider in https://github.com/GoogleCloudPlatform/terraformer/blob/0.8.4/providers/aws/aws_provider.go#L195
3. I recommend to add definitions of connections to other resources in https://github.com/GoogleCloudPlatform/terraformer/blob/0.8.4/providers/aws/aws_provider.go#L43
4. Update `README.md`

To quickly test the provider, you can use e.g. https://github.com/GoogleCloudPlatform/terraformer/blob/0.8.4/tests/aws/main.go

**Comment by dbarranco** [comment]
awesome, thanks for the info.

I guess during the next week me or someone from the Bitnami SRE team will contribute to the project with these resources.

Thanks again! 🚀

**Comment by dbarranco** [comment]
hey @meshuga!

I added support for the AWS customer gateway in the fork I created this morning:
https://github.com/dbarranco/terraformer/commit/4ea3c6f9f8d982d79f88522ca30f9365c2c5e159

But would like to ask you a quick question.
I've been running the tests by changing [this](https://github.com/dbarranco/terraformer/blob/master/tests/aws/main.go#L47) to the new `customer_gateway` resource I added and works fine, but I'm now wondering if there would be any way to run that test with more than one resource (let's say `vpn_connections` and `customer_gateway`) so I can properly test if these two elements are connected.


Btw, I'm not submitting yet a PR because I am in the process to get approved in the Google CLA.

Thanks again!

**Comment by meshuga** [comment]
Sure, just add `'vpn_connections', 'customer_gateway'` instead of `'sg'` in test class https://github.com/GoogleCloudPlatform/terraformer/blob/0.8.5/tests/aws/main.go#L47 and run it. The test settings will try to connect the resources and compact the resulting terraform resource file to one.

**Comment by dbarranco** [comment]
#355 has been landed, I think we can close this issue.

Thanks! :)

**Comment by meshuga** [comment]
Thanks @dbarranco for the contribution!
