### ISSUE TITLE
[GCP Dataproc] - Error 400: Region '' is invalid

### ISSUE THREAD

**Issue by thanidev** [GoogleCloudPlatform/terraformer#281]
terraformer import google --connect --projects=my-proj --resources=dataProc --regions=global

```bash
2019/11/13 00:48:20 google importing project my-proj region global
2019/11/13 00:48:22 google importing... dataProc
2019/11/13 00:48:22 googleapi: Error 400: Region '' is invalid. Please see https://cloud.google.com/dataproc/docs/concepts/regional-endpoints for additional information on regional endpoints, badRequest```

**Comment by sergeylanzman** [comment]
dataproc API need region, global not valid for this case

**Comment by dimakri** [comment]
I am getting the same error with subnetworks:

./terraformer import google --projects=my-proj --resources=subnetworks

`2020/09/30 09:25:01 google importing project mls-sre-playground region global
2020/09/30 09:25:02 google importing... subnetworks
2020/09/30 09:25:03 googleapi: Error 400: Invalid value for field 'region': ''. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalid
2020/09/30 09:25:03 google Connecting....
2020/09/30 09:25:03 google save subnetworks
2020/09/30 09:25:03 google save tfstate for subnetworks`

**Comment by ReToCode** [comment]
Same for `memoryStore`
```
terraformer import google --resources=memoryStore --projects=xxx -s local                                     
2020/10/05 09:52:27 google importing project xxx region global
2020/10/05 09:52:28 google importing... memoryStore
2020/10/05 09:52:28 googleapi: Error 400: location is not specified in method "redis.googleapis.com/CloudRedis/ListInstances", badRequest
```
