### ISSUE TITLE
Question: How does compact work?

### ISSUE THREAD

**Issue by Ghost---Shadow** [GoogleCloudPlatform/terraformer#282]
This is the command I am running

```sh
go build -v && ./terraformer import alicloud --resources=ram,ecs --regions=ap-southeast-3 --compact=true
```

It still generates two terraform states.

I was under the assumption that the compact argument merges all the terraform states. Am I using it wrong?

**Comment by meshuga** [comment]
I agree it might be confusing how to generate compact files but we'd need to conform to other configuration parameters that are used to configure the tool.

One of them is `-p, --path-pattern string` to define there to save generated resources with default value `{output}/{provider}/{service}/`.

You need to configure that parameter and pass e.g. `{output}/{provider}/` to have resources for all services for a given provider to be generated in a single file.

**Comment by Ghost---Shadow** [comment]
I think this should be included in the `README.md`
