### ISSUE TITLE
Error when trying to import cloudformation stack

### ISSUE THREAD

**Issue by roeera** [GoogleCloudPlatform/terraformer#284]
Hi,

Tried to run the following command on my infra :

terraformer import aws --resources=cloudformation --regions=us-west-1

Receiving the following errors in the output and nothing got generated:

ERROR: Read resource response is null for resource aws_cloudformation_stack.tfer--awseb-e-fcsb6rbmfw-stack

appreciate your help.

**Comment by meshuga** [comment]
Can you described how you configured your account on local machine? It seems Terraform has troubles fetching resources.

There are some differences in terms how credentials are being used by terraformer and terraform (especially when using MFA), so some cases might not be handled.
