### ISSUE TITLE
AWS SQS Will only list 1000 queues, after that is ignored

### ISSUE THREAD

**Issue by marcelobartsch** [GoogleCloudPlatform/terraformer#291]
as the AWS API Works for SQS, it will list only the first 1000 queues, if you have more than 1000 queues in SQS you will need to use QueueNamePrefix to list queues after that. 

It would be nice to have a parameter to pass when importing SQS , to be able to bypass this limitation.

in sqs.go we have:

queuesList, err := svc.ListQueues(&sqs.ListQueuesInput{})

this will list the first 1000 queues only. it would be nice to have something like:

var prefix = &sqs.ListQueuesInput{
		QueueNamePrefix: aws.String(os.Getenv("SQS_PREFIX")),
	}
	queuesList, err := svc.ListQueues(prefix)

Sorry my GO is not good enough to figure out how to pass _sqs_queue_prefix_ from command line to the module, but this 'hack' do the trick.

**Comment by meshuga** [comment]
I agree, I does the trick and unfortunately there isn't any better approach.
