### ISSUE TITLE
Importing a VPC

### ISSUE THREAD

**Issue by copernicus** [GoogleCloudPlatform/terraformer#300]
When you import a VPC should it not be also importing associated configured resources? Like a VPC is associated with route table and subnet configuration and others.  Apologies if I missed this in the docs.

```
terraformer import aws --resources=vpc --filter=aws_vpc=myvpcid --regions=eu-west-1
```

thanks!

**Comment by meshuga** [comment]
Hi, technically it's possible to do since we have crafted a list of resource connections (ref https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/aws_provider.go#L43) although for now you'd need to do it manually.

**Comment by copernicus** [comment]
Ah, ok. Thanks!
