### ISSUE TITLE
Restore TF state for a set of existing TF resource files

### ISSUE THREAD

**Issue by jvanzyl** [GoogleCloudPlatform/terraformer#305]
Hi,

I have a set of TF resource files that were used to create some infrastructure in AWS and then I accidentially deleted the state... I'd like the state to be recreated using the names of the resources in the existing resource files I have.

For the resources in AWS it would not be possible to deterministically assign the name of the resources in the state without a little help. If tags were appropriately assigned when resources were created maybe this type of recovery could be entirely automated.  Let's say I had the following tags for a VPC and subnet:

VPC
creator=concord
concord.resourceName=main
concord.group=worker-network

Subnet:
creator=concord
concord.resourceName=public
concord.group=worker-network

Then with a form of filter I could grab all the AWS resources tagged with concord.group=worker-network and then look for the concord.resourceName tag that could be applied to the state that was generated.

I'd be happy to try and contribute this if you thought this was a decent idea and provided some guidance on how you might like it implemented. I used `terraformer` yesterday and it completely saved me from hours of very tedious work. I wrote some scripts to do more or less what I described above but from looking at the code you have all the bits and pieces to fully automate this.

Thanks for Terraformer!

Jason

**Comment by sergeylanzman** [comment]
Look like use `terraformer plan aws ` command, but it's manually
https://github.com/GoogleCloudPlatform/terraformer#planning
