### ISSUE TITLE
Q about terraforming datadog resources, import single resource by id or filter by tag

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/terraformer#308]
I am trying to bootstrap to help clone some of the dashboards, but dont want to terraforming the entire space. I wonder if there is good way to just terraform either a single resource or terraform sources by tag.

**Comment by meshuga** [comment]
You can use filters for that purpose by either providing resource id(s) [1] or you can try filtering resources by attributes [2]. The thing is the second option is more intended for AWS provider although in theory that should work for other providers as well :)

[1] https://github.com/GoogleCloudPlatform/terraformer#resource-id
[2] https://github.com/GoogleCloudPlatform/terraformer#attribute-filters
