### ISSUE TITLE
Add support for AWS WAF

### ISSUE THREAD

**Issue by cncoder** [GoogleCloudPlatform/terraformer#311]
It would be nice to have support for WAF.

**Comment by meshuga** [comment]
To be more specific - WAF V1 can be supported.
WAFv2 resources are still under proposal e.g. terraform-providers/terraform-provider-aws#11176

**Comment by volym3ad** [comment]
WAFv2 seems to be supported by provider started from version 2.67.0. Is there any plan to add it to terraformer?
