### ISSUE TITLE
Fails to scan on Windows, incorrect path for plugins

### ISSUE THREAD

**Issue by JamesWoolfenden** [GoogleCloudPlatform/terraformer#314]
I downloaded the terrafomer-all-windows-amd64.exe executable and tried a basic scan:
```
 terraformer import aws --resources=vpc,subnet
2019/12/10 10:43:50 aws importing default region
2019/12/10 10:43:50 aws importing... vpc
2019/12/10 10:44:00 plugin error 1: open C:\Users\james.woolfenden\.terraform.d/plugins/windows_amd64: The system cannot find the path specified.
2019/12/10 10:44:00 open C:\Users\james.woolfenden\.terraform.d/plugins/windows_amd64: The system cannot find the path specified.
```
Should it not be looking for (ignoring the wrong slashes):
C:\Users\james.woolfenden\.terraform.d\\**plugin-cache**\\windows_amd64

Thanks

**Comment by meshuga** [comment]
The issue also been raised in hashicorp/terraform#23320. Terraformer has copied logic from Terraform but should apply fix to bug above to perform lookup in `%APPDATA%\terraform.d\plugins` on Windows machines.

**Comment by vpernankil** [comment]
any update on this ?

**Comment by MostHated** [comment]
I am having this issue as well, though it is with Cloudflare if that makes a difference.

**Comment by meshuga** [comment]
Oh my, just saw a problem we use slashes instead of backslashes on Windows 🤦🏻
