### ISSUE TITLE
Go panic on providers using terraform-plugin-sdk 

### ISSUE THREAD

**Issue by guile32** [GoogleCloudPlatform/terraformer#327]
Hello, 

I'm trying to add kafka resources in terraformer using the community provider https://github.com/Mongey/terraform-provider-kafka

This provider follows hashicorp guidelines and use the new terraform-plugin-sdk.

Sadly, It's not possible to include both "github.com/hashicorp/terraform/terraform" and "github.com/hashicorp/terraform-plugin-sdk/terraform"

This problem should also occur when official terraform providers will switch to terraform-plugin-sdk

Is there any plans to use the sdk instead of terraform core in terraformer?

## *How* do we replicate the issue?
include "github.com/hashicorp/terraform-plugin-sdk/terraform"
```
./terraformer import kafka -r topics 
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag

goroutine 1 [running]:
encoding/gob.RegisterName(0x3bf357a, 0x18, 0x4370540, 0x0)
	/usr/local/go/src/encoding/gob/type.go:820 +0x558
encoding/gob.Register(0x4370540, 0x0)
	/usr/local/go/src/encoding/gob/type.go:874 +0x123
github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags.init.0()
	/$GOPATH/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfdiags/rpc_friendly.go:58 +0x36
```
## Expected behavior (i.e. solution)
Being able to use a provider which has terraform-plugin-sdk as a dependency

## See also
 - https://github.com/hashicorp/terraform-plugin-sdk/issues/268
 - https://www.hashicorp.com/blog/announcing-the-terraform-plugin-sdk/

**Comment by sergeylanzman** [comment]
I tried to use `terraform-plugin-sdk`, but it's complicated.
2 issues:
1. `registering duplicate types`
2. internal package in terraform-plugin-sdk, but terraformer need use them.

Why you need include terraform-plugin-sdk or kafka provider? terraformer can work without provider code.

**Comment by guile32** [comment]
I was following the way others providers are working. 
The provider already manage the connection to kafka. Including the provider makes terraformer simplier to maintain since we need the same thing.

I´ll remove the dependency and manage the kafka configuration within terraformer.

I was just wondering if terraformers dev also had the same issue. It might raise again when other terraform providers will switch to the sdk.

**Comment by sergeylanzman** [comment]
Terraformer talk with provider as terraform with GRPC protocol. 
You don't need use code from provider. You can see GCP or AWS provider.
