### ISSUE TITLE
Why terraformer cannot pull right .tf file

### ISSUE THREAD

**Issue by wzf1943** [GoogleCloudPlatform/terraformer#328]
Hi I tried to pull .tf file from google GCP based on tutorial says. I write init.tf and copy google plugin to 

```
ls ~/.terraform.d/plugins/darwin_amd64/
lock.json                           terraform-provider-google_v3.2.0_x5
```

The command works but not works as my expected. I tried to pull instance .tf file. But the file that terraformer pulled is too simple and those files cannot show the details of my running instance.

**Comment by sergeylanzman** [comment]
What command you run?
