### ISSUE TITLE
Plugin error during a try of importing project

### ISSUE THREAD

**Issue by nlamirault** [GoogleCloudPlatform/terraformer#33]
I use the binary release, and the binary after having cloned the repository. I've got same error : 

```
$ ~/bin/terraformer-linux-amd64 import google --resources=gcs,firewalls,forwardingRules,networks --connect=true --projects=mygcpproject
2019/05/06 09:17:33 google importing project mygcpproject
2019/05/06 09:17:33 google importing... gcs
2019/05/06 09:17:34 plugin error: fork/exec : no such file or directory
2019/05/06 09:17:34 fork/exec : no such file or directory
```

**Comment by sergeylanzman** [comment]
It's look like you don't have provider binary 
check in README 
`Copy your Terraform provider's plugin(s) to folder ~/.terraform.d/plugins/{darwin,linux}_amd64/, as appropriate.`

**Comment by nlamirault** [comment]
Works fine. I made a mistake with the plugin's directory. Sorry for noise.

**Comment by etiennetremel** [comment]
For the one ending on this issue because of looking for this error...
If you run Terraformer from a Linux based Docker container and mount a directory from your osx/windows machine, make sure to delete the `.terraform/` diretory before running Terraformer.

**Comment by syswipe** [comment]
I have the same issue :(
I installed binary release and placed all *.go file built from sources and related to AWS. But I still have an error:
```
terraformer import aws --resources=vpc --regions=eu-central-1
2020/08/11 14:10:58 aws importing region eu-central-1
2020/08/11 14:10:58 aws importing... vpc
2020/08/11 14:10:59 fork/exec : no such file or directory
```

**Comment by Efrat19** [comment]
my solution for MAC - adding the plugin manually:
```bash
# install aws plugin (or whatever plugin you need)
curl -LO https://releases.hashicorp.com/terraform-provider-aws/3.58.0/terraform-provider-aws_3.58.0_darwin_amd64.zip 
mkdir -p ~/.terraform.d/plugins/darwin_amd64
mv terraform-provider-aws_3.58.0_darwin_amd64.zip ~/.terraform.d/plugins/darwin_amd64
cd ~/.terraform.d/plugins/darwin_amd64
unzip terraform-provider-aws_3.58.0_darwin_amd64.zip 
```

**Comment by sankalp-khare** [comment]
I symlink the binary from the project I want to import resources to. Ensures that we're using the same provider version (terraformer and my project)
