### ISSUE TITLE
GCP Instances not generating .tf files

### ISSUE THREAD

**Issue by shankarcs** [GoogleCloudPlatform/terraformer#335]
Hi Team,

I have used terraformer to import GCP instance into .tf file. But its only importing provider.tf , terraform.tfstate files. Kindly help me with this.

I have used below command:
terraformer import google --resources=instances --projects=useful-matter-230809

If I import GCS it's working perfectly fine as I am excepted.
terraformer import google --resources=instances --projects=useful-matter-230809

**Comment by sergeylanzman** [comment]
Try with regions `./terraformer import google --resources=instances --regions=us-west1 --projects=useful-matter-230809`
