### ISSUE TITLE
GCP HTTP2 health checks not imported correctly

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/terraformer#341]
(On d8e13fac.) The HCL generated for an HTTP2 health check looks like this:
```
resource "google_compute_health_check" "...name..." {
  check_interval_sec  = "5"
  healthy_threshold   = "2"
  name                = "...name..."
  project             = "...project..."
  timeout_sec         = "5"
  unhealthy_threshold = "2"
}
```
It's missing the `http2_health_check` [section](https://www.terraform.io/docs/providers/google/r/compute_health_check.html#example-usage-health-check-http2-full).

**Comment by sergeylanzman** [comment]
What version of google provider you use? http2_health_check look inserted in 3.0

**Comment by dhduvall** [comment]
2.11; I guess it's too old. But then I'm surprised that I got the object at all, instead of an incomplete one.
