### ISSUE TITLE
sort JSON plans

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/terraformer#342]
It would be convenient if the JSON plan files generated by `terraformer plan` were more stable in their output. I did two runs, one with `-z global` and one with `-z us-west1` (this is on GCP), which came up with nearly-identical content (disks and instances were `null` in the former), but it was really hard to tell, since many of the lists and objects were ordered arbitrarily. The ordering isn't stable even across two runs in the same zone.

Obviously there could be some intention to the ordering, but I think that at least with GCP, the places where ordering counts are handled by having key names with indices in them (`foo.0.key`, `foo.1.key`, etc).

The places where I saw it was in `IgnoreKeys` (lists of strings), `Item.access` (lists of objects related to roles), `Item.role_entity` (lists of strings), and service account `scopes` (lists of strings).

**Comment by brunson** [comment]
Definitely desirable as we want to put our reverse engineered files into git for tracking purposes.
