### ISSUE TITLE
terraformer --resource  error

### ISSUE THREAD

**Issue by rduart** [GoogleCloudPlatform/terraformer#348]
I am having any issue when running the terrarformer command.    I have search the web hoping to find a solution, but nothing has surfaced.  

terraformer import aws --resources=vpc,subnet --regions=us-west-2 --profile=prod

error produced
2020/01/09 19:10:55 unknown flag: --resources

I am running:  
go version go1.13.5 linux/amd64
Terraform v0.12.18
+ provider.aws v2.25.0

I have also tried:
Terraform v0.12.18
+ provider.aws v2.43.0

The install went as expected I did not see any errors.  I think that I must have something wrong in the configuration?   Can anyone provide any guidance/help?

**Comment by rduart** [comment]
Its been solved.   I had an issues when building from the source.  I rebuilt and the problem corrected it self.    As such, I am not sure what exactly happened.    Thank you to anyone who might been thinking about my problem.

**Comment by meshuga** [comment]
That’s strange. I’ve been building the project many times and never got this kind of random error.

**Comment by rduart** [comment]
I created a new ec2 instance to determine what went wrong with my original build.   In doing so, I discovered the rebuild did not fix the problem.  I was pointing to the release version I download earlier.   I now think the problem might simply be my "GO" skills and environment setup.

To build the Terrafomer executable - I follow the directions as specified:

Git clone  
GO111MODULE=on go mod vendor
go build -v
created the init.tf -- added AWS provider
ran terraform init

I did not see any errors during the build.

Command an error. 
$ ./terraformer import aws --resources=vpc,subnet --regions=us-west-2
2020/01/13 22:09:10 unknown flag: --resources

I also noticed a big difference in the executable size of the built version compared to the relaese version.

Release version is around 86M
Built version is around 31M

I am running:
go version go1.13.5 linux/amd64
Terraform v0.12.18
provider.aws v2.25.0

Any idea what I done wrong?

thanks

**Comment by anandray** [comment]
Hi,

I'm seeing similar issues:
**1. When installed from source using the following instructions:**
```
  - Run git clone <terraformer repo>
  - Run GO111MODULE=on go mod vendor
  - Run go build -v 
```
**Error:**
```
$ terraformer-v0.8.5 import google --projects=<project_name> --zone=us-west1-a
2020/01/18 12:15:00 unknown flag: --zone
```

**Version info:**
```
MacOS: High Sierra
Version: 10.13.6

$ go version
go version go1.13.4 darwin/amd64

$ terraformer version
Terraformer v0.8.5

$ ls -lt `which terraformer`
-rwxr-xr-x  1 root  admin  211566124 Jan 18 12:02 /usr/local/bin/terraformer
```

**2. When installed using these steps:**
```
  - export PROVIDER={all,google,aws,kubernetes}
  - curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64
  - chmod +x terraformer-${PROVIDER}-darwin-amd64
  - sudo mv terraformer-${PROVIDER}-darwin-amd64 /usr/local/bin/terraformer
```

**Error:**
```
$ terraformer import google --projects=<project_name> --zone=us-west1-a
2020/01/18 12:12:01 unknown flag: --projects
```

**Version info:**
```
MacOS: High Sierra
Version: 10.13.6

$ go version
go version go1.13.4 darwin/amd64

$ terraformer version
Terraformer v0.8.5

$ ls -lt `which terraformer`
-rwxr-xr-x  1 anand  staff  54953380 Jan 18 12:08 /usr/local/bin/terraformer
```

Thanks!
~anand

**Comment by sergeylanzman** [comment]
Maybe it's bad readme:
1. `- export PROVIDER={all,google,aws,kubernetes}` - need choose one of options
2. in google provide use region only, not zone

**Comment by anandray** [comment]
Thanks @sergeylanzman 

1. I did export only google as PROVIDER.
```
$ echo $PROVIDER
google
```
2. My build from the source worked with --region.  Thanks for pointing that out. 

However, when I tried the binary obtained from:
```
https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest
```
I got the following error:
```
$ terraformer import google --resources=gcs,forwardingRules,httpHealthChecks --connect=true --regions=us-west1 --projects=<project_name>
2020/01/18 12:28:02 unknown flag: --resources
```

So I reverted back to using the one I built from source.

Thanks!

**Comment by sergeylanzman** [comment]
Problem in 0.8.5 binary.
Updated you can download again and use.

**Comment by sektorhybrid** [comment]
For anyone that might reach this issue, this happened to me when I used WSL2. In my case, with WSL1 it runs as expected.
