### ISSUE TITLE
Error: Unknown flag resources 

### ISSUE THREAD

**Issue by khaderkhan** [GoogleCloudPlatform/terraformer#364]
Hi, I'm using version v0.8.5 of terraformer.

I'm trying to generate tf code for my gcp project. 

When I run: 

terraformer import google --resources=gcs,forwardingRules,httpHealthChecks --connect=true --regions=asia-south1-a --projects=agile-sanctum-2xxxxx2

It throws me this error:  unknown flag: --resources

How can I solve this?

**Comment by sergeylanzman** [comment]
Problem in 0.8.5 binary.
Updated you can download again and use.

**Comment by mariolameiras** [comment]
Hello, I'm using the linux binary and have the same problem

**Comment by sergeylanzman** [comment]
@mariolameiras release now 0.8.6 for all platform

**Comment by digomeloo** [comment]
@sergeylanzman Same error here 

erraformer import google  --resources=gcs,gke,firewalls,cloudsql,networks,subnetworks --projects=lexical-aquifer-249215 --zone=southamereica-east1
2020/03/06 14:53:59 unknown flag: --resources

**Comment by hcliff** [comment]
osx still occuring
```
 terraformer --version
version v0.8.7
```

**Comment by cursedcoder** [comment]
same here

```
⋊> ~/P/t/t/s/cbt on master ⨯ terraformer import aws --resources=vpc,subnet --connect=true --regions=eu-west-1                       17:11:30
2020/03/31 17:11:30 unknown flag: --resources
⋊> ~/P/t/t/s/cbt on master ⨯ terraformer -v                                                                                         17:11:30
2020/03/31 17:11:41 unknown shorthand flag: 'v' in -v
⋊> ~/P/t/t/s/cbt on master ⨯ terraformer --version                                                                                  17:11:41
version v0.8.7
```

**Comment by ricardo6142** [comment]
Same here at Linux

 ✘ ricardo@home  ~  terraformer import google --resources
2020/04/03 14:11:58 unknown flag: --resources
 ✘ ricardo@home  ~  terraformer --version
version v0.8.7
 ricardo@home  ~ 

**Comment by sergeylanzman** [comment]
bug in build process for release. 

Try build terraformer in your machine.

**Comment by 10dip** [comment]
Hello 
I am still facing this issue on Windows. Any suggestions ?

**Comment by Shaker53** [comment]
I am using Windows 10, loaded terraformer via `choco instal lterraformer` and faced this issue.
Resolved by installing terraformer according to this insrtuction: https://github.com/GoogleCloudPlatform/terraformer#installation (downloaded .exe file for required provider (in my case - Google Cloud))

**Comment by arunibm** [comment]
Used powershell to resolve this issue on Windows 11. I tried the installation from source as provided at https://github.com/GoogleCloudPlatform/terraformer

**Comment by harsiddhdave44** [comment]
Is there any other way to make this work other than building from source ? The latest version as of now v0.8.24 doesn't seem to fix it yet.
