### ISSUE TITLE
"role" and "members" arguments missing from generated "google_storage_bucket_iam_binding"

### ISSUE THREAD

**Issue by sjourdan** [GoogleCloudPlatform/terraformer#368]
Hello,

- terraformer version: v0.8.5
- terraform version: v0.12.20
- google provider version: v3.5.0

### Crash Output

Terraformer output: 

```bash
$ ./terraformer-all-darwin-amd64 import google --resources=gcs --regions=europe-west1 --projects=XXXX
2020/01/27 16:37:08 google importing project XXXX region europe-west1
2020/01/27 16:37:09 google importing... gcs
2020/01/27 16:37:10 Refreshing state... google_storage_bucket.tfer--terraformer_test_1
2020/01/27 16:37:10 Refreshing state... google_storage_default_object_acl.tfer--terraformer_test_1
2020/01/27 16:37:10 Refreshing state... google_storage_bucket_acl.tfer--terraformer_test_1
2020/01/27 16:37:10 Refreshing state... google_storage_bucket_iam_member.tfer--terraformer_test_1
2020/01/27 16:37:10 Refreshing state... google_storage_bucket_iam_policy.tfer--terraformer_test_1
2020/01/27 16:37:10 Refreshing state... google_storage_bucket_iam_binding.tfer--terraformer_test_1
2020/01/27 16:37:10 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer--terraformer_test_1
2020/01/27 16:37:11 ERROR: Unable to refresh resource tfer--terraformer_test_1
2020/01/27 16:37:11 google Connecting....
2020/01/27 16:37:11 google save gcs
2020/01/27 16:37:11 google save tfstate for gcs
```

Then a validate fails:

```bash
$ terraform validate

Error: Missing required argument

  on storage_bucket_iam_binding.tf line 1, in resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1":
   1: resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1" {

The argument "members" is required, but no definition was found.


Error: Missing required argument

  on storage_bucket_iam_binding.tf line 1, in resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1":
   1: resource "google_storage_bucket_iam_binding" "tfer--terraformer_test_1" {

The argument "role" is required, but no definition was found.
```

### Expected Behavior

- should include (as per documentation, see References below): 
  - member/members - (Required)
  - role - (Required)

### Actual Behavior

- the output above (missing arguments in tf resource)

### Steps to Reproduce

1. create a simple Google Cloud Storage bucket (single region (belgium), standard storage class, any access control, default google managed key for encryption)
1. import this default GCS bucket
1. terraform init 
1. terraform plan

### References

- https://www.terraform.io/docs/providers/google/r/storage_bucket_iam.html

Please tell me if you need any other information!

**Comment by mayeco** [comment]
I'm having the same issue

- terraformer version: **v0.8.10**
- terraform version: **v0.13.5**
- google provider version: **v3.51.1**

Any updates about this?

**Comment by dvdantunes** [comment]
Hi!, I'm having this issue too

My configuration:
- terraformer version: `v0.8.10`
- terrafom version: `v0.13.6`
- google provider version: `v3.53.0`

Any updates about this? It this an issue related with terraformer or with the official google provider?

Thanks!

**Comment by ericraskin** [comment]
I have the same issue as well:

- terraformer:  v0.8.10
- terraform: 0.14.7
- provider hashicorp/google - v3.57.0

Could it be that I am using the wrong provider?
