### ISSUE TITLE
Hyphen-minuses in names becomes  -002D-

### ISSUE THREAD

**Issue by ppmag** [GoogleCloudPlatform/terraformer#378]
This behavior is visible everywhere, not just in lambda names. 
AWS CLI output:

```
$ aws lambda list-functions

"Functions": [
        {
            "FunctionName": "get-client",
            "FunctionArn": "arn:aws:lambda:us-east-1:631001006968:function:get-client",
            "Runtime": "nodejs12.x",
            "Role": "arn:aws:iam::631001006968:role/service-role/get-client-role-xbocqvrg",
            "Handler": "index.handler",
            "CodeSize": 727,
....
```

Terraformer output:

```
2020/02/10 11:50:33 Refreshing state... aws_lambda_function.tfer--get-002D-client
```

**Versions:**

aws-cli/1.17.9 Python/3.7.5 Linux/5.3.0-29-generic botocore/1.14.9

Terraform v0.12.20
+ provider.aws v2.48.0

$terraformer --version
version v0.8.6

**Comment by julian-alarcon** [comment]
I can confirm this!

**Comment by sergeylanzman** [comment]
yes, it's by design https://github.com/GoogleCloudPlatform/terraformer/pull/263 
Maybe ugly, but we has many problem with name of resources.
I be happy for better solution.

**Comment by ppmag** [comment]
> yes, it's by design #263
It would be great to document this in some way.

**Comment by julian-alarcon** [comment]
This is similar to the points converted to other characters. If this is by design, this bug should be changed to add documentation about this behavior.
