### ISSUE TITLE
"all" build is missing in 0.8.6

### ISSUE THREAD

**Issue by sjourdan** [GoogleCloudPlatform/terraformer#387]
Hi, 

Until v0.8.5, an "all" build was made available in the releases (with all the supported providers built-in), ie.: `https://github.com/GoogleCloudPlatform/terraformer/releases/download/0.8.5/terraformer-all-linux-amd64`

It's not the case anymore for v0.8.6: is this just a temporary missing build or is it a decision on your side to not build it? 

Thanks! 

Kind regards,
Stephane

**Comment by sergeylanzman** [comment]
bug...
Fixed uploaded

Thanks!
