### ISSUE TITLE
AWS Lambda not supported service message

### ISSUE THREAD

**Issue by rduart** [GoogleCloudPlatform/terraformer#390]
Would anyone have any idea why AWS Lambda is giving the following error message?

> terraformer import aws --resources=lambda --regions=us-west-2 
2020/02/13 17:28:39 aws importing region us-west-2
2020/02/13 17:28:39 aws importing... lambda
2020/02/13 17:28:39 aws: lambda not supported service

I am using
> terraformer version
Terraformer v0.8.5
 
and

> terraform version
Terraform v0.12.18
+ provider.aws v2.25.0

and 
aws --version
aws-cli/1.16.102 Python/2.7.16 Linux/4.14.154-99.181.amzn1.x86_64 botocore/1.12.92

thanks

**Comment by meshuga** [comment]
AWS Lambda support was introduced in Terraformer v0.8.6 - https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.6
