### ISSUE TITLE
DATADOG: allow filtering using dd tags

### ISSUE THREAD

**Issue by pratikmallya** [GoogleCloudPlatform/terraformer#392]
Many enterprises have shared datadog accounts; teams generally differentiate their resources with the help of tags. Allow using tags to specify the resources required.

e.g. a team `sre` might have the tags `team:sre` on their datadog resources monitoring their services. This team should be able to import all of their resources using:

```
terraformer import datadog --resources=synthetics --filter=tags=team:sre
```

**Comment by meshuga** [comment]
@pratikmallya Can you try adding the following filter param:
`--filter=Name=tags;Value='team:sre'`?
That should be a quick workable solution.

**Comment by pratikmallya** [comment]
This worked perfectly, thanks so much @meshuga !
