### ISSUE TITLE
DATADOG: synthetics: assertions not using valid tf0.12 syntax

### ISSUE THREAD

**Issue by pratikmallya** [GoogleCloudPlatform/terraformer#393]
After generating code for datadog synthetics, I see the following error:

```
Error: Unsupported block type

  on synthetics_test.tf line 2, in resource "datadog_synthetics_test" "tfer--synthetics_3my-002D-8ah-002D-t7c":
   2:   assertions {

Blocks of type "assertions" are not expected here. Did you mean to define
argument "assertions"? If so, use the equals sign to assign it a value.

```

My terraform version is 0.12.20:
```
terraform version
Terraform v0.12.20
+ provider.datadog v2.7.0
```

I believe the solution is to fix the generator to output an array instead of blocks

**Comment by pratikmallya** [comment]
I did a bit of digging and it appears that its the result of the `hcl Parser` used is currently hclv1: https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/hcl.go#L29. I imagine upgrading it to v2 might fix the issue; but it appears that hclv2 exposes a very different interface. Going to stop looking at this for now, but this makes it hard to use terraformer for any resources that have nested attributes (guessing that this issue isn't scoped just to this resource)

**Comment by meshuga** [comment]
@pratikmallya That's a general problem with Terraform - they don't provide much tools to work with HCL2 - V2 doesn't currently provide any parser (see hashicorp/hcl#294), so we must rely on a series of hacks to make things working and that's an approach that even TF devs are following.

Fortunately, TF v0.12 provides an option to export files in JSON format. Terraformer can output data in that format by adding a parameter `--output=json`. I understand it's not an ideal solution to your problem but might work for you.

**Comment by sergeylanzman** [comment]
@pratikmallya can you provide generate tf code and expected?

**Comment by pratikmallya** [comment]
e.g. the generated tf looks like:

```hcl
resource "datadog_synthetics_test" "tfer--synthetics_3my-002D-8ah-002D-t7c" {
  assertions {
    operator = "is"
    target   = "200"
    type     = "statusCode"
  }

  assertions {
    operator = "lessThan"
    target   = "2000"
    type     = "responseTime"
  }

  locations = ["aws:us-west-1", "aws:ap-northeast-1"]
  message   = "<REDACTED>"
  name      = "<REDACTED>"

  options = {
    min_failure_duration = "0"
    min_location_failed  = "1"
    tick_every           = "300"
  }

  request = {
    method  = "GET"
    port    = "443"
    timeout = "30"
    url     = "https://<APPURL>"
  }

  request_headers = {
    Content-Type = "application/json"
  }

  status  = "live"
  subtype = "http"
  tags    = ["app:<APPNAME>", "team:<TEAMNAME>"]
  type    = "api"
}
```

What tf012 expects is for `assertions` to be an array i.e.

```hcl
assertions = [{
    operator = "is"
    target   = "200"
    type     = "statusCode"
  }, 
{
    operator = "lessThan"
    target   = "2000"
    type     = "responseTime"
  }]
```
