### ISSUE TITLE
Google: error importing instances created by GKE

### ISSUE THREAD

**Issue by pratikmallya** [GoogleCloudPlatform/terraformer#399]
Seeing this error trying to import instances created by GKE: (1668c152b3c558cedaf24641b0f3e1fdb4a1983a)
```
$ terraformer import google --resources=instances --projects=<p1> --regions=<r1>

2020/02/18 00:03:39 error formatting HCL: At 133:153: illegal char
```

looking at line 133:
```
133|       configure-sh = "#!/usr/bin/env bash\n\n# Copyright 2016 The Kubernetes Authors.\n#\n# Licensed under ....
```

**Comment by sergeylanzman** [comment]
Know issue
options:
1. Skip GKE instances. You really cannot manage single GKE instance with terraform
2. Convert configurate-sh(and other sh tags) to base64 and use `base64decode` for decode

WDYF?

**Comment by pratikmallya** [comment]
(1) seems ideal; I agree completely that we shouldn't be managing individual GKE nodes with terraform; the node pool and cluster resources are sufficient for that

**Comment by sergeylanzman** [comment]
fixed
