### ISSUE TITLE
error parsing terraform json: <big number>:<huge number>: illegal char escape

### ISSUE THREAD

**Issue by rulatir** [GoogleCloudPlatform/terraformer#406]
An error message like this is printed when terraformer fails to parse terraform's JSON response. Could this message contain a fragment of the context around the error location in the JSON response, so that one might have a chance of figuring out what the problem is?

**Comment by sergeylanzman** [comment]
Can you provide example?

**Comment by rulatir** [comment]
I'm not really invested in this anymore, but I optimistically believe that there is ultimately a single subroutine responsible for parsing terraform's response, and that subroutine can be modified to include a few lines of context in the error message thrown when there is a parse error. I don't think any example is necessary.
