### ISSUE TITLE
Default IgnoreKeys regexps don't match flattened keys in InstanceState.attributes

### ISSUE THREAD

**Issue by rulatir** [GoogleCloudPlatform/terraformer#425]
The default simple regexps that initially appear in the `IgnoreKeys` arrays in plan.json don't match "flattened" keys in `InstanceState.attributes`. This results in undesired/illegal properties ending up in HCL, like the `outputs` property of `aws_cloudformation_stack`.

When a key can hold an array or object, the regexp should be something like `^keyname(?:\..*)?$`.

**Comment by meshuga** [comment]
FYI #432 fixed the undesired property in the CF stack.
I agree it would be nice to have support for regexps in that place although that would be a breaking change, so all current keys should be reviewed.
