### ISSUE TITLE
AWS: Unable to import AWS managed policies

### ISSUE THREAD

**Issue by Juice178** [GoogleCloudPlatform/terraformer#427]
# Summary
 AWS managed policies such as AmazonS3FullAccess can not be imported with the following command (customer managed policies and inline policies are imported successfully).
```
$terraformer import aws --resources=iam
```
# Version Information
```
$ terraformer version
Terraformer v0.8.6
```

Is this an expected behavior or is there any option to import AWS managed policies?

**Comment by rulatir** [comment]
I noticed that too, but I think those policies are precisely "AWS managed", which means they are not "managed by you". They are set in stone and their content is predefined. Do you want to import them just for reference?

**Comment by meshuga** [comment]
That's true @rulatir  - we do import only entities that are managed within a given account. Otherwise we'd end up with hundreds resources that only make the import files less readable.

**Comment by Juice178** [comment]
Thank you for your comments.  @rulatir I just wanted to managed all policies attached to at least one entity with Terraform. In this way, I can attached policies to entities in tf files, not in AWS console onwards.
@meshuga That's true. It may not be a good practice because of the less readability ....

**Comment by sergeylanzman** [comment]
AWS has many build-in policies, You can't change them or delete them. One option use them in terraform it's only for connect to your resources.
it's by design. Here https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/iam.go#L247-L249
You can delete this `if` and try how it's  less readability...
