### ISSUE TITLE
 query: kubernetes import, is it possible to filter just based on namespace?

### ISSUE THREAD

**Issue by russ-te2** [GoogleCloudPlatform/terraformer#428]
attempting to import a subset of resources restricted by namespace on a cluster with multiple
namespaces, not sure if this is possible.

**Comment by meshuga** [comment]
@russ-te2 According to [1], every resource contains a namespace under path `metadata.namespace`. You should be able to filter and get resources that you only want to have by applying a parameter: `--filter="Name=metadata.namespace;Value=your.namespace.label"` with namespace of resources you want to get.

[1] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata

**Comment by russ-te2** [comment]
Thanks a lot for the suggestion, this didn't seem to work though. :(

**Comment by maps90** [comment]
any update on this ?

**Comment by maps90** [comment]
I already tried 
```terraformer import kubernetes --resources=deployments,services,storageclasses --filter=kubernetes_namespace=name1:name2:name3```

as suggested in https://github.com/GoogleCloudPlatform/terraformer#use-with-kubernetes but no luck

my terraformer version: v0.8.7

**Comment by rmenn** [comment]
this works, in importing the resources with a filter for the exact namespace

```
terraformer import kubernetes --resources=deployments,services,configmaps --filter="Name=metadata.namespace;Value=kube-system"
```

If you further want to add a filter for a particular resource you can use the type to specify for each resource.  

```
terraformer import kubernetes --resources=deployments,services,configmaps --filter="Type=kubernetes_deployment;Name=metadata.name;Value=yourdeploymentsname,Type=kubernetes_service;Name=metadata.namespace;Value=kube-system"
```

The above should import a deployment named `yourdeploymentsname`, all the services from the `kube-system` namespace and all the configmaps ( since there is no filter ) 

Hope this helps
