### ISSUE TITLE
Access denied for aws import

### ISSUE THREAD

**Issue by dimisjim** [GoogleCloudPlatform/terraformer#45]
Hey there,

I am trying to test this cool tool to import some aws resources into our tf project.
Problem is, we are using cross account assumed roles, with 2FA enabled. For example, my ~/.aws/credentials file looks like this:

```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[profile1]
role_arn = arn:aws:iam::<account-id-1>:role/<role-name-1>
source_profile = default
mfa_serial = arn:aws:iam::<central-account-id>:mfa/<my-username>

[profile2]
role_arn = arn:aws:iam::<account-id-2>:role/<role-name-2>
source_profile = default
mfa_serial = arn:aws:iam::<central-account-id>:mfa/<my-username>
```

so when trying to import s3 buckets, with this commands: `terraformer import aws --resources=s3 --connect=true --regions=eu-west-1`
I am getting:
```
2019/05/08 13:13:47 aws importing region eu-west-1
2019/05/08 13:13:47 aws importing... s3
2019/05/08 13:13:47 AccessDenied: Access Denied
	status code: 403, request id: 7164....5B8F351, host id: 7q8nhD6LnVeniWww9arkIcBQX.................NdzDgMCNBhC610MZM=
```

Ismy cross-account setup currently supported by terraformer?

**Comment by sergeylanzman** [comment]
shared_credentials_file - It's work with terraform as provider configuration, not support today in terraformer
BUT
`shared_credentials_file = (Optional) This is the path to the shared credentials file. If this is not set and a profile is specified, ~/.aws/credentials will be used.`
Try to set in ~/.aws/credentials path to shared_credentials_file

**Comment by sergeylanzman** [comment]
https://github.com/GoogleCloudPlatform/terraformer/issues/1 same

**Comment by shogomuranushi** [comment]
If you want to use assume role, it is recommended to [assume-role](https://github.com/remind101/assume-role).

You can easily use assume role.
```
$ assume-role your_profile terraformer import aws --resources=vpc,subnet --connect=true --regions=eu-west-1
```

**Comment by mohag** [comment]
> If you want to use assume role, it is recommended to [assume-role](https://github.com/remind101/assume-role).
> 
> You can easily use assume role.
> 
> ```
> $ assume-role your_profile terraformer import aws --resources=vpc,subnet --connect=true --regions=eu-west-1
> ```

That still gets the resources from the default profile instead....
