### ISSUE TITLE
Create data source in a provider

### ISSUE THREAD

**Issue by Trois-Six** [GoogleCloudPlatform/terraformer#451]
Hi,

I would like to be able to create data sources instead of resources only in a terraformer provider. In the case of the keycloak provider, when we create a keycloak_realm, keycloak creates automatically some keycloak_openid_clients in the master realm and some keycloak_openid_clients in every realm created.

At the moment, my provider imports all these resources as resources, and it works; but only if they already exist. When I try to apply the resulting terraformer import to a new installation, it doesn't work because I have some conflicts for all these openid_clients, because the new IDs are not equal to the old ones.

In terraform_utils, we only can create NewResource, not NewData... Maybe I could workaround this by using a PostConvertHook and transform some resources in datasources, but I don't think that it would be a good pattern (and what would I do for the tfstate ?).

Regards,

Pierre

**Comment by sergeylanzman** [comment]
Maybe connecting between resources can help you here
See example here https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/aws_provider.go#L49-L139

Terraformer can connect between resources in terraform style `${provider_resource_type.resource_name.id}`

**Comment by Trois-Six** [comment]
Yes I know, I am already doing such connections (https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/keycloak/keycloak_provider.go#L100-L122), but that's not enough, when creating a resource triggers the creation of other resources (with different IDs than the one we had imported).
