### ISSUE TITLE
tfstate version 3, does not merge with tfstate 4

### ISSUE THREAD

**Issue by on3iropolos** [GoogleCloudPlatform/terraformer#455]
When using terraformer (most recent build) to generate a tfstate, it is created in version 3. Then when attempting to merge the tfstate into an existing tfstate (created with version terraform 0.12.24) the versions are incompatible.

Unless I am missing something, the version difference makes it very different to pull existing aws objects into an existing terraform tfstate file.

**Comment by MikePrynAvenga** [comment]
Still actual
