### ISSUE TITLE
S3 bucket support to import state

### ISSUE THREAD

**Issue by Sebor** [GoogleCloudPlatform/terraformer#460]
It would be good to have opportunity to import tftate into S3 bucket.
When I try the command:
--bucket= s3://<bucket_name> --state=bucket
I get the error:
aws upload tfstate to  bucket
23:17:41 Failed to create client: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by sergeylanzman** [comment]
terraformer support today only gcs import state upload.

**Comment by Sebor** [comment]
> 
> 
> terraformer support today only gcs import state upload.

I know that, that's why I wrote "It would be good to have opportunity"

**Comment by rchand21** [comment]
+1 for this

**Comment by srodgers-awaze** [comment]
+1 Bump
