### ISSUE TITLE
Add support for Datadog Metrics / metric_metadata

### ISSUE THREAD

**Issue by PatrykMilewski** [GoogleCloudPlatform/terraformer#465]
This is feature request.

I would like to manage configuration of existing DataDog Metrics, due to this I need to import them from DataDog. 

Terraform DataDog provider supports this resource type already:
https://www.terraform.io/docs/providers/datadog/r/metric_metadata.html

**Comment by PatrykMilewski** [comment]
Isn't it only about adding a new service here:
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/datadog/datadog_provider.go

And copy paste wrapper:
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/datadog/synthetics.go

Of course I would have to change resource names etc.

**Comment by meshuga** [comment]
You're right - just copy and paste with small adjustments is all you need to do.

Once done, an information in https://github.com/GoogleCloudPlatform/terraformer/blob/master/README.md#use-with-datadog must be added for other to know about the newly supported resources.

Say hi to Krzysiek P for me :)

**Comment by PatrykMilewski** [comment]
@meshuga Alright, I have no idea about Go Language and it looks like it won't really change that much after adding this feature 😄 

I did, forwarding greetings back!

**Comment by PatrykMilewski** [comment]
Closing it since I don't need it anymore and I believe it was possible to achieve with newer DataDog API that is already supported with Terraform.
