### ISSUE TITLE
iam_role_policy_attachments/AWS-managed policies-attached-to-roles missing

### ISSUE THREAD

**Issue by blakestoddard** [GoogleCloudPlatform/terraformer#467]
Looks like Terraformer currently doesn't generate configs for non-user-managed policies that are attached to roles, unless I'm doing it wrong (every other IAM resource I expect gets TF configs generated without issue).

I may try my hand at adding support.

**Comment by blakestoddard** [comment]
#427 is related, but that seems to cover policies attached to groups.

**Comment by meshuga** [comment]
You're right, the attachments aren't being added. I tried to add them some time ago but gave up (forgot exactly what was the issue).

**Comment by ksunil6266** [comment]
is there any update for add AWS managed Policy including in IAM roles.

**Comment by ksunil6266** [comment]
I think you miss "iam_role.tf" resource file.
