### ISSUE TITLE
Unknown flag resources

### ISSUE THREAD

**Issue by rzuku** [GoogleCloudPlatform/terraformer#470]
Trying to import no matter if from GCP o r AWS I always have the same error message:
`terraformer import google --resource=google_container_cluster --regions=europe-west1 --project=my-project
2020/04/10 10:02:44 unknown flag: --resource
`
The version I have is as follows. 
`terraformer --version
version v0.8.7
`
The same exactly message I have for aws.

**Comment by meshuga** [comment]
Related issue #364

**Comment by meshuga** [comment]
@rzuku Can you write which file in https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.7 did you download?
I can execute command `terraformer-aws-darwin-amd64 import aws --resources=vpc,subnet --connect=true --regions=eu-west-1` with `terraformer-aws-darwin-amd64` file.

**Comment by rzuku** [comment]
I did it as in the installation instructions:

> export PROVIDER={all,google,aws,kubernetes}
> 
> curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-linux-amd64
> 
> chmod +x terraformer-${PROVIDER}-linux-amd64
> sudo mv terraformer-${PROVIDER}-linux-amd64 /usr/local/bin/terraformer```

**Comment by meshuga** [comment]
Thanks! In line `export PROVIDER={all,google,aws,kubernetes}`, what value did you choose?

**Comment by rzuku** [comment]
I tried with `all` and `google` and I have the same for both cases.

**Comment by rzuku** [comment]
For all & linux and version 0.8.4 I have exactly the same.

**Comment by sergeylanzman** [comment]
I tried now all/google/aws for mac and it's working. I try find issue with linux binary.
Any way it's look like bug in build process for release and not code. 

Try build from master or from tag on your machine it's working.

**Comment by dfoley3118** [comment]
Did you get this resolved? I am having the same issue

**Comment by rzuku** [comment]
i have built that from sources.

**Comment by ayush--s** [comment]
the latest release has this bug
```
$> terraformer import cloudflare --resources=firewall,dns
2020/08/20 22:00:56 unknown flag: --resources

$> terraformer --version
version v0.8.8

```

workaround: a fresh build from master branch worked for me

**Comment by peterduchnovsky** [comment]
Hey, is this going to get fixed any time soon ? From what I gather this bug is there since 0.8.4 which means last 5 releases are affected ?

**Comment by TriplEight** [comment]
Also crossed it, v 0.8.8, Ubuntu 20.04

**Comment by tetsuya0617** [comment]
I got the same issue with v0.8.9, mac

**Comment by meshuga** [comment]
It's hard to find it, I cannot reproduce it.

**Comment by tetsuya0617** [comment]
When I installed it following the instruction with go, it worked, but when I installed it with brew, I got the same error as this issue.

**Comment by meshuga** [comment]
That's somehow concerning. That's okay `--resource` parameter won't work as it's supposed to be a plural word `resources` that should be used. That why the original issue was throwing error, because `terraformer import google --resource=google_container_cluster --regions=europe-west1 --project=my-project` uses `--resource` (apart from that, `projects` parameter should be used instead of `project`).

I just installed terraformer 0.8.9 with brew (mac os, 11.0.1) and issued command `import cloudflare --resources=firewall,dns`, which was working well. Same with corrected google provider parameters - everything is working well.

**Comment by tetsuya0617** [comment]
Thank you for checking it but unfortunately, I can not solve it yet. 
I executed the installation of the terraformer again following the two way with brew command and go command. 

>When I installed it following the instruction with go

I tried to install it with the go command again but I got the same error. 

> That's somehow concerning. That's okay --resource parameter won't work as it's supposed to be a plural word resources that should be used

I thought that the typo happened when he was writing this issue.
Even in the case of the command with `--resources`, the same error occurred like this below. 

```
$ go version
go version go1.15.4 darwin/amd64

$ brew -v
Homebrew 2.5.10

$ terraformer -v
version v0.8.9

$ terraformer plan google --resources=gke
 unknown flag: --resources

$ terraformer import google --resources=gke
 unknown flag: --resources
```
I got the same above error by the installation with brew (mac os, 10.14.6) command and go command.

**Comment by tetsuya0617** [comment]
UPDATE:
```
$cd /usr/local/bin 
$rm -rf terraformer
```
Then, I re-installed terraformer with `curl command `and finally, it worked well.

**Comment by ehillhd** [comment]
@tetsuya0617 - I'm also running into the same issue. Perhaps you enlighten us with the steps and logic used when you re-installed terraformer with `curl` please?

**Comment by tetsuya0617** [comment]
@ehillhd 

This is written in README. 
```
export PROVIDER={all,google,aws,kubernetes}
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64
chmod +x terraformer-${PROVIDER}-darwin-amd64
sudo mv terraformer-${PROVIDER}-darwin-amd64 /usr/local/bin/terraformer
```

**Comment by sergeylanzman** [comment]
Can you check this issue in 0.8.10?

**Comment by OmarEltamasehy** [comment]
I have the same issue with terraformer version 0.8.10

**Comment by grayside** [comment]
I also encountered this, I started with the curl command as written and got further by re-running with `export PROVIDER=google`.

**Comment by rymnc** [comment]
I have the same issue with the latest build, 0.8.15

**Comment by tendai-lino** [comment]
initially worked for  me with version 0.8.15 now having the same issue on all my subsequent installations

**Comment by jmaybe** [comment]
I had the same issue today. What I did was the following:

`rm /usr/local/bin/terraformer #get rid of problematic install`

Moved back to home dir and ran the original curl command from instructions after modifying it to match only the provider that I needed, i.e.,

`
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-linux-amd64
chmod +x terraformer-aws-linux-amd64
sudo mv terraformer-aws-linux-amd64 /usr/local/bin/terraformer`

Ended up being the same version (for me at this point 0.8.15), but the --resources flag worked this time. The command I ran was as follows:

`terraformer import aws --resources=route53`

I wanted to capture some global information first before targeting individual regions. Worked like a charm.

**Comment by diomalta** [comment]
Install separated plugins is working

```
curl -LO https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-aws-linux-amd64

chmod +x terraformer-aws-linux-amd64

sudo mv terraformer-aws-linux-amd64 /usr/local/bin/terraformer
```

**Comment by 10dip** [comment]
Hello 
I am still facing this issue on Windows. Any suggestions ?

**Comment by guysaarTikal** [comment]
Im running on mac, rm /usr/local/bin/terraformer and than brew install terraformer 
solved the issue for me

**Comment by MaffooBristol** [comment]
For me it seems to be the brace expansion side of things causing issues. When I installed on linux with `PROVIDER={all,aws,google,kubernetes}` the commands ran super quickly and I got the above error. But if I do it just as `PROVIDER=aws` and then run the rest of the commands again, it takes a while downloading 150MB or so of the file and then the commands work fine.

**Comment by priyanshur-curefit** [comment]
I am again facing this issue.
I tried :
`export` PROVIDER=aws
curl -LO "https://github.com/GoogleCloudPlatform/terraformer/releases/download/$(curl -s https://api.github.com/repos/GoogleCloudPlatform/terraformer/releases/latest | grep tag_name | cut -d '"' -f 4)/terraformer-${PROVIDER}-darwin-amd64"
chmod +x terraformer-${PROVIDER}-darwin-amd64`
