### ISSUE TITLE
Add docker way use terraformer

### ISSUE THREAD

**Issue by sergeylanzman** [GoogleCloudPlatform/terraformer#471]
* Dockerfile include terraformer version with all providers
* Script install providers on start container
* Manual in README about docker run command, include volume mounts for outputs, credentials and etc.

**Comment by meshuga** [comment]
Good idea, that’d simplify the tool usage for people without much knowledge on terraform

**Comment by bryanasdev000** [comment]
This tool has helped me a lot in the past, I will attack this issue. 

If desired, one can check my progress here: [https://github.com/bryanasdev000/terraformer](fork)

**Comment by sergeylanzman** [comment]
@bryanasdev000 Thanks!

**Comment by bryanasdev000** [comment]
Hey, guys!

This and what I have so far:

`Dockerfile`
```
FROM alpine:3.12.0 
RUN apk add --no-cache go git
RUN git clone https://github.com/GoogleCloudPlatform/terraformer /root/terraformer
RUN cd /root/terraformer && go mod download && go build -v 

FROM alpine:3.12.0 
COPY --from=0 /root/terraformer/terraformer /root
RUN apk add --no-cache terraform
COPY OfficialProviders.tf /root
RUN cd /root && terraform init
WORKDIR /root/
```
`OfficialProviders.tf `
```
provider "google" {}
provider "rabbitmq" {}
provider "cloudflare" {}
provider "github" {}
provider "datadog" {}
provider "newrelic" {}
provider "digitalocean" {}
provider "fastly" {}
provider "heroku" {}
provider "linode" {}
provider "ns1" {}
provider "openstack" {}
provider "vultr" {}
provider "kubernetes" {}
provider "aws" {}
```
I'm looking now at the unofficial providers, but I would like to hit some points.

Will we always use the master branch? Shall we embed providers in the image? If so it will be relatively large as this one is already with `904MB`.

To use the container I was thinking of something like:

`docker container run -v $PWD:/root --rm terraformer terraformer import google --resources=gcs,forwardingRules,httpHealthChecks --connect=true --regions=europe-west1,europe-west4 --projects=aaa,fff
`

For the credentials I am still thinking but I will probably follow the standard behavior of Terraform, open the necessary variables in the container for providers that use variables and for others like GCP that need the file, put it in the same folder that will run the import.

I apologize for the delay, I'm having a lot of internet outages here.

**Comment by peterHoburg** [comment]
@bryanasdev000 I have been messing around with getting terraformer working in docker using what you posted as a starting point. 2 issues I have run into when using what you purposed are:

1. Terraformer will not be on the PATH if placed in `/root. I added `ENV PATH=$PATH:/root:` to the end of my Dockerfile to fix this
2. When mounting $PWD to the `/root`, $PWD will overwrite the terraformer and terraform plugins installed in previous steps. To solve this, I changed the mount to `-v $PWD/output:/opt` and changed the output directory of terraformer with `-o "/opt"`.

I went with the simple solution for gcloud creds and just mounted my gcloud config dir and pointed gcloud to the correct credential dir inside the docker file. This is not a good general solution, but it does work for GCP. 

My docker build/run ended up looking like 
```
docker build -t terraformer .
docker run -v $PWD/output:/opt -v ~/.config/gcloud:/root/.config/gcloud/ \
  -e GOOGLE_APPLICATION_CREDENTIALS="/root/.config/gcloud/creds.json" \
  --rm terraformer terraformer import google --resources=bigQuery --connect=true --regions=us-central1 --projects=aaa \
  -o "/opt"
```

And my Dockerfile:
```
FROM alpine:3.12.0
RUN apk add --no-cache go git
RUN git clone https://github.com/GoogleCloudPlatform/terraformer /root/terraformer
RUN cd /root/terraformer && go mod download && go build -v

FROM alpine:3.12.0
COPY --from=0 /root/terraformer/terraformer /root
RUN apk add --no-cache terraform
COPY OfficialProviders.tf /root
RUN cd /root && terraform init
WORKDIR /root/

#Added this to fix the path
ENV PATH=$PATH:/root:
```

**Comment by bryanasdev000** [comment]
> @bryanasdev000 I have been messing around with getting terraformer working in docker using what you posted as a starting point. 2 issues I have run into when using what you purposed are:
> 
> 1. Terraformer will not be on the PATH if placed in `/root.` I added `ENV PATH=$PATH:/root:` to the end of my Dockerfile to fix this
> 2. When mounting $PWD to the `/root`, $PWD will overwrite the terraformer and terraform plugins installed in previous steps. To solve this, I changed the mount to `-v $PWD/output:/opt` and changed the output directory of terraformer in the docker run with `-o "/opt"`.
> 
> I went with the simple solution for gcloud creds and just mounted my gcloud config dir and pointed gcloud to the correct credential dir inside the docker file. This is not a good general solution, but it does work for GCP.
> 
> My docker build/run ended up looking like
> 
> ```
> docker build -t terraformer .
> docker run -v $PWD/output:/opt -v ~/.config/gcloud:/root/.config/gcloud/ \
>   -e GOOGLE_APPLICATION_CREDENTIALS="/root/.config/gcloud/creds.json" \
>   --rm terraformer terraformer import google --resources=bigQuery --connect=true --regions=us-central1 --projects=aaa \
>   -o "/opt"
> ```
> 
> And my Dockerfile:
> 
> ```
> FROM alpine:3.12.0
> RUN apk add --no-cache go git
> RUN git clone https://github.com/GoogleCloudPlatform/terraformer /root/terraformer
> RUN cd /root/terraformer && go mod download && go build -v
> 
> FROM alpine:3.12.0
> COPY --from=0 /root/terraformer/terraformer /root
> RUN apk add --no-cache terraform
> COPY OfficialProviders.tf /root
> RUN cd /root && terraform init
> WORKDIR /root/
> 
> #Added this to fix the path
> ENV PATH=$PATH:/root:
> ```

Thank you for pointing out these problems.
I was too focused on building the container that I forgot basic things.

I was wondering what would be the best way to deal with providers in this case, I don't think the image should have a little more than 1GB just to accommodate official providers, people with unreliable internet will have problems using it.

**Comment by bryanasdev000** [comment]
Guys, v0.13 of Terraform open some ways to use and mirror providers, for example, we can provide a way do mount the `~/.terraform.d/` inside the container and only provide the basic inside the container. No more 1GB images :smile: .

Doc: https://www.terraform.io/upgrade-guides/0-13.html#new-filesystem-layout-for-local-copies-of-providers

**Comment by Haddox19** [comment]
Hello, I am following up that I have attempted to put terraformer in a docker image alongside of terraform using Alpine as the base image. Alpine is unable to run terraformer, installing terraformer in ubuntu worked no problems. I was using: https://github.com/GoogleCloudPlatform/terraformer/releases/download/0.8.22/terraformer-aws-linux-amd64

**Comment by fahadysf** [comment]
@Haddox19 Can you share a Dockerfile for this?
