### ISSUE TITLE
support for vmware

### ISSUE THREAD

**Issue by thatsk** [GoogleCloudPlatform/terraformer#485]

**Comment by AssafKatz3** [comment]
Hi,
Both vSphere and VCD will be very welcomed.
Thanks

**Comment by eizedev** [comment]
It would be ingenious if the [terraform-provider-vsphere](https://github.com/hashicorp/terraform-provider-vsphere) would be supported. Do you by chance already have a status there?

[Import documentation provider-vsphere](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine)  

Thanks

**Comment by eizedev** [comment]
Andy news on this?

**Comment by AssafKatz3** [comment]
Hi,
We still need it.
Thanks

**Comment by AssafKatz3** [comment]
Any news about it?

**Comment by meshuga** [comment]
Actually, I might have soon time to focus on support for that provider, around Sep/Oct

**Comment by clementbernet** [comment]
I would be very interested to use this provider too. It's super cool if you're planning to support this Terraform provider.

**Comment by AssafKatz3** [comment]
Any news?

**Comment by mteplyakov** [comment]
+1 for the waiting list)

**Comment by thatsk** [comment]
+1

**Comment by nord3l** [comment]
+1

**Comment by otk1001** [comment]
+100500

**Comment by AssafKatz3** [comment]
Still waiting:-)

**Comment by seryeb** [comment]
+1

**Comment by miconx** [comment]
+1

**Comment by tonysummerfelt** [comment]
I could have used this  years ago... 

+1

**Comment by kevinbbd** [comment]
This would definitely complement the terraform provider vsphere!

+1

**Comment by shittiidavincii** [comment]
+1

**Comment by AceXintense** [comment]
+1 This would be great to have!

**Comment by Decstasy** [comment]
+1 would be really nice

**Comment by kevinbbd** [comment]
Still waiting, this would be a great feature to have :-)

**Comment by thatsk** [comment]
yup

**Comment by eizedev** [comment]
… news? Closed using the stale action, great…
