### ISSUE TITLE
Import of Route53 records does not escape percent symbols

### ISSUE THREAD

**Issue by livingstaccato** [GoogleCloudPlatform/terraformer#499]
Just tried out terraformer for the first time today. Pretty cool.

It does look like it didn't quite get importing all our Route53 records right though. Specifically, our SPF records.

Example of the output of running "terraform state list":
```
Error: Invalid template control keyword

  on route53_record.tf line 1427, in resource "aws_route53_record" "tfer--redacted_email-002E-redacted-002E-org-002E-_TXT_":
1427:   records = ["v=spf1 include:email.redacted.org._nspf.vali.email include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all"]

"i" is not a valid template control keyword. Did you mean "if"?
```

Terraformer would be even cooler if it properly escaped percents for route53 records. :)

Thanks!

**Comment by wellingk** [comment]
I am trying to set a similar record up using terraform it does not work for creation either :-(

**Comment by wellingk** [comment]
p.s found a work around / fix for this.  If you put the spf record in a file spf.py and then use the file syntax to include the record it works file("${path.module}/files/spf.py it works.  Its python syntax this record.  :-)
