### ISSUE TITLE
Terraform apply to notify if reboot needed for any changes that are applied

### ISSUE THREAD

**Issue by suvsap** [GoogleCloudPlatform/terraformer#501]
Hi,

WE recently did some resizing our GCP instances to save cost. This would ideally go for reboot. We have observed that some of our engineers who are new to terraform not aware that the particular change that will be applied will go for reboot. This affected our live client.

Is their any way by which when we do terraform apply and if it requires to reboot the instance for sucessful completion then it should ask before doing reboot?

This change will require reboot. Do you want to proceed? Yes/no

Thanks,
Suvankar

**Comment by sergeylanzman** [comment]
Hey 
You question not relevant to terraformer, but I tring help you.

if you use `google_compute_instance`, by default it's not stop VM for change instance type.
Only if you set `allow_stopping_for_update = true` https://www.terraform.io/docs/providers/google/r/compute_instance.html#allow_stopping_for_update

In any cloud provider change VM size require stop/start of VM.
