### ISSUE TITLE
CloudFunctions importing fails on Permission Denied

### ISSUE THREAD

**Issue by nimrodkor** [GoogleCloudPlatform/terraformer#507]
I'm using credentials for an owner service account. I import gcs, pubsub etc successfully, but I keep receiving this error on cloudFunctions:
```
2020/05/20 23:56:51 google importing... cloudFunctions
2020/05/20 23:56:51 googleapi: Error 403: Permission denied on 'locations/' (or it may not exist), forbidden
```
Any idea why the API broke?

**Comment by sean-ersw** [comment]
Me too

**Comment by sergeylanzman** [comment]
I checked and it's worked with this command `terraformer import google -r cloudFunctions  --projects test-p --regions europe-west1`
I got some error if not provide `--regions`

**Comment by dmedora** [comment]
To add to sergeylanzman's comment, Cloud Functions are a [region-specific resource](https://cloud.google.com/functions/docs/locations), whereas `--regions` defaults to `global`, resulting in this error.

**Comment by Goryudyuma** [comment]
I also encountered the same problem
The solution was not to specify "region"
The solution was to enable the "Compute Engine API"

https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/gcp_provider.go#L54
I was getting an error here, but the error was not handled correctly
As a result, the default "general" is specified.

Please handle the error correctly
Or write somewhere in the documentation that you need to enable the "Compute Engine API"
Should I set up a separate issue?

**Comment by erickertz** [comment]
> I also encountered the same problem
> The solution was not to specify "region"
> The solution was to enable the "Compute Engine API"
> 
> https://github.com/GoogleCloudPlatform/terraformer/blob/b5ec1bfeac946ff62d378831335571b0aae6d071/providers/gcp/gcp_provider.go#L54
> 
> 
> I was getting an error here, but the error was not handled correctly
> As a result, the default "general" is specified.
> Please handle the error correctly
> Or write somewhere in the documentation that you need to enable the "Compute Engine API"
> Should I set up a separate issue?

OMG Thank you so much for posting this. It was driving me nuts trying to figure it out!
