### ISSUE TITLE
Can't get AWS resource filter to work

### ISSUE THREAD

**Issue by chrisgallivan** [GoogleCloudPlatform/terraformer#521]
I run this command and it isn't working. It pulls down files with minimal content (no definitions).

terraformer import aws --resources=lambda --profile=test --filter=aws_lambda_function=tfer--lambda-002D-demo-002D-kms

Here is a snippet of the resource definition:

resource "aws_lambda_function" "tfer--lambda-002D-demo-002D-kms" {

I want to be able to allow the user to specify a specific resource ids and only pull for those ids

**Comment by meshuga** [comment]
_tfer--lambda-002D-demo-002D-kms_ is a resource name, not its identifier. The resource identifier for Lambda function is its name [1] but the thing is Terraformer is using ARN for a function identifier [2].That is something to be fixed.

In the meantime, you still should be able to filter resources by its field `--filter="Name=name;Value=lambda-demo-kms"`

[1] https://www.terraform.io/docs/providers/aws/r/lambda_function.html#import
[2] https://github.com/GoogleCloudPlatform/terraformer/blob/25a1f37c2cddb3a53d5d167f2635406e68e4bccd/providers/aws/lambda.go#L77

**Comment by chrisgallivan** [comment]
i think the filters aren't working for me on any AWS resource. I don't think it's specific to lambda.

Here is my adjusted command and resulting output. It is pulling all the lambdas:

devusr@4e2f7408ffb0:/clocal$ terraformer import aws --resources=lambda --regions=us-east-2 --profile=test --filter="Name=name;Value=lambda
-demo-kms" --compact=true                                                                                                                 
2020/06/03 14:53:12 aws importing region us-east-2                                                                                        
2020/06/03 14:53:12 aws importing... lambda                                                                                               
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--api-002D-example-002D-root-002D-get                                     
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--api-002D-example-002D-houses-002D-get                                   
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--Lambda-002D-list-002D-buckets-002D-xray                                 
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--hello-002D-world                                                        
2020/06/03 14:53:37 Refreshing state... aws_lambda_function_event_invoke_config.tfer--feic_arn-003A-aws-003A-lambda-003A-us-002D-east-002D
-2-003A-909371103522-003A-function-003A-hello-002D-world-003A--0024-LATEST                                                                
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--lambda-002D-demo-002D-kms                                               
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--hello-002D-world-002D-ssm                                               
2020/06/03 14:53:37 Refreshing state... aws_lambda_function.tfer--dynamo-002D-db-002D-stream-002D-test                                    
2020/06/03 14:53:37 Refreshing state... aws_lambda_event_source_mapping.tfer--e4cb0798-002D-1977-002D-48ac-002D-8160-002D-1a5da4e70d90    
2020/06/03 14:53:38 aws Connecting....                                                                                                    
2020/06/03 14:53:38 aws save lambda                                                                                                       
2020/06/03 14:53:38 aws save tfstate for lambda                                                                                           
devusr@4e2f7408ffb0:/clocal$ ls

**Comment by chrisgallivan** [comment]
i should note nothing is being saved in the tf files when i use the --filter flag.

**Comment by chrisgallivan** [comment]
it works without the --filter flag.

**Comment by chrisgallivan** [comment]
This worked for lambda:

terraformer import aws --resources=lambda --regions=us-east-2 --profile=test --filter="Name=function_name;Value=lambda-demo-kms" --compact=true

**Comment by meshuga** [comment]
You should be able to provide multiple filter expressions with a comma separator (I wonder if providing multiple `--filter=...` would work as well 🤔). All filters are _AND_, so will filter out resources that do not match given criteria but you can narrow the search criteria.

For Lambda functions filtering, you can make use of tags and assign a tag projects=valuable to the functions. Then, I think the following filter expression should work: `--filter=Type=lambda;Name=tags.project;Value=valuable,Type=s3;Name= bucket;Value=my-tf-test-bucket`.

A thing to stress, I've never tested multiple such attribute level filter expressions before.

**Comment by chrisgallivan** [comment]
I've only been able to get it to work with a single filter. Tried numerous permutations to try to get multiple filters to work, nothing has worked so far.

**Comment by chrisgallivan** [comment]
I was able to get multiple clauses to work with the comma separator.

The type for lambda is aws_lambda_function. Your example said lambda, and this is why it wasn’t working

**Comment by chrisgallivan** [comment]
S3 is aws_s3_bucket

**Comment by meshuga** [comment]
Sorry for the mistake. I need to adjust the documentation

**Comment by chrisgallivan** [comment]
it works

**Comment by gfrankel97** [comment]
I really think this need to be included in the documentation. There is no mention of being able to have multiple filters, no mention of being able to use a comma separator (granted, it is obvious in hindsight). Please include this functionality in the docs. Once I found this issue, Terraformer works like a charm. Thanks for all the hard work put into this.
