### ISSUE TITLE
NS1 Support

### ISSUE THREAD

**Issue by nitrocode** [GoogleCloudPlatform/terraformer#522]
Ticket for someone or myself in the future to add [NS1](https://ns1.com/) support

> The NS1 provider exposes resources to interact with the NS1 REST API. The provider needs to be configured with the proper credentials before it can be used. Note also that for a given resource to function, the API key used must have the corresponding permissions set.

https://www.terraform.io/docs/providers/ns1/index.html

Should be able to export

* zones
* records
* monitoring jobs
* notify lists
* datasources
* datafeeds
* apikeys ?
* teams
* users

https://github.com/ns1/ns1-go

To create a new provider

* Add new directory to `providers/`
* ns1 requires an API key so the [newrelic_service.go](https://github.com/GoogleCloudPlatform/terraformer/blob/5c8c660ef3e3f8a4bc03e92ee4274f667a6f91ad/providers/newrelic/newrelic_service.go) can be used as an example

**Comment by chenrui333** [comment]
Added some initial support per #527, 

- `ns1_user` resource, created an issue in the golang lib, https://github.com/ns1/ns1-go/issues/103
- `ns1_notifylist`, there is no golang lib support for importing the resouce?
- `ns1_ datasource`, there is no golang lib support for importing the resouce?
- `ns1_ datafeed`, there is no golang lib support for importing the resouce?

Have some weird issue reverse record resource, I could use the golang lib, but somehow could not get terraformer work for it.

**Comment by nitrocode** [comment]
@chenrui333 I just want to say thank you for putting in some support for the ns1 provider.

Looks like my monitoring jobs were imported correctly but my `ns1_zone` resources have `zone` arguments like `asdjasldjasldas239448329042309`. I believe these should be reserved for the `id` argument. If I run 

```
cd generated/zone
terraform plan
```

It seems to fail after terraformer generates the values.

If I manually create a `ns1_zone` and import it.

```
resource "ns1_zone" "example" {
  zone = "terraform.example.io"
  ttl  = 600
}
```

Then run 

```
terraform import ns1_zone.example snip.com
terraform plan
```

```
-/+ resource "ns1_zone" "example" {
        autogenerate_ns_record = true
      ~ dns_servers            = "snip" -> (known after apply)
      ~ dnssec                 = snip -> (known after apply)
      ~ expiry                 = snip -> (known after apply)
      ~ hostmaster             = "snip" -> (known after apply)
      ~ id                     = "asdjasldjasldas239448329042309" -> (known after apply)
      ~ networks               = [
          - 0,
        ] -> (known after apply)
      ~ nx_ttl                 = snip -> (known after apply)
      ~ refresh                = snip -> (known after apply)
      ~ retry                  = snip -> (known after apply)
      ~ ttl                    = snip -> snip
      ~ zone                   = "snip" -> "terraform.example.io" # forces replacement
    }
```

**Comment by nitrocode** [comment]
@sergeylanzman why close this ticket? Initial support has been done but hasn't been fully implemented. 

Are you advising to create a separate ticket for this?
