### ISSUE TITLE
[google] GCE instances and instanceGroups import issue

### ISSUE THREAD

**Issue by dmedora** [GoogleCloudPlatform/terraformer#528]
Provider: Google
When trying to import the `instances` and `instanceGroups` resources, nothing is generated, despite these resources existing in the target project.

```
google importing project terratest-proj region global
google importing... instances
google importing... instanceGroups
google Connecting.... 
google save 
google save tfstate
```

**Comment by dmedora** [comment]
It seems that this works fine as long as a region is specified. Is this working as intended for `--regions=global`? Is there a way to include all regions? Thanks!

**Comment by sergeylanzman** [comment]
no, it's by regions. Because `instanceGroups` in GCP it's region object

**Comment by dmedora** [comment]
Got it, no issues then, thanks for the quick follow-up!
