### ISSUE TITLE
AWS IAM Policy with erroneous control character yields corrupted policy resource

### ISSUE THREAD

**Issue by danopia** [GoogleCloudPlatform/terraformer#534]
This issue is something no one should come across but it should also be pretty easy to reproduce:

One of the policies in a generated `iam_policy.tf` was overly escaped with lots of backslashes, and also includes an incorrect escape near the end which `terraform plan` crashed at:

```terraform
  policy = <<POLICY
{
    \"Version\": \"2012-10-17\",
    \"Statement\": [
        {
            \"Sid\": \"VisualEditor0\",
            \"Effect\": \"Allow\",
            \"Action\": [
                \"sqs:DeleteMessage\",
                \"sqs:ReceiveMessage\"
            ],
            \"Resource\": \"arn:aws:sqs:eu-west-1:redacted:commands.fifo\\"
        }
    ]
}
POLICY
```

```
$ terraform plan

Error: "policy" contains an invalid JSON: invalid character '\\' looking for beginning of object key string

  on iam_policy.tf line 2680, in resource "aws_iam_policy" "redacted":
2680: resource "aws_iam_policy" "redacted" {
```

Turns out there is actually a tab character in the real IAM policy there:

![Screenshot 2020-06-18 at 16 40 20](https://user-images.githubusercontent.com/40628/85035243-3c605600-b183-11ea-91b6-ebfe1aa6d8d6.png)

Removing the control byte and rerunning terraformer fixes the generated tf file. So it seems like some sort of encoding bug in terraformer.

**Comment by meshuga** [comment]
Thanks for reporting that! Part of the terraformer tool is code to properly format/encode field values, so that Terraform can process it. It seems to be a problem with this character.

**Comment by arlekinjose** [comment]
I am dealing with this issue as well, but I can't use the proposed workaround because I only have read permissions
