### ISSUE TITLE
Terraformer article on medium

### ISSUE THREAD

**Issue by Amet13** [GoogleCloudPlatform/terraformer#556]
Hi Sergey and community.
Thank you for such a great tool.
I've used it for myself and it works like a charm. I've decided to write an article about terraformer and my experience with it in my medium blog.
Right now it's not published yet, it's only a draft, so you have to have a medium account to read it:
https://medium.com/@Amet13/terraformer-5036241f90cc

If you don't have a medium account and don't want to register, feel free to see the copy on Google Docs: https://docs.google.com/document/d/1kjPmGFc_cSpvIqtMcG9CsB-SniKVTvuXRF0ufAiYWxQ/edit?usp=sharing

It would be cool to get your feedback before publication, I think it could be helpful for this article.
WDYT?

**Comment by sergeylanzman** [comment]
Thanks for you article. I added 2 small comments
