### ISSUE TITLE
Error importing azure virtual_machine

### ISSUE THREAD

**Issue by nomad-007** [GoogleCloudPlatform/terraformer#561]
$ terraformer version
Terraformer v0.8.8

$ terraformer import azure -r virtual_machine

2020/07/24 13:31:51 azurerm importing... virtual_machine
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x353059f]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/azure.VirtualMachineGenerator.createResources(0xc0002a2c60, 0xf, 0x0, 0x0, 0x0, 0x611c766, 0x7, 0xc0006d2240, 0xb20bd40, 0x0, ...)
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/providers/azure/virtual_machine.go:37 +0x10f
github.com/GoogleCloudPlatform/terraformer/providers/azure.(*VirtualMachineGenerator).InitResources(0xc0000b4f60, 0x6b434a0, 0xc0000b4f60)
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/providers/azure/virtual_machine.go:72 +0x332
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x6b344e0, 0xc00069c0d0, 0xc000119d10, 0x1, 0x1, 0x617c505, 0x1e, 0x61216c1, 0x9, 0x61194fd, ...)
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/cmd/import.go:102 +0x670
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAzureImporter.func1(0xc0004f9080, 0xc0005c5c00, 0x0, 0x2, 0x0, 0x0)
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_azure.go:30 +0xe2
github.com/spf13/cobra.(*Command).execute(0xc0004f9080, 0xc0005c5be0, 0x2, 0x2, 0xc0004f9080, 0xc0005c5be0)
	/Users/sergeylanz/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e6840, 0xc000118df0, 0xc00006e0f0, 0x62782a8)
	/Users/sergeylanz/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/sergeylanz/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x6a1b380, 0xc000118df0)
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x27
main.main()
	/Users/sergeylanz/go/src/github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x60

**Comment by superlooper615** [comment]
I have the same issue. Any suggestions?

**Comment by pir8g33k** [comment]
this issue still persist any update on this?

**Comment by JavierCCC** [comment]
Same problem here, Ubuntu 20.04 WSL, last versions of az cli, terraform, terraformer.
