### ISSUE TITLE
Not working terraformer yandex cloud

### ISSUE THREAD

**Issue by unixzen** [GoogleCloudPlatform/terraformer#565]
Hello! I builded terraformer from source (master branch) with support yandex provider
```
go mod download
go run build/main.go yandex.cloud
```
I created init file init.tf with content
```
provider yandex {}
```
I exported YC_TOKEN and YC_FOLDER_ID
Terraformer version
```user@computer:/tmp/yandex-cloud $ terraformer-yandex version
Terraformer v0.8.8
```
And i try import instance resource according this instruction https://github.com/GoogleCloudPlatform/terraformer#use-with-yandex and i get strange message
```
user@computer:/tmp/yandex-cloud $ terraformer-yandex import yandex -r instance
2020/07/29 23:04:46 unknown shorthand flag: 'r' in -r
```

**Comment by sergeylanzman** [comment]
Try `go run build/main.go yandex`

**Comment by unixzen** [comment]
Yes, terraformer success builded. But now other error
```
user@computer:/tmp/yandex-cloud $ env | grep YC
YC_FOLDER_ID=agXxxxxxxXXXxxx
YC_TOKEN=AgXXXXXXXXXXXXXX
```
And now message
```
eugene@devlocal:/tmp/yandex-cloud $ terraformer-yandex import yandex -r instance
2020/07/29 23:23:38 required flag(s) "folder_ids" not set
```
With these envs i run other go program and all fine. I guess cause at this place (env only YC_TOKEN but not YC_FOLDER_ID)
https://github.com/GoogleCloudPlatform/terraformer/pull/563/files#diff-2326e26fda26c8cd9b8a7c49acad9899R31

**Comment by diversys** [comment]
I'm getting exactly the same error. Both `YC_FOLDER_ID` and `YC_TOKEN` are exported but running
`./terraformer-yandex import yandex -r subnet` gives
```
2022/03/10 00:03:29 required flag(s) "folder_ids" not set
````

This is under WSL1 if this matters. 
Any idea what's going on here?

**Comment by diversys** [comment]
Tested on macOS and Linux with the same results, so it's not WSL1 related.

**Comment by diversys** [comment]
@GennadySpb any thoughts?

**Comment by GennadySpb** [comment]
@diversys Hi!
There is an error in the documentation :(
I just checked and the folder_id parameter should be set like this:
```
./terraformer-yandex import yandex -r subnet  --folder_ids b1g8jffcdmit678lcn49
```
Thus, the YC_FOLDER_ID environment variable does not affect anything.

**Comment by diversys** [comment]
Thanks @GennadySpb! With this I got a bit further now. However now it complains about a token:

```
2022/03/15 15:53:29 yandex importing folder id b1gg5ic4o9tlkb64jxxx
2022/03/15 15:53:29 yandex importing... subnet
2022/03/15 15:53:30 yandex error initializing resources in service subnet, 
err: iam token create failed: rpc error: code = Unauthenticated desc = OAuth token is invalid or expired
```

Any idea what could be wrong?

**Comment by GennadySpb** [comment]
I think I know a problem that could lead to this (requires a go-sdk update). I will try to fix/PR optimistically today.

**Comment by GennadySpb** [comment]
@diversys Please build and try `terraformer` from #1259 for your case.

**Comment by diversys** [comment]
@GennadySpb turned out it is not possible to use OAuth token for Yandex Cloud federation account I use and service account key file should be used instead.
Is it possible to use service account key file with terraformer?

**Comment by GennadySpb** [comment]
So, the current authentication method in Terraformer supports only OAuth.
After #1263, all methods should be available, as in terraform-provider-yandex.

Example command:
```
YC_TOKEN=$(yc --profile=prod-fed iam create-token) terraformer import yandex -r subnet  --folder_ids b1g8jffcdmit678lcn49
```

**Comment by diversys** [comment]
Very cool! I'm going to try that now and report back.

**Comment by diversys** [comment]
Not there yet.

```
YC_TOKEN=$(yc --profile=default iam create-token) ../../terraformer/terraformer import yandex -r subnet  --folder_ids b1gg5ic4o9tlkb64jxxx
2022/03/16 21:51:18 yandex importing folder id b1gg5ic4o9tlkb64jxxx
2022/03/16 21:51:18 yandex importing... subnet
2022/03/16 21:51:18 yandex error initializing resources in service subnet, err: iam token create failed: rpc error: code = Unauthenticated desc = OAuth token is invalid or expired
```

```
export YC_SERVICE_ACCOUNT_KEY_FILE=../service-account-key.json
../../terraformer/terraformer import yandex -r subnet  --folder_ids b1gg5ic4o9tlkb64j21k
2022/03/16 21:44:58 yandex importing folder id b1gg5ic4o9tlkb64j21k
2022/03/16 21:44:59 yandex importing... subnet
2022/03/16 21:44:59 yandex error initializing resources in service subnet, err: rpc error: code = Unauthenticated desc = iam token create failed: rpc error: code = InvalidArgument desc = Validation failed:
  - identity: One of the options must be selected
```
However, reading the diff I should be getting this message, right?:
`one of 'YC_TOKEN' or 'YC_SERVICE_ACCOUNT_KEY_FILE' env variable should be specified; if you are inside compute instance, you can attach service account to it in order to authenticate via instance service account`

But this is not the case here.

**Comment by diversys** [comment]
Any thoughts @GennadySpb?

**Comment by GennadySpb** [comment]
I can't reproduce it, sorry. Just check all there auth methods with latest terraformer release **v0.8.19**.

A few comments about the places that can lead to an error:
1) to create SA key use command like
`yc iam key create   --service-account-id ajeqpggm78fl9qqqqqqq -o sa_key.json`
You will get a SA key file in json format  that can be used with terraformer.

2) check validity of token (`yc --profile=default iam create-token`) by `yc` CLI tool before use with terraformer.
`YC_IAM_TOKEN=<your_token_here> yc compute instance list`

**Comment by diversys** [comment]
I'm using the latest [v0.8.19](https://github.com/GoogleCloudPlatform/terraformer/releases/tag/0.8.19).

>    `yc iam key create   --service-account-id ajeqpggm78fl9qqqqqqq -o sa_key.json`
>    You will get a SA key file in json format  that can be used with terraformer.

I've just created it using your command. 

```
YC_SERVICE_ACCOUNT_KEY_FILE=sa_key.json ./terraformer import yandex -r subnet --folder_ids b1gg5ic4o9tlkb64jxxx
2022/03/20 14:22:36 yandex importing folder id b1gg5ic4o9tlkb64jxxx
2022/03/20 14:22:36 yandex importing... subnet
2022/03/20 14:22:36 yandex error initializing resources in service subnet, err: rpc error: code = Unauthenticated desc = iam token create failed: rpc error: code = InvalidArgument desc = Validation failed:
  - identity: One of the options must be selected
2022/03/20 14:22:36 yandex Connecting.

```
> 2. check validity of token (`yc --profile=default iam create-token`) by `yc` CLI tool before use with terraformer.
>    `YC_IAM_TOKEN=<your_token_here> yc compute instance list`

This does list instances jus fine but errors out with:

```
YC_TOKEN=<my token> ./terraformer import yandex -r subnet --folder_ids b1gg5ic4o9tlkb64jxxx
2022/03/20 14:20:39 yandex importing folder id b1gg5ic4o9tlkb64jxxx
2022/03/20 14:20:39 yandex importing... subnet
2022/03/20 14:20:39 yandex error initializing resources in service subnet, err: iam token create failed: rpc error: code = Unauthenticated desc = OAuth token is invalid or expired
2022/03/20 14:20:39 yandex Connecting....
```

Running terraformer without `YC_TOKEN` or `YC_SERVICE_ACCOUNT_KEY_FILE` never reaches this line:
https://github.com/GoogleCloudPlatform/terraformer/blob/1fe586b6abe7bd3855019e2a31bb570c47144db1/providers/yandex/yandex_service.go#L74

Thanks for your help so far!

**Comment by GennadySpb** [comment]
> 
> Running terraformer without `YC_TOKEN` or `YC_SERVICE_ACCOUNT_KEY_FILE` never reaches this line:
> 
> https://github.com/GoogleCloudPlatform/terraformer/blob/1fe586b6abe7bd3855019e2a31bb570c47144db1/providers/yandex/yandex_service.go#L74

This is very strange. Check your environment (env vars) before run terraformer. Or just unset both vars before run:
```
$ unset YC_TOKEN
$ unset YC_SERVICE_ACCOUNT_KEY_FILE
```

**Comment by diversys** [comment]
Of course, they are empty. Anything I can add to the code to help with debugging?  I can build stuff, but I have zero knowledge of Go, tho.

**Comment by diversys** [comment]
So from strace output it doesn't seem terraformer even attempts to open `sa_key.json`

`env | grep YC`
```
YC_SERVICE_ACCOUNT_KEY_FILE=/home/diver/terraform/sa_key.json
```
`strace terraformer import yandex -r subnet  --folder_ids b1gg5ic4o9tlkb64j21k 2>&1 | grep open`
```
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/sys/kernel/mm/transparent_hugepage/hpage_pmd_size", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/local/bin/terraformer", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
openat(AT_FDCWD, ".terraform/providers/registry.terraform.io", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, ".terraform/plugins/registry.terraform.io", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/diver/.terraform.d/providers/registry.terraform.io", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/diver/.terraform.d/plugins/registry.terraform.io", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, ".terraform/plugins/linux_amd64", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/diver/.terraform.d/plugins/linux_amd64", O_RDONLY|O_CLOEXEC) = 3
```

**Comment by diversys** [comment]
Scratch that, adding `-f` to strace (to follow forks) shows that it actually reads it:
```
strace -f terraformer import yandex -r subnet  --folder_ids b1gg5ic4o9tlkb64j21k 2>&1 | grep key
[pid 17024] newfstatat(AT_FDCWD, "/home/diver/terraform/sa_key.json",  <unfinished ...>
[pid 17024] openat(AT_FDCWD, "/home/diver/terraform/sa_key.json", O_RDONLY|O_CLOEXEC <unfinished ...>
```

**Comment by diversys** [comment]
Solved! Service account was missing the following permission `vpc.publicAdmin` and `vpc.privateAdmin`.
It would be nice to list required permissions [in the docs](https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/yandex.md) and in when import fails.

**Comment by diversys** [comment]
Turned out I had to regenerate OAuth-token from this page:
https://cloud.yandex.com/en/docs/iam/concepts/authorization/oauth-token

Problem solved.

**Comment by GennadySpb** [comment]
> Note that when I use `export YC_SERVICE_ACCOUNT_KEY_FILE=service-account-key.json` instead of `YC_TOKEN` the problem persi

How are you get `service-account-key.json`? And what problem occured?

**Comment by diversys** [comment]
`yc iam key create --service-account-id aje52155ko37hc2vf13p -o service-account-key.json`
`terraformer import yandex --resources="*" --folder_ids b1gg5ic4o9tlkb64j21k --compact --path-pattern .`
```
2022/06/14 19:52:59 yandex importing folder id b1gg5ic4o9tlkb64j21k
2022/06/14 19:52:59 Attempting an import of ALL resources in yandex
2022/06/14 19:52:59 yandex importing... disk
2022/06/14 19:52:59 yandex done importing disk
2022/06/14 19:52:59 yandex importing... instance
2022/06/14 19:53:00 yandex done importing instance
2022/06/14 19:53:00 yandex importing... network
2022/06/14 19:53:00 yandex error initializing resources in service network, err: rpc error: code = Unauthenticated desc = iam token create failed: rpc error: code = InvalidArgument desc = Validation failed:
  - identity: One of the options must be selected
2022/06/14 19:53:00 yandex importing... subnet
2022/06/14 19:53:00 yandex error initializing resources in service subnet, err: rpc error: code = Unauthenticated desc = iam token create failed: rpc error: code = InvalidArgument desc = Validation failed:
  - identity: One of the options must be selected
2022/06/14 19:53:00 Number of resources for service disk: 71
2022/06/14 19:53:00 Number of resources for service instance: 41
2022/06/14 19:53:00 Refreshing state... yandex_compute_disk.tfer--epd2lhbas2uajieh1r4e
2022/06/14 19:53:00 Refreshing state... yandex_compute_instance.tfer--epd3mcvkkl0v1hblqv63
2022/06/14 19:53:00 Refreshing state... yandex_compute_instance.tfer--epd33iq7742nsa5ben5c
2022/06/14 19:53:00 Refreshing state... yandex_compute_instance.tfer--fhmm34jeot18m1sbhrfj
```

Import works without errors when **both** `YC_SERVICE_ACCOUNT_KEY_FILE` and `YC_TOKEN` are exported.

**Comment by diversys** [comment]
```
env | grep YC
YC_SERVICE_ACCOUNT_KEY_FILE=service-account-key.json
YC_TOKEN=<token>
```
No errors:
```
2022/06/14 20:10:10 yandex importing folder id b1gg5ic4o9tlkb64j21k
2022/06/14 20:10:10 Attempting an import of ALL resources in yandex
2022/06/14 20:10:10 yandex importing... disk
2022/06/14 20:10:10 yandex done importing disk
2022/06/14 20:10:10 yandex importing... instance
2022/06/14 20:10:11 yandex done importing instance
2022/06/14 20:10:11 yandex importing... network
2022/06/14 20:10:11 yandex done importing network
2022/06/14 20:10:11 yandex importing... subnet
2022/06/14 20:10:11 yandex done importing subnet
2022/06/14 20:10:11 Number of resources for service disk: 71
2022/06/14 20:10:11 Number of resources for service instance: 41
2022/06/14 20:10:11 Number of resources for service network: 1
2022/06/14 20:10:11 Number of resources for service subnet: 3
```
