### ISSUE TITLE
Filter based on different resource ID

### ISSUE THREAD

**Issue by Arlington1985** [GoogleCloudPlatform/terraformer#568]
How can I specify different resource id in one or several filter blocks on one command?

**Comment by vxavictor513** [comment]
@Arlington1985: I guess this is what you're looking for:

![image](https://user-images.githubusercontent.com/27017678/98501267-a5a74980-2289-11eb-95e1-fdfa774513a0.png)

https://github.com/GoogleCloudPlatform/terraformer#filtering

**Comment by sandk985** [comment]
any way to tell terraformer to import specific vpc with all its sub-componenets like subnets, rtb, etc.

**Comment by meshuga** [comment]
You can try `--filter="Name=vpc_id;Value=vpc-xx"`.
