### ISSUE TITLE
Error - Resource GCS -Filter Google Storage Bucket IAM Binding

### ISSUE THREAD

**Issue by ialvaradohn** [GoogleCloudPlatform/terraformer#570]
When I run terraformer import google --resources=gcs —filter=google_storage_bucket_iam_binding --projects=<project name> --regions=us-central1
2020/08/04 07:58:47 google importing project region us-central1
2020/08/04 07:58:48 google importing... gcs
2020/08/04 07:58:50 Refreshing state... google_storage_bucket.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_notification.tfer---businesses-002F-cloud-002D-functions-002D--j9f6f0145d036f861-002D-tp
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_acl.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_binding.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_default_object_acl.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_acl.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_bucket.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_bucket.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_acl.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_policy.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_binding.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_default_object_acl.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_member.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_policy.tfer---businesses
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_member.tfer---ads
2020/08/04 07:58:50 Refreshing state... google_storage_default_object_acl.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_member.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_binding.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_bucket_iam_policy.tfer---categories
2020/08/04 07:58:50 Refreshing state... google_storage_notification.tfer---categories-002F-cloud-002D-functions-002D--j9f6f0145d036f861-002D-tp
2020/08/04 07:58:50 Refreshing state... google_storage_bucket.tfer---data
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_acl.tfer---data
2020/08/04 07:58:51 Refreshing state... google_storage_default_object_acl.tfer---data
2020/08/04 07:58:51 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---businesses
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_binding.tfer---data
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_member.tfer---data
2020/08/04 07:58:51 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---ads
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_policy.tfer---data
2020/08/04 07:58:51 Refreshing state... google_storage_bucket.tfer---products
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_acl.tfer---products
2020/08/04 07:58:51 Refreshing state... google_storage_default_object_acl.tfer---products
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_binding.tfer---products
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_member.tfer---products
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_policy.tfer---products
2020/08/04 07:58:51 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---data
2020/08/04 07:58:51 Refreshing state... google_storage_notification.tfer---products-002F-cloud-002D-functions-002D--j9f6f0145d036f861-002D-tp
2020/08/04 07:58:51 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---categories
2020/08/04 07:58:51 Refreshing state... google_storage_bucket.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_acl.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_default_object_acl.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_binding.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_member.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_policy.tfer---promos
2020/08/04 07:58:51 Refreshing state... google_storage_notification.tfer---promos-002F-cloud-002D-functions-002D--j9f6f0145d036f861-002D-tp
2020/08/04 07:58:51 Refreshing state... google_storage_bucket.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_acl.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_default_object_acl.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_binding.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_member.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_policy.tfer---users
2020/08/04 07:58:51 Refreshing state... google_storage_bucket.tfer---appspot-002E-com
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_acl.tfer---appspot-002E-com
2020/08/04 07:58:51 Refreshing state... google_storage_default_object_acl.tfer---appspot-002E-com
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_binding.tfer---appspot-002E-com
2020/08/04 07:58:51 Refreshing state... google_storage_bucket_iam_member.tfer---appspot-002E-com
2020/08/04 07:58:52 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---products
2020/08/04 07:58:52 Refreshing state... google_storage_bucket_iam_policy.tfer---appspot-002E-com
2020/08/04 07:58:52 Refreshing state... google_storage_bucket.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 Refreshing state... google_storage_bucket_acl.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 Refreshing state... google_storage_default_object_acl.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 Refreshing state... google_storage_bucket_iam_binding.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---users
2020/08/04 07:58:52 Refreshing state... google_storage_bucket_iam_member.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 Refreshing state... google_storage_bucket_iam_policy.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:52 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---promos
2020/08/04 07:58:52 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer---appspot-002E-com
2020/08/04 07:58:53 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---ads
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---businesses
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---categories
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---data
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---products
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---promos
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---users
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer---appspot-002E-com
2020/08/04 07:58:53 ERROR: Unable to refresh resource tfer--staging-002E--appspot-002E-com
2020/08/04 07:58:53 google Connecting.... 
2020/08/04 07:58:53 google save gcs
2020/08/04 07:58:53 google save tfstate for gcs

As you can read in the log, there seems to be a problem when ready IAM members and roles. Am I missing something?

**Comment by dvdantunes** [comment]
I was struggling with this too, and apparently it is a bug. It is marked as bug on #368 and in https://github.com/hashicorp/terraform-provider-google/issues/8162

**Comment by Jayant203** [comment]
I am facing this too, is there any solution for this?
