### ISSUE TITLE
Remove attachement{} block for aws_network_interface (ENI) without instance attached

### ISSUE THREAD

**Issue by Arlington1985** [GoogleCloudPlatform/terraformer#575]
Currently when you import aws_network_interface it adds 
```
attachment {
    device_index = "1"
}
```
block without `instance` key when there is no instance_id attached to the network interface which is wrong. `attachment {}` block is optional and network interface can be created without the attached instance. In this case, you need just opt-out this block. 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface#attachment

**Comment by meshuga** [comment]
@sergeylanzman closed in #571
