### ISSUE TITLE
Support using plugins from canonical location

### ISSUE THREAD

**Issue by pratikmallya** [GoogleCloudPlatform/terraformer#579]
After `terraform init` is run, it pulls in all the required dependencies to a local `.terraform.d` folder. `terraformer` should look in this folder to find the relevant plugins, rather than make users download provider plugin binaries.

**Comment by sergeylanzman** [comment]
I think it's support today.

I regular use `terraform init` and local `.terraform`, but if I don't have provider in local, terraformer try to find in `~/.terraform.d/`
