### ISSUE TITLE
Azure Network Security Group - Duplicate resource found

### ISSUE THREAD

**Issue by cheungw9** [GoogleCloudPlatform/terraformer#580]
Receive the following error when running 'terraformer import azure -r network_security_group`

Error Message:
ERR]: duplicate resource found: azurerm_network_security_group

Using:
terraformer v0.8.8
terraform v0.12.29
provider.azurerm v.2.5.0

**Comment by chayano** [comment]
TaroEnterprises

**Comment by chayano** [comment]
TaroEnterprises

**Comment by chayano** [comment]
https://www.TaroEnterprises.com

**Comment by sergeylanzman** [comment]
fix for don't crash on duplicate resource here https://github.com/GoogleCloudPlatform/terraformer/pull/641

but problem with name of network_security_group in terraformer.

I see in code network name not uniq in azure
