### ISSUE TITLE
Feature Request: Add MongoDB Atlas

### ISSUE THREAD

**Issue by mshiriv** [GoogleCloudPlatform/terraformer#589]
I suggest adding MongoDB Atlas to the supported cloud as a feather.

**Comment by demon** [comment]
I'd like to see this as well, came here to file the exact same request.

**Comment by MarkAndersonTrocme** [comment]
Started PR: #1188

**Comment by MarkAndersonTrocme** [comment]
@sergeylanzman can you re-open this issue please?

**Comment by MarkAndersonTrocme** [comment]
Blocked by: https://github.com/GoogleCloudPlatform/terraformer/pull/845

Only able to import projects. Need a more up to date version of terraform

**Comment by devnoname120** [comment]
@markandersontrocme @mshiriv Do you have updates on this by any chance?
