### ISSUE TITLE
plugin error 1: open /Users/me/.terraform.d/plugins/darwin_amd64: no such file or directory [Terraform Version v0.13.0]

### ISSUE THREAD

**Issue by jjorissen52** [GoogleCloudPlatform/terraformer#590]
I am seeing the same issue as indicated in https://github.com/GoogleCloudPlatform/terraformer/issues/184 when using `terraformer` with plugins initiated by terraform v0.13.0

0. `brew uninstall terraformer && brew install terraformer` (version 0.8.8 installed)
1. Make directory, cd
2. init.tf:
```tf
provider "google" {
  version = "~> 3.35"
  project_id = "credible-torus-262216"
}
```
3. `terraform init`
4. `terraformer import google ...`
5. 
```
2020/08/22 00:32:34 google importing... 
2020/08/22 00:32:35 open /Users/me/.terraform.d/plugins/darwin_amd64: no such file or directory
```

Terraform version:
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/google v3.35.0
```

**Note that this error does not occur for previous versions of terraform, e.g.**
```
Terraform v0.12.10
+ provider.google v3.35.0
```

**Comment by maxim-clc** [comment]
Similar issue on Linux (Ubuntu 20.04) with direct install from GitHub.

Error:
2020/08/26 13:32:10 aws importing default region
2020-08-26T13:32:10.601-0700 [INFO]  plugin: configuring client automatic mTLS
2020-08-26T13:32:10.661-0700 [DEBUG] plugin: starting plugin: path= args=[]
2020/08/26 13:32:10 fork/exec : no such file or directory

Layout:
drwxrwxr-x 4 user user 4096 Aug 26 13:33 .
drwxrwxr-x 4 user user 4096 Aug 26 13:26 ..]
-rw-rw-r-- 1 user user   18 Aug 26 13:27 init.tf
drwxr-xr-x 3 user user 4096 Aug 26 13:27 .terraform
drwxr-xr-x 3 user user 4096 Aug 26 13:27 .terraform.d

[ Yes, I did created two redundant dirs out of despair - still "terraformer" can't find what is looking for. ]

strace result: 
strace -f -t -e trace=file,open,read terraformer import aws --resources=route53,vpc,subnet -v 2>&1

strace ---------- START ------------

[pid 2198941] 13:38:04 readlinkat(AT_FDCWD, "/proc/self/exe", "/usr/local/bin/terraformer", 128) = 26
[pid 2198941] 13:38:04 openat(AT_FDCWD, "/usr/local/bin/terraformer", O_RDONLY|O_CLOEXEC) = 3
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198944] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198945] 13:38:04 read(5, "\0", 16) = 1
[pid 2198941] 13:38:04 openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
[pid 2198941] 13:38:04 read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\5\0\0\0\5\0\0\0\0"..., 4096) = 2836
[pid 2198941] 13:38:04 read(3, "", 4096) = 0
2020/08/26 13:38:04 aws importing default region
[pid 2198941] 13:38:04 openat(AT_FDCWD, ".terraform/plugins/linux_amd64", O_RDONLY|O_CLOEXEC) = 3
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/ns1", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/vultr", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/keycloak", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/cloudflare", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/commercetools", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/yandex", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/heroku", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/alicloud", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
**[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/aws", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0**
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/datadog", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/rabbitmq", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/octopusdeploy", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/openstack", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/azure", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/kubernetes", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/gcp", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/mikrotik", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/linode", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/newrelic", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/logzio", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/github", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/fastly", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/digitalocean", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 2198941] 13:38:04 newfstatat(AT_FDCWD, ".terraform/plugins/linux_amd64/gmailfilter", {st_mode=S_IFDIR|0775, st_size=4096, ...}, AT_SYMLINK_NOFOLLOW) = 0
2020-08-26T13:38:04.726-0700 [INFO]  plugin: configuring client automatic mTLS
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198946] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198946] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198946] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198946] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198945] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198945] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198945] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 read(5, "\0", 16) = 1
[pid 2198945] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198945] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198944] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198943] 13:38:04 read(5, "\0", 16) = 1
2020-08-26T13:38:04.790-0700 [DEBUG] plugin: starting plugin: path= args=[]
strace: Process 2198948 attached
[pid 2198948] 13:38:04 execve("", [""], 0xc0000bc5a0 /* 32 vars */) = -1 ENOENT (No such file or directory)
[pid 2198948] 13:38:04 +++ exited with 253 +++
[pid 2198946] 13:38:04 --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=2198941, si_uid=1000} ---
[pid 2198941] 13:38:04 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=2198948, si_uid=1000, si_status=253, si_utime=0, si_stime=0} ---
[pid 2198946] 13:38:04 read(10, "\2\0\0\0\0\0\0\0", 8) = 8
2020/08/26 13:38:04 **fork/exec** : no such file or directory
[pid 2198947] 13:38:04 +++ exited with 1 +++
[pid 2198946] 13:38:04 +++ exited with 1 +++
[pid 2198945] 13:38:04 +++ exited with 1 +++
[pid 2198944] 13:38:04 +++ exited with 1 +++
[pid 2198943] 13:38:04 +++ exited with 1 +++
[pid 2198942] 13:38:04 +++ exited with 1 +++
13:38:04 +++ exited with 1 +++

strace ------ END ------

However, the directory exists:

ls -lh .terraform/plugins/linux_amd64/aws/{vpc,subnet,route53}.go
total 392K
-rwxrwxr-x 1 user user 4551 Aug 25 12:11 .terraform/plugins/linux_amd64/aws/route53.go*
-rwxrwxr-x 1 user user 1881 Aug 25 12:11 .terraform/plugins/linux_amd64/aws/subnet.go*
-rwxrwxr-x 1 user user 1726 Aug 25 12:11 .terraform/plugins/linux_amd64/aws/vpc.go*
......

It would help to have clear indication where "terraformer" really looks for plugins and not just fail in esoteric - **fork/exec** - way.

**Comment by jjorissen52** [comment]
I believe that the issue stems from the fact that Terrafrom < 0.13 installs plugins to a different path than Terraform 0.13+.

**Comment by ThomasGHenry** [comment]
Moving back to terraform 0.12 resolved this for me.

**Comment by maxim-clc** [comment]
Confirming that this is indeed the case. Moving Terraform to latest 0.12.29 changed the terraformer behavior. Good as a work around, however, this issue needs attention in a future.

**Comment by yashshah** [comment]
Is there any way to get this plugin working with Terraform v0.13?

**Comment by alexjmoore** [comment]
As per previous comments, seems 0.13 now installs plugins within a .terraform directory in the templates directory by default, rather than the home directory, so on a fresh 0.13 install terraformer is currently looking in the wrong place for the plugins.

**Comment by alexjmoore** [comment]
The issue might be here:

https://github.com/GoogleCloudPlatform/terraformer/blob/8be92a9f59e1b551fdda1cf6a6191fdaff0547e9/terraformutils/providerwrapper/provider.go#L244

This assume to search here in a flat structure:

`.terraform/plugins/darwin_amd64`

But in reality in 0.13 this should now be searching through a registry structure, so now the provider appears here (using azurerm as an example):

`.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.20.0/darwin_amd64`

So this code just needs to be updated to account for this new registry/version structure I believe.

**Comment by meshuga** [comment]
To ensure backwards compatibility, the tool should check two paths. Thanks for the feedback!

**Comment by v1bh0r** [comment]
Here's what I had to do in order to get it working. 
1. Created the path ~/.terraform.d/plugins/darwin_amd64
2. Downloaded https://releases.hashicorp.com/terraform-provider-google/, extracted the package, copied the file in ~/.terraform.d/plugins/darwin_amd64 as terraform-provider-google.
3. chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-google
4. I had to manually open the executable manually once in order to get rid of the Mac malicious executable warning.

**Comment by jerryvurbl** [comment]
> `brew uninstall terraformer` and `brew install --HEAD terraformer`

This worked for me on Mac OS v10.15 Catalina to fix the same problem.  These steps compiled and linked a different version of Go so I assume the issue had something to do with whatever i had in its place before.

**Comment by BenLiyanage** [comment]
> brew uninstall terraformer and brew install --HEAD terraformer

This didn't work with me using terraform 0.14.

**Comment by jaygorrell** [comment]
^ worked for me on `0.14.5`

**Comment by Jeiwan** [comment]
> Here's what I had to do in order to get it working.
> 
> 1. Created the path ~/.terraform.d/plugins/darwin_amd64
> 2. Downloaded https://releases.hashicorp.com/terraform-provider-google/, extracted the package, copied the file in ~/.terraform.d/plugins/darwin_amd64 as terraform-provider-google.
> 3. chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-google
> 4. I had to manually open the executable manually once in order to get rid of the Mac malicious executable warning.

This worked for me with terraform 0.13 and latest terraformer. The file shouldn't be renamed though, otherwise it causes `Can't find provider version` warning when calling `terraformer import plan`.

**Comment by meshuga** [comment]
Thanks for pointing this out!

**Comment by maxlim0** [comment]
Why it's closed? The issue is here

**Comment by elysium-12** [comment]
This is still an issue on terraform 1.0 & terraformer v0.8.14even after applying the above-mentioned workaround:

`brew uninstall terraformer` and
` brew install --HEAD terraformer`

**Comment by BismarckY** [comment]
the issue is still there when execute the terraformer import with google provider.
**_fork/exec : no such file or directory_**

with latest terraform version:V1.01 on Darwin_amd64, Terraformer version:V0.8.15

**Comment by Mistic92** [comment]
I just tried to use terraformer on WSL2 and I got this error. I'm using latest release from github.

**Comment by xgp** [comment]
Idk if anyone is still wrestling with this issue, but the following fixed it for me with versions `0.12.31`, `0.13.2` and `0.14.8`. It seems you just need a new directory, with a versions file in it. E.g.:
```
$ mkdir some-new-dir
$ cd some-new-dir
$ tee -a versions.tf <<EOF
terraform {
 ​required_version = ">= 0.13"
 ​required_providers {
   ​aws = {
     ​source  = "hashicorp/aws"
   ​}
 ​}
}
EOF
$ terraform init
$ terraformer import aws ...
```

**Comment by RaissaBergamini** [comment]
@xgp your solution worked for me, thanks!!

**Comment by geolffreym** [comment]
> Here's what I had to do in order to get it working.
> 
> 1. Created the path ~/.terraform.d/plugins/darwin_amd64
> 2. Downloaded https://releases.hashicorp.com/terraform-provider-google/, extracted the package, copied the file in ~/.terraform.d/plugins/darwin_amd64 as terraform-provider-google.
> 3. chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-google
> 4. I had to manually open the executable manually once in order to get rid of the Mac malicious executable warning.

This it worked for me in `terraform 1,1+ terraformer 0,8`.. Thank you

**Comment by devfreddy** [comment]
> Here's what I had to do in order to get it working.
> 
> 1. Created the path ~/.terraform.d/plugins/darwin_amd64
> 2. Downloaded https://releases.hashicorp.com/terraform-provider-google/, extracted the package, copied the file in ~/.terraform.d/plugins/darwin_amd64 as terraform-provider-google.
> 3. chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-google
> 4. I had to manually open the executable manually once in order to get rid of the Mac malicious executable warning.

Similar but slightly different. Running the following version:

```sh
terraform -v
```

```sh
Terraform v1.1.7 on darwin_amd64
```

Steps I took:

1. Add provider you need (in this case `newrelic/newrelic` to a `.tf` file and run `terraform init`
  
    ```tf
    terraform {
      required_providers {
        google = {
          source = "newrelic/newrelic"
        }
      }
      required_version = ">= 0.13"
    }
    ```

1. Create plugin directory

    ```sh
      mkdir -p ~/.terraform.d/plugins/darwin_amd64
    ```

1. Copy provider that was imported in step 1

    ```sh
      cp ~/.terraform/providers/registry.terraform.io/newrelic/newrelic/2.48.1/darwin_amd64/terraform-provider-newrelic_v2.48.1 ~/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.48.1
    ```

**Comment by bongardino** [comment]
If you're on a silicon mac, note this will be `darwin_arm64` and not `darwin_amd64`

**Comment by mccartney** [comment]
@devfreddy I think your instructions have a typo. It should **not** mention `~` in source of your `cp`. E.g. I believe you rather meant:
```
cp .terraform/providers/registry.terraform.io/newrelic/newrelic/2.48.1/darwin_amd64/terraform-provider-newrelic_v2.48.1 ~/.terraform.d/plugins/darwin_amd64/terraform-provider-newrelic_v2.48.1
```

**Comment by tom10271** [comment]
> the issue is still there when execute the terraformer import with google provider. **_fork/exec : no such file or directory_**
> 
> with latest terraform version:V1.01 on Darwin_amd64, Terraformer version:V0.8.15

https://github.com/GoogleCloudPlatform/terraformer/issues/1171

You need to run `terraform init` first

**Comment by peterdeme** [comment]
To me, the issue was that my Terraform was an arm64 binary and Terraformer was amd64.

I downloaded the darwin-arm64 image and it fixed it. Although it's pretty huge (380mb)

**Comment by omergulen** [comment]
In my case using MacOS Ventura 13.0 on Apple M1, thanks to @peterdeme's comment, I have created `providers.tf` in the folder I'm working in and put the provider (`aws` in my case)
```
provider "aws" {}
```
and then ran
```
terraform init
```
and finally ran the `terraformer import aws ...` and everything worked smoothly.

**Comment by dangvanduc90** [comment]
> In my case using MacOS Ventura 13.0 on Apple M1, thanks to @peterdeme's comment, I have created `providers.tf` in the folder I'm working in and put the provider (`aws` in my case)
> 
> ```
> provider "aws" {}
> ```
> 
> and then ran
> 
> ```
> terraform init
> ```
> 
> and finally ran the `terraformer import aws ...` and everything worked smoothly.

thank you, work like a charm

**Comment by marek-knappe** [comment]
> > In my case using MacOS Ventura 13.0 on Apple M1, thanks to @peterdeme's comment, I have created `providers.tf` in the folder I'm working in and put the provider (`aws` in my case)
> > ```
> > provider "aws" {}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then ran
> > ```
> > terraform init
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and finally ran the `terraformer import aws ...` and everything worked smoothly.
> 
> thank you, work like a charm

Worked for me too! thanks! :)

**Comment by ansghof** [comment]
> Here's what I had to do in order to get it working.
> 
>     1. Created the path ~/.terraform.d/plugins/darwin_amd64
> 
>     2. Downloaded https://releases.hashicorp.com/terraform-provider-google/, extracted the package, copied the file in ~/.terraform.d/plugins/darwin_amd64 as terraform-provider-google.
> 
>     3. chmod +x ~/.terraform.d/plugins/darwin_amd64/terraform-provider-google
> 
>     4. I had to manually open the executable manually once in order to get rid of the Mac malicious executable warning.

Thanks a lot, that brought me on the right direction. I forgot to look at point 4. and recompiled the plugin from source which also worked fine after I renamed it to contain a version in the filename.

**Comment by cfurst** [comment]
This is still causing an issue for me. I'm on Terraform v1.9.7
on darwin_arm64, and i get the same issue when running the terraformer to import datadog dashboards:
```
 terraformer import datadog --resources=dashboard --filter=dashboard=<dash-key> --api-key=<api-key --app-key=<app-key> --api-url datadog.uri.com

 /home/sweet/home/.terraform.d/plugins/darwin_amd64: no such file or directory
```
Any ideas? 
I did a `terraform init` against the datadog provider and it seems to have installed properly.

**Comment by tom10271** [comment]
> This is still causing an issue for me. I'm on Terraform v1.9.7 on darwin_arm64, and i get the same issue when running the terraformer to import datadog dashboards:
> 
> ```
>  terraformer import datadog --resources=dashboard --filter=dashboard=<dash-key> --api-key=<api-key --app-key=<app-key> --api-url datadog.uri.com
> 
>  /home/sweet/home/.terraform.d/plugins/darwin_amd64: no such file or directory
> ```
> 
> Any ideas? I did a `terraform init` against the datadog provider and it seems to have installed properly.

Are you running terraform init in the same directory you run terraformer?
