### ISSUE TITLE
googleapi: Error 403: Project [DELETED PROJECT] has been deleted., forbidden

### ISSUE THREAD

**Issue by stlbucket** [GoogleCloudPlatform/terraformer#593]
my command
```
terraformer import google --projects=[MY CURRENT PROJECT] --regions=us-central1 --resources=*
```

this is in a folder that only has a main.tf file:
```
provider "google" {
  project     = "MY CURRENT PROJECT"
  region      = "us-central"
  zone        = "us-central1-a"
}
```

i have already run terraform init on this directory.

output when i run terraformer:
```
$ terraformer import google --projects=[MY CURRRENT PROJECT] --regions=us-central1 --resources=*
2020/08/26 17:13:18 google importing project [MY CURRRENT PROJECT] region us-central1
2020/08/26 17:13:18 Attempting an import of ALL resources in google
2020/08/26 17:13:18 google importing... addresses
2020/08/26 17:13:19 google importing... autoscalers
2020/08/26 17:13:20 google importing... backendBuckets
2020/08/26 17:13:21 google importing... backendServices
2020/08/26 17:13:21 google importing... bigQuery
2020/08/26 17:13:22 googleapi: Error 403: Project [DELETED PROJECT] has been deleted., forbidden
```

i am using terraformer 0.8.8 on a mac.   logged into gcloud [MY CURRRENT PROJECT].

**Comment by briantopping** [comment]
Same exact problem here. In my case, gcloud as multiple credentials listed via `gcloud auth list` and the deleted project was under a non-active credential.

**Comment by briantopping** [comment]
I had the same problem. In my case, I had multiple authentications and projects, deleted project was under a non-current auth login. Problem persisted after deleting extra logins and making sure no other projects showed up in `gcloud projects list`. Still giving error for deleted project. 

I gave up and deleted `~/.config/gcloud` and started over. That worked.

**Comment by sergeylanzman** [comment]
I think it's gcloud issue, but I fixed code here https://github.com/GoogleCloudPlatform/terraformer/pull/638, don't crash on API error

**Comment by m-torin** [comment]
The "problem" is in the `application_default_credentials.json` file. Either change the project there or delete that file and re-run `gcloud auth application-default login`.

**Comment by mikila85** [comment]
@m-torin  THANK YOUUU
if anyone doesnt find that file run the command anyway it resets everything.
