### ISSUE TITLE
Duplicate resource found, terraformer dies

### ISSUE THREAD

**Issue by pwillis-els** [GoogleCloudPlatform/terraformer#595]
I'm getting some errors and some inconsistency in how terraformer handles duplicate resources.

Right now just grabbing 'alb' aws resources dies with the following error:
```
# for what it's worth, two "Reading certificate ... of listener " lines are printed for this certificate ID before this
# ...
2020/08/30 12:02:06 [ERR]: duplicate resource found: aws_lb_listener_certificate.tfer--arn-003A-aws-003A-acm-003A-us-002D-east-002D-1-003A-XXXXXXXXXXXX-003A-certificate-002F-XXXXXXXX-002D-XXXX-002D-XXXX-002D-XXXX-002D-XXXXXXXXXXXX
```
(some output redacted)

Without dumping my whole verbose log here, I can at least tell you that I grepped for the certificate ID listed in that duplicate resource, and it is returned as a member in two separate *DescribeListenerCertificates* API calls, so basically it is a member of two different listeners. My assumption is that the code is finding it twice, and trying to create the resource twice.

My request is that a feature option be added that allows me to ignore these errors (`--force` or similar). Right now it won't even dump the rest of the resources and dies randomly; if I run the same command multiple times, it continues to create more resource files as it doesn't encounter the error right away, but eventually dies with an error. As these resources are in use I can't delete them in AWS to allow the command to continue.

Thanks

**Comment by meshuga** [comment]
This `--force` is something I quite like. Previous versions of terraformer didn't crash if one resource failed, so a breaking change was introduced.

**Comment by sergeylanzman** [comment]
It's always crash on duplicate resources name
I created PR change to warning only and take first

WDYT? https://github.com/GoogleCloudPlatform/terraformer/pull/641
