### ISSUE TITLE
API Error 403 Forbidden

### ISSUE THREAD

**Issue by adam-git-ai** [GoogleCloudPlatform/terraformer#597]
Hello!

When attempting to import Datadog dashboards with Terraformer, according to the docs, I get the following error:
```
API error 403 Forbidden: {"errors": ["Forbidden"]}
```

I'm using the following command:
```
 terraformer import datadog --resources=dashboard --filter=datadog_dashboard=<my-dash-id> --api-key=<my-api-key> --app-key=<my-app-key>
```

However it works fine to import *states* of dashes using Terraform's commands using the same keys. Here are Terraform's commands that import the states of dashes:
```
terraform import datadog_dashboard.<name-of-dash> <my-dash-id>
```

Does anyone have an idea on the reason to why I'm getting this API error?

Thanks!

Edit:
I'm using Datadog EU, so is it necessary to state the API url for EU in Terraform's commands?

**Comment by adam-git-ai** [comment]
Solution: Needed to add api key, app key and host url to zshrc file

**Comment by Kiy0p** [comment]
Hey,

I curently have the same problem, do you have by any chance more explanations on how you solved this ? my error :

2021/04/30 10:22:05 datadog importing... monitor
2021/04/30 10:22:06 datadog error initializing resources in service monitor, err: 403 Forbidden
2021/04/30 10:22:06 datadog Connecting.... 

my command :

terraformer import datadog --resources=monitor --api-key="" --app-key=""

**Comment by therve** [comment]
Are you passing real values for the keys?

**Comment by Kiy0p** [comment]
> Are you passing real values for the keys?

I firugred it out thanks, the problem was I was using the free trial and i guess you don't have access to the API. Tried on a paid account works like a charm.
