### ISSUE TITLE
Would love a walkthrough in the docs

### ISSUE THREAD

**Issue by dmartin-isp** [GoogleCloudPlatform/terraformer#599]
Hi, I'm loving terraformer.  

It would be extra awesome if there was a simple walkthrough that took the user from installation to terraformer import to terraform import and apply.  I had trouble figuring out the .terraform.d/... plugins and filtering and I'm about to do a mass import into terraform and I don't know a good way to do mass imports so I'm probably going to write my own script to iterate over all my resources and import them.

Thanks!  I'm sooooooper grateful for terraformer.  I would die a horrible death if I had to do this all by hand.

**Comment by baasdenj** [comment]
I would like to add to this - and request a little more clarity on using the "sub" resources. Like importing an aws loadbalancer (alb) I can do, but can't figure out the correct syntax of the command to import aws_lb_listener_rule:

`./terraformer import aws --resources=aws_lb_listener_rule --filter="Name=tags.Name;Value=test" --connect=true --regions=eu-west-1 --profile=test`
2020/09/08 17:09:09 aws importing region eu-west-1
2020/09/08 17:09:09 aws importing... aws_lb_listener_rule
2020/09/08 17:09:09 aws: aws_lb_listener_rule not supported service

`./terraformer import aws --resources=alb,aws_lb_listener_rule --filter="Name=tags.Name;Value=test" --connect=true --regions=eu-west-1 --profile=test `
doesn't work either.
