### ISSUE TITLE
unclear on how to filter specific AWS Route53 zones

### ISSUE THREAD

**Issue by MrVJTod** [GoogleCloudPlatform/terraformer#601]
I've been trying to filter out one of my many Route53 zones, but none of these seem to work

```
--filter=aws_route53_zone=Z111111
--filter=aws_route53_zone.zone=Z111111
--filter=aws_route53_zone.zone_id=Z111111
--filter=aws_route53_zone.hosted_zone_id=Z111111
--filter=aws_route53_zone.hostedzone=Z111111
--filter=aws_route53_zone=my.zone.com
--filter=aws_route53_zone.name=my.zone.com
--filter=zone_id=Z111111
--filter="Name=zone_id;Value=Z111111"
--filter="Name=ZoneId;Value=Z111111"
--filter="Name=HostedZoneId;Value=Z111111"
--filter="Name=HostedzoneId;Value=Z111111"
--filter="Name=hosted_zone_id;Value=Z111111"
--filter="Name=tags.name;Value=my.zone.com"
--filter=Name=my.zone.com
--filter=Name=zone_id;Value==Z111111
--filter=Name=zone_id;Value=Z111111
--filter=Name=zone_id;Value=Z111111"
--filter=name=my.zone.com
```

**Comment by rmenn** [comment]
This works, I know i tried `zone_id` myself 
`terraformer import aws --resources=route53 --filter="Name=id;Value=111111111111"`

**Comment by MrVJTod** [comment]
Yeah, that's not what I'm seeing
I query for one zone and I see all zones

$ terraformer --version
version v0.8.8
$ terraformer import aws -v --resources=route53
--filter="Name=id;Value=Z1111"
 <ListResourceRecordSetsResponse...<HostedZoneId>Z1111
 <ListResourceRecordSetsResponse...<HostedZoneId>Z2222
 <ListResourceRecordSetsResponse...<HostedZoneId>Z3333
 <ListResourceRecordSetsResponse...<HostedZoneId>Z4444

ahhh - I see - the -v, the verbose output, is showing that terraformer is
analyzing all zones and only dumping my one zone

I do see that my zone is "imported", but the zone contents, the actual
resource records were not actually imported to anything under ./generated/

**Comment by marek-knappe** [comment]
This actually worked for me:
```
terraformer import aws --resources route53 --filter "Name=id;Value=ZONEID1:ZONEID2"
```
But it didn't get any records - which makes a bit sense as records don't have that ID, but is there any way of importing all zone records from specifics zoneID?

**Comment by stobias123** [comment]
Seeing this same issue. Can't get records with a filter on zone-id

**Comment by artazar** [comment]
Hi, I also bumped into the need to split the resulting output into per-zone files with all records belonging to particular zone.

Created a small python tool to do that, based on `terraformer` plan capabilities:
https://gist.github.com/artazar/c7c3cf77c38eb1e45042b16fa307cf54

Hope it helps someone too.

**Comment by elnarabackbase** [comment]
I have exactly the same question. It imports all the records, meanwhile I need to import only 1 zone.

**Comment by Efresia** [comment]
This command imports only the records for the specified zone - after processing all records in all zones:
 `terraformer import aws --resources=route53 --filter="Name=zone_id;Value=<zoneid>" --connect=true --profile default`
Once it iterates all records, you will see an output similar to:
Filtered number of resources for service route53: 123
aws Connecting.... 
aws save route53
aws save tfstate for route53

So it's a "post filter" vs. "pre filter".
