### ISSUE TITLE
Specifying which resource should not be imported, ignoring errors

### ISSUE THREAD

**Issue by knyttl** [GoogleCloudPlatform/terraformer#607]
I am trying to import all resources as 

```
terraformer plan google --resources=* --projects=goout-cloud --regions=europe-west1,europe-west2 --path-pattern {output}/{provider}/
```

However I am getting:

```
2020/09/14 16:55:50 googleapi: Error 400: Location must equal europe-west2 because the App Engine app that is associated with this project is located in europe-west2, badRequest
```

1. Is there a way to say `--resource=* --ignore=app-engine`?
2. Can I somehow say "don't die on error"?
3. Why does it throw this error even though the region is specified?

**Comment by nyetsche** [comment]
@knyttl 

> Is there a way to say --resource=* --ignore=app-engine?

#628 merged, so there is now a `-x/--excludes` option in `master`
