### ISSUE TITLE
Add the Gitlab Provider

### ISSUE THREAD

**Issue by SultanSGillani** [GoogleCloudPlatform/terraformer#609]
Requesting that you add the new Gitlab Provider as a new VCS Provider.

See here for the provider details: https://registry.terraform.io/providers/gitlabhq/gitlab/latest

**Comment by royca** [comment]
Is this still available to pe picked up and worked on ?

**Comment by SultanSGillani** [comment]
> Is this still available to be picked up and worked on ?

I am assuming so. Looks like it hasnt been worked on.

**Comment by SultanSGillani** [comment]
Any update on this?

**Comment by duyleekun** [comment]
@SultanSGillani Here's my first trial at implementing this https://github.com/GoogleCloudPlatform/terraformer/pull/1006
