### ISSUE TITLE
Cannot specify both 'source' and 'initializeParams'

### ISSUE THREAD

**Issue by aamarques** [GoogleCloudPlatform/terraformer#621]
Hey..
I'm using terraformer with Google Provider. I've imported all the resources I want, including compute instances.
For test purposes, I have deleted on instance from GCP console and did :

$ terraform init
$ terraform refresh 
$ terraform apply

.. and got this error

google_compute_instance.tfer--instance-002D-2: Creating...

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0]': '{  "mode": "READ_WRITE",  "source": "projects/ccmn-devadm/zones/europe-west2-b/disks/instance-2",  "...'. Cannot specify both 'source' and 'initializeParams'., invalid

if I open the file and comment on the **source** line, terraform runs successfully..
But why terraformer is putting these two lines ?

Regard,s

**Comment by aamarques** [comment]
Terraform v0.12.29 (is outdated but that's the supporter version for terraformer)
+ provider.google v3.43.0

$ terraformer -v
version v0.8.8

**Comment by aamarques** [comment]
compute_instance.tf:
resource "google_compute_instance" "tfer--instance-002D-2" {
  boot_disk {
    auto_delete = "true"
    device_name = "instance-2"

    initialize_params {
      image = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-10-buster-v20201014"
      size  = "10"
      type  = "pd-standard"
    }

    mode   = "READ_WRITE"
    source = "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west2-b/disks/instance-2"
  }
....


terraform plan:

      + boot_disk {
          + auto_delete                = true
          + device_name                = "instance-2"
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = "https://www.googleapis.com/compute/v1/projects/myproject/zones/europe-west2-b/disks/instance-2"

          + initialize_params {
              + image  = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-10-buster-v20201014"
              + labels = (known after apply)
              + size   = 10
              + type   = "pd-standard"
            }
        }

terraform apply  : 

Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0]': '{  "mode": "READ_WRITE",  "source": "projects/myproject/zones/europe-west2-b/disks/instance-2",  "...'. Cannot specify both 'source' and 'initializeParams'., invalid

**Comment by aamarques** [comment]
Any ideas or I'll still be deleting source from tf file ?
Regrads

**Comment by sergeylanzman** [comment]
Terraformer read all fields from provider. 
We can add one of them to ignore list, but..
If we delete from tf `initialize_params` you can't recreate same instance in other project(like copy)
If we delete from tf `source` you can't manage current instance in this project.

I think better it's delete `initialize_params`

**Comment by aamarques** [comment]
Thanks @sergeylanzman
