### ISSUE TITLE
"terraformer plan aws" outputs json file default, but in docs, it says the command output hcl file

### ISSUE THREAD

**Issue by yugaraxy** [GoogleCloudPlatform/terraformer#626]
Hey, thank you for this awesome product!

In the docs showed by "terraformer plan aws" with --help option,
it says like this👇:

>   -O, --output string         output format hcl or json (default "hcl")

And, when "terraform plan aws" command excecuted like this:
`$ terraformer plan aws -r=vpc,subnet -c=true --regions=ap-northeast-1 -O=hcl`
or
`$ terraformer plan aws -r=vpc,subnet -c=true --regions=ap-northeast-1`

The standard output shows:
`Saving planfile to generated/aws/terraform/plan.json`

It's a little confusing, because the output file's extension is json though "terraform plan aws" was excecuted with the option "-O=hcl".

I know that HCL is compatible with json syntax.
It's just little confusing.

Thank you.

**Comment by sergeylanzman** [comment]
Plan command return always json format, it's hardcoded 🙄  and support only json today. https://github.com/GoogleCloudPlatform/terraformer/blob/master/cmd/import.go#L158

I can add hcl option, but I don't find any case where you need hcl format for plan terraformer?
