### ISSUE TITLE
Log error, but skip over scope, disabled APIs

### ISSUE THREAD

**Issue by nyetsche** [GoogleCloudPlatform/terraformer#627]
I'm looking at using the tool for reconstructing an entire GCP project. It would be great if `terraforming` could do a "best effort" at retrieving all the resources. Right now, if a resource import fails no Terraform is generated and the process stops.

So far I've seen a resource fail from insufficient permissions:

```
2020/10/22 13:17:47 google importing... bigQuery
2020/10/22 13:17:47 googleapi: Error 403: Request had insufficient authentication scopes.
More details:
Reason: insufficientPermissions, Message: Insufficient Permission
```

and also `accessNotConfigured`:

```
2020/10/22 13:21:09 google importing... dataProc
2020/10/22 13:21:09 googleapi: Error 403: Cloud Dataproc API has not been used in project QQQQ before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/dataproc.googleapis.com/overview?project=QQQQ then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
```

I have a simple work-around for dataProc: add an `error` return to `createClusterResources`, `log.Println` instead of `log.Fatal`, and a `continue` in the import loop after `err = provider.GetService().InitResources()`.

Doing so for all the resources is a bit tedious. I see that there's a GCP Compute generator at `gcp_compute_code_generator`, but not for other resources.

While I can manually change all the resources to include an error and not `log.Fatal`, I'm wondering if my approach is missing something from the `terraforming` design. Is there a different code generator I should be using? 

Somewhat related to #595 asking about a `--force` / always-go-on feature.

Thanks for this very useful project.

**Comment by nyetsche** [comment]
I've crafted a PR to have an `--exclude`/`-x` flag, so resources can be skipped if you can't/don't want to read them. https://github.com/GoogleCloudPlatform/terraformer/pull/628

It's useful in other contexts but can also be a workaround for when some projects can't read a service.

**Comment by meshuga** [comment]
I think it'd be good to have an option to skip failing resources. There is already an issue for that in https://github.com/GoogleCloudPlatform/terraformer/issues/607
