### ISSUE TITLE
Failed to format TF file when the key value of tag is a number

### ISSUE THREAD

**Issue by chushenmeshile** [GoogleCloudPlatform/terraformer#632]
Hi,I had a problem with terraformer. When the key value of the resource tag is a number, formatting TF file fails, which results in the template file not generating normally. Such as :
`resource "****" "***"{
  tags = {
    123 = "123"
    qwe = "qwe"
  }
}`
Error message：
expected: IDENT | STRING | ASSIGN | LBRACE got NUMBER

**Comment by sergeylanzman** [comment]
Can you add example?
expected and actual? which provider and resource?

**Comment by chushenmeshile** [comment]
@sergeylanzman Any resource that starts with a number or has a bool value will report an error. Alicloud provider,image resource. You'd better try to create a resource whose key value is a number and export it. For example, the tag key value is 123 or true or false
