### ISSUE TITLE
Problem Azure import Virtual_machine and disk  --filter

### ISSUE THREAD

**Issue by jorchis05** [GoogleCloudPlatform/terraformer#648]
Good Morning, 

We are using th ecomands:

**terraformer import azure --resources=virtual_machine --filter=virtual_machine=[resource_id]
terraformer import azure --resources=disk --filter=disk=[resource_id]**

But, We have the problem that the "resource_id" filter does not work correctly.
In the result, it generates the configuration of all the virtual machines and all the associated disks in our azure account.

Can you confirm if there is some kind of problem with these resources?
Could any other filter be done for a virtual machine or disk besides the resource_id?

Thank you for this awesome product!

**Comment by EdersonSC** [comment]
still have the problem.
I'm trying to use the filter and it doesn't work for virtual machines in Azure. How should we use?
