### ISSUE TITLE
google_compute_managed_ssl_certificate fails with "unknown resource type"

### ISSUE THREAD

**Issue by brunobowden** [GoogleCloudPlatform/terraformer#653]
`google_compute_managed_ssl_certificate` support is mentioned in the [README](https://github.com/GoogleCloudPlatform/terraformer/blob/master/README.md) but it failed for me during a project export with the error "panic: unknown resource type". Version 0.8.9.

```
$ terraformer --version
version v0.8.9
...
2020/11/04 15:18:46 google importing... sslCertificates
2020/11/04 15:18:46 Refreshing state... google_compute_managed_ssl_certificate.tfer--who-002D-myhealth-002D-cert-002D-brunos
panic: unknown resource type google_compute_managed_ssl_certificate

goroutine 1538 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xc00074e1c0, 0x80f9c9f, 0x26, 0x0, 0x0)
	github.com/hashicorp/terraform@v0.12.29/plugin/grpc_provider.go:92 +0x12a
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc00074e1c0, 0x80f9c9f, 0x26, 0x88792c0, 0xc001534618, 0x6e26ac0, 0xc001772270, 0xd3d9b50, 0x0, 0x0, ...)
	github.com/hashicorp/terraform@v0.12.29/plugin/grpc_provider.go:321 +0xa5
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc0012f46c0, 0xc0011c4820, 0xc0011c47d0, 0x2, 0xc0016f8070, 0x69)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:153 +0x28b
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc0019f6980, 0xc0012f46c0)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:122 +0x4f
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0xc0019e0900, 0xc000e8cda0, 0xc0012f46c0)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:107 +0xcd
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
	github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:77 +0x108
```

**Comment by nyetsche** [comment]
Try changing your Terraform provider to `google-beta`.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_managed_ssl_certificate & https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_versions

**Comment by brunobowden** [comment]
The `google-beta` provider is already specified in the `main.tf` file for this resource. Is there something else I need to do?

https://github.com/WorldHealthOrganization/app/blob/master/server/terraform/modules/http-load-balancer/main.tf#L65

**Comment by nyetsche** [comment]
I was successful with renaming `terraform-provider-google-beta_v3.48.0_x5` to `terraform-provider-google_v3.48.0_x5` ( `.terraform.d/plugins/linux_amd64`, or wherever great plugins are found). Try that?

The provider name is hardcoded at https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/sslCertificates_gen.go#L44 ; that code itself is generated by https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/gcp_compute_code_generator/main.go#L77

Try renaming the provider executable, or recompiling your binary with the provider name changed to `google-beta`. I don't see a runtime configuration way to change it.

**Comment by aamarques** [comment]
> I was successful with renaming `terraform-provider-google-beta_v3.48.0_x5` to `terraform-provider-google_v3.48.0_x5` ( `.terraform.d/plugins/linux_amd64`, or wherever great plugins are found). Try that?
> 

This works fine to me but is a workaround (not polite).

> The provider name is hardcoded at https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/sslCertificates_gen.go#L44 ; that code itself is generated by https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/gcp/gcp_compute_code_generator/main.go#L77
> 
> Try renaming the provider executable, or recompiling your binary with the provider name changed to `google-beta`. I don't see a runtime configuration way to change it.

So, I think terraform should have a` -g, --google-provider` where we can pass `alpha, beta or nothing`

Thanks for the workarround

**Comment by brunobowden** [comment]
@nyetsche - thanks for a thoughtful workaround. Feel free to downgrade the importance of the bug. Naturally the performance will improve over time.

**Comment by nyetsche** [comment]
@brunobowden see my linked issue, I believe this can be fixed upstream.

**Comment by sergeylanzman** [comment]
now in 0.8.10
