### ISSUE TITLE
Bug using the Azure Provider on Azure Bash Cloud Shell

### ISSUE THREAD

**Issue by devmast** [GoogleCloudPlatform/terraformer#654]
Hi!

I am running into issues getting the Azure provider to work using Azure CLI on a Azure Cloud Shell instance. The best I can guess is that it is related to case sensitivity (The AZ CLI reports `environmentName: AzureCloud`, but the error is reporting that it cannot find `"AZURECLOUD"`) but that may be a red herring. 

The error and shell config are below.

Thanks!

```
$ ~/bin/terraformer/terraformer plan azure

2020/11/05 21:52:33 Testing if Service Principal / Client Certificate is applicable for Authentication..

2020/11/05 21:52:33 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..

2020/11/05 21:52:33 Testing if Service Principal / Client Secret is applicable for Authentication..

2020/11/05 21:52:33 Testing if Managed Service Identity is applicable for Authentication..

2020/11/05 21:52:33 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..

2020/11/05 21:52:33 Using Obtaining a token from the Azure CLI for Authentication

2020/11/05 21:52:33 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```
The cloud shell is configured as such:
```
ds@Azure:~/terraformer-cifc-azure$ terraform -v

Terraform v0.13.5

+ provider registry.terraform.io/hashicorp/azurerm v1.35.0

ds@Azure:~/terraformer-cifc-azure$ ~/bin/terraformer/terraformer -v

version v0.8.9
```

 Azure CLI Connection:
```
ds@Azure:~/terraformer-azure$ az account show

environmentName: AzureCloud

homeTenantId: *****

id: ****

isDefault: true

managedByTenants: []

name: Pay-As-You-Go

state: Enabled

tenantId: ****   

user:

  cloudShellID: true

  name: ***

  type: user
```

**Comment by gvdm90** [comment]
Hello,
I have the same error but running the `import` command:

```
$ terraformer import azure -r *
2020/11/12 12:57:00 Testing if Service Principal / Client Certificate is applicable for Authentication..
2020/11/12 12:57:00 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2020/11/12 12:57:00 Testing if Service Principal / Client Secret is applicable for Authentication..
2020/11/12 12:57:00 Testing if Managed Service Identity is applicable for Authentication..
2020/11/12 12:57:00 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2020/11/12 12:57:00 Using Obtaining a token from the Azure CLI for Authentication
2020/11/12 12:57:00 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```

System: Ubuntu on Windows (WSL)

**Comment by gvdm90** [comment]
I tried this same command with terraformer v 0.8.6, 0.8.7 and 0.8.8 but have the same error.

**Comment by rodolfobandeira** [comment]
@gvdm90 @devmast Did you figure out any workaround? Have you tried using a different authentication method instead of just the `az login`?

I just found out about the `Terraformer` project but when I tried, I'm getting the same error you're getting. Here are my results on MacOS:

```bash
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0
```

```bash
terraformer -v
version v0.8.9
```

**Comment by rodolfobandeira** [comment]
Hi there! I just found the solution!

Here is what I had on my `~/.zshrc` before:

```bash
export ARM_SUBSCRIPTION_ID=[0000000-0000-0000-0000-000000000000]
```

When I tried to inject the `ARM_ENVIRONMENT` I decided to remove the `[` `]` from there. I don't remember seeing that format on bash before. So after removing it and adding the `public` env, everything worked.

```bash
export ARM_SUBSCRIPTION_ID=0000000-0000-0000-0000-000000000000
export ARM_ENVIRONMENT=public
```

Cheers!

**Comment by riemers** [comment]
Instead of doing -r * try -r "*" or doing -r virtual_machine. That seemed to do the trick for me.

**Comment by DanielSSilva** [comment]
I have the same issue.
I've exported the arm subscription by doing 
`export ARM_SUBSCRIPTION_ID=0000000-0000-0000-0000-000000000000`

then tried to run 
`./terraformer-azure-linux-amd64 import azure -r my-rg`
tried with and without quotes. But I have the same error
```
2021/02/03 14:47:03 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/02/03 14:47:03 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/02/03 14:47:03 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/02/03 14:47:03 Testing if Managed Service Identity is applicable for Authentication..
2021/02/03 14:47:03 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/02/03 14:47:03 Using Obtaining a token from the Azure CLI for Authentication
2021/02/03 14:47:03 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```

**Comment by ufcu-david-gumm** [comment]
I have the same issue as stated above.
`2021/03/19 15:42:01 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/03/19 15:42:01 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/03/19 15:42:01 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/03/19 15:42:01 Testing if Managed Service Identity is applicable for Authentication..
2021/03/19 15:42:01 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/03/19 15:42:01 Using Obtaining a token from the Azure CLI for Authentication
2021/03/19 15:42:01 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"`

I have set my variables like below but that's not fixing the issue.
`export ARM_SUBSCRIPTION_ID=0000000-0000-0000-0000-000000000000
export ARM_ENVIRONMENT=public`

I have tried rolling back to older version of azurerm was well to try and fix it but still not working.

I'm running WSL version 2 with Ubuntu 20.04
I have tried Azure Cloud Shell and get the same error.

**Comment by dsacora** [comment]
Ok, so firstly this is an issue with using the "azure login" method. It works from cloud shell using a Service Principle (with secret, haven't tried with client certificate).

After running into this same issue I believe I have located the issue and I think it's not in terraformer but rather in go-autorest...but it's a deeper error than just the one. 

If you look at the error: 

An Azure Environment with name "" was not found: **autorest/azure**: There is no cloud environment matching the name "AZURECLOUD"

This is from the autorest/azure command. Tracing that error back we come to this file:
https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

Within that we have this block:

var environments = map[string]Environment{
	"AZURECHINACLOUD":        ChinaCloud,
	"AZUREGERMANCLOUD":       GermanCloud,
	"AZUREPUBLICCLOUD":       PublicCloud,
	"AZUREUSGOVERNMENTCLOUD": USGovernmentCloud,
}

However if we look at what is available we get this:
az cloud list -o table
IsActive    Name               Profile
----------  -----------------  ---------
True        AzureCloud         latest
False       AzureChinaCloud    latest
False       AzureUSGovernment  latest
False       AzureGermanCloud   latest

Now, I _did_ bodge it enough to get past this by hacking about the downloaded go-autorest (ie run go mod download then changing AZUREPUBLICCLOUD to be AZURECLOUD in ~/go/pkg/mod/github.com/\!azure/go-autorest/autorest@v0.11.12/azure/environments.go) and then building which got _further_ but then it still fell over.

microsoft@Azure:~/clouddrive/terraformer$ ./terraformer-azure import azure -r "*"
2021/03/22 22:53:18 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/03/22 22:53:18 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/03/22 22:53:18 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/03/22 22:53:18 Testing if Managed Service Identity is applicable for Authentication..
2021/03/22 22:53:18 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/03/22 22:53:18 Using Obtaining a token from the Azure CLI for Authentication
2021/03/22 22:53:18 Getting OAuth config for endpoint https://login.microsoftonline.com/ with  tenant
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x189375b]

Looking at the difference between when it succeeded with the SP and it with the "azure login" and it appears it failed to pick up the tenant although this may be a red-herring.

**Comment by JasonDonnelly** [comment]
I'm seeing this issue when running with service principal authentication as well as az login authentication.

Microsoft have replied to the open issue saying their not going to fix their go code.

Any update on a fix coming soon?  (Humbly bows) Thx.

**Comment by bugcy013** [comment]
Hi Team,

Still, I am getting the same error, any workaround is there

```
➜ terraformer version                                                             
Terraformer v0.8.18
```

```
➜ terraformer plan azure --output hcl --resource-group JumpServer -r "*" --verbose
2021/11/13 21:23:03 Testing if Service Principal / Client Certificate is applicable for Authentication..
2021/11/13 21:23:03 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2021/11/13 21:23:03 Testing if Service Principal / Client Secret is applicable for Authentication..
2021/11/13 21:23:03 Testing if Managed Service Identity is applicable for Authentication..
2021/11/13 21:23:03 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2021/11/13 21:23:03 Using Obtaining a token from the Azure CLI for Authentication
2021/11/13 21:23:03 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"

```

**Comment by serefacet** [comment]
Same issue here as well :/

```
terraformer plan azure -r mysql-backup --verbose
2022/02/22 14:58:15 Testing if Service Principal / Client Certificate is applicable for Authentication..
2022/02/22 14:58:15 Testing if Multi Tenant Service Principal / Client Secret is applicable for Authentication..
2022/02/22 14:58:15 Testing if Service Principal / Client Secret is applicable for Authentication..
2022/02/22 14:58:15 Testing if Managed Service Identity is applicable for Authentication..
2022/02/22 14:58:15 Testing if Obtaining a token from the Azure CLI is applicable for Authentication..
2022/02/22 14:58:15 Using Obtaining a token from the Azure CLI for Authentication
2022/02/22 14:58:15 An Azure Environment with name "" was not found: autorest/azure: There is no cloud environment matching the name "AZURECLOUD"
```

**Comment by dsacora** [comment]
The provider of go-autorest refuses to fix it as they don't want to break other stuff that has already had to implement work-arounds!

Try complaining on https://github.com/Azure/go-autorest/issues/624

**Comment by pguan-ntap** [comment]
Looks like they released a fix, someone try updating the dependency to autorest@v0.11.27
