### ISSUE TITLE
Multiple AWS Route53 zones with same domain name causes "duplicated resource" error

### ISSUE THREAD

**Issue by ktogo** [GoogleCloudPlatform/terraformer#66]
If you have multiple zones configured on AWS Route 53 with same domain name, Terraformer raises an error stating that resources are duplicated.

```
duplicate resource found: aws_route53_zone.example--com
```

**Comment by sergeylanzman** [comment]
@ktogo fixed in https://github.com/GoogleCloudPlatform/terraformer/pull/67
now it's create name of resource zoneID_domain `GDGHJDUDJ_example--com`

**Comment by ktogo** [comment]
@sergeylanzman Thanks for the quick fix! That should solve the issue so I've LGTMed it 👍

**Comment by sergeylanzman** [comment]
@ktogoI fixed it with temp hack in route53.
https://github.com/GoogleCloudPlatform/terraformer/pull/70
