### ISSUE TITLE
set ARM_SUBSCRIPTION_ID env var

### ISSUE THREAD

**Issue by ekorondy** [GoogleCloudPlatform/terraformer#674]
When running terraformer import azure command I get the following error:
set ARM_SUBSCRIPTION_ID env var

Please let me know where to set this variable.

**Comment by rodolfobandeira** [comment]
It depends on which OS you're using. Basically, you need to add that to your environment variables. On Linux/MacOS, it could be in `~/.profile` or `~/.bashrc` or `~/.zshrc`, etc. 
You can use that from the command line directly as well with:

```bash
ARM_SUBSCRIPTION_ID=your_id_here terraformer import azure -r virtual_machine
```

**Comment by himanbhard** [comment]
Using zsh 

{export ARM_SUBSCRIPTION_ID=xxxxxxx}

**Comment by eortega74** [comment]
Hi I have the same issue and I was set up the Subscription:
PS C:\Users\EMartinez2\repo\terraformer\azure> $ARM_SUBSCRIPTION_ID="xxxxxx-xxxx-xxxxxx-xxxxxx-xxxxx-xxxx-"
PS C:\Users\EMartinez2\repo\terraformer\azure> ./terraformer import azure -r resource_group
2022/09/21 15:16:18 set ARM_SUBSCRIPTION_ID env var
PS C:\Users\EMartinez2\repo\terraformer\azure>

Have the same error?

**Comment by smonda41** [comment]
> Hi I have the same issue and I was set up the Subscription: PS C:\Users\EMartinez2\repo\terraformer\azure> $ARM_SUBSCRIPTION_ID="xxxxxx-xxxx-xxxxxx-xxxxxx-xxxxx-xxxx-" PS C:\Users\EMartinez2\repo\terraformer\azure> ./terraformer import azure -r resource_group 2022/09/21 15:16:18 set ARM_SUBSCRIPTION_ID env var PS C:\Users\EMartinez2\repo\terraformer\azure>
> 
> Have the same error?

I am also facing the same issue. plz help

**Comment by dani3lheidemann** [comment]
@smonda41 & @eortega74 you have to mark it as an environment variable in Powershell using:

```` powershell
$env:ARM_SUBSCRIPTION_ID="xxxxxx-xxxx-xxxxxx-xxxxxx-xxxxx-xxxx"
````

Hope that helps :)
