### ISSUE TITLE
Terraformer and Azure Cloud Shell (bash)

### ISSUE THREAD

**Issue by MariuszG7** [GoogleCloudPlatform/terraformer#680]
I am trying to install the Terraformer using the Installation instructions you have here, but cant get it to work.
Not sure what I am missing....

>  git clone ....
>  cd terraformer  
>  go mod download
>  go run build/main.go azure

got versions.tf with:
 terraform {
   required_providers {
     azure = {
       source = "hashicorp/azurerm"
     }
   }
   required_version = ">= 0.13"
 }

> terraform init

does what it does successfully... 
at this point not sure what to do here next...
like terraformer command is not even recognized... but like I said... not sure what I am missing here to get it to work. Instructions are missing some detail?

**Comment by riemers** [comment]
Your not mistaking "terraform" with "terraformer" ?

**Comment by sergeylanzman** [comment]
look good, you can start use terraformer
https://github.com/GoogleCloudPlatform/terraformer#use-with-azure
