### ISSUE TITLE
How to use it in alicloud? You can give me a tutorial

### ISSUE THREAD

**Issue by smallhorsegg** [GoogleCloudPlatform/terraformer#681]
in this case , i am running  terraformer in shell， but  there was no response，What information do I need to provide？

my command info：
terraformer import alicloud --resources=ecs -p --regions=cn-qingdao --profile=default

**Comment by cofyc** [comment]
this patch will fix this issue: https://github.com/GoogleCloudPlatform/terraformer/pull/689
