### ISSUE TITLE
Datadog Tags ordering

### ISSUE THREAD

**Issue by nghesquier** [GoogleCloudPlatform/terraformer#682]
Hi,

I'm using terraformer on a jenkins job to weekly backup my monitors and dashboards.

It then automatically creates a pull request if some changes are detected.

My problem is about tags on the monitor. The ordering of the tags in the created file doesn't seem consistent. Therefore for my case it will create a new PR even though the only change was the order in the tag list.

I think it would be a nice thing to have consistent ordering.
What do you think?

**Comment by nyetsche** [comment]
The underlying issue is covered in #526 but there's not a solution yet. Go maps aren't sorted, so there would have to some logic added to manually sort them before writing.
