### ISSUE TITLE
v0.8.9 gcp instances not supported service

### ISSUE THREAD

**Issue by hanerd** [GoogleCloudPlatform/terraformer#693]
When attempting to import GCP instances in 0.8.9 GCP instances is not supported.

```
terraformer plan google --resources=instances --projects=<project>--regions=us-central1-a,us-east1-b,us-central1-a
2020/12/01 09:46:41 google importing project <project> region us-central1-a
2020/12/01 09:46:42 google importing... instances
2020/12/01 09:46:42 gcp: instances not supported service
```

It looks like this was fixed in 0.8.8 so possibly a regression? #604 

This does work when building from source, so it seems to be only in the release that it doesn't.

**Comment by sergeylanzman** [comment]
fixed in master and in 0.8.10
