### ISSUE TITLE
Unable to use terraform version 0.12.20

### ISSUE THREAD

**Issue by arik-porat** [GoogleCloudPlatform/terraformer#704]
Hi,
I'm using terraform 0.12.20 but when I run terraformer the state file get 0.12.29 version.
Any idea why?

$ terraform -version
Terraform v0.12.20
+ provider.aws v2.70.0

Your version of Terraform is out of date! The latest version
is 0.14.2. You can update by downloading from https://www.terraform.io/downloads.html

$ ./terraformer-aws import  aws --resources=s3 --regions=us-west-2 --filter="Name=bucket;Value=arik-crr-test1-us-west-2"
2020/12/09 14:30:28 aws importing region us-west-2
2020/12/09 14:30:36 aws importing... s3
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--elasticbeanstalk-002D-us-002D-west-002D-2-002D-760370564012
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--ut-002D-inapp-002D-test
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--ut-002D-sf-002D-debug-002D-logs
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--ut-002D-profiles
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--aws-002D-athena-002D-query-002D-results-002D-760370564012-002D-us-002D-west-002D-2
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--motion-002D-data-002D-export
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--sendbox-002D-cloudtrail
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket_policy.tfer--sendbox-002D-cloudtrail
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--undertone-002D-sf-002D-logs
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--ut-002D-cookie-002E-test
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--arik-002D-crr-002D-test1-002D-us-002D-east-002D-1
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--arik-002D-crr-002D-test1-002D-us-002D-west-002D-2
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket.tfer--ut-002D-motion-002E-sample
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket_policy.tfer--elasticbeanstalk-002D-us-002D-west-002D-2-002D-760370564012
2020/12/09 14:31:06 Refreshing state... aws_s3_bucket_policy.tfer--ut-002D-profiles
2020/12/09 14:31:07 Refreshing state... aws_s3_bucket.tfer--ut-002D-sf-002D-logs
2020/12/09 14:31:07 Refreshing state... aws_s3_bucket.tfer--ut-002D-sf-002D-logs-002D-flattened
2020/12/09 14:31:20 aws Connecting....
2020/12/09 14:31:20 aws save s3
2020/12/09 14:31:20 aws save tfstate for s3

$ cat generated/aws/s3/terraform.tfstate
{
    "version": 3,
    "terraform_version": "0.12.29",
    "serial": 1,
    "lineage": "82a029f1-ebe3-2000-22b3-08c2191c48c8",
    "modules": [
...

**Comment by sergeylanzman** [comment]
You can edit state to 0.12.20, it's working
Terraformer not call to terraform and don't use version on you laptop
