### ISSUE TITLE
Clarify in docs how to find attribute names to filter on

### ISSUE THREAD

**Issue by schollii** [GoogleCloudPlatform/terraformer#708]
Awesome tool!

Now say I want to import all security groups for a specific VPC, how would I go about finding the filter name? If I look at https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html, I can see the --filter shows `vpc-id` (hyphen, not underscore), but that does not work. It looks like it has to be `vpc_id`, which I'm guessing is the field as named by terraform in `aws_security_group`. So the docs should say that `Name` must be a terraform attribute name, not an AWS CLI attribute name.

The docs should give an example of filter on 2 resource types eg `terraformer import aws -r sg,vpc --filter Type=sg;Name=vpc_id;Value=VPC_ID --filter Type=vpc;Name=id;Value=VPC_ID` seems to work. Notice how the Name is different. 

I could submit PR if that helps.

**Comment by sergeylanzman** [comment]
If `terraformer import aws -r sg,vpc --filter Type=sg;Name=vpc_id;Value=VPC_ID --filter Type=vpc;Name=id;Value=VPC_ID` working? we happy get new PR :)

**Comment by schollii** [comment]
Submitted PR #709

**Comment by schollii** [comment]
This can be closed as my pr fixes it
