### ISSUE TITLE
AWS iops attribute is only valid for io1 and io2 type EBS volumes, not gp2, sc1 and st1 types.

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/terraformer#715]
Description:  When Terraformer generates Terraform code for AWS EBS volume types gp2, sc1 and st1 the output includes an `iops` attribute which is invalid syntax.

> https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ebs_volume
> _iops - (Optional) The amount of IOPS to provision for the disk. **Only valid for type of io1 or io2**._
> 

Expected: Import AWS resources and be able to use the resulting Terraform code without modification.

Actual: Terraformer will output invalid Terraform code.

Reproducing:

1. Launch EC2 instance.
1. Import via terraformer (example: `terraformer import aws --resources=ec2_instance --filter=Name=id\;Value=i-07a2282453eb0afd5`)
1. Terminate EC2 instance (or don't, it's not essential).
1. Run `terraform apply`
1. Get `Error: error creating resource: iops attribute not supported for root_block_device with volume_type gp2`
1. The error is fatal; `terrform apply` will not not launched any resources. 

Running `terraform plan` will not report the error in the Terraform code.

The `iops = "100"` (excerpted from `generated/aws/ec2_instance/instance.tf`) is invalid syntax:
```
  root_block_device {
    delete_on_termination = "true"
    encrypted             = "false"
    iops                  = "100"
    volume_size           = "8"
    volume_type           = "gp2"
  }
```
Tested on:
```
$ terraformer version
Terraformer v0.8.10
$ terraform version
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.21.0
```
Error also occurs testing with prior versions of terraform.

**Comment by meshuga** [comment]
IOPS is also valid for gp3.
To add checks for throughput in gp3 too, as is also being checked in https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_instance.go
