### ISSUE TITLE
terraform plan leads to error "Error: Failed to read state file" after generating files with --compact

### ISSUE THREAD

**Issue by k3rst1n** [GoogleCloudPlatform/terraformer#742]
Hi there,

I was able to create successfully my terraform .tf files using terraformer, however when I now try to execute _plan_ (and _apply_) I am receiving the following error (_terraform init_ ran successfully):

```
Error: Failed to read state file

The state file could not be read: read terraform.tfstate: The process cannot
access the file because another process has locked a portion of the file.

```
I am using the following versions:

```
 .\terraformer.exe -v
version v0.8.10

terraform version
Your version of Terraform is out of date! The latest version
is 0.14.4. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.42.0
```

I used the following command to generate my .tf files:
```
.\terraformer.exe import azure --path-pattern deployment -r "resource_group,virtual_network,virtual_machine,storage_account,public_ip,public_ip_prefix,network_security_group,network_interface,managed_disk" -R "kr-rg-bust1-test-001"
```

Directory content:
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---          13/01/2021    13:59                .terraform
la---          13/01/2021    13:58           1462 linux_virtual_machine.tf
la---          13/01/2021    13:57           2186 network_interface.tf
la---          13/01/2021    13:57           1428 network_security_group.tf
la---          13/01/2021    13:57           2367 outputs.tf
la---          13/01/2021    13:59            153 provider.tf
la---          13/01/2021    13:57            969 public_ip.tf
la---          13/01/2021    13:57            149 resource_group.tf
la---          13/01/2021    13:57           1314 storage_account.tf
la---          13/01/2021    13:57          35632 terraform.tfstate
la---          13/01/2021    13:57            111 variables.tf
la---          13/01/2021    13:58            696 virtual_network.tf
la---          13/01/2021    13:58           1522 windows_virtual_machine.tf
```

I used resource manager and process explorer to see if any processes are locking the state file but neither of those tools shows anything. I've also tried a reboot without any success.

If someone has an idea as to what is causing the problem or what else I can try, that'd be amazing!

Thanks a lot,
Kerstin

**Comment by BSick7** [comment]
I have the same issue.
If you have connections between different resource types, the tool tries to bridge them through local tfstate files.
When you generate these resources to the same output directory, it relies on a single `terraform.tfstate` file which is trying to be read by terraform while being written.
This seems like an odd way to connect resources.

**Comment by k3rst1n** [comment]
Thanks @BSick7, nice finding! Have you found a way to just have one state file and therefore run terraform plan and apply just one for the whole deployment rather than separately for each service (as designed with the default directory structure)?

**Comment by kerstin-ramer-swo** [comment]
Still looking to use the --compact parameter, please leave issue open.

**Comment by k3rst1n** [comment]
Still looking to use the --compact parameter, please keep issue open.

**Comment by amosting** [comment]
Hello does anyone have a solution to this issue?
