### ISSUE TITLE
Kubernetes Missing Daemonset Resource

### ISSUE THREAD

**Issue by jschwartzy** [GoogleCloudPlatform/terraformer#743]
Using terraformer version v0.8.10
Hashicorp Kubernetes provider 1.13.3

Running `./terraformer import kubernetes list`

Result:
`apiservices
certificatesigningrequests
clusterrolebindings
clusterroles
configmaps
cronjobs
csidrivers
deployments
endpoints
horizontalpodautoscalers
ingresses
jobs
limitranges
mutatingwebhookconfigurations
namespaces
networkpolicies
persistentvolumeclaims
persistentvolumes
poddisruptionbudgets
pods
podsecuritypolicies
priorityclasses
replicationcontrollers
resourcequotas
rolebindings
roles
secrets
serviceaccounts
services
statefulsets
storageclasses
validatingwebhookconfigurations
`

Daemonset support exists in the provider itself:

[https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/daemonset](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/daemonset)

Attempting to import a daemonset resource results in an error

**Comment by sergeylanzman** [comment]
strange... 
because kubernetes code in terraformer merge between clusters support service and terraform provider automatically on the fly
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/kubernetes/kubernetes_provider.go#L90-L133

**Comment by jschwartzy** [comment]
Issue seems to be coming from this method in providers/kubernetes/utils.go:
```
func extractTfResourceName(kind string) string {
	return "kubernetes_" + strcase.ToSnake(kind)
}
```

Terraform defines the resource as: kubernetes_daemonset

I added logging statements in the kubernetes_provider.go for those types that are filtered out:
```
// filter to resource that are supported by terraform kubernetes provider
    if _, ok := resp.ResourceTypes[extractTfResourceName(resource.Kind)]; !ok {
      log.Println(resource.Kind)
      log.Println(extractTfResourceName(resource.Kind))
      continue
    }
```
This is the output:

```
2021/01/14 12:34:06 DaemonSet
2021/01/14 12:34:06 kubernetes_daemon_set
```

Since the result is **kubernetes_daemon_set** it doesn't match the provider's definition of **kubernetes_daemonset** and is skipped.
