### ISSUE TITLE
Error 400: Invalid value for field 'region

### ISSUE THREAD

**Issue by OmarEltamasehy** [GoogleCloudPlatform/terraformer#746]
Appreciate your support as we try to run the below command 

`terraformer import google --resources=routers,forwardingRules,addresses,iam --regions=us-central1-a --projects=<my-project>`

but unfortunately we faced the below error for (routers, forwardingRules, addresses) but resource (iam) is ok.

> googleapi: Error 400: Invalid value for field 'region': ''. Must be a match of regex '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalid

Also please advice which terraformer resource I can use in my command to get my external IP (static IP).

**Comment by sergeylanzman** [comment]
us-central1-a it's zone A
us-central1 it's region
