### ISSUE TITLE
Importing wildcard DNS records from AWS Route53 fail

### ISSUE THREAD

**Issue by Mallear** [GoogleCloudPlatform/terraformer#75]
Hello,

Terraformer's output is empty when importing wildcard DNS records from Route53.

`terraformer import aws --resources=route53 --filter=aws_route53_record='myzoneid_*.example.com._CNAME' --regions=eu-west-3`

There is no problem importing this record from `terraform import`.

**Comment by sergeylanzman** [comment]
fixed

**Comment by lpossamai** [comment]
> terraformer import aws --resources=route53 --filter=aws_route53_record='myzoneid_*.example.com._CNAME' --regions=eu-west-3

Sorry to be commenting on such an old issue, but this doesn't work for me... I've created a question [here](https://github.com/GoogleCloudPlatform/terraformer/discussions/1174).

**Comment by leandroblanc** [comment]
Try ```terraformer import aws --resources=route53 --connect=true --regions=eu-west-1 --profile=default```

**Comment by lpossamai** [comment]
> Try `terraformer import aws --resources=route53 --connect=true --regions=eu-west-1 --profile=default`

Yes, this works. But I want to import only records of a specific zone. I want to be able to import for a specific domain only.

**Comment by joelgaria** [comment]
> 

have you resolved this problem?

**Comment by tunyioh** [comment]
terraformer import aws --resources=route53 --filter=route53={hostedzoneid} --profile={sso profile name}

this works for me
