### ISSUE TITLE
Not able to import s3 buckets with a specific tag Key. Only tag Key + list Values works.

### ISSUE THREAD

**Issue by vainkop** [GoogleCloudPlatform/terraformer#756]
Hi.

I was trying to use the following query to get all buckets with tag where Key=Abc & it doesn't as I expected:
`terraformer import aws -v --resources=s3 --regions=us-east-1,eu-central-1 --filter="Name=tags.Abc"`

The query above imports all buckets containing the tag with Key=Abc, but also imports buckets which do not have it at all.

I had to parse the buckets with `s3api` to get the list of all buckets with tag Key=Abc + their values & then import all the buckets specifying the exact values like so:
`terraformer import aws -v --resources=s3 --regions=us-east-1,eu-central-1 --filter="Name=tags.Abc;Value=value1:value2:value3"`

I guess that some adjustments need to be made to https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/s3.go#L126 by @sergeylanzman or @meshuga 

Thanks for the great tool btw! :)

**Comment by vainkop** [comment]
@meshuga I'll try to build & run from your commit. Thanks!

Btw, is there a way to import policies attached to tagged buckets as well?

I had to import all s3 resources to get policies too & when I all the filter & list the tags on the buckets with values explicitly, then buckets do get imported, but not their policies.

**Comment by meshuga** [comment]
Yeah, that's not an easy thing, filters are complicated and an additional mechanism would need to be added to support proper filtering of policies. I'll move the policies to be inlined.

**Comment by vainkop** [comment]
> Yeah, that's not an easy thing, filters are complicated and an additional mechanism would need to be added to support proper filtering of policies. I'll move the policies to be inlined.

Meaning that they'll get imported along with their respective s3 buckets?
