### ISSUE TITLE
Issue with importing GCP resources | dial tcp 169.254.169.254:80: connect: host is down

### ISSUE THREAD

**Issue by shivamgupta211** [GoogleCloudPlatform/terraformer#777]
Hi everyone,
I am not able to import the google resources.

I followed the installation process in the Readme but still not able to import the resources. 
Always getting `dial tcp 169.254.169.254:80: connect: host is down`
Am i missing something here?
I am using Mac(10.15.6) and terraform(0.14.5)

init.tf

> terraform {
  required_providers {
    google = {
      source = "hashicorp/google-beta"
    }
  }
  required_version = ">= 0.13"
}

did `terraform init` as well 
but after running the following command

`terraformer import google --resources=dns --regions=us-central1,asia-south1 --projects=<project> --connect=true`

getting following error

> 2021/02/04 10:43:15 google importing project <project> region us-central1
2021/02/04 10:43:16 google importing... gcs
2021/02/04 10:43:16 Get "https://storage.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=<project>": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... dns
2021/02/04 10:43:16 Get "https://dns.googleapis.com/dns/v1/projects/<project>/managedZones?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readonly%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... gke
2021/02/04 10:43:16 Get "https://container.googleapis.com/v1beta1/projects/<project>/locations/-/clusters?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 Get "https://container.googleapis.com/v1beta1/projects/<project>/locations/-/clusters?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... instances
2021/02/04 10:43:16 google Connecting....
2021/02/04 10:43:16 google save gcs
2021/02/04 10:43:16 google save tfstate for gcs
2021/02/04 10:43:16 google save dns
2021/02/04 10:43:16 google save tfstate for dns
2021/02/04 10:43:16 google save instances
2021/02/04 10:43:16 google save tfstate for instances
2021/02/04 10:43:16 google importing project <project> region asia-south1
2021/02/04 10:43:16 google importing... gcs
2021/02/04 10:43:16 Get "https://storage.googleapis.com/storage/v1/b?alt=json&prettyPrint=false&project=<project>": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_write": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... dns
2021/02/04 10:43:16 Get "https://dns.googleapis.com/dns/v1/projects/<project>/managedZones?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readonly%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... gke
2021/02/04 10:43:16 Get "https://container.googleapis.com/v1beta1/projects/<project>/locations/-/clusters?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 Get "https://container.googleapis.com/v1beta1/projects/<project>/locations/-/clusters?alt=json&prettyPrint=false": Get "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform": dial tcp 169.254.169.254:80: connect: host is down
2021/02/04 10:43:16 google importing... instances
2021/02/04 10:43:16 google Connecting....
2021/02/04 10:43:16 google save gcs
2021/02/04 10:43:16 google save tfstate for gcs
2021/02/04 10:43:16 google save dns
2021/02/04 10:43:16 google save tfstate for dns
2021/02/04 10:43:16 google save instances
2021/02/04 10:43:16 google save tfstate for instances

Need some urgent help. Cheers in advance.

**Comment by dkochiashvili** [comment]
I fixed it by setting `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
