### ISSUE TITLE
Error while importing GCP resources using terraformer

### ISSUE THREAD

**Issue by tanvipk** [GoogleCloudPlatform/terraformer#779]
Hi,

**Issue 1:**
Ive been trying to import my gcs buckets and I used this command to do so
terraformer import google --resources=gcs --regions=<my_region_name> --projects=<my_project_id>

This command is able to read the bucket names, but fails to get the IAM policy of the bucket. Below is the error that I get:

2021/02/05 11:46:46 Fail read resource from provider, trying import command
2021/02/05 11:46:46 Error when reading or editing Resource "storage bucket \"b/<bucket_name>\"" with IAM Member: Role "" Member "": Error retrieving IAM policy for storage bucket "b/<bucket_name>": googleapi: Error 403: Insufficient Permission, insufficientPermissions

When I do "gsutil iam get gs://<bucket_name>" , I get the IAM policies of that bucket

Even though the service account I'm using has Storage Admin role. I tried giving it owner role as well, but didn't work.

**Issue 2:**
when I try to import the gcp instances using the command :
terraformer import google --resources=instances --regions=<my_region_name> --projects=<my_project_id>

I do not get any instances at all.

But when I do gcloud compute instance list I can see all my instances.

Please help me resolve these issues asap

Thank you

**Comment by amankhare94** [comment]
I am facing similar issues while trying to import my existing GCP infrastructure using terraformer.
