### ISSUE TITLE
Not able to install terraformer

### ISSUE THREAD

**Issue by MayurBMahajan** [GoogleCloudPlatform/terraformer#79]
Hi, I am newbie here.
**OS: Windows 10**
Following the Readme.md, I am able to clone the git repo. But after that I hit complete road block.

Can you please add documentation for Windows as well. 
I have installed go lang as well. 
but not sure how to execute this command ?

**Run GO111MODULE=on go mod vendor
Run go build -v
Copy your Terraform provider's plugin(s) to folder ~/.terraform.d/plugins/{darwin,linux}_amd64/, as appropriate.**

**Comment by sergeylanzman** [comment]
It's never tested on windows....
I think it's can work in windows with small changes..
on windows terraform use `%APPDATA%\terraform.d\plugins` and not `~/.terraform.d/plugins`
terraformer use `$HOME/.terraform.d/plugins` https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/provider_wrapper/provider.go#L117
maybe more small changes.

**Comment by gliptak** [comment]
@sergeylanzman would you be interested in a PR pointing the plugins to the current directory? the install process would need to change:

+ run ```terraform init``` against an ```init.tf``` installing the platform correct plugin relative to current directory
```
# Configure the AWS Provider
provider "aws" {
}
```
+ update code to read relative to current directory

I tested this change above on Windows against AWS.

**Comment by sergeylanzman** [comment]
@gliptak Good idea.
1. Find provider in current folder .terraform/ (regular path with terraform after `terraform init`)
2. If not find provider in current folder => fallback to $HOME/.terraform.d/plugins.

It's can be more easy for install process.

**Comment by sergeylanzman** [comment]
Windows support now 
Thanks @gliptak

**Comment by gliptak** [comment]
@sergeylanzman please generate a Windows binary with next release at https://github.com/GoogleCloudPlatform/terraformer/releases

**Comment by imkhan1104** [comment]
did you manage to get it to work @MayurBMahajan ?
