### ISSUE TITLE
 Filters not working on AWS

### ISSUE THREAD

**Issue by sandk985** [GoogleCloudPlatform/terraformer#793]
Hi Champs,

The below filter doesn't work for sg, igw 

can someone pls correct/guide on this?

OR Is it possible to have one common filter to fetch all resources running under a specific vpc? That's my ultimate goal. 
Doc says that's feasible but not sure about the right syntax, pls help.

terraformer import aws -r vpc,subnet,route_table,sg,igw --filter="Type=vpc;Name=vpc_id;Value=vpc-xx" --filter="Type=subnet;Name=vpc_id;Value=vpc-xx" --filter="Type=route_table;Name=vpc_id;Value=vpc-xx" --filter="Type=sg;Name=vpc_id;Value=vpc-xx" --filter="Type=igw;Name=vpc_id;Value=vpc-xx" 

Thanks

**Comment by tn819** [comment]
Would be solved here: https://github.com/GoogleCloudPlatform/terraformer/pull/816 so let's get it merged in!

**Comment by meshuga** [comment]
@sandk985 You can take a look at what been done in #789. Most of the resources have field vpc_id, so you can in theory just filter for that field. More info: https://github.com/GoogleCloudPlatform/terraformer#field-name-only

@tn819 #816 is a nice optimisation of the filtering functionality as as of today, only very limited number of calls to a cloud provider pass the filters. That results in a big dataset of resources that temporarily is stored in terraformer memory. I got colleagues at my work who unfortunately suffer from this as some cloud accounts contain thousands of resources. For now I can recommend to run the tool on a machine with high amount of memory and keep adding PRs like the one you mentioned to improve performance of the tool :) The PR doesn't seem to be related to the issue.

**Comment by skambiente** [comment]
@meshuga Thanks for the response. I have already tried the field name filter (tags) but didn't work.
In one month of practice, I have realized that there is a lot of confusion regarding filters especially with AWS so it would be worth posting a tutorial or video on the same which will help many people who are going through this pane. If the tag filter works then it will become much easier to tag through tag editor and filter/import via terraformer. Many thanks on behalf of all aws reverse engineers who are stuck in pain, deadlines, and awaiting clear help on this.

**Comment by skambiente** [comment]
Terraformer import works excellent as it fetches all dependencies too. 
Until we get AWS resource filters working ....we can use the import feature and then delete the not-needed resources. (the trick is useful for SMB setups) 
e.g   terraform state list.  then ..terraform state rm xxresourcexx

One more step as we have to delete the resource from the config file manually.
So ..any command to delete to resource from config file too ?

**Comment by meshuga** [comment]
1. A post on terraformer and filters is a great idea. I can think of several examples of use cases and what filters to apply
2. Unfortunately, filters don't work with dependencies. I already faced that issue when tried to fix S3 buckets and accompanying bucket policies defined as separate resources. I ended up adding bucket policies to bucket resource. I'd need to think how that could be easily solved. The same problems are with security groups and security group rules - that's not yet solved.
3. Thanks for new cases where filters aren't working as expected - can work on them :)

**Comment by meshuga** [comment]
Ad 2
Thanks @nicolam1 for reporting this issue! I just found out #750 broke filters. Will fix that.

**Comment by skambiente** [comment]
Does anyone get success to filter s3, lambda based on vpc or tags? 
I tried multiple ways but it failed to filter and fetches all resources.
Providing working filters/command will be highly appreciated, thanks

**Comment by skambiente** [comment]
@meshuga Thanks a lot for fixing the filters issue. It's a great help.

I have verified that vpc and tag filter is working now 
example
terraformer import aws -r alb --filter="Name=vpc_id;Value=vpc-xxxxxxxxxx" (filter based on vpc id )

terraformer plan aws --resources=ec2_instance --filter="Name=tags.Env;Value=rc" --regions=us-west-2 (filter based on tagging..Name=Env, Value=rc)

Cheers!

**Comment by skambiente** [comment]
@meshuga please feel free to close this ticket, thanks.

**Comment by adsanz** [comment]
I have found a similar issue, when running this:

```
terraformer plan aws -r sg  --filter="Type=sg;Name=vpc_id;Value=vpc-XXXXXX" --profile=myprofile --path-output .
```

It gives all the results, basically is not filtering anything, debug does not show anything interesting (I can attach it if requested) 

However if I remove the Type

```
terraformer plan aws -r sg  --filter="Name=vpc_id;Value=vpc-XXXXXX" --profile=myprofile --path-output .
```

It does apply filtering.

I also checked if it was something general, filter with type works with route53.... So more than a "issue" related to code looks like an issue related to documentation on filters... How is this supposed to work? What should be put on type?

**Comment by ramonmpa** [comment]
> I have found a similar issue, when running this:
> 
> ```
> terraformer plan aws -r sg  --filter="Type=sg;Name=vpc_id;Value=vpc-XXXXXX" --profile=myprofile --path-output .
> ```
> 
> It gives all the results, basically is not filtering anything, debug does not show anything interesting (I can attach it if requested)
> 
> However if I remove the Type
> 
> ```
> terraformer plan aws -r sg  --filter="Name=vpc_id;Value=vpc-XXXXXX" --profile=myprofile --path-output .
> ```
> 
> It does apply filtering.
> 
> I also checked if it was something general, filter with type works with route53.... So more than a "issue" related to code looks like an issue related to documentation on filters... How is this supposed to work? What should be put on type?

To filter multiple resources where they share the same property to filter you must use the ':' to separate each value of the property you want to filter. 

Example Filter SG and VPC resources where SG Id = sg-id and VPC Id = vpc-id:

```
terraformer import aws -r sg,vpc --filter="Type=sg:vpc" --filter="Name=id;Value=sg-id:vpc-id"
```
```
...
Number of resources for service sg: 1
Number of resources for service vpc: 1
Refreshing state... aws_vpc.tfer--vpc-id
Refreshing state... aws_security_group.tfer--sg-name_sg-id
Filtered number of resources for service sg: 1
Filtered number of resources for service vpc: 1
...
```

This was the only way I found that works to filter multiple resources of different resources.
