### ISSUE TITLE
aws securityhub - panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x441490c]

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/terraformer#800]
mikez@my-pc: terraformer % terraformer import aws --resources=securityhub --connect=true --profile=mikez-biz
2021/02/17 19:32:14 aws importing default region
2021/02/17 19:32:26 aws importing... securityhub
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x441490c]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityhubGenerator).addMembers(0xc000751800, 0xc000661a98, 0xc001a99220, 0xc, 0xc0005f8100, 0x0)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/securityhub.go:92 +0x22c
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*SecurityhubGenerator).InitResources(0xc000751800, 0xc001c8b418, 0x10fd6ec)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/securityhub.go:50 +0x246
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).InitResources(0xc000c84d20, 0x9bac860, 0xc000c84d20)
	github.com/GoogleCloudPlatform/terraformer/providers/aws/aws_facade.go:61 +0x38
github.com/GoogleCloudPlatform/terraformer/cmd.buildServiceResources(0xc000a3b320, 0xb, 0x9b8b480, 0xc000138b90, 0xc0016a6220, 0x1, 0x1, 0xf28a088, 0x0, 0x0, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:145 +0x1cc
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x9b8b480, 0xc000138b90, 0xc0016a6220, 0x1, 0x1, 0xf28a088, 0x0, 0x0, 0x920f218, 0x1e, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:123 +0x485
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc0016a61f0, 0x1, 0x1, 0xf28a088, 0x0, 0x0, 0x920f218, 0x1e, 0x919c120, 0x9, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x238
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0013562c0, 0xc0016b21e0, 0x0, 0x3, 0x0, 0x0)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:59 +0x51b
github.com/spf13/cobra.(*Command).execute(0xc0013562c0, 0xc0016b21b0, 0x3, 0x3, 0xc0013562c0, 0xc0016b21b0)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001263340, 0xc00125ad30, 0xc000138000, 0x9374f10)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x9a3e480, 0xc00125ad30)
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x2a
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x65

Ran terraform init with this versions.tf file:

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.28.0"
    }
  }
}

**Comment by t0rr3sp3dr0** [comment]
@meshuga, would you be able to create a PR that exclusively addresses this issue? I see that your commit is part of PR #806, but it is still in draft and has some dependencies. The Securit Hub patch doesn't require the new AWS SDK to work and creating another PR would allow us to solve this problem before #806 gets merged.

**Comment by t0rr3sp3dr0** [comment]
Fixed by #806
