### ISSUE TITLE
ExactlyOne error after importing routes

### ISSUE THREAD

**Issue by ericraskin** [GoogleCloudPlatform/terraformer#805]
I did a full import of my entire project (resources="*").  I am now running plan on each directory to see how close I got to a valid import.  

My routes are not imported properly.  I get this error from "terraform plan":

> Error: ExactlyOne
> 
>   on compute_route.tf line 1, in resource "google_compute_route" "tfer--default-002D-route-002D-01f629a174d2c70b":
>    1: resource "google_compute_route" "tfer--default-002D-route-002D-01f629a174d2c70b" {
> 
> "next_hop_instance": one of
> `next_hop_gateway,next_hop_ilb,next_hop_instance,next_hop_ip,next_hop_vpn_tunnel`
> must be specified

This occurs for all my pre-defined virtual networks (generated by Google when the project was created).  For example:

>  resource "google_compute_route" "tfer--default-002D-route-002D-01f629a174d2c70b" {
>   description = "Default local route to the subnetwork 10.172.0.0/20."
>   dest_range  = "10.172.0.0/20"
>   name        = "default-route-01f629a174d2c70b"
>   network     = "data.terraform_remote_state.networks.outputs.google_compute_network_tfer--default_self_link"
>   priority    = "0"
>   project     = "paslists"
> }

The next hop listed on the Google Console route screen is "Virtual network default".

How do I repair this?

**Comment by checco** [comment]
From Terraform docs:

> A Route resource must have exactly one specification of either nextHopGateway, nextHopInstance, nextHopIp, nextHopVpnTunnel, or nextHopIlb.

So, you can extract all the nexhop by yourself an put them on your routes with this command:
```
for route in `gcloud compute routes list | grep "default-route" | awk '{print $1}'` ; do echo ${route}; gcloud compute routes describe ${route} | grep next; done
```

**Comment by garettmd** [comment]
This issue is still occurring for me as well.
