### ISSUE TITLE
Datadog Downtime resource - terraformer extraction downtime by Tagname

### ISSUE THREAD

**Issue by stwe11** [GoogleCloudPlatform/terraformer#818]
Hi,

I found an issue extracting downtimes grouped by monitor Tags.
The downtime.tf file contains a duplicate monitor definition, by monitor Id and by monitor Tag

ex:
resource "datadog_downtime" "tfer--downtime_31360272" {
  active       = "false"
  disabled     = "false"
  end          = "1614636000"
  message      = "Automatically disable al the day-time monitors"
  **monitor_id   = "0"
  monitor_tags = ["nightly"]**

to fix this issue I removed all monitor_id = "0" strings via sed before save the file.

Cheers,
Stefano.

**Comment by skarimo** [comment]
Hi, @stwe11 we resolved the root cause of this behavior in the provider it self. Thanks for the report!
