### ISSUE TITLE
Add support for service_level_objective widget in Datadog Dashboards 

### ISSUE THREAD

**Issue by plynch-magnolia** [GoogleCloudPlatform/terraformer#834]
It is not currently possible to import a Datadog dashboard that contains the Service Level Objective(SLO) widget when the global_time option is selected.

## Terraformer Version
version v0.8.11

## Error Message
datadog error initializing resources in service dashboard, err: Data failed to match schemas in oneOf(WidgetDefinition)

## Terraform Provider Reference
https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard#nestedblock--widget--service_level_objective_definition

## Workaround
You presently have to remove the global_time option from the widget, run the terraformer, and then manually add the widget back which can then be imported into your project state. 

## Expected Behavior
The widget is imported like all the other widgets currently found in the Datadog provider

**Comment by therve** [comment]
I believe it's blocked by https://github.com/DataDog/terraform-provider-datadog/issues/994. Once fixed it should work as expected.

**Comment by skarimo** [comment]
You might be using an older version of the datadog provider. Could you make sure you are using the latest datadog provider version. I was able to successfully import a dashboard with the SLO widget with datadog provider version `2.23.0` although `global_time_target` param might be missing.

**Comment by plynch-magnolia** [comment]
I am also using 2.23.0 as the data dog provider version. I updated the comment above to specify it only happens when the global_time option is selected.
