### ISSUE TITLE
support terraform 0.14.x

### ISSUE THREAD

**Issue by vinayluzrao** [GoogleCloudPlatform/terraformer#835]
If the support is already there, make that clear in README.md

**Comment by aamarques** [comment]
I have the same question.

**Comment by meshuga** [comment]
Support for new path for plugins was added in #765 but it seems we need to fix file generation. TF 0.14 throws following error:
```
Error: Invalid legacy provider address

This configuration or its associated state refers to the unqualified provider
"aws".

You must complete the Terraform 0.13 upgrade process before upgrading to later
versions.
```

**Comment by Jeiwan** [comment]
A workaround for `Invalid legacy provider address` error:
```
terraform state replace-provider -- -/google hashicorp/google
```

Or:
```
terraform state replace-provider -- -/aws hashicorp/aws
```

**Comment by meshuga** [comment]
Thanks for the workaround!

Yes, terraformer uses legacy way of addressing the providers. That was already fixed in the PR and now am working on refactoring existing code to use new Terraform API. That takes some time but it's now a straightforward job 🥳

**Comment by aamarques** [comment]
Thanks @meshuga and @Jeiwan !
