### ISSUE TITLE
terraformer import aws EKS : panic: interface conversion: interface {} is nil, not []interface {}

### ISSUE THREAD

**Issue by vsloboda-tibco** [GoogleCloudPlatform/terraformer#844]
2021/03/30 15:47:00 WARN: Fail read resource from provider, wait 300ms before retry
2021/03/30 15:47:00 Fail read resource from provider, trying import command
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
...

Can you please advise?

command:  terraformer import aws --resources=ec2_instance --regions=eu-west-2

same for resource: eks

**Comment by sergeylanzman** [comment]
I tested on master now, working for me, can you check again on master branch?

**Comment by alexbricepalo** [comment]
Still experiencing the same thing with ec2_instance using the master branch.

**Comment by artazar** [comment]
Same issue with ec2_instance resource:

```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook(0xc00075d680, 0x539b314, 0xc00075d680)
        /home/runner/work/terraformer/terraformer/providers/aws/ec2.go:99 +0x371
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0xc000142cb0, 0x6896188, 0xc000142cb0)
        /home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:75 +0x34
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc000dcd530)
        /home/runner/work/terraformer/terraformer/terraformutils/providers_mapping.go:175 +0xee
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x6893968, 0xc000708c30, 0xc00026f280, 0x3, 0x4, 0x8161698, 0x0, 0x0, 0x5edad28, 0x1e, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:104 +0x370
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc00026f240, 0x3, 0x4, 0x8161698, 0x0, 0x0, 0x5edad28, 0x1e, 0x5e7f80c, 0x9, ...)
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:112 +0x225
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc000154b00, 0xc00026ef80, 0x0, 0x4, 0x0, 0x0)
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
github.com/spf13/cobra.(*Command).execute(0xc000154b00, 0xc00026eb80, 0x4, 0x4, 0xc000154b00, 0xc00026eb80)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000278000, 0xc000702bd0, 0xc000144000, 0x5f5e2f8)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x672bfa0, 0xc000702bd0)
        /home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x2a
main.main()
        /home/runner/work/terraformer/terraformer/main.go:39 +0x65
```

**Comment by wonderg** [comment]
Same 
```
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook(0xc00018e6c0, 0x6ad65b4, 0xc00018e6c0)
        github.com/GoogleCloudPlatform/terraformer/providers/aws/ec2.go:99 +0x371
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0xc000665030, 0xaf3d650, 0xc000665030)
        github.com/GoogleCloudPlatform/terraformer/providers/aws/aws_facade.go:75 +0x34
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc0029db530)
        github.com/GoogleCloudPlatform/terraformer/terraformutils/providers_mapping.go:175 +0xee
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0xaf2f600, 0xc000319270, 0xc000b4b430, 0x1, 0x1, 0xef87010, 0x0, 0x0, 0xa19e009, 0x1e, ...)
        github.com/GoogleCloudPlatform/terraformer/cmd/import.go:104 +0x370
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc000b4b3b0, 0x1, 0x1, 0xef87010, 0x0, 0x0, 0xa19e009, 0x1e, 0xa118f65, 0x9, ...)
        github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x225
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00084b8c0, 0xc000319220, 0x0, 0x5, 0x0, 0x0)
        github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
github.com/spf13/cobra.(*Command).execute(0xc00084b8c0, 0xc0003191d0, 0x5, 0x5, 0xc00084b8c0, 0xc0003191d0)
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00084ab00, 0xc00191dfc0, 0xc00012c050, 0xa30bcd0)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0xad374e0, 0xc00191dfc0)
        github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x2a
main.main()
        github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x65
```

terraformer 0.8.14
unfortunately it is not clear which instance is causing the problem

**Comment by alexbricepalo** [comment]
> Same
> 
> ```
> panic: interface conversion: interface {} is nil, not []interface {}
> 
> goroutine 1 [running]:
> github.com/GoogleCloudPlatform/terraformer/providers/aws.(*Ec2Generator).PostConvertHook(0xc00018e6c0, 0x6ad65b4, 0xc00018e6c0)
>         github.com/GoogleCloudPlatform/terraformer/providers/aws/ec2.go:99 +0x371
> github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0xc000665030, 0xaf3d650, 0xc000665030)
>         github.com/GoogleCloudPlatform/terraformer/providers/aws/aws_facade.go:75 +0x34
> github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc0029db530)
>         github.com/GoogleCloudPlatform/terraformer/terraformutils/providers_mapping.go:175 +0xee
> github.com/GoogleCloudPlatform/terraformer/cmd.Import(0xaf2f600, 0xc000319270, 0xc000b4b430, 0x1, 0x1, 0xef87010, 0x0, 0x0, 0xa19e009, 0x1e, ...)
>         github.com/GoogleCloudPlatform/terraformer/cmd/import.go:104 +0x370
> github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc000b4b3b0, 0x1, 0x1, 0xef87010, 0x0, 0x0, 0xa19e009, 0x1e, 0xa118f65, 0x9, ...)
>         github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x225
> github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc00084b8c0, 0xc000319220, 0x0, 0x5, 0x0, 0x0)
>         github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
> github.com/spf13/cobra.(*Command).execute(0xc00084b8c0, 0xc0003191d0, 0x5, 0x5, 0xc00084b8c0, 0xc0003191d0)
>         github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
> github.com/spf13/cobra.(*Command).ExecuteC(0xc00084ab00, 0xc00191dfc0, 0xc00012c050, 0xa30bcd0)
>         github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
> github.com/spf13/cobra.(*Command).Execute(...)
>         github.com/spf13/cobra@v1.1.1/command.go:895
> github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0xad374e0, 0xc00191dfc0)
>         github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x2a
> main.main()
>         github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x65
> ```
> 
> terraformer 0.8.14
> unfortunately it is not clear which instance is causing the problem

I'm betting it's an EC2 Classic instance.  I just tagged the instances I wanted to copy over and then pulled them in by the tag as a filter.
