### ISSUE TITLE
AWS tags with dot in name generate invalid TF

### ISSUE THREAD

**Issue by gliptak** [GoogleCloudPlatform/terraformer#85]
Tag named ```foo.bar``` with value ```baz``` generates

```
  tags {
    foo {
      bar = "baz"
    }
  }
```

**Comment by okazu-dm** [comment]
I read codes and found this line causes this problem.
 https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraform_utils/resource.go#L121

I have an idea but I don't know whether following idea is good.
```
// from L115(this is pseudo code)
+ if (blockName == "tags") {

+ initialize r.Item[tagName]  as []string // if nil, tagName = foo.bar in this case
+ r.Item = append(r.Item[tagName], tagValue) // tagValue = "baz" in this case
+ } else if _, exist := r.Item[blockName]; exist {
			continue
		}
...
```

I'll write and submit patch if this idea work

**Comment by okazu-dm** [comment]
https://github.com/okazu-dm/terraformer/pull/1 This change fix the issue but this may have some unexpected side effects. This is for just showing cause of the issue.

**Comment by sergeylanzman** [comment]
https://github.com/okazu-dm/terraformer/pull/1 look work, but it's not good insert provider name in shared infra. 
It's global problem, not only aws tag, same issue with kubernetes provider, we need global solution.
