### ISSUE TITLE
Split README.md per provider Doc

### ISSUE THREAD

**Issue by medmedchiheb** [GoogleCloudPlatform/terraformer#862]
The README.md is quite large!
 I suggest creating a `/docs`   and split the documentation for each provider in it's own file.
on the end the README.md will has links to supported providers.

**Comment by medmedchiheb** [comment]
I can took this!

**Comment by meshuga** [comment]
I'm for it!

**Comment by sergeylanzman** [comment]
We can create file for each provider in docs folder, and links in readme
