### ISSUE TITLE
terraformer "panic: interface conversion: interface {} is map[string]interface {}, not string" for aws provider, while processing ebs and ec2_instances in WorkAndOverride

### ISSUE THREAD

**Issue by DmitryFrolovTri** [GoogleCloudPlatform/terraformer#880]
trying to discover aws resources with following command

```
terraformer import aws --resources=ebs,ec2_instance --profile=<aws_profile> --regions=<aws_region>
```
Produces the following error: "```panic: interface conversion: interface {} is map[string]interface {}, not string```"

Here are the logs (removed real instance ids): 
```
2021/04/14 20:13:06 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 ERROR: Read resource response is null for resource aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:07 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:08 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:08 Refreshing state... aws_ebs_volume.tfer--vol-002D-00de88172ddb6f170
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_volume_attachment.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:09 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:10 ERROR: Read resource response is null for resource aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:10 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_ebs_volume.tfer--vol-002D-0efdbd2029858676d
2021/04/14 20:13:11 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_ebs_volume.tfer--vol-002D-0bdfc2da2f3937406
2021/04/14 20:13:11 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:11 Refreshing state... aws_ebs_volume.tfer--vol-002D-05e6ba7a714fef395
2021/04/14 20:13:12 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:12 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:12 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:13 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:13 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:13 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:13 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:14 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:14 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:14 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:15 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:15 Refreshing state... aws_instance.tfer--i-private_info_removed
2021/04/14 20:13:19 ERROR: Unable to refresh resource tfer--i-private_info_removed
2021/04/14 20:13:19 ERROR: Unable to refresh resource tfer--i-private_info_removed
2021/04/14 20:13:19 ERROR: Unable to refresh resource tfer--i-private_info_removed
2021/04/14 20:13:19 ERROR: Unable to refresh resource tfer--i-private_info_removed
2021/04/14 20:13:19 ERROR: Unable to refresh resource tfer--i-private_info_removed
2021/04/14 20:13:19 Filtered number of resources for service ebs: 29
2021/04/14 20:13:19 Filtered number of resources for service ec2_instance: 175
2021/04/14 20:13:19 aws Connecting.... 
panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride(0xc001861ce0, 0x1, 0x1, 0xc001248450, 0x15, 0xc000196240, 0x5d, 0x7ce4e40, 0xc0024e7830)
        /Users/sergey/temp/terraformer/terraformutils/walk.go:101 +0xce8
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride(0x8b5374c, 0x10, 0xc001248450, 0x15, 0xc000196240, 0x5d, 0x7ce4e40, 0xc0024e7830)
        /Users/sergey/temp/terraformer/terraformutils/walk.go:33 +0xcc
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc001c16b40, 0x8b3e03d, 0xc, 0xc000e3ecc8, 0x2, 0x2, 0xc001a8c190, 0xc00111ff40, 0x0, 0xc0018fe580, ...)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:54 +0x40f
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc001c16b40, 0xc001c16c01, 0xc001c16c90, 0x8b4f02c)
        /Users/sergey/temp/terraformer/terraformutils/connect.go:31 +0x3da
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan(0x987e960, 0xc0006c6730, 0xc001713b80, 0xc000f82000, 0x1d)
        /Users/sergey/temp/terraformer/cmd/import.go:223 +0x56a
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(0xc000e3f530, 0xc0000c9320, 0x2, 0x2, 0xd5bbe50, 0x0, 0x0, 0x8bae53e, 0x1e, 0x8b31498, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:191 +0x473
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x987e960, 0xc0006c6730, 0xc0000c9320, 0x2, 0x2, 0xd5bbe50, 0x0, 0x0, 0x8bae53e, 0x1e, ...)
        /Users/sergey/temp/terraformer/cmd/import.go:106 +0x3d1
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc0000c92e0, 0x2, 0x2, 0xd5bbe50, 0x0, 0x0, 0x8bae53e, 0x1e, 0x8b31498, 0x9, ...)
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:112 +0x225
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc000ad7b80, 0xc000b19cb0, 0x0, 0x3, 0x0, 0x0)
        /Users/sergey/temp/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
github.com/spf13/cobra.(*Command).execute(0xc000ad7b80, 0xc000b19c80, 0x3, 0x3, 0xc000ad7b80, 0xc000b19c80)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ad6840, 0xc000781530, 0xc00020c000, 0x8d0b1a0)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/sergey/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x96a4ae0, 0xc000781530)
        /Users/sergey/temp/terraformer/cmd/root.go:36 +0x2a
main.main()
        /Users/sergey/temp/terraformer/main.go:39 +0x65
```
This is on a terraformer version v0.8.12 downloaded from releases page, go version go1.15.9 linux/amd64, 

the issue happens due to this line of code:
https://github.com/GoogleCloudPlatform/terraformer/blob/afaf8825eb736a122ee9e02cf421969b44ef86a9/terraformutils/walk.go#L101
where panic happens as there is a map instead of string in currentValue. 

So here is some extra information.
Variable ``val`` after this line
https://github.com/GoogleCloudPlatform/terraformer/blob/afaf8825eb736a122ee9e02cf421969b44ef86a9/terraformutils/walk.go#L85 is:
```
map[ami:ami-xxxxxxxxxxxxxxxxx associate_public_ip_address:false availability_zone:us-east-1a cpu_core_count:1 cpu_threads_per_core:2 credit_specification:[map[cpu_credits:unlimited]] disable_api_termination:false ebs_block_device:[map[delete_on_termination:true device_name:xvdb encrypted:false iops:0 throughput:0 volume_size:50 volume_type:standard]] ebs_optimized:true enclave_options:[map[enabled:false]] get_password_data:false hibernation:false iam_instance_profile:COAmazonSSMRoleForInstancesQuickSetup instance_type:t3.large ipv6_address_count:0 key_name:zzzzzzzz metadata_options:[map[http_endpoint:enabled http_put_response_hop_limit:1 http_tokens:optional]] monitoring:false private_ip:0.0.0.0 root_block_device:[map[delete_on_termination:true encrypted:false volume_size:130 volume_type:standard]] source_dest_check:true subnet_id:subnet-xxxxxxxxxxxxxxxxxx tags:map[XX:zzzzzz yyyyyyy:LLLLLL mmmmmm:NNNN kkkkkkkkk:TTT Expiration:Never Name:HHHHHH Notes:NNNN esw:ec2-resizing-status:LatestGeneration] tenancy:default vpc_security_group_ids:[sg-LLLLLL sg-KKKKKK sg-FFFFFFF sg-RRRRRRR]]
```
Variable pathSegments is  ```[ebs_block_device]```

So at this line:
https://github.com/GoogleCloudPlatform/terraformer/blob/afaf8825eb736a122ee9e02cf421969b44ef86a9/terraformutils/walk.go#L101
following happens:
currentValue is ```map[delete_on_termination:true device_name:xvdb encrypted:false iops:0 throughput:0 volume_size:50 volume_type:standard]```
which is not a string so panic is thrown

I have replaced line 101-103 
https://github.com/GoogleCloudPlatform/terraformer/blob/afaf8825eb736a122ee9e02cf421969b44ef86a9/terraformutils/walk.go#L101-L103
with following code:
```
							t := reflect.ValueOf(currentValue)
							if t.Kind() == reflect.Map {
								walkAndOverride(pathSegments, oldValue, newValue, t.Interface())
							} else {
								if oldValue == currentValue.(string) {
									valss[idx] = newValue
								}
							}

```
This is very dirty as I had no time to understand the real meaning of those functions.

However, I have a feeling that this WalkAndOverride might not be doing what it is supposed to do as there is never an "oldValue" in any of the resources (seems AMI) that it is looking through. The volume ID is simply never present in the AMI that it is scanning and in the ebs_block_device map on my dataset. I suppose it is called to replace all occurencies of the volume in the resources but it seems on my case it replaces it nowhere. So in which resource other then ebs volume would this information be present? 

Please advise if you think that there is some other place where this should be changed or if this is ok from your point of view.

**Comment by AzySir** [comment]
Thanks @DmitryFrolovTri !

**Comment by DmitryFrolovTri** [comment]
@meshuga do you think this is something that would be fixed in next releases?

**Comment by meshuga** [comment]
I fixed that in TF 0.15 support but don't much have time to finish it. Lockdown time in Singapore...

**Comment by DmitryFrolovTri** [comment]
Thank you @meshuga ! Looking forward to see.

**Comment by WVan** [comment]
I'm running into this as well. Is there any update on a potential fix for this?

**Comment by EduardoOliveira** [comment]
This still happens, any workaround?

**Comment by mpraveenreddie** [comment]
terraformer import aws --resources=ec2_instance,ec2_instance --filter="Name=tags.Name;Value=test" --regions=us-east-1 --profile dev. This works for me.
terraformer import aws -r ec2_instance --regions us-east-1 --profile dev

**Comment by ops-hummus** [comment]
Hitting also the same error
`terraformer import aws --resources="*" --connect=true --regions=eu-central-1 --profile=mfa`
`panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/terraformutils.walkAndOverride(0xc00349b890, 0x1, 0x1, 0xc001fb8318, 0x15, 0xc00348cf60, 0x5d, 0x9b10a60, 0xc0022df9e0)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:102 +0xd08
github.com/GoogleCloudPlatform/terraformer/terraformutils.WalkAndOverride(0xac27bf2, 0x10, 0xc001fb8318, 0x15, 0xc00348cf60, 0x5d, 0x9b10a60, 0xc0022df9e0)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/walk.go:34 +0xcc
github.com/GoogleCloudPlatform/terraformer/terraformutils.mapResource(0xc001d87ef0, 0xac0fa45, 0xc, 0xc002036cc0, 0x2, 0x2, 0xc0021b30e0, 0xc000fc5540, 0x0, 0xc0021bef00, ...)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:54 +0x416
github.com/GoogleCloudPlatform/terraformer/terraformutils.ConnectServices(0xc001d87ef0, 0xc001d87f01, 0xc001d87f50, 0xac22d42)
	github.com/GoogleCloudPlatform/terraformer/terraformutils/connect.go:31 +0x405
github.com/GoogleCloudPlatform/terraformer/cmd.ImportFromPlan(0xba9cfe0, 0xc000664780, 0xc0008cde40, 0xc0026c2000, 0x12)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:223 +0x56a
github.com/GoogleCloudPlatform/terraformer/cmd.importFromPlan(0xc002037530, 0xc001033800, 0x50, 0x80, 0x109660f8, 0x0, 0x0, 0xac8c971, 0x1e, 0xac018d7, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:191 +0x47b
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0xba9cfe0, 0xc000664780, 0xc001033800, 0x50, 0x80, 0x109660f8, 0x0, 0x0, 0xac8c971, 0x1e, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/import.go:106 +0x3d1
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc00197ce20, 0x1, 0x1, 0x109660f8, 0x0, 0x0, 0xac8c971, 0x1e, 0xac018d7, 0x9, ...)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:112 +0x225
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc0018f22c0, 0xc0005129c0, 0x0, 0x4, 0x0, 0x0)
	github.com/GoogleCloudPlatform/terraformer/cmd/provider_cmd_aws.go:51 +0x32f
github.com/spf13/cobra.(*Command).execute(0xc0018f22c0, 0xc000512980, 0x4, 0x4, 0xc0018f22c0, 0xc000512980)
	github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc001887340, 0xc0018833b0, 0xc0000fe050, 0xae047d0)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0xb89b340, 0xc0018833b0)
	github.com/GoogleCloudPlatform/terraformer/cmd/root.go:36 +0x2a
main.main()
	github.com/GoogleCloudPlatform/terraformer/main.go:39 +0x65`
