### ISSUE TITLE
Issue with terraformer import for commercetools, generated tf files doesnt have the valid data

### ISSUE THREAD

**Issue by github-aji** [GoogleCloudPlatform/terraformer#890]
I am trying to import the commercetool  config for one of my project . When I ran import , the generated  tf files only contain the resource block and it doesnt have any other attribute inside. I get the following message when I run the import
![image](https://user-images.githubusercontent.com/29443279/115501545-bf2bd300-a2b6-11eb-95ab-92ee5beecd12.png)
Iam using  terraform v0.13.0
commercetools provider 0.27.0

**Comment by saaguero** [comment]
I did have this same issue with the commercetools `subscription` resource, here is the issue at their repository:

https://github.com/labd/terraform-provider-commercetools/issues/93#issuecomment-822581777

I recommend you to follow the steps from the above issue using your commercetools resources, and if you keep reproducing the issue, please create it in https://github.com/labd/terraform-provider-commercetools.
