### ISSUE TITLE
Im not able to import acces_application with the ClouFlare provider

### ISSUE THREAD

**Issue by zahidferz** [GoogleCloudPlatform/terraformer#891]
Even when having a CLOUDFLARE_API_KEY (global scope) 
im not able to import any acces_application 
 
![Screen Shot 2021-04-21 at 12 51 44](https://user-images.githubusercontent.com/15253645/115598792-681b0380-a2a0-11eb-816c-c3155744735c.png)

**Comment by chenrui333** [comment]
`403 authentication error`?

**Comment by zahidferz** [comment]
Yeah . I know its a 403 Authentication error . But i have an API_KEY  that its a global scope key for my account, and im an admin on this account , also im able to import all the resources (with terraformer) except access_applications. You could try to reproduce it with your own account

**Comment by sergiofteixeira** [comment]
any news regarding this issue?
