### ISSUE TITLE
GCS objects fail to import

### ISSUE THREAD

**Issue by mpiatliou** [GoogleCloudPlatform/terraformer#898]
Trying to plan/import gcs resources with:
```terraformer plan google --resources=gcs --projects=foo --regions=central1```

And an output is following for all buckets in a project:
```2021/04/26 10:38:22 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer--gcf-002D-sources-002D-567909564917-002D-us-002D-central1```
```2021/04/26 10:38:22 ERROR: Unable to refresh resource tfer--gcf-002D-sources-002D-567909564917-002D-us-002D-central1```

Env versions:

- Terraform v0.15.0 on linux_amd64 + provider registry.terraform.io/hashicorp/google v3.65.0
- Terraformer v0.8.13

Importing iam resources works fine, for example. The service account has admin permissions.
Can you please help?

**Comment by debojitkakoti** [comment]
Getting same  error on trying to import gcs.

**Comment by Jayant203** [comment]
> Getting the same error on trying to plan/import GCS. Error ` ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer`
> 
> ```
> Terraform v0.13.0
> + provider registry.terraform.io/hashicorp/google v3.44.0
> terraformer --version
> version v0.8.13
> ```

I am struggling with this too, is there any solution?
