### ISSUE TITLE
Fail read resource from provider, trying import command panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by raeder1986** [GoogleCloudPlatform/terraformer#909]
It is strange but from 30-04-2021 we started to get this error using Terraformer for IAM AWS resources:

_terraformer import aws --resources=iam --profile=sandbox --connect=true
2021/05/03 10:46:59 aws importing default region
2021/05/03 10:47:02 aws importing... iam
2021/05/03 10:47:11 aws done importing iam
2021/05/03 10:47:11 Number of resources for service iam: 33
2021/05/03 10:47:11 Refreshing state... aws_iam_role_policy.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_role.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group.tfer--developers-002D-XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_user_group_membership.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 Refreshing state... aws_iam_group_policy_attachment.tfer--XXXX
2021/05/03 10:47:11 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/03 10:47:11 WARN: Fail read resource from provider, wait 300ms before retry
...
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Refreshing state... aws_iam_role_policy_attachment.tfer--XXXX
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Refreshing state... aws_iam_user_policy_attachment.tfer--XXXX
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Refreshing state... aws_iam_user_group_membership.tfer--XXXX
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Fail read resource from provider, trying import command
2021/05/03 10:47:20 Fail read resource from provider, trying import command
...
2021/05/03 10:47:24 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/03 10:47:24 Fail read resource from provider, trying import command
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*IamGenerator).PostConvertHook(0xc0000acb40, 0x52862db, 0xc0000acb40)
        /home/runner/work/terraformer/terraformer/providers/aws/iam.go:376 +0x6a5
github.com/GoogleCloudPlatform/terraformer/providers/aws.(*AwsFacade).PostConvertHook(0xc0001f0bd0, 0x67857c8, 0xc0001f0bd0)
        /home/runner/work/terraformer/terraformer/providers/aws/aws_facade.go:75 +0x3b
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*ProvidersMapping).CleanupProviders(0xc000921530)
        /home/runner/work/terraformer/terraformer/terraformutils/providers_mapping.go:175 +0x10a
github.com/GoogleCloudPlatform/terraformer/cmd.Import(0x6782d68, 0xc00062c000, 0xc00044c770, 0x1, 0x1, 0x806eb58, 0x0, 0x0, 0x5dc7005, 0x1e, ...)
        /home/runner/work/terraformer/terraformer/cmd/import.go:104 +0x370
github.com/GoogleCloudPlatform/terraformer/cmd.importRegionResources(0xc00044c730, 0x1, 0x1, 0x806eb58, 0x0, 0x0, 0x5dc7005, 0x1e, 0x5d6acbe, 0x9, ...)
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:112 +0x238
github.com/GoogleCloudPlatform/terraformer/cmd.newCmdAwsImporter.func1(0xc000129080, 0xc0007c6300, 0x0, 0x3, 0x0, 0x0)
        /home/runner/work/terraformer/terraformer/cmd/provider_cmd_aws.go:59 +0x4fb
github.com/spf13/cobra.(*Command).execute(0xc000129080, 0xc0007c6270, 0x3, 0x3, 0xc000129080, 0xc0007c6270)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000128000, 0xc00044d1a0, 0xc0000ae050, 0x5e4ab00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/GoogleCloudPlatform/terraformer/cmd.Execute(0x661ac20, 0xc00044d1a0)
        /home/runner/work/terraformer/terraformer/cmd/root.go:36 +0x2e
main.main()
        /home/runner/work/terraformer/terraformer/main.go:39 +0x6a_

Terraformer version v0.8.13

**Comment by bencohen2** [comment]
Did you ever get this fixed?
