### ISSUE TITLE
'002D' Unicode printed instead of hyphen '-'

### ISSUE THREAD

**Issue by AzySir** [GoogleCloudPlatform/terraformer#921]
Resource names keep printing `002D` for '-' (assumed unicode) is there a way to avoid this? or is this API specific. Apologies if in documentation somewhere, have not found anything related

**Comment by whyman** [comment]
I am also seeing this.

**Comment by whyman** [comment]
Stale bots are pointless and do not help project quality 🙂

**Comment by AzySir** [comment]
I just had another one closed. I wish I had time to fix it all but I don't imagine closing issues that people have encountered and raised to try and make your product better...

**Comment by deepak-kosaraju** [comment]
I started using this tool and noticed similar issue after importing `aws-sg's`, something like
`resource "aws_security_group" "tfer--us-002D-east-002D-1-002D-example_default-002D-public_sg-002D-dh1gga2b":`

BTW: are we expected to see `tfer--` prefix and `sg-id` suffix in resource name?

Cc: @meshuga 

Please suggest?

**Comment by deepak-kosaraju** [comment]
With help of my colleague found this interesting issue https://github.com/GoogleCloudPlatform/terraformer/issues/378  and this https://github.com/GoogleCloudPlatform/terraformer/pull/263, so it's by design as per the discussion in references issues and PR. So this can probably be closed for now?

**Comment by georgewilliamherbert** [comment]
You can post-process the output (trivially `sed -e 's/-002D-/-/g' ` but can do in python or whatever you like) but the unmodified output including escaped "-"s to 002D makes the human readability of the files questionable.

If you're purely machine processing then it doesn't much matter if it's left as-is, but with human readability of the output to assess what's there before running a restore, it creates a significant pain point for operational use.  Object names for complex naming schemes (necessary for semantic context in complex clouds, hybrid, or DC environments) easily break past a single line of output once substituted and become very hard to manually parse.

I understand the need to escape characters which aren't allowed in Terraform object names.  But escaping the dash itself was not precisely necessary (the unicode escape sequences for everything else are still distinct and unambiguous if dash isn't escaped) and postprocessing the -0026D- out is a minimal readability fix.  I think this reasonably should be a command line option to not escape the simple dash (yes for everything else).  My go fu is weak but am working on fixing that, hopefully can build a patch for that and submit it.
