### ISSUE TITLE
Development docs.

### ISSUE THREAD

**Issue by stobias123** [GoogleCloudPlatform/terraformer#932]
Trying to add a new provider, and I'm really struggling with the development workflow. Any chance someone could put together a short "getting started" guide?

I'm building with `go run build/main.go fortios`, I've put together some code for basic provider init, then  - then using the resulting binary to try to import my resources.

I run `terraformer-fortios import list` and get help text (no resources listed). 

I run `go build -v` and then ` ./terraformer import fortios list` - and get help text. It appears my provider wasn't built.

Probably missing something fundamental, but a simple walkthrough would be very helpful and appreciated.

**Comment by sashasimkin** [comment]
I've got no experience in this either so might be completely wrong, but it seems that you need to expose possible commands and what you provider does manually as done for others under `cmd/`, e.g. https://github.com/GoogleCloudPlatform/terraformer/blob/master/cmd/provider_cmd_aws.go

and then you need to add it here: https://github.com/GoogleCloudPlatform/terraformer/blob/fe17310bbb934d01c2b8378707884184e5d48336/cmd/root.go#L39 for cmd to discover it and add necessary sub-commands.
