### ISSUE TITLE
AWS: Couldn't download resources from specific region.

### ISSUE THREAD

**Issue by saravankrish** [GoogleCloudPlatform/terraformer#933]
I am able to import S3 bucket configurations from all other regions except us-east-1 region. Do you think it's related to permission?

**us-west-2 region:**
❯ terraformer import aws -r s3 --profile=*** --regions=us-west-2 --filter="Name=id;Value=xyz"
2021/05/14 08:04:15 aws importing region us-west-2
2021/05/14 08:04:19 aws importing... s3
2021/05/14 08:04:35 aws done importing s3
2021/05/14 08:04:35 Number of resources for service s3: 1
2021/05/14 08:04:35 Refreshing state... aws_s3_bucket.tfer--xyz
2021/05/14 08:04:39 Filtered number of resources for service s3: 1
2021/05/14 08:04:39 aws Connecting....
2021/05/14 08:04:39 aws save s3
2021/05/14 08:04:39 aws save tfstate for s3

**us-east-1 region:**
❯ terraformer import aws -r s3 --profile=*** --regions=us-east-1 --filter="Name=id;Value=objstoretest.s3.amazonaws.com"
2021/05/14 08:06:17 aws importing region us-east-1
2021/05/14 08:06:19 aws importing... s3
2021/05/14 08:06:41 aws done importing s3
2021/05/14 08:06:41 Number of resources for service s3: 0
2021/05/14 08:06:41 aws Connecting....
2021/05/14 08:06:41 aws save s3
2021/05/14 08:06:41 aws save tfstate for s3

**Comment by sergeyr87** [comment]
when using s3 us-east-1 is the default region,
Try to run it without `--regions`

**Comment by saravankrish** [comment]
If I don't provide the regions then I am getting this warning messages and s3_bucket.tf doesn't have any resources listed:

❯ terraformer import aws -r s3 --profile=hwx --filter="Name=id;Value=objstoretest.s3.amazonaws.com"
2021/05/14 13:22:52 aws importing default region
2021/05/14 13:22:53 aws importing... s3
2021/05/14 13:23:14 aws done importing s3
2021/05/14 13:23:14 Number of resources for service s3: 1
2021/05/14 13:23:14 Refreshing state... aws_s3_bucket.tfer--objstoretest-002E-s3-002E-amazonaws-002E-com
2021/05/14 13:23:14 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/14 13:23:15 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/14 13:23:15 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/14 13:23:16 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/14 13:23:16 WARN: Fail read resource from provider, wait 300ms before retry
2021/05/14 13:23:17 Fail read resource from provider, trying import command
2021/05/14 13:23:17 Filtered number of resources for service s3: 1
2021/05/14 13:23:17 aws Connecting....
2021/05/14 13:23:17 aws save s3
2021/05/14 13:23:17 aws save tfstate for s3

❯ cat s3_bucket.tf
resource "aws_s3_bucket" "tfer--objstoretest-002E-s3-002E-amazonaws-002E-com" {}

**Comment by sergeyr87** [comment]
i notice when using env var with  `AWS_SESSION_TOKEN` `AWS_SECRET_ACCESS_KEY` `AWS_ACCESS_KEY_ID`
for some reason, it first tries to use the `AWS profile` and then the env var 
and of course, it failing 

did you check that you don't have any AWS env var exported?

**Comment by saravankrish** [comment]
@sergeyr87 Thanks. It's working now. I changed my region in .aws/config to us-east-1 and removed --regions parameters.

**Comment by veggerby** [comment]
We have experienced the same issue. The primary issue is that based off the terraformer response everything looks fine, except that we know we are missing resources (it fails successfully :)). However it is actually worse that, it makes us wonder, what else is missing **that we don't know of**. 

Terraformer should respect the --regions parameter if it has been provided, and if there is some implicit conflict in configuration/auth then it should at least fail or report on it.
