### ISSUE TITLE
 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer*

### ISSUE THREAD

**Issue by black-snow** [GoogleCloudPlatform/terraformer#937]
Running `terraformer plan google --resources=cloudsql,gcs,iam,instances` I receive

```
2021/05/17 16:08:48 ERROR: Read resource response is null for resource google_storage_bucket_iam_member.tfer--xxx-002D-rfq-002D-sql-002D-dumps
2021/05/17 16:10:18 ERROR: Unable to refresh resource tfer--xxx-002D-sql-002D-dumps
```
(x-ed out some details)

I have no idea what that means ;)  
 (I guess tfer is short for terraformer? But there is no such member.)

version v0.8.13  
Provider: google

**Comment by Jayant203** [comment]
> 

I am struggling with this too, is there any solution?
