### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by oscaraoc** [GoogleCloudPlatform/terraformer#94]
Hi 
This is not an issue
First congratulation for the greate tool
I want to know if you have best practices or recommendation for the better use with GCP
For example I must run the import with all the resources at same time or you recommend separate for example networks from instances??

**Comment by bryanasdev000** [comment]
Hi @oscaraoc !

I may be wrong but I'm not sure if "good practices" apply here, I have used this tool more as a oneshot and I imagine it is the main use of it (massively importing existing infrastructure), and I usually take all the resources of the project (note I only used it with GCP).

Importing pieces that have relationships separately can lead to problems I imagine.
