### ISSUE TITLE
No EC2 imds role found

### ISSUE THREAD

**Issue by KangGeonu** [GoogleCloudPlatform/terraformer#940]

**Comment by dlombard-fox** [comment]
I am getting the same issue:
```
$ terraformer import aws --resources=alb --regions=us-east-1
2021/06/03 10:01:30 aws importing region us-east-1
2021/06/03 10:01:32 aws importing... alb
2021/06/03 10:01:37 aws error initializing resources in service alb, err: no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down
2021/06/03 10:01:37 aws Connecting....
```

**Comment by zmezei-dpc** [comment]
I'm getting the same error as well:

`$ terraformer import aws --resources=vpc --regions=eu-central-1  -v
2021/06/04 01:10:01 aws importing region eu-central-1
2021-06-04T01:10:01.676+0200 [INFO]  plugin: configuring client automatic mTLS
2021-06-04T01:10:01.705+0200 [DEBUG] plugin: starting plugin: path=/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5 args=[/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5]
2021-06-04T01:10:01.706+0200 [DEBUG] plugin: plugin started: path=/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5 pid=238753
2021-06-04T01:10:01.706+0200 [DEBUG] plugin: waiting for RPC address: path=/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5
2021-06-04T01:10:01.734+0200 [INFO]  plugin.terraform-provider-aws_v3.44.0_x5: configuring server automatic mTLS: timestamp=2021-06-04T01:10:01.734+0200
2021-06-04T01:10:01.762+0200 [DEBUG] plugin: using plugin: version=5
2021-06-04T01:10:01.762+0200 [DEBUG] plugin.terraform-provider-aws_v3.44.0_x5: plugin address: address=/tmp/plugin098518608 network=unix timestamp=2021-06-04T01:10:01.762+0200
2021-06-04T01:10:01.796+0200 [TRACE] plugin.stdio: waiting for stdio data
2021-06-04T01:10:01.863+0200 [INFO]  plugin.terraform-provider-aws_v3.44.0_x5: 2021/06/04 01:10:01 [INFO] AWS Auth provider used: "EnvProvider": timestamp=2021-06-04T01:10:01.863+0200
2021-06-04T01:10:01.865+0200 [INFO]  plugin.terraform-provider-aws_v3.44.0_x5: 2021/06/04 01:10:01 [DEBUG] Trying to get account information via sts:GetCallerIdentity: timestamp=2021-06-04T01:10:01.865+0200
2021-06-04T01:10:02.388+0200 [INFO]  plugin.terraform-provider-aws_v3.44.0_x5: 2021/06/04 01:10:02 [DEBUG] Trying to get account information via sts:GetCallerIdentity: timestamp=2021-06-04T01:10:02.388+0200
2021/06/04 01:10:03 aws importing... vpc
2021/06/04 01:10:08 aws error initializing resources in service vpc, err: no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
2021/06/04 01:10:08 aws Connecting....
2021-06-04T01:10:08.071+0200 [DEBUG] plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-06-04T01:10:08.073+0200 [DEBUG] plugin: plugin process exited: path=/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5 pid=238753
2021-06-04T01:10:08.073+0200 [DEBUG] plugin: plugin exited`

`$ terraformer --version
version v0.8.14`

`$ ls ~/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5
/home/zmezei/.terraform.d/plugins/linux_amd64/terraform-provider-aws_v3.44.0_x5`

**Comment by hthakkar-crest** [comment]
I am also getting same error!

**Comment by jmcgill** [comment]
Same error here.

I've verified that my credentials have permissions to list/describe/read VPC and have reproduced on a new account with only the default VPC, so suspect that this is not related to nuances of how my particular account is configured.

**Comment by jmcgill** [comment]
It seems that this is related to the handling of the provider chain when trying to load the "default" profile - possibly in cases where that profile is not available.

I'm not entirely sure *why* this produces this error, however I'm able to work around it by explicitly setting the profile to an empty string, which avoids trying to customize that in the AWS provider chain. e.g.

`terraformer import aws -r vpc --profile ""`

I think the right fix here is to have the default value of --profile be "" rather than "default". If someone else in this thread can confirm that this fix works for them, then I would be happy to implement a patch.

**Comment by tehleet** [comment]
Doesn't work

```BASH
❯ terraformer import aws -r lambda --regions=eu-west-1 --profile ""
2021/06/30 00:53:57 aws importing region eu-west-1
2021/06/30 00:54:03 aws importing... lambda
2021/06/30 00:54:07 aws error initializing resources in service lambda, err: no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down
2021/06/30 00:54:07 aws Connecting....
```

I'm using plain AWS profiles without any customizations `~/.aws/config` and `~/.aws/credentials` with `export AWS_PROFILE=name`
I didn't change anything in my credentials handling, but it worked on March 25th.

**Comment by abuxton** [comment]
@tehleet  the workaround suggested by @jmcgill works for me in following conditions. 
```
AWS_ACCESS_KEY_ID=<set>
AWS_DEFAULT_REGION=<set>
AWS_PROFILE=<set>
AWS_SECRET_ACCESS_KEY=<set>
AWS_SHARED_CREDENTIALS_FILE=/Users/abuxton/.aws/credentials
```
provider config is blank in *.tf files (works set too)
```
provider "aws" {
   # Configuration options
//   region     = "eu-west-2"
//   shared_credentials_file = "/Users/abuxton/.aws/credentials"
//   profile = "default"
}
```
i can then repeatidly pass fail
```
❯ terraformer plan aws -r "ec2_instance,s3,vpc, lambda"
2021/07/21 11:04:09 aws importing default region
2021/07/21 11:04:11 aws importing... ec2_instance
2021/07/21 11:04:11 aws error initializing resources in service ec2_instance, err: operation error EC2: DescribeInstances, https response error StatusCode: 401, RequestID: 5e55e966-547f-4b51-adf8-93ed81b96860, api error AuthFailure: AWS was not able to validate the provided access credentials
2021/07/21 11:04:11 aws importing... s3
...
2021/07/21 11:06:34 Saving planfile to generated/aws/terraformer/plan.json

❯ terraformer plan aws -r "ec2_instance,s3,vpc" --profile ""
2021/07/21 11:06:40 aws importing default region
2021/07/21 11:06:42 aws importing... ec2_instance
2021/07/21 11:06:43 aws done importing ec2_instance
...
2021/07/21 11:06:59 Saving planfile to generated/aws/terraformer/plan.json
```

**Comment by udomsak** [comment]
## environment
*  AWS assume role  
*  Ubuntu linux
*  S3

## work 
regard to @abuxton comment, how to make it work. 

```shell
#export variables
AWS_ACCESS_KEY_ID=<set>
AWS_DEFAULT_REGION=<set>
AWS_PROFILE=<set>
AWS_SECRET_ACCESS_KEY=<set>
AWS_SHARED_CREDENTIALS_FILE=<set>
```

run command
```
terraformer import aws --resources=s3 --regions=ap-southeast-1 --profile=""
```

**Comment by vkulyk-mindk** [comment]
UP!
Problem still exist

**Comment by MushiTheMoshi** [comment]
Documentation is vague on this one, should be more concise and the example should be included in the repository itself.

**Comment by ravindraprasad85** [comment]
Looks no solution for above issue yet 

same issue here
Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down

**Comment by ykishorereddy** [comment]
Facing the issue
│ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded

**Comment by nikelin** [comment]
Same here. It was fine before but started to fail just a few days ago.

![Screenshot 2022-02-17 005045](https://user-images.githubusercontent.com/82799/154278368-dac624cf-e6c2-47c1-8466-24bcc1f05f5b.png)

**Comment by Amina-Emenena** [comment]
Facing the same issue "Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed"

**Comment by vjdhama** [comment]
Folks,

Upgrade to AWS provider version 4.1.0. That one seemingly has the fix.

https://github.com/hashicorp/terraform-provider-aws/pull/23191

**Comment by venkawu** [comment]
i noticed i had to change the name of env variable so that it could be used appropriately.
originally i was using:
export TF_VAR_aws_access_key=YOUR_ACCESS_KEY
export TF_VAR_aws_secret_key=YOUR_SECRET_KEY

changed to:
export AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY

This worked with 4.2.0

**Comment by axi0m** [comment]
I'm still having this problem with latest Terraform, provider and terraformer. 

Adding this parameter was 💯 : `--profile=""`

**Comment by brianmaresca** [comment]
still having the issue as well with latest terraform (1.5.3) and aws provider (5.9.0). for me it seems as though terraformer just expects the aws profile to be `default` and ignores any other profile names.

say my profile name is `dev`, and `export AWS_PROFILE=dev` - then I get the "no EC2 IMDS role found..." error. however, if i just change the profile name in my ~/.aws/credentials file to `default` then it works (didn't change my `$AWS_PROFILE` value either, seems to be totally ignored)

example  content of `~/.aws/credentials` - produces the error:
 ```
[dev]
output = json
region = us-east-1
aws_access_key_id = *OMITTED*
aws_secret_access_key = *OMITTED*
aws_session_token = *OMITTED*
 ```
 
 example  content of `~/.aws/credentials` - works, only change being `[dev]` -> `[default]`
 ```
[default]
output = json
region = us-east-1
aws_access_key_id = *OMITTED*
aws_secret_access_key = *OMITTED*
aws_session_token = *OMITTED*
 ```

**Comment by Deepak9829** [comment]
**terraformer import aws  --resources=ec2_instance --regions=ap-southeast-1**
Getting this error while terraforming 

```
2023/09/08 21:16:08 aws importing region ap-southeast-1
2023/09/08 21:16:15 aws importing... ec2_instance
2023/09/08 21:16:19 aws error initializing resources in service ec2_instance, err: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: connect: host is down
2023/09/08 21:16:19 aws Connecting....
```

**Comment by StepanMatula2** [comment]
--profile="" is works for me!! 

 terraformer import aws --resources=* --regions=us-west-2 --profile=""
 
version.tf
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "4.1.0"
    }
  }
  required_version = ">= 0.13"
}

**Comment by fengxia41103** [comment]
After 4 hours of trying, the only one worked for me is to `--profile=""` even though I have profiles defined in the `~/.aws/config`.

verions.tf:

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = ">= 5.0.0"
    }
  }
  required_version = ">= 1.7.0"
}
```

and `main.tf`

```hcl
provider "aws" {
  region = "us-east-2"
}
```

Further, I wrap the cli in `aws2-wrap` w/ a profile specified:

```
aws2-wrap --profile <name>  ./terraformer-aws-linux-amd64 import aws -r vpc,subnet,sg --profile=""
```

And sample output (truncated):

```
➜  tmp myaws ./terraformer-aws-linux-amd64 import aws -r vpc,subnet,sg --profile=""
2024/02/11 17:03:32 aws importing default region
2024/02/11 17:03:34 aws importing... vpc
2024/02/11 17:03:34 aws done importing vpc
2024/02/11 17:03:34 aws importing... subnet
2024/02/11 17:03:34 aws done importing subnet
2024/02/11 17:03:34 aws importing... sg
2024/02/11 17:03:34 aws done importing sg
2024/02/11 17:03:34 Number of resources for service sg: 1
2024/02/11 17:03:34 Number of resources for service vpc: 1
2024/02/11 17:03:34 Number of resources for service subnet: 3
```

Hope this helps someone.

**Comment by KurtLehnardt** [comment]
```
terraformer import aws --resources=glue --connect=true --regions=us-east-1 --profile=my-profile-that-throws-an-error
```

produces this error:
```
aws error initializing resources in service glue, err: failed to refresh cached credentials, operation error SSO: GetRoleCredentials, https response error StatusCode: 403, RequestID: <guid> api error ForbiddenException: No access
```

and running the same command with an empty string for the profile:
```
 terraformer import aws --resources=glue --connect=true --regions=us-east-1 --profile=""
```

works as expected
