### ISSUE TITLE
Generated Datadog provider.tf

### ISSUE THREAD

**Issue by lcardito** [GoogleCloudPlatform/terraformer#949]
Hey team!

We're getting to know `terraformer`, for a quick spike we're using it to import some Datadog resources. Everything seems to be setup correctly and the command to import those resources seems to do its job:

```
terraformer import datadog --path-output="my-project" --path-pattern="{output}/" --compact \
    --resources=monitor --filter="Name=tags;Value='role:my-awesome-role'" \
```

The above generates a `provider.tf` which seems to be in conflict with the latest datadog provider published address:

```
terraform {
  required_providers {
    datadog = {
      version = "~> 3.0.0"
    }
  }
}
```

When running `terraform plan` we're getting the following error:

```
╷
│ Error: Could not load plugin
│ 
│ 
│ Plugin reinitialization required. Please run "terraform init".
│ 
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│ 
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│ 
│ failed to instantiate provider "registry.terraform.io/hashicorp/datadog" to obtain schema: unknown provider "registry.terraform.io/hashicorp/datadog"
```

We're assuming the `provider.tf` configuration _should_ override the source path of the module, like:

```
terraform {
  required_providers {
    datadog = {
      source = "datadog/datadog"
      version = "~> 3.0.0"
    }
  }
}
```
Adding the `source` field for the provider fixes our issue, would be nice tho that `terraformer` generated the right provider configuration.

Thoughts?

Many thanks!

**Comment by magoncalves** [comment]
+1

**Comment by lcardito** [comment]
Yeah might be stale but still an issue I think.. :)

**Comment by seagullmouse** [comment]
+1

**Comment by keeganwitt** [comment]
Agreed, this is still an issue.

[provider.go](https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraformutils/providerwrapper/provider.go) currently parses a file path like `.terraform/providers/registry.terraform.io/datadog/datadog/3.15.1/darwin_amd64/terraform-provider-datadog_v3.15.1` to figure out the name and version. The source is not there to parse, so the fix for this would probably have to have a mapping of names to sources hard coded.
