### ISSUE TITLE
terraform 1.0.0 support

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/terraformer#952]
[HashiCorp just announced Terraform 1.0 General Availability](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability)

**Comment by chenrui333** [comment]
should be re-open until get supported

**Comment by jeff-clearcover** [comment]
https://github.com/GoogleCloudPlatform/terraformer#migration-state-version
