### ISSUE TITLE
Azure Virtual Machine Import

### ISSUE THREAD

**Issue by pir8g33k** [GoogleCloudPlatform/terraformer#959]
Im getting error in importing resources only happens for virtual machine, please advice

![image](https://user-images.githubusercontent.com/63558386/122226331-76744d00-cee8-11eb-99ff-7ea163adb6a7.png)

**Comment by csbogdan** [comment]
Getting the same thing for virtual machines.
Terraform 0.15 installed via brew, Azure provider 2.63.0, Mac OS BigSur.

**Comment by Bladou46** [comment]
Same error with multiple terraform versions (0.13, 0.14, 1.0). I have also tried multiple azurerm provider versions from 2.49 to 2.66. In all cases, the result is the same as above, it fails for `virtual_machine`.

**Comment by besthitman7** [comment]
I got the same error for my virtual machines.
Having tried changing Terraform versions and azurerm provider versions but still not working.

**Comment by snerdish** [comment]
Likewise. Looks like this has been the case for some time.

**Comment by Bladou46** [comment]
I may have found some interesting things about this. The problem occurs when I use Azure Migrate to create the virtual machine. For some reason I don't understand yet, the generated virtual machine resource does not contain an `osProfile` block. This explains the failure when **terraformer** tries to check if it is a Linux or a Windows, using the fore mention block.  

![image](https://user-images.githubusercontent.com/7149904/126156509-abd139d5-8fab-4650-86ce-84385bc164dc.png)

https://github.com/GoogleCloudPlatform/terraformer/blob/a535b6d3a6243c3127d24ed355ca02780e8403ab/providers/azure/virtual_machine.go

**Comment by Bladou46** [comment]
It should be fixed when the following pull request is merged #989
