### ISSUE TITLE
Allow OR with multiple filters

### ISSUE THREAD

**Issue by ethpran** [GoogleCloudPlatform/terraformer#968]
It's possible to use multiple filters by running something like:
`terraformer import aws --resource iam --filter="Name=role;Value=role1:role2" --filter="Name=name;Value=name1:name2" `

Specifically, in this example, the `iam` resource actually imports several resources, including `aws_iam_policy` and `aws_iam_role_policy_attachment`. In [aws_iam_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy) there is a field named `name` and in [aws_iam_role_policy_attachment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy_attachment) there is a field named `role`. Unfortunately, the above command will return 0 results because terraformer requires all filters to be true to allow a resource to be imported and neither of these resources has both `name` AND `role`.

It would be cool if there was a way to specify an OR relationship in cases like this to allow for the desired outcome. I don't have a proposal for how to achieve this at the moment. I might be wrong about how I'm understanding this also, so let me know if what I want here is achievable and if not, what a good way to implement this might be. Thanks

**Comment by TrevorChan1** [comment]
This would be a very helpful feature

**Comment by oubaydos** [comment]
this is interesting
