### ISSUE TITLE
Unable to connect to EU region for New Relic provider

### ISSUE THREAD

**Issue by ArunSisodiya** [GoogleCloudPlatform/terraformer#970]
Guys, 

I am unable to connect to the EU region account of the new relic while passing `--region=EU` to the terraformer cli.

```bash
terraformer import newrelic -r alert,synthetics --account-id=<account_id> --api-key=<api-key> --region=EU
```

Please find the error in the screenshot. Please help me on an urgent basis.

[](url)
![Screenshot 2021-06-28 at 11 56 23](https://user-images.githubusercontent.com/24604679/123617812-ec8d8380-d807-11eb-84fe-c83d44a12f69.png)

**Comment by arun1801** [comment]
Still looking for reply from Developers.
