### ISSUE TITLE
AWS import firehose resources hangs with no output

### ISSUE THREAD

**Issue by svarosky90** [GoogleCloudPlatform/terraformer#976]
When I try to import a kinesis firehose resources with the last version of terraformer command execution hangs with no output: 
I use this command: `terraformer import aws --resources=firehose --filter="Name=<resource-name>" --regions=<region>`

```
2021/07/02 11:44:15 aws importing region eu-west-1
2021/07/02 11:44:17 aws importing... firehose
```

No additional output is provided to undestand the issue.
Furthermore, importing other resources like EKS, KINESIS ecc, produces the expected output.
Anyone else has the same problem?

**Comment by sap-nocops** [comment]
I have kind of the same problem since I cannot import firehose resources but I get an error.

```
% terraformer import aws -r firehose --regions=eu-west-1
2021/07/02 11:45:18 aws importing region eu-west-1
2021/07/02 11:45:20 aws importing... firehose
2021/07/02 11:45:59 aws error initializing resources in service firehose, err: operation error Firehose: ListDeliveryStreams, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: d1b7f777-915a-8b41-88ef-15e0abd007f1, api error ThrottlingException: Rate exceeded
2021/07/02 11:45:59 aws Connecting....
```

I am using darwin arm64

**Comment by svarosky90** [comment]
@sap-nocops I use linux-amd64 machine.
