### ISSUE TITLE
Fail to import dashboard widgets from Datadog

### ISSUE THREAD

**Issue by magoncalves** [GoogleCloudPlatform/terraformer#996]
Hi team!

I am having issues importing dashboards using the [Terraformer Datadog provider](https://github.com/GoogleCloudPlatform/terraformer/blob/master/docs/datadog.md).

When I run
```bash
terraformer import datadog --resources=dashboard \
--filter=dashboard=<MY_DASHBOARD_ID> \
--path-output <MY_REPO_DIRECTORY>
```
It only imports general dashboard information, but no widget is described in the `dashboard.tf` file. Example:
```hcl
resource "datadog_dashboard" "tfer--dashboard_MY_ID" {
  is_read_only = "false"
  layout_type  = "ordered"
  reflow_type  = "auto"

  template_variable {
    default = "*"
    name    = "some name"
    prefix  = "some prefix"
  }

  title = "My title"
  url   = "The dashboard URL"
}

```

If I try to run `terraform plan`, the following error is shown:
```
│ Error: Insufficient widget blocks
│ 
│   ...
│ 
│ At least 1 "widget" blocks are required.
```

If I use the `dashboard_json` resource, instead of `dashboard`, it works fine. But I would rather use the regular HCL format that would be provided by "dashboard" :) 

The versions I am using:
**Terraform:** 1.0.2
**Datadog provider:** 3.2.0
**Terraformer:** 0.8.15

Please, let me know if there is anything I can do to get it working.
Thanks!

**Comment by skarimo** [comment]
👋  This was addressed in the following PR: https://github.com/GoogleCloudPlatform/terraformer/pull/985. PR has been merged so should be available in the next release (whenever the Terraformer cuts a new release). In the meantime, you should be able to build the tool from source: https://github.com/GoogleCloudPlatform/terraformer#installation

**Comment by magoncalves** [comment]
Awesome, worked perfectly ✨ 
Thanks @skarimo
