### ISSUE TITLE
Feature suggestion: process output of terraformer so that terraform can be applied directly to it...

### ISSUE THREAD

**Issue by symbiont-ji** [GoogleCloudPlatform/terraformer#999]
(If this is already done, I could not find a reference to it)

I have two use immediate use cases for `terraformer`:

1. Take an existing installation (e.g., an entire GCP Project or an entire AWS (sub)account) that has been changed manually too many times and turn it into something that can be cloned in a different project/subaccount. 

2. Again, take an existing installation, create a usable configuration as with the previous case, and use it with a tool such as https://github.com/fugue/regula for security auditing.

I volunteer to do this if nobody is working on it, but I hate doing duplicate work!

**Comment by rajnadimpalli** [comment]
Hi @symbiont-ji ,

I'm thinking about doing something similar and happy to collaborate.
What do you think is the best way to achieve your objective #1 ?
